# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:1hGiRpEjZYL1phBikSFfewICf2zkcEF22E3wPFH3GSu7ju0dcz70CxFxAGix583W4Q0WAN15+xlWTzaAgd/AQUpzf1/lMvAgZmpXAcW1fCVtl3WN4IhBGD8uX85D9QyrFvUJjmuOLNatrXA03GF1ggDUiwv+ojpnzX4RfYLlEYaRMHFVJpoe,iv:2fY3rijo85OChpjfp9/Y/8X9UeqhBsWfRp+1JRUgoGg=,tag:7YPkih4jyMepp5QFHB66Jw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:OqXgVoxCRmziiJhyjUA=,iv:X4ciRWlFC7T6l8fJ7jsn+0EMKXPd6Y/iXZCf/FqMN58=,tag:F3V1Ic3LqECrYfsSXxRx0Q==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:fo23q7eSdpe3wLGudAH13ZhT7g==,iv:hSCRe59a3gimmx+2EOyGebGmAdEtbxVkKGDdmJLO+kc=,tag:4RvCChplesggs+NxImGk7g==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:KB02fgZcasPyF9Fnt+Y6WylAUA==,iv:CuWifnOQIJ0iukXfeWpkXFIc4tV1q86QaWLSh9DyGFQ=,tag:pu8RmBllIvEOJSJ4R1bgaw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:cqgBqv7xD28UEvxMcfOzXg==,iv:nyYL7f8vJmcaXn5gmtzE7PM225cVgU64y1tsPFskNUU=,tag:IzmPy4+3Z9GWW464vOnRyg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYczF3enB6N2NrMUJCWmRp
        MzdZUGFnL2d5a1dQUUZsMzdwNDlEQ0hJRFRRCkpPNHpsdThoZ21sT2lGcUFDRjJu
        YVplOWhhMFY0cmRTUFpVOUNOSmFXVEEKLS0tIDFrd3BCRFhKRmptMjh2Mkk1VzBK
        dHFkTVFNZ0FSTzZhcjQvL1F4OFkyZEEK/MMeYv4yTmN2LaKKWYy7Q6f0/40mFgFU
        3XEfeobDragaOHXeBwQzPNW8FloQlnEzxQswCuPGQ4XDUJfAkaxSXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:rZzEKckQ1NzJBNLT60n5qGpGSl1WvHK/tEXScutKbmuGajhJ69jPlUxE8ZjGXszJEjNCgl5sLJsDDuys/AqIZ7AN0epVcb7fRCCxRYq2ULI37pf78L6LnmcNRHLZIz6X/GHGPrKhNC0Ln59lbAZrMgMUYB1uauvkWziBi+a8cRQ=,iv:SbEoEPcBQJF/nSLcDQiHmKNHu1Va6bbj8Wd6tC4cYLc=,tag:C3gYxphCrSUmdMmZmB4sDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
