# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:XhH1M2TTNS1jfcwd8xu3u1DPZYkOrbaj1KDLW6lMm4KlfLjb3MTHm2PKzS6JKagn4PHpECbz/dvR+o6IYyisTDbeBXqwBgUCeq4hy/p6iAh/KXDRgO86kf0f9QBTxhkDHA8i3QZqRv2jAL9Lt0LwS1s9Z1DcgGmnI+Ce6UChmQFukeV9nZU=,iv:1WMP1kWyqcCOtVFCWwPv4v1M9qtsOIUtJiCV9gMEcuw=,tag:ARcbqvGg7py9dBXI7LC3/A==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:qI1M8ihsILFg0x0QprA=,iv:YK3TuklN1o6Pj6fpZorJJGlKNoa2fFwKCYbdwZYCArs=,tag:/zPd+CCXYYBHFbu4f8cFmg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:ET9Bf1fLoM1X4MHr6MGX/2/EcQ==,iv:keaaTkXEpf3QkpNWN/6NOTpWRg7ZJ3DinEiDw96aokw=,tag:gTvDe8bfOmHTfuW24VrvOQ==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:F+a/dlVXWo8bnVdVBSENasmeqA==,iv:4MIG3pLhUGru10E/Nj+cp1FWJDQocGChf/Cs65wpQ9U=,tag:GAuT6OjiMB+2Jx0Kct83vQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:niRwERs6xN1tCyehNF42Jw==,iv:iyUdcjnUXJhRImdoQw+JACqbP+OmYb07R2Qm9z7Z8Y0=,tag:9iKEOiNNWIWrNyNP/bVktA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueWxHRjFuaExFcllGOW1h
        S09NWmRIc052UC9mdjVqcFl4T1hiZllpaW13CmpTd1B4cXBvUFVRWjdubDA2NzVH
        V3pnMGZpQXVlTTkrNmhBODIxM3hod1UKLS0tIGJocE1zZzJqYm1TRmY0UGlxTWZr
        dG5Yb05LOFVLR2VsNFIzVTJQdkxxR2cKdrq33dHy2j/pppPxjg/or6H4yGven4DP
        F1GurI2HlcaswYYQK1ZxcheSdkigcKXccdQuLAOiqVTTmhC/n3rvLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:Jy3xDMC2dtRY80r4kaSuLn4QQd72sD0+GRmAmE7If5Nd3IX/ZHdD3cLtZUkVgBZOGW+XyhlgriGItdLtBeXRt1+o3ZvTfwb+SPH0uYbpV41gF+NLx+f0ujiDkjspO0XVJuDUSgFP0sfjwbzevHWLQQZzwzRg4r1U1BLjnTQZKjA=,iv:PVqEm3lCpoW4gd0W6bNeiSf2AzVlK8owCC099TepwRs=,tag:I/fwpVwufPAfjU2Zp60ADQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
