# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:oa4shmgr/rgZps9HXnePrxIGdAYscy6zeSWaDGlqff/0IMdN2HohNMrAY/3WcMN36R9l/ZGXWrjzA1uhDZZubuNh36ap4lTIpZMJS6qj9uyskx4fIwKzKSENqiySgEyhX4D9uLSgsB7P,iv:HJF2JOwmann86kgE2VndJLKK4R6LRM/TlN4s4MUiNI0=,tag:rm3AWvzM1iOvDSwp3rQdNw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:nBIPtSAhzb1MGY4Ndcs=,iv:ficDobvkD2U7V7ogvIhhIqYaIXiib42lUTF9VyGFUxM=,tag:pqtupfW4ed5e5RUHoRAuvg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:T15FNxnc3u+PKeGqtsyrjPT+fA==,iv:YJfPeGEYhWZ9k98vUKTTKXjHSeVROSPMu+p2rPhznM0=,tag:K3BGze1xz3cZs3xefZJZDQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:m1jhb0khAU8RgqxJnBIOXE1slA==,iv:Zcaed5HIzaiWRMa77lVDUaYS/8fq1PveYt2taR49Ovw=,tag:zEkOnTkqzmPIP1zi2P4gHA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:+Z9OCIZG+cMrhWvugCo2Ig==,iv:3RxYlf+rUFZCPWT/OE/Uz0imYHhjHJ1ZZkt6qip0bl0=,tag:EjcZI3PjEq535q4eGbLTYA==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T20:53:20Z"
    mac: ENC[AES256_GCM,data:wjIBTIwTt8yI72LpPhQAzF7iEqPUD93H8wmqvKivKFTwbeitEN4EGl6yULCtMlr0DJQ2D8JUjqEimO/Y6BwBzMeRaLwG1jy+cTKB9eX2EFND6gFNGb+uHOZNnr51+UEzO+7PXye+d2ILCcrVZDRD4JET9DL5GEnjGUDh5d1j/ko=,iv:7auqVoxh6nziQdZ35c2KsrdEp1ByoMOYB2LHocSu+Tk=,tag:V9TgnnuVvKsaH7t2Mu7OWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
