# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:jclSt0yCk+7o3Y6ebSyNlo9AL9AR4SKyNSsNs3tLk91ANagtjXdFJoWWiGIyaInN36DQ8X/8qT1K5nAbd8DuiT8dh9EWXW2ZcXQdkV4OrQzjh04jOT7m5LKsw979BzAMNCcM2UtAfOYgchmy2UuFYh7Yjtd4BCU4cIzh8sklwm3qW5O6ugr0,iv:tpYMeImCbhN9RAzovVSS8f92zIpDAHThKq+LHixcKDE=,tag:syHNPO0AOuhcXDQWWU1kfA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:ZP5QUIcq+bj+bnIKurY=,iv:EAMsSIabjW7BCu6jtHXBUXY2RTvJeoMQVG0vjXsEMsQ=,tag:kF95Nm74e3P4FvcbGb4QhQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:yqOi6GDwkmpOvWK7cDuaweqkKg==,iv:DoKLQZRIO6t/Ynx4MyeBiGoq6XQgOHTMamajUXrxVa8=,tag:7luXUkcoWF5mYY+4aGIANw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:ERbQGe1tuBdGSELwRgUOn8tI8A==,iv:n8TdTdFP3oSbOulJ/5gHl+0C/Jot5rWNktKcDlIR3K8=,tag:v32N4SjpJD4miZJ8RIVXaw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:turp66XqrmoV2vcNZQOOfQ==,iv:k3nVsHNYX9L9SBryvRhwyfaNjdnTcf2mkol8AMpp12M=,tag:tojvFPmHO/DejAoR4JwQEg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTmtoZEFidVN4cHNwWFhs
        MUJDRW53ZmhOOVk4bGFYQ292ZUFWVUxxaUhFCmtkN0hJand2QU1ZRW5DVGROZTNo
        QU5LbnBKWXBhSE9xRWQ1Zy9TOWdaNFUKLS0tIEtDUDlpMS9jekJacXZyRFkwVHFN
        MTd5RTFNUFNIVXVWbWV1dG1WSnR4TUEKpkEUqYhmFuap7algNg8Of3kbsIWdpPEr
        1WOHlJdEuirnoyKGidFMfpRoNcBA19CiSPe5X2Fs8NF8ZOT1TSS12Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:LRR95+FFFuqHJkRzNzFkuxld+nv3DGRxKUTmB5AcK9oGM6Ah0ah7aY0uQvYPkCO34tdKprLGejFjJE1aQr/7Gu8OO8d4BQgrcnuFwjtf4KW4009Dd+H3duz348BTL79RTymM1YYjVqr5Ec2y5DuKEtefTkq/qbF+YOgLAGVJbhY=,iv:jrOfJAU2/PaZ2yh9Ktbe5y5mrjWZKHozP1EpzgGkWFw=,tag:o4omnn7abDeWLfbJquwRyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
