# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:87enbsy7fSpACOk5FZ4Ihc4+IIW6EYyGGwU2YLCj6sBIXiUioleZ8HjxldZ6r/smjzw7XimtWbx7IW9rsGLmdrYh529tSLw6oPLTd+hag2ay+YuXCCZe06rRE4alJUi/fl6UsAlPoibhjc9lny6ykaoH1STjjLmyeW/T82TTkCCkHslre9pE,iv:F6wyKiJ4VE6KkBu81qjZFDB1CC2fFVjJbpiJhok6x9Y=,tag:bDFy5iJy5XTSlKJI6ywkrQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:ss3Mak8ug/StHhCHAlc=,iv:+AkCJAhDE9oQg6D25K1KcxCJsl5XhB8O6zLv2DnfOCE=,tag:i+Z0getgVM04DSd593OLQw==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:RuNVPamF0X2BgnYfghaH21AOMw==,iv:5BCGe/+UWSmRNBEH74Cwdk75ECimCC1oClkxcWrReRY=,tag:yS/rr4u/DDk1bs/mqBnljg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:TmWGQHAmReUOqpU+gvYWNI/Fvw==,iv:rEc8FplknwRFYZ0/mlCDDrbBe6lrUmyq91bw0x31VIU=,tag:bsZUvV8EuCuk7eskqmD1Xg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:n983aB1/C4PQsRZ8S9GUmw==,iv:rcrbU9n+IqcFLEHP3sUr+vu3+URYlhTsob3AvvVV1lQ=,tag:MUWrMEQQOhuy48OuM4T+2g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bU9yZXNmZ1Z2RHFMM0VX
        ZlJZbXZmKzc2VFVMN0YxMm1XbGZlZ2xhMXhVCmVDV0dxSERvYTUxU0grcVk1blor
        ckZMckgxeEMvS0ZwSkF5SUlJMWxyTjgKLS0tIDdCSjNPcDlWLzJjdFlBd3Y5ekVR
        cjZObDJMNmh1Nk8wSjlyUGVRUUFnN00KZdDhky1UjhYrO+24aNOm2Xgq2/2f31i6
        8rzUEmQGC2C29B3EGBQGzaeyh0RdtnqMh3ELf0LedH/1jaa3B5Xgxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:1cffiTxTcpe3IZlOJbumLg/YkcSkQWX6QH2OxHwpYhQmy58+NU/ImMC8T9UUekWpst/2Aht88TkJZVWuWIfD90VjXM3x2yEjGmSOssIbqSsAJTgd6S7V2d6lVmQAwxFn1a+TevPjXx6P7vUJEG8MS6gh6MxyaYVJtrzoRE+M5DU=,iv:pvaGwD7F73Dkzyb9HtAxhaEqyE2q+I1uEzf9rONqzwQ=,tag:HwWtZSGFleqt18iodAsyNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
