# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:3Yjk5nQB18l9seTJCx4SW2lAE0Bhmql9o89MEj8aT2Nby0duJPSDzp70F6WKAg6vetuVPDtKDO7l5RMN2I54kjk8eSxHhj6/AX/xpJdgUXrGO3oSZUsmKhCphyGEGCC5KVxttV/fTMo5b4VnZ0Dghbi4AX1GXtK6uujw4FFUAGO7k3V8K7kO,iv:EQAa8PYxNRZENN1chbD6yzgQHr7mpEtk+YGJIlr7CMY=,tag:UEKqzWSL4Cg2UFW8td3KrQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:f2LQDUmOVU8MTIpvze8=,iv:J77naFGiOz19ZwWtp8Ny1N0GGyMYXUJ7obQTX5xaYHQ=,tag:jPyrPXJ5hgaB+1IN2IG/2g==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:hSq198LHSKlfQG7iYM/Kwnp01Q==,iv:JfTa1JhMwEHyWKRfh7sDiw6V0M4VxYxftWitmPjoScU=,tag:9R909XyheFCtdb5/SLqLiw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:F0FkhCIg0HuX66IHnU5Xg8nEVQ==,iv:EnG6udvTPW5mfCP67WXMPWLTyrO+N7X7Mj34m+5Et9w=,tag:DQQDwjfdtuiWNDBC/rXxEg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:p3nANZYsVAnWdnhAziGbXw==,iv:By+ZoltizmNVeHtKB7aged4Fz8Saax4fDtEdswlahPs=,tag:VAUwHCY1423/vIOSXPefUA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTlDWUc3Vkg5Rkc3MCtm
        TytQRnNaeE1KMjRzaVZOdTdaUjVFYVR0aWlvCm94K09TMDFrbitjbVB3cm9sZjBa
        RE4vc0hCRXlLbnNIOUd4TTlGMUZqNGcKLS0tIFJtaXcrcFRWRjdKVGtvcitxN2w3
        SHRNWURoWGlvMjgxSWtvc0JyZ3ZvTFEKrx9GfrRS0LUBYSuxaMt1tryPxHWlfX+r
        SRjddmNRhWrjlF2IDXTpAW1/cBbo4Uxqg0DO4BeAD38CQZSvazKgmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:l+KVHOuUOgWOVxigk8mZYK0mUhj1s2IH7GjGdADaA8KPRVCdFaBrdo7gmNg9dmRCaTG//retD8ru1C+J08sQg9JANcF1IMmV402ou36Zrs99uirsSxQF89SV95vRq5D5ro99FoZiHt44vBZfXrPcYvQeSBU8qF/NslJKrl6aFck=,iv:cYqaL/3qVSmj3Y3VDzwzGvkoZTDqeUFDkZvQ49yngIo=,tag:CJNew/lVZXHTwoX7tpcppA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
