# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TH38CH5S/cvjVPtn4TKaOM2NsvlX9TduL/3jmlb7ag52r6WgKsNZOJgfDKRimKZ08/mJNwww24reJTjF4UbHzw0f8oQtQWrZdb+mkLVNaoAvT4QQUUw7okFe9ib7GrmkAbNYzb/uoxqR,iv:ce7EDwuD8BkaCO8LflEHz00z/daf1J0EJKIKKmwoTZA=,tag:UeeCJlltiz1ej4u7756CpA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:nBIPtSAhzb1MGY4Ndcs=,iv:ficDobvkD2U7V7ogvIhhIqYaIXiib42lUTF9VyGFUxM=,tag:pqtupfW4ed5e5RUHoRAuvg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:T15FNxnc3u+PKeGqtsyrjPT+fA==,iv:YJfPeGEYhWZ9k98vUKTTKXjHSeVROSPMu+p2rPhznM0=,tag:K3BGze1xz3cZs3xefZJZDQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:m1jhb0khAU8RgqxJnBIOXE1slA==,iv:Zcaed5HIzaiWRMa77lVDUaYS/8fq1PveYt2taR49Ovw=,tag:zEkOnTkqzmPIP1zi2P4gHA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:+Z9OCIZG+cMrhWvugCo2Ig==,iv:3RxYlf+rUFZCPWT/OE/Uz0imYHhjHJ1ZZkt6qip0bl0=,tag:EjcZI3PjEq535q4eGbLTYA==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T21:06:19Z"
    mac: ENC[AES256_GCM,data:Mc6MnjdkjWGn/G7/0kkjpdiOBByFmZjCKqxkX5fJrF01CKdQoP2J71VHa1p6N5/onP1tJSfOI+f7W9wgaNzluesU8Utjt9wK+t20j0T2KHQwPoaxX6kiZmjIbM4AwQPB5LqpWdmyJwnIA5koDkwcN13D4C244qALYg64wHUb5DU=,iv:AVY1Rw+N4uA+VDeFoyNUBOKz+uP/HZxgpf53OvPj6e8=,tag:1wpYXc6BL9M6MvrEbLNWOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
