# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:52ujLbnrPN5s2NTz6sP0WOaeI4AXKeaJUoTSrTSaE5fNgUO1kbmzMzQRCChE3gbvNljcGJGB7TultNB0MjDNoEppDw+8zJ8lAeYsW1kNT80BUejnjeJ3g+7QXDwZxxUvyu9EJ8wrohjz/r9Xrzs4SsLCOMTcIEU66GZMlGRoNtNZcMkIefrw,iv:h0Eec9zJp8HQi6f/4bZ7QrV2fKbeqhNpGG+108/Sq2M=,tag:H4S+U8G7POnpH85eesdi5w==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:FYZgvJ3WFhdLTlsabSQ=,iv:T4NectUzEzwLE40mAcNR5vaTThmbDPrF9ZvWdh94DHQ=,tag:rJsJqYh9YJxXRf+GZlzNCA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:pxMlaHuHfxE/bZZXUOxBiKa3YA==,iv:88X6tag6o9gWNshKy7sFubXMHhsNF01zsYNOg4pavAg=,tag:Bsm3GLK4Bjq6x+NILUW6Fg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:udVw619Bsjj9cVN+f1CTaJ19Kg==,iv:j7OErCS3ReMYPuHfVXwhRo3TKuXyDewlTMQLWrVn8As=,tag:BxuYhuchh9SEvqXyp8q4lg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:TYmRrfmKZap0Fu9TlF61CA==,iv:u+XDXKTLKf5Z+XvZiR4UN/+m/F7v7jAW2ZNI2ZgmQFY=,tag:8mnROzYlAhLXLFJAYfZWnQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd1UrUEVwMlJqSlRwUy8w
        R3JhVEt5MlNRS2JHRXg4QWtFNm9sWEYyL1ZNCnk5dkNHR0c0cC93WFpqT01NRThn
        Sm1IYU1oWVVGdk5EODc0cDJCSFJ4WU0KLS0tIFcwTUVNNnNGMXpIaEE5TG5PbVZa
        V1NXUEU5cXA4aU8zdGhSa01PdDFYZEUKUpauw8VQiG1BCCI44p24FK5LwMqzoyK8
        TPJmOqiMpVTU/YmexZLG7NflDXfgeltuJq0TWP+CgRWtZ7GotODL2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:nnCs+7Ar+krslKbLizHzaTUl+71psQzjuFw6GGQi7iVC/SCqz/l3crNw1ZNxBFCOIyhwXn1zhck9+iWuP4fgh1T+g5yBbEtIXL+J/6O1BBcFFVw/sqcXyg6kySESdGYprXQ5MKwtwvoe1Je5SQ6W950oSJZb3gbY9aXy8mJwfRQ=,iv:SQ+8nldkwT4qkIlFu9HdLc9er3eq4MEo71bGAKqDRMc=,tag:SDzF23nwIsCNK9ld6JfvdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
