# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:Sq57ihqBYAdDOMSbKMuK9L9QDu64tsll0OF4S+HGpL3+Sar1A+oNiXJ08WAz8zOAQ6yiAyzA5JqaoyahNwZhu4CwDMRTmEYJuxlxzf+UqvB0+mp+s+GEMle51k1fgmXQJNj6eVoUvDsfFsG0+YB7JAM3jaaeKDl7wg76OovzBNOKEskk6MFr,iv:f3G55MsMR9yWWd+6MZwXTW6TE8XgNv8UO+s0bf14+2Y=,tag:CRGEp5/Yv44SbzjrenFUVQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:mT+wC8RSGSPvXkFBAjw=,iv:xH0NgaL7Cf3O+7K083YqIFa4mv8yAbF/i0kWmXE6qzs=,tag:7M7K901btWiAAXi1ULSZIg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:dusIHJFfUjscYCYKtuT/tLqkVw==,iv:Qsf0eR0uHBzjSG3IMz6y65nNEWKllA+ETNHlPmGTzWo=,tag:wxDuGWrsPQaGJNWAPcRVDA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:nmMmf/OP4VnMP+aaRVH2956ZMQ==,iv:84yPjSbYxuCV4zMOyxIHC1ST/+TCvWIveonMwNVYiA4=,tag:lzVuSnuhDNCJlcoo08JgNA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:ByCdm4wgnFWxo0xumYGX7Q==,iv:XWW+AShZIFHdjpgixr1utb7vDYbLwK95LptgQ61wJEc=,tag:ESdBlOsqqkUtv3rxj5x7CA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QlpLeGpJbUVkdnBOaGJP
        OWhXNmg1MGJSREd1OVBYUEpvUXYwYmx5eHpjCllBNkMrRmxYcStTb1gyc05paGkz
        TThteVE3NFh5NFRPcWhuWWtuenJ2ZzAKLS0tIDZCZWNIcVFDenU4SEhXbTBpVHB5
        S3ZLLy9jejNJYlpORUNiY0tKdGg5Y1kKfDNo6Lq4QezdjLYqxytE7O1KqRCBaZ3Y
        I1HolI0uLuE4YQmho8wC/DLnaOEJNJc9XCr9LWmzIAcT0bcxDcAqFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:8O29Fo5C3KV4hDI8HCLPK1N3AXJstBwsOPfqYkV+S832+WK2wkdcV8VYh9P3Wvzbz/bVdSdVvW071YKvUT3FTswfszEIZ7ys+YVaIYK+cGqDoMjDTazKT3lBohSl51v87CGLcGdKYgzcTkhdPH2uBdNDzt2CbLthYApVxekQwWM=,iv:+qg0d30rblPEURHVpmzJrz8Ebfjhh3/cAVzkEMCBicE=,tag:OYG2PzfiA6MVYA0iN0gI/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
