# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:Cm53NQcdFTCYqboEJWDJX4vIKgNZf/EUfOZ78in52Cbpn+fOFUWkb9FelUYLTUZQALPP87ywQr+X5d/blGWcuLMaQH7HcSuvGWYl11VjPfZz2wxR5OyEN8YM9M5jjinCSsW6Jb0vU8JSIFw3qz3st0i+5Vu64MnjWI5m5duKd5rvcVahrBU=,iv:qir+71bFGV+i6Z+EzYhBrSezGKWPGA5nIKFUDRNzLqM=,tag:R+mdi3Z2FH7u80JZ16gbZw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:U2RckHF2fQ4HRXSzih0=,iv:2Mhyu/QwlM5nMGxowTXAKMPd7HGmTja3uqoa+wxsWYk=,tag:KKQhIn8MT7jFr48g7PgeUg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:u7qoEtxw29n5Z5LP/XFZ2eR6LA==,iv:A4CZzJS93vIYvbStct4XRh0Ru/eeSwLa+16NkK881bQ=,tag:1BpnnJXKRUO5JTD/YtXaBQ==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:V7z/AguIPc0NvCIU7Q7Cj5+kgQ==,iv:91sl0YrrSzxrolupusZ3WkQS8xHQhXuAF+DYensnz04=,tag:EkLYwS0eW3NDEYDQ61Bl+w==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:dwLZs66YUL7nxYLMkZG8/Q==,iv:2QWpst9UpcQmq7SMnjsyRswhQfP4XU3uOMMDsm+bUFU=,tag:n0mqophRT5cNkauphxJ34g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQWZxU2hsRndTenBUQmlL
        SFpKalc1cjRQcjRsYm9iTDZ4L3BNc0R3L0ZBCnpZeElDY2VEOW5BeGp4K1hVU1cv
        QUNYQURwdEF0aFRrUVJvaG1RdXoyL2sKLS0tICt2UzdQb3B0UWNncnJqZzY4VjZQ
        U3F1bkVFQy8rSm1ENFpaYmk3Mjlka2MKCz02wGpijBYsftGyvYCKsdtOJ+Lh8vvp
        YC5G23lJ5MEKMCrtm4z7WjZRcTrYYGkb/mLEdhT7TRFvY0WBXPV8Yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:uQPGa3W2USiwkwa9sH4P6cM1RC+PVuu+T6Um/IRVHHp75+3JdIOsGEYRY3jImWyfzBLR+l7AHkajzCKe9Q+HVnNKAgTX8TPOK/bIy/0f105DLjjW+DVa/nb71VFn2lEWuVKq/ZKldM1iB89grY7vzARuF3+tpRtVK/cOG316L2Q=,iv:Zh31j/6Vns2PtN4UhDXVbNDxmfvJfmivo4ISHYQ3vNk=,tag:FceNyXntAHn66k+NkV+sMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
