# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:W2CcAq1MZ191sjtZte4bt1xf4ND+5BppexVbjkVspdl0q9ZVqlG6yCN7XkypmtrzO5EHYuQMbsixnmzf3lVXG0fvy8d77dgUWV5yLuS0AJnTnnEHo1Kpa/zhz9ffazOGyJwVbuY3i1p5hOS8HWThK9D0mUVik1tucaQ01VFbALuXglBxMEE=,iv:5Vl2n1IrD4U121Dl3NIjrPsMQsQ9qISBflTLkTTjEDg=,tag:GP9ss0rURHAwd8iM9+ZUYQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:0OFvEoWxN77bMoe5IEE=,iv:QZITdI4fTT6xzC2JQUiPAoUGwX2s2ZwnUvYJrMwOs3k=,tag:MNn/pxb1Atw5F5bwDJ+W+g==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:z6nmCB6wrvsie7eDsRD2MIpkcQ==,iv:gxKMBmk8ko90/D84/Ph1kaioZNXGd+pVW1pwRKVabQM=,tag:2ZzLAD8XYPScADCUkprSHQ==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:ovFRxWR7Gs82BEeGjZzhNBnZMA==,iv:w9IhM+NNSy7wRzL3ZrTxvpn0cCzB+FfmcP8485iZUtg=,tag:Vjlbr8Fu5koYGFAsGn9yZA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:moou2tmG72d4GEn+rWMMdQ==,iv:jdNsqm8UfrzhP+c/vadKZuA9AxMQeHZJghn9a/kqY+c=,tag:gTyuv388EfeWllP547nTQw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvazFGUVdMeEZyZW81UTJj
        SU5CUGsxWmRLY0o5M1FXMzRKK3N0WnVMSEc4CndXSDQ0aVJQV25rVTFncGc2MTNo
        RElZSWZIaklieWlGY3JkSXY2RUdGN00KLS0tIEI0M2NMVTRHZ0pnMnNrRmxVRDRU
        U1E3ekZBczNVc2FmdzJKb0VQWG0rL3cKO/MzZv1kSBVX/1/EDKjku2INFrlBWI5Q
        I/Lgz/lwAqND2O5s92dwjDUG/nBNPobX243i1YFoN2A+CgFifj1Aag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:kZBVhsL6vQ6/FIPa4K6DX0T0r7s2eXAGiGJ1dB3vqGwpy998fXG5FmX3Lmoe+cyutnYmMJlX6UfXU8B5LsMe6FfbhEujnK0m+TxPj+g5wgcXKvMX7JcTVK5rmpLb7GRD1CBttLE9CwfUxjROTjLPQdjqVVd/WKiV2JmV6SuOpsk=,iv:Y3E2yKoYXep6mA4gxjjqXJoIv28DmYmBjoTw65MANyo=,tag:9fkkeK+IVPmN1Bm3rS0jgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
