# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:+7u1kfsi0zN3orce0Kf9rrf08+YEdn8UWgydgjPh557DniAeMquAQ8pXPLQd0vR0+4hLECXf5R7ZzM/fLmrwa+d0NXQs7VXJU7olgFvBTto9B/MIG23lzERENjRaEKpYewCm6qIIAMtQh4lAPhkcSuUe5eFPROuZfZN/4ga29Af6xRskZIc=,iv:E6mMAyF87K6f4UVX+dIe02aC+rnilfQ8nG8QAc8B74A=,tag:RXYwrX5MYC32fJHxnHDItg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:yp8wo3Oj8ODOq4pDLb4=,iv:VlZUgFFLoPon2Mvp0f8tWC9PgvBjy/jH7RALYg5M69I=,tag:hoNw7uIj6R/SbRFizlynCw==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:1ekm9Ce+B+6Joyt53q8yG2NtEA==,iv:PC3FiYkFTnHX2kkcqH+TAoOkyQPuWBx2LfmplRny9OQ=,tag:jriwXU9Ar35tceJNqCYOIg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:YmYSaooeKl/2+SEHu9qY7dUXBQ==,iv:3TvibMCdRIJsL3WZO1C84qRv1BgAEC3nCyhYgDAhdBI=,tag:qt6nxij3buASMJfoKCrPPw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:HbWc5oXhM4h3Lea1Pzi5BA==,iv:QbSAYwaK7HDZ1wghpATO2z0/dtY7kQDltw7fRSo2CB8=,tag:pNDbQYhkJCbyXCX1sO+0lw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTZaSlp5NkI4N2hEbjRr
        VUNEaUdKUVNuaHRBWVBKWTdXOTVYL0gvSEJJCjNNT1FaeklXMXp1K3JCa2Npa09y
        QVI3QU1BOHI5ODYvdFFiRFdFZjI2YTgKLS0tIHA4RGZhZlVsMmxiV2FaZVNqc1lq
        U3p5UEZPTXpaQkhxV1FnZW5iQ2FrbUkKdhzRicqs8Ul3vXnWBJqyz7ziziWsTcoR
        TrG4H8l44n9sMFKR06FVJr3p4N5bwKfHn6x9xmyX9gsBApvbLDm2og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:Cx4j3Zwn23qNoLE9q9Zv5PXYO5Y37D6sP1VSFxH39CI7UAPYxLYc5Oc2RDSgX02Z3gF+adF0NoufGXXYIr3r/CNAVK3YGXZAzz9OH0OcmfoBQNHamfL1ztcC/WTvikNr9w9aQZoHHusp0Mmj1kjWQ21E1WyOYvHXwocM6Mhed20=,iv:QyKjJbtv5yLnWL2WhOOiHZMFvNyeOaFiXHEa4PG2NU0=,tag:En2LpPyDow1d3zjOGSYGWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
