# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:CChk+/sDuDPG81UxkE4Q+ufMPz3Xr9/ebSQOqprlMPKgjXbNEucj+NG80cIBdMUZLFBl8qS+tdpiFkIdxGRppMpT+X3d6SMefr7UeQ5kndfpRW4HSWxkp/JC2WFguPm8DHG6FBpVpadMsTDP/O2hqoDqpp9f1OQpxjKykEBIXewk0g4wGZw2,iv:R9VPzFnY81vZHGRjGrC4aqWAZyxUE01Uf9r4aSxqUWY=,tag:Sa3UD1d+hszsFFEQLHYzjw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:D/K86B0Tvucm+Zh5U7s=,iv:pHiqax4buS/Rn7K2L5CtWYQjIVJYX8vruAbFqwVFXtg=,tag:ZvMAtulVQU4h6py0GbAaOQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:IVYGH3uzfZ4sBmUOA+pRK0Rv0w==,iv:KqE651JsoAlPx4Dne61KAwaGFWegK7tIElUSd+ztLu0=,tag:NK4CkF3dK9/fqOHMyOlYpw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:TnQKFJteYwf0kIxK0J1in33i6w==,iv:sOh0oqqffTwnqciiLoGEF597Vmc+yN06BTB5r9EZsK4=,tag:sUtijQTS5LMrJ9dd1QYoAQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:6wQBD0GxU1G1rr1S/EM+uQ==,iv:Qk2vvMsiVmB1PcQ//qdEhvKKn9YGsPgyRbcPRCuyGoQ=,tag:4lCqxNJ9DqAXheHeK1GPGA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraGxKYU1vck9ETXZPWkJ3
        bUErUW1GR1V4TzhubWZaY28zb2hkQ1R4R0dZCjRmbGY0YVF5c1I0VGlXdWJXRzI5
        ekxmQ1NqRkx2MFZsL0tqY0dIVzhzRFUKLS0tIHhHSWE1Ry9kak9hcWhwMVhRcTVB
        VHRuRGJyVS93Njc1ckJmSEFMLzhZMUUKfc2LrFWWfhGdY0ce4Did/GpaCRcKJS1D
        V7BjHDfBzsbJcgY/23l5hLtQ9GW+jhVEvMAP4BHQGGrW13/XZ+Io9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:f0vtAcXhUxkeo8ZX8ngNFDo9R32a02FLP6T/+R8UgaP1ZHwtWV3XGQb52/YhHlJthgMdb06rhe/dSuBAVMvjzMgKg9/038tuVt4T+FJHX6fiGYugz6dySfBp0kjAjJHISUDX18rbWWWkeyK0bgZyq9aQDTnSmUJYysnHh62IxwE=,iv:pNzQpmOeN9aZIXQpicZf/+wslBoqO8kz572p6FioZas=,tag:cCqYfPd09ga7NrhEhTqpWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
