# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:+xtigQbSEyRB33//iPfODCBTqJc7MXmoPnQTqhmhUI+KqQNVEbwV6qPsIDoodt79DjkcqHj291lHj81gJmngHHgDXF4eKtLpUQLnFPpGl+3K3+9KQzFNH4mLu37uyIdoYb4H0c06Z0g/BjfgEdlp9Rv1lvcGBCi3iRzI80A9gnDJhyyXg6Ba,iv:fdgKoDkzFAPjsDaYnegzqMTVAWudkgS0gDF2fPBnOWY=,tag:n/Bf3t/J70AlIYR2WYZYAg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:iQfOpYHOIFbYpsJOXXE=,iv:t+J7BDbIVkxRNXlH5p1nHidax0y9knyiatM0CkEKKbs=,tag:dMLVzPsE8rkEpQBrwsva+w==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:pnjgCQ/GIku7dbiyt6Hw6agNeg==,iv:zCkcGy62c/ytk5oO7CJRnOgKTgqBbcKalkmiXoailYM=,tag:vjYV9kZ5yLxSr5cocp5GYA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:aBI3eYq4vw2SC+eEv5nzDMjnzw==,iv:qtAMPXlhmHT6laiYYsm9XC9JXJPpO5kv7gJb79Z7p70=,tag:CP0U8OtbGXYobCes/6yQOQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:HFU4Fs1iy81Uny33ZTfdzg==,iv:h0Ls6y3i44KXAXouyKJ4iNYgH05joeH2b8mgnatgZYQ=,tag:VNwNCTNZFaUcUJSa4GRIyg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU1FzYTRJL1c4SS9YUVh0
        cjZTQVdxenBwaXpmSWdhR0V1cGU2Tmc0ckZNClhaNytwaEtadkdKWEFZdlNCM29L
        Si9IVXI1MnRoUFpySHhibGtHdU54Y0kKLS0tIHZ3RU5UcHhIRndiTndrOVZMTk14
        cEVBQ2grWlY3bm90clFocG4ySHlmencK0oHZogl5lDvgrCVzoG9b7c1v5W8WcBxC
        OqZ4H9RuI+DAk3FZbTng53mcv576iHSvkTo2dT2eT72Hw9XKGuW82g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:QbR0WnXbqkUPaJmmd8uzYD6qzKXouMqw9aQHdGrVJw73cA4TSjyD06g+Mqt46cjhI9paEN2/xnn6hukqnTBNu327w9MFmyMuqd6281ev2h/0+GoX+DT+QzMEFBJ9AXAxkV00t/ti42H8bcfw2deUTEZxwZyG5lCRVt9sMtrqe3k=,iv:Aq1Ent/EsQhfCAPztFPS1jClmSnpNCmh0udeFkwe3EQ=,tag:1vYkqbeTHjW6QcVI+o+JPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
