# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:auIzKvmU9Bu9aT3GWpeyXtxnScVBSFIZ+u7FB1gh3KWNns8EVLlGI+LQfH3JYilG5i1qlGAe5ur8q9RsVamtF08fZjGdeLmsm/Xbe6/A0vTPzKyN6oLsQf8V7DPZieXMqIjHrDH7hpq1xm6BEVx+snb4sevcC38dYW7D0Lji+kDlgvK9UBap,iv:gOet+YqNfGKActCIhnuHU2ltJJPaMJN8P0oL2vH2A10=,tag:P/C+EoHhWPe2e1gSRE/gIA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:cKniBH5gQnY9+jVXCuk=,iv:2UrDF9Fb8rwhovwpyRh9vMlqksR8Raye7ZJ1kbcCO+U=,tag:UWQJVu1r+Gjzb9hYMs+U6A==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:JvJDn73RuR1iqJs2HvZYvNBhEg==,iv:/7KU9Ujch6up6rHM+3MlUGSftsQ/cRQ0GlgpleL5nbw=,tag:ujNK+ALE840zzDtirFiWkg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:s4CisQ/skeVP2KKqib6YRRecog==,iv:DOpYC7txxPmkJ8OTUaYvxJTKU7ZCfeC50dz7xLFqql8=,tag:TUL9WrILLb1QtPcdimn6uw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:wI4dd7GOkivbHH5689hj+A==,iv:uucW3b0xnnFhnMG+2Uxpz8aT6iYlddSXD/fA068EWNI=,tag:5UocX6DUWuG2Yp9dlH6HQg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U3NpWDVsMjErNE80c2Ex
        OWk4K2gyYUpzOTJPWTZMRElVVGhiaVNoMDN3Ck5qV3lJa3N4Z3NnaWJIWE9pMzZz
        NnB6SENUMUtkcWFvRk5HWWMxNlFlekkKLS0tIEo4T09lR2lvYW1PZTlkUEFRU1J0
        akdNVUZjYzVTaEN5bXBpWGtKOHlMbGcKqbkRbTJmF6R6HJzK8rIRJmqTkxQ6o2ji
        B8QAlHSbfbRsg9HZmNT6MqAvCW4KOFlblYQhR7rpuy/CAmc/BMcSGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:lDh35H4M8Xj0Mdh0vUNlFJ1rGwjLNvZlOEOyx1WfrBs/u6VXB2L69uGxYMS+d6yrq2jcsSLyIBGKk34hryEoZDPIcLuKp7ZnsMksVLdr/Glq/F1cnpuRxGszOmN3xWXgrX6hUCnpj5xUJ1f4s6q7dsxP2IMPcl0w/GaIiS/RW7A=,iv:R7XuFJnht33R9PnpM1zXr1uLB72VxsNh+220+d0Fr5k=,tag:vCsmZ2GMJz9jPSp+GUPHRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
