---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml

configMapGenerator:
  - name: opencloud-config
    files:
      - csp.yaml=./config/csp.yaml
      - proxy.yaml=./config/proxy.yaml
      - app-registry.yaml=./config/app-registry.yaml
generatorOptions:
  disableNameSuffixHash: true
# configurations:
#   - ./config/kustomizeconfig.yaml

