# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:R1KYNA90gynONo1Oabv4mzpBwizXRzWFs5Gr,iv:scFBrr9KVbPMAyLjHe/e37aANxQzRXlV5peNKF43UlE=,tag:J4EzR5yCSVWNaUvYavxzKQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeHdGbFhSQmdaR2p0VGRV
        MFNKb0ZSbVM1L1NtaFY5Rng1Q0szcHRiZUZFCklZeHJmQ2tsT2FtcE85MmFpMFlL
        d0JydHg4RkxIRUlyZCtQUFJxOGV0cEEKLS0tIFpkaWYwczN4N2FtNmJVaHRJcHlr
        RzRscUZ1NVl3V0QwdFB5MVAxcXloTzAKe8avs8tF8Uvh/cbi+o+NrX3PLnBmH6wI
        OJ6BPdByT9MRPwLampgKHK23AsoAO2CdfcJqyg4GHCKPhraQ3ydEqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:4sgJSvg+SqitYpzg8DGoRtrzwNZXySieNhokImjvuwmLmErz1rEYe+Jo+uMj+SHfI2vGwoLKgj3oE66VwsVtGBSG3igKDiy+dpqj40z9RmaBBhSuX8LGuOqLpowJdoXHBzYkgr5ClF46yRXeWr/AdfSnFX1KznCqAlZ5deeXGWQ=,iv:rkJzrTGrUcA5ePH0vYCGQWA8LLt/igyRxx3WR6689/w=,tag:w8yYOcv+L7opb5hreCIxVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
