# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:RdEqayii92z/zdUx7BpoAAuQaMLyJILC36HO,iv:G6Ai4YsT73IootZl6jLolf/bI1/omIYCi4+SKNJToP0=,tag:NjHHV6KI0EeHFBmeqsW5Fw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaEtlcmZET0hWeGV4WFNH
        amExbWxGMWhPL0t0WGF4MUxUalRMaVdlWGdjCkF0YUtselc5enFoZ21DZWY1Y3E0
        QmUrTkZ3eHZkR2d6U3N5bXhQcFE0N3MKLS0tIC9WWmVCdkVjSTludnMxWTRrVmpL
        MURoeEp2VXc5bExUdGpNZXdlWkF2a1EKLMNffndQL+NeiuhhprgOB1n+YaPAEJPr
        tbUdkp9anhZ5lAKwpD2ZdZGxdtJOg+w/QqpS+RCGE3T6NXJV+GbIjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:4FYUt0x5lItvijk1CtuQGm2CxC8VQjU+/oV845q+jBiX58oYpZR/bXsXasnqNCeRUAYwahbp9XXV+8NNEgh2Fb1JI6PFVYxLPAKpb/6hZdJoXto6J8JhLMNqK7/v5oYxx6wWbvDmBJzP4b4d1XPQEKNDi8ooj1Kck/B6yFOMosk=,iv:nIUYOF8KJzmaWbBOZvQjOyMgmGMT9ttrOcELMDHRKGU=,tag:sqTOpAX2yEqHsHdIbchkoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
