# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:R6L9XhRb/ijBH4dYztYRu3HRliteI67XZe24,iv:1pUrdyqygfYECNSHkqyArV9QQaD2Q5CZ+uoiSMz9r5k=,tag:JR2pcEZofujJ0LJsYYM+iw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3FoTUYxd3JLZWdNeldJ
        b3NLNzdCeWZ4K3Y5SlNqcEZLMk1XbVA1VWdJCnRJcHY4Vmk4YzVIdzRMOG1BNHpT
        bE53ZWhHc0dnWGVOdTBXdG5mTGFKcmMKLS0tIHUzMjZicjBhZ2NyczhwYXJYY2Zz
        cUR3WUFMZllHNlBOM1I2MlZUNmgrYlkKwfrIKMpQgfJSL06gjeA9VW3yA6ZxXR4R
        YLF8NkfPd9/E7meZwTCqzg6BYd/iRmRCM46AuDU28Hk5qpRgfKMDwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:FyZ3ud++o+mQScw8wnPJhAvNwggrt0FV79zKl4pqGXRM9KWwkxpCGKKiKEEnczWnwFzkSDwhdQA4VNNIuGmz431NHIPGQWBxbaVd0At7fNjQ0V9orFZ2F1hxjUwGpHQqtzUtgptorQQDAreDPOqSEbeR6xdSwW3631w+MpiOmNA=,iv:tlvo75xmha1giLtc+V4vEjdwzUT9wdG/ZzIt3mCosxw=,tag:FSsEQ83BnZuFR5zqcEO1LQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
