# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:T0p48G+Pt52bozDA8QcFKZZgk7okw7csbQ3E,iv:ulX4mFc9r/GlcdUZDhujrS3yYdJlnLgBWmDmHb+m3mU=,tag:V7K7wXgd64VkTY25O+0aEQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRXdFa2ZtM1R6Z1A0YjRh
        eG1VeWRZTkQ3bTVZS242MVNxeGRZUnBvWXlBCmd4aVBQQkJzT1VpWXJBcHl1NXhG
        QkZkSmY3elAzbVRneEFPM2Ftck9hSVkKLS0tIFh4cm1DSWtDSElObDdlTVk5OE95
        dnc2alp2anIxbHpzaldmTlc0QWNUcDQKMcgoQs7w1M3xE6+u+O/ie/teMevF30Cl
        lic4KD+FRskt1ShMxQoDtGppkMSOgwbEmyTtITRGknDMe35BvgicPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:RU34mZWxKJ4cR+pxueC3JUpMCsNaIowM+Oddn9W4T+GQWQxwkDqiSylCd4SCK0TN59arEpRi1tc1eijhvYbM6XBLlwXrDXMCapoPoM1Afe54wNQOw06q2ex8rbt04L4U5lFH05E1JeihMk0egO3WeCV9enLF3rmYC1EFpn7OlOo=,iv:gxzYSAUKSlu1UuhDihsPEfiTsTUoH/ISVSJDnWeQFC8=,tag:p0aIVobJWIF8S/aCUJfQQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
