# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:CkH1oYBD20HkMg6Pq/jZ2KxOrKvFvdtmwdTm,iv:ON291Cgm1C9m0b1TUVFT5kZ1QYdzSoFSQ5h1qJQoRXs=,tag:tufGj2v8coxXHbXDEfLHaw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TVErUGhTRnNIWSs2RUFI
        WUgwZGt0OTdSS3hPK2ZUd2lXUklxemRDeHhzCmJONnFaT20vdXA1Q3VYdnErTFQy
        OThqNHR1V3VNY3d0MkZuSkM3NzU0UjAKLS0tICtGZ25sY0VlM0pLMElPS2k3eGtt
        Q0g5WU4zTzljdVQySk1icHZTWjZKOFUKY6UJCF5ejEdJXf2gsjwGmaLEG4poSpkd
        Dw+CC+nENyQN+2AEhcDvog7/lQbYxexEtzx/tuScHCLTK7mDdVTM6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:J/956/xlETyHiW+pt/COmIz7pOTtV7xgiqS/6ms5tYuzUL0j5Mi+JvUlXgVb6W8Yq31OopFl0YrxFxUQp7Hx1Xv9uJKBj+/jL+YEL5atfr3NbHyOCoM2GJ9ZgQiA6ePNggFYSvPwIxzN8KqnaSMaa4DBjoeluVADUiR6gNyBo6g=,iv:fFhFXKcLihCONRStK+KjbpMyOJuodvSigLpj4NTy2HM=,tag:/fzBzwkbbOWmMbby5flKmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
