# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:ECQnUBX3R5QzZ8k6LD9agosb6pfSm0SL8skp,iv:O3JZIZY3nt3o2jLOCxnDQIpXTJwqBJ83f/qSdzVFaAU=,tag:Pb//GpB31ZuUxa3Vr4ibdQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaGRRa01KSyt6bmxuV3hX
        Umw4U2p6N3pGbk9xOUVSdFc1TlNOQ3grYkJrCkRKalZVRUpHeWhIMHczMTdYSys4
        NTRtakJUVWk2MndBdzVQQ3JWVk5zQUUKLS0tIDEzK0I1SUI4QXdJK1FYbVRML0pn
        eTBYZDg2UnJicXlBMnZPV0NyUGhsMHcKkmd1cQFR2ksYXgaCEs2Q3OTWDEv4u6DO
        OrcJCEh6Re8aPVn+wD1uYqjEVxNVcBS3SWZc6QWzadeVkhJkSBPp5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:z5/BqtZ2e3LX4uATQuRBsL+nVqcSmqaS1a9771tprASe+PouvGZBTAthspq5PRs35mkDvrqhdnYG2HMlmBGXhvJz7Eq2giwR6p6iKdWAhhJ7EXqME9Eg31CVETPeM9A1ND87TRrzGReYBd/brXt9rJn8ANVBNCy4SpC+edw1iFA=,iv:2Af0MbiwUgMnDvcLzGaWJgtzul0IGUYbJ6mt8+HpfuE=,tag:ieopiFkaqQvxae0mOJEyOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
