# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:4H6itlz8RvH6nYWHegcYyB4m87v+k9OpCvTZ,iv:d0+mrSRMMgCtKkN/ZOwr1NVD15RwODScqgrdM4TSNSI=,tag:NRobs9SyxSkSyO8OjB9bCQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY01rb3hEZkVqOXdYTm5n
        b0FEVW55SzNzWnZtekVjbzBvOGZnbDNIWVQ4CkJLWGluY1YxSkdueXEzZXVqS1Nv
        aUVtVlh5c3NnUTZadWVkeFY3Z2xqRTQKLS0tIDdIZmZqZ0N1d2dNNnBMMVlNOVdQ
        Q2FNTzVDMjltclVJZU9hb3BUWm9rTmsKdUywMuver/HxBmjhRcRPk0qK9eFnuvn6
        CwAKjfblpD6Wsp5q4OZk2ZgWjnzIerIIPUJTQu9IxuH6J58TZt8lDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:8xYSrBrHvMBUcfBfc1ialEoCzYeSYkEBb+XSQTMPGmQGfKLU9skewXzAj7M5fVs1QaX5V9ZAxQ0qUplKBlis85T4REQgPqOJlBUopxusyeNOUCT9/ATcQIS+9/h1xF8PpMF9Nh6+b+4YOvf2Zv/0b2E0euy+bfF5LWlzLk7L8fk=,iv:7mGwzncnXJESXzFq4apd8UIys6EeG3FLXRRGtWHydPQ=,tag:PTj5i2cp+KBjc0PfPtKPIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
