# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:t5AHcbUV1YfzNwpO8CwvF1FH6bkVr8ACeuZB,iv:OhSPWfCkFKqAtIRKZtdQL45zXPEKUGm4T3zRSBawzNE=,tag:14ukNe3eTdY70tRGDeGrMw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRXZBZ0hzRFlEc09TWXEx
        enBDNU16V0VWZlBHYzgyRFE1RWdYblBWS0NrCnZKMHN1YW5vUkwrbk5IY1RSUjhG
        ZGFtRUdodk52eWpKUEx3RFFra0Fjbm8KLS0tIGI0M3ExMzBOSHZmeW53TjdpaG8w
        OGFzcmdNZzZwbVZ2UWdkVFZUVGVrejAKAP3i6Af5vFdPLZV2eyxmqD91vtx264xh
        4vBLU/NpeTktKtcbDPmjhM/rdaNO6bUXWM3kL5olIFiFEeLCmXy85A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:adyaGRbWojoba+JtVTL9wTijAlBrdUvDSPsOtIF7WVteGLeDHOE9Ki7yeI3bHg6L55qIhKwN3HNpjQfyIsF3XCJGOnnku9xOBfZE5C2pf2jem1hkhGWr5S5y2Us8JbbuDaNXtYbKvGXCbkf4wSsYsfYhIDcALV3IlZMKW0kkGFs=,iv:mVEOSlcIAlxCrRDtZmTrrHKan1LYUye8XwMatcW60W8=,tag:vn7Lu2xiKGkScme/75jSRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
