# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: opencloud-secret
stringData:
    idm-admin-password: ENC[AES256_GCM,data:UrJyBRzPF9uRRaWej4Nm5GjwtoKYCTOQrIVn,iv:2JIv3awLcJnKYa5vXQzvPA/MNRdtMvg4ql+TgYT0aJA=,tag:WSpWFxComQ+PGqTqcRKalQ==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3FoTUYxd3JLZWdNeldJ
            b3NLNzdCeWZ4K3Y5SlNqcEZLMk1XbVA1VWdJCnRJcHY4Vmk4YzVIdzRMOG1BNHpT
            bE53ZWhHc0dnWGVOdTBXdG5mTGFKcmMKLS0tIHUzMjZicjBhZ2NyczhwYXJYY2Zz
            cUR3WUFMZllHNlBOM1I2MlZUNmgrYlkKwfrIKMpQgfJSL06gjeA9VW3yA6ZxXR4R
            YLF8NkfPd9/E7meZwTCqzg6BYd/iRmRCM46AuDU28Hk5qpRgfKMDwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T19:38:42Z"
    mac: ENC[AES256_GCM,data:P+1PpGJrXQgrSnz6HmmIK9IyqsgUif55HXQPwFEI92rucJ5INRWixdhfh4ptGD1mwW3oY9sORMMbikKmQdjCTg8ob3F/5Q891MD2kkKezo1E68B+WdPFstszSi5rhjtV/LRaaKTzRqCAYcN6tD78VdLtL1A8Msq12yd4HheR4+4=,iv:WqROOVm5m1ZAoo5g1bpV+U0XkOZbZi4zbLaPIgdRvCY=,tag:x7gquqCWMwgKIGFt44nejw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
