# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:u4qd2Et/+slhI/Gwal7SUGmX36jtTJ/tkl8Z,iv:5aqBK0y2eq8GjZOPSLVTTRqrblrM52BhMuktqC8nSeQ=,tag:UY3trYLtFqxBYFW85V50PQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmdEN3FlVmZFbW1nV3lT
        SmwyUVQ5YkxzLzUrT2wwR0dFdGVIVWdMUlFZCjkwbHVacHpDb1lJZURqSjhZN2FN
        cFIyZ2E2ZStoYVZRc2dadEZQNlVZcVEKLS0tIHJ6aE9pMVozSjlqVUR3MkRpTzRm
        VEpiSk43dE9MS0R0ald2TWpLU3RzOE0KCGU2/D+jAkf9GRDc6AhDdYVEhmqUnEoP
        imsKWOu11ZPJ8ADbaY7EZP30HVsxHNH86hGHBhi6Y3O50+pfxNkA5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:tpF8yDQYJJo2OqvaqGMlmOrMl3f6/zK0cg82ib7iOPgwQ6TvDgGbu0KcqIPTZxzY/IBtNn58DdMJs7nqCHDPtKm9hQ7VkcGjOETBGoT20pS1kJ4QSo/Qqrd0wP3hunO0jIDXX03MhEp1p7w/pXHOwT0V1iVGf89U7gz0MNUbyIQ=,iv:i3Qtmj04wXsNbkcbvx1lx7BLvbaiSkuKZtrnIyw1/Rw=,tag:pzNfCHuyyvB7p6V8vnXUsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
