# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:rjpvK/xe/jty9BpSHkj7uYyRhJalAMn7mBtm,iv:ht7qcZUKzAGdMF8R78X4VRGyEQtadpASu+V7vgV+vko=,tag:o8jY6Grl2/ETwE78Ko1ZDw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UU04K1J6MUpOcUdGRzBU
        U1M0Z0ZuTzM4VzRaTm1wTDFuVVIzUDJkTzJBCmk0ckNHTzZvZ1ZOcFNUa1JFZkI4
        eFlldnNMVzhlbjMrN2dRWWtDTWwyWFEKLS0tIDI2ZTZ4U042NWhiOStWTzlaQVht
        MUU2QzB3L3NBQUpoNytFejdvbzFwRHMK1llBlx7QGDHDoSUhXCWY97PQSMR94KxU
        FgM7FKjlZSpcRQcUKFNTX8PqG9Gc0eFRx07nnWmFb2qV0P/Uqfpbmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:oupeFe3Vu/cVD34SOgE1SuEKrdVCcxQOJs3O4t/8oq8HAhWqqr21zcS24YnP3bG1ACWzSpgkDRl5vJk6VQyojL8Zl4VBOCIGeMTkKwAOUsiFIf5RjTK0LR+oU4UAsOgBg8imLfERmJVXePds7Me3pTAD2UJDR9SLsnCBxYVKsq8=,iv:p1JxOz9KFrl3Xx77seW2ocZt1JcD7yska2y7z4SeT+M=,tag:rtcmP4BOW7M/eG6XBE2Dlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
