# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:ceJceRhXeBvZVHox+S5xkKS9shjmUlNWIua2,iv:fLMZoKXtx8uqfPmy3fO7LgOwJDLvH4E2pK1avleWC+Y=,tag:bmBjYKOYlNeFYEUgI9jfJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROUl6NnhjMTB3U0N2UVY2
        UXYvK2luL3RPd2RmUXEySlI5QnM0RFgxUXhJClRreENpcFpTVGFsLzAwZE44Ym8y
        OU5vSnlSS0pnanJpL0ZxaDFZTnQ5UzQKLS0tIGdpcXdLZVZnMDhNSG5mS1ZGa0lR
        OWJOQzZZQVh6Q2M3OVB1VkZSTDIxekUKecBk+QwWTn5g5PXD1VK+36HRlJyfrnHY
        +drVB4hRM7/CJ+J7iX5G1RFV8kMW3pJO5gCyNYp5THeIU2+1LVcqhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:qW2gaWk0NWVNHhZch2nS2zqcX6V8GwZ9/GB4OPsenwHZGGo0UL8wBlyTmCk7wablL+Lg+aANT7AciehBJEFxdwVVRNvtrLFv7LzqVWFh6RoDsAVBVHR1CnXpmdKPTEca5vn9Bc7sACcmUwKkVuFQkVB6k2UncFiF8vQRpwKY6WI=,iv:cdcRr609t/3CJmvkpeHfUPgmLb1Jy6ue0wPKLXEgfzI=,tag:kirX3zUAhTTNxjsCZaQjmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
