# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:53QhBDwdljzCLHn9U0AESWeAIZ9ao4pwdN1W,iv:PcxLLfTceBTpPOFuv3tc8aXccJ763zqTP+Qpe7I0Bgw=,tag:M2z9z9Bz+M8sUPV/ALykHw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdm9qRy9SVzN4blpRWitN
        dGxUWTVhbXVRd2hqMzIwUktqaTBmaXljUlhVClBpRjNuRVNvMWhEL3daVXVhbFB1
        QXcwQWNrd1hDY1VZZ3BhTWdlWUZYR1UKLS0tIEhQUWphL3g2aG5CN2pPMXA5OHlt
        aWExWFZ3eTBROU1YS0JTN1M1MmJJVzQKsDtHXaMnRp1s6QxI2Y6+cL82+x8MXr+Y
        0bypR1A8DBxc18ms5tdgSqa7uwjYH5HXOYeebrh2L5HIXD53KJVJLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:LOpPKuuGkgEB0Im+OGODDjD/015QhTc7UZM+PJ95f/hG2nK01AXNAoAAnbkJWihbmXXyzVtYuioEia/EpSUKLJMJdOJcaVvQZYwde2Ao8UFPw0fYB1sN9tYTll9UYqlvOh5Hm0CFuFNU+hhH51IlVpS8QHqENgIbFoKVdCT+T1M=,iv:dPWtvXZLvj1bdLLi1BF6J3kdr1RGUZy3FbuHzxRNfqY=,tag:1wng++SrnrlMK5rhUE2T/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
