# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:3NN+UeKiIhHbkjRywq3ZvS9Qu3cXGWmCa5p+,iv:E644ZBC6+p21ZhQLXiOdExUc5IXs9kKCveAPljgGrpE=,tag:CSaIFoc7B6S69nfrQB3fdQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZGxwbEdBZFdERjlUcGMx
        WWVSZW41YmsrbW9lRWZYcmhONGxrQnhEbXc0CmhoKytDcnJ0UEpWYStjKzV1dWNX
        NzF6YzhFNE14azIyZzBGUEdTcWplbFUKLS0tIC85Z3ErZlFlK1dsc291Y0VmejlD
        LzcyK2tsNTFxMkRKVkRVaCtEYlltVWMKp4NEt+5Q+e2Cr7sGRDwzzFQO+PuX0saq
        FuAGWewY4haO0vyjxJIPlEBW9ORZJrf3HUjAbfNG0HtFMpyoThO+pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:RMdFAyG9ILoVQK5YS4JGT/aC/tg2izK7s3GwZ8RoaQ+kp7iDIzmiBsTvw2DOD+mGPhj9nyKPDgp3VdllvhnkUlHUW3ID7aG0I9Z3G5vp1naaLud5WQ5jYWyjQmM86uhOe7V+AFmLxmrUv7Owbz1fvbLcX60VDU+ty8z3LdNSQXc=,iv:fN/Qzgp5tgWVXOgW8A+JPpb/lrBQwKok3PJzqxZBY8I=,tag:oT3mYDSdjypD8eOsZKgNMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
