# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:rUUGklsdmDbd/MbMAbaXs1sOkqlIUlVuYZYs,iv:oLHGClHWpul0A0LkTCyhJE24QljTEMVUkYMl2I2UYCg=,tag:2IJ2tSxHYbz9efoPPPu3fw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1RQakptbHV3bkNuNTdp
        b2gvZ0JvOVhOMUcyMG1vN2YvUXVMZlRTWlRBCklIVnV0Q3ZqVlpWcERJdjVxUk04
        VWpDbGN1S2libzNZMkhxQTJZc1ZGVm8KLS0tIFBjNFVsTzJtWERJbTNIZmp1NVQ1
        TFVLLzk0RmhSUmlQTDgxR0F5WU9QUncKBWqxWV+3hhjeW/FVZvUT5lTHWo9Oo27/
        LxwB/Hbi/9/vBJddnAL/q7peA1n0d9VEuMP/+KIfi+CX69GflfGdRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:kTXGUmsWhNRcS13EwiI2dJ2SxGvVEeYN8LMV3X+7VPKZYgv5qUqD7yF41iLBUu1B/v9fRyT9AwIDbJ7+AySPxgTO1hm4pjr5y4VaBwPfNM1v6N+dM/K2vYMEYgJTjJ4YDN8bYRBd3P68Tm5qyH+xi4X3QE+jlKFbIPqC7a499TY=,iv:w/RZeTpKdMd4twc170dYadIekbGs+6OcmOJeiGGBHcU=,tag:ZwcpzvT0fZA4vzhG0LlnUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
