# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:Q603eIezjwI/mn0Oio5LVXv22ydgBLO5G0OE,iv:CVklKnblXFgFlWV2IQrFto7UGB59LWsnIOcJSjm2qXo=,tag:lZZJgi5Mzq4CKZ/SDzxQsA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcnlFR1d6bzBIc1RuTmgv
        WXl4VWNTbTNSK2ppYWVwaFoxbmF3bFViRzJvCk9lSEZpWGlkV1A3c0kvYXRhNGVE
        RGdLcDQxNk1NSmI5NGoxWlpodURmcG8KLS0tIEdiRnh6bjZDVjJ4US9IVkFmR0lY
        SkhtQmJwb2ZXeGJHNjFUQmx4ejJSMmcK7Xz560d/WEaQDGy80+vhMp7ZiFnSDMkb
        FBAvRLd8TcYMiur/zNNjf0dXdagKmkhEMMAAGnizr8tEM8bZZt2dRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:s5IV+gPt7BHr0MhZu+QT63fD0oG4IWICOhyDa6yQubtJeJsBQ1u9oSvQGTad104gJkUNQe0r0ZK2WpzK42LPuEGKFaxmvfmlu+/CVnyeoDqnV6OmsCx9xDTzhgRRB7DewjLZwmp2nAEbEhPpeljC+YzRZD4r+G4MJzltd/udi3g=,iv:fjJ58z5H1OmM8bBOC49CEk+sl8UpQc3TV/uH/+iXiis=,tag:dQEzMn8o9Kn0rQVSeiHrsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
