# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:QJcs83ShMkEueDvw430ZAqrdtAX2ALNoCboG,iv:oGi8fwlkjrYIHgx9I42yxI8m1NVPpQIYf3w2ZUQeIeY=,tag:sEC9YslnKG91TiDGdlLL2A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSUtreThOODhEbHFkOXJn
        R1B0dGtHYXdQdGxOcFluVGZjZ3BNM3g0eFVBClBnR2c2cEQrNnFBZ1JjcHpkd1ZB
        cGhQaW9RRmxXa09XcXBQUHNKdEY5WGsKLS0tIEpyOVV4Njl6alhQdWYwQ2JmMm10
        aVlnaXhJWHgvWnViL3hjYWFtMEpTVVEKTxNiHZGiSHwN7DYBp+7Cd5uSbItxkY8n
        C09o0X2ZmNYRzXqY3LB04wzTr1d3HXM8376v3XSj8ia+X5unnd0ZAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:ls+FOP+Om/mWGm3nObqyAl+Wh9R+8AgDIe/Iyut8zmfv2IVI3XgJhaotFYtgBc5W2k1apALfEJfgitZ389B3cDoWb7qGu3qc72qh+uegNe+fjAms2UizxIRZG5dt84nfCjjWt9spCBLcxa6bMjRAS4QuO5NriwyPX+R+1+zfQyg=,iv:+085XSder1SBFHc7ImKzQYh13J0Lxcf00rt1zU1R8N4=,tag:FScNgVgmrt+Qn/Mk6cuzbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
