---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  #- ./cluster.yaml
  - ./objectstore.yaml
  - ./pooler.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
  - ./podmonitor.yaml
  - ./recovery-cluster.yaml


