apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  configuration:
    destinationPath: s3://barman-backups/
    endpointURL: https://minio.harissaeed.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: MINIO_ROOT_USER
      secretAccessKey:
        name: cloudnative-pg-secret
        key: MINIO_ROOT_PASSWORD
    wal:
      compression: gzip
  retentionPolicy: "30d"
