# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:x13nYvthNeSfavZmac34L3q0pZtf,iv:L0sfisiBSr4hs1yhrkPYI9ywLhQnWZqBnBhgsu3zxi0=,tag:U9lDlzGpdUB8KsV6UfZP5w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTk1veEx2OVM1dEZiYkxN
        YStnL2hlR0p2NFJodE5CMkdUWHFhZXVFbUhjCnc0bUlLUjNLdDIvOTVMM3N3citw
        N1dsZU1zcUJOd1ZseDl5bkZub3AwYzgKLS0tIENBKzUyVWYzZVJ3VnlJWEcwVUJP
        am4zRUE1eWFBMnkvV0JJNHdZMkMvMkUKlDf8gWIXWBjP2s75g+ox70vhDPeZCEvD
        nPQy5bHyn/3qUKonBQYcmdQRzXEP72Vzq6vN+rOXUmm3q+Ys27gbTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:nuZsBjhccfTDvt5Qi+zg2RFljLqpQcpJ2wS81SdFmTJtbDqPRH1L1nCPf2Vnn14RAWkjrX3KC6phP1iIi71eqBbQ4ZXSN1C2mcdBeXEdQcMa8xrMPp6XvKbSxqGooiNt/ZJ1PzjN50LpfFxTDbs9HxXMo/sgIzHoIvVY1Rk3ckw=,iv:VOxT/e0H/fPjIQpgsZ3zDWflfTwj2lu6OP7ovhIh8iY=,tag:63OoWu1IBTd3VyfTNc3CQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
