# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:QGLrIYgRsBkKXXQpnrtBINuFfyle,iv:WiTVqYOR48tIQ06VVu1mVGeBDqEcN6go43D1eybMmP4=,tag:9cvR0Mg6Y7kZlFekOAiW4g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMjcweWlOd29Ha0QxUVhn
        bVNzdHRiQ2IvdUtYNUg3TVV3dyt6WVl5UXlzCjNRTFpUZ0JRZVROMVlCQ2djbFNp
        NVNYK284V29QSThVTDA0Wm14d0o1Vk0KLS0tIFRyZFlEbnh5Rm15YW1jVXg5amha
        RjErZytqYTNNbHVBU05xQnVuUG9XT2sKIALjvFHQ1/lGKzCCbUUMu1Jo8oYJe7nD
        m+mPrworhKTw6oouAH8v93OtTXTLOavhUOiSQl6jzJRu4XZmV/Povg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:y7lHTpp+5RAY9VwHj0QqIZ7g7g49U0jCqP6uNGKSnQdsvPFaR5ZZvQ9AAdFFe/MF3BtEOKm8a/MGTt1wc8fJkZjBKJS9gExNn+zCGTelNZmG1KVt/qYUr72wqWg+i5liG3/uJKYVpW1Tc7wSwI1/sZdRQQ7+ai5UunLV5Zchs8o=,iv:1umPeT67Mr7I2SBNhU0kJPgRyJIEZbZ5p6TUmq5lVpo=,tag:PBw1nZAKJ8sAOOLrPyzaPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
