# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:veZA6FZwPku/iYOB/jsV9Y92xWKA,iv:LsGU6C/Ckdxvnm8aIxegoOyvOTj3ljVedavDQNmalog=,tag:DkdcWfCgpsUNP1XDIArldQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TFQ3RHE5ZGsweGU1V3ls
        MnBGZE5tZGVNakJOVDNnSC9mSmV0RTc2SEE4CnE1dU5wb0QyYVFJWjF1SncyYVJn
        NkR5M21QK0pYV3V2RTRtYjEvbFhSdnMKLS0tIFc2TDJ2cXhBK0wrK0xJeXJFZ2ZO
        OU8vUGRTdzA0K3NCZTgrVEhiV2dyUlkKMCQAi/J2t15+aJ/yPHwEGjo9B2B+T4eq
        tz/3Y2qZA6BAQzClAPUZ37bgcmmKCN+TDQHKs3AA9zSed0/yi54ehg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:77iy31BChBhMBWhkSSyylYOaON14Y8jaLVpFCM0NL84p5/ZQfyVD5zz5xKa/Ef0wrOV/anWwJ3+GeEiaq20rosego3PZBPJEOsMj1OW5cjkekw4KKbRbmRHDeJWluEEtjx1rLO13odJfQzbhkl37Dpc6IrIWRNBClXZSL1WSYBE=,iv:H7KByfZZe9pHuIrMdDc88DUOYZhIOvWHNijZpQJAKtY=,tag:WEDAuAfrk+3RktBraG7xrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
