# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:X0+YINyi9O2lGLbrwyyhTE2Bj+zQ,iv:lka8LFvmj8DFiP8soUun9T5bSIDkdveYAnj/fWgvAYs=,tag:QV0i8l7eHok0G3V3Aw4WyA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VG9rNVJtZDJVa2djZUVW
        Y0wrSWdoR09vKzRwRjg5VXRKK1BJb1BrRmlZCmdIczVMNjNXOWV1ZHZ4TnllK2ZQ
        Mk5lcXJwWXNqcDM1MnR2aVZLUi9UaGMKLS0tIG9iZmdVd2VURmlyZnhWdytxUUw3
        R29GTit3L1J1NXVOWW5ZdXI0RXYwZ3MKDksx7DekfFhCgTrU1g6eyUR2y59qV0Pr
        K5ENrjZXaCrHd0e4Qb57P7p995puQ2KlV+nhgxXuBz08VPmseCKOPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:SEu8LPJmMNhLvF/bL/36H85L2JNkMgWjp3QjrrawbNv6Ctvrraoep+eZc1EnadFooZm9ZppcxOKoP+AF5qHfLXnD9wcXPSFMDpxNlPe07Wy2Pl7j+yA+6kkJfPwQAFKWbTuj9T8+k2f5c1OcY1i5zIKvLhr28lpEmyMFjC2echs=,iv:gWS5aoCgSx6J1pD6vpoXUAmIkv1qTLNalpJkEIqM1lM=,tag:1Z3xW9N5xrFBUa2XfuOIlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
