# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:yYEgChXb9XM3OSzrQxXZL6L6AWbw,iv:szM+Kdwhgk6W6wI/ldOW6FFtb/yBdB5d2zCinz7xo+g=,tag:/Bt8XQkGSlUoT+oFvzNmQg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrclVYNmNXbmhXeGNkRXNp
        T0J5clJWWU9xM21jOXpCSGVOSVUxSnloTlVBCjJoRXQxaVZ2bWVSTnF4c0NuSjdX
        VkZwU0hEa0I3Q3FueG1pMnI1U2pHMzQKLS0tIHFBWktVMmlFVmlXQU9iVGd5Nng2
        NEtGM0g2akVxZHVCQldrdlBGRk1lam8KcNpx7HmSziUyJZXveejDMB85nQJkZldb
        a69L0MyevB8cvcivAUM0NM0QT/mAFn69cLI9AHleJudZeAk5O6WFPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:pkTV/QXMwRaU/btvXzQ1hBwpvnfFUhdBMQUtvJpjT40RML+DYe5lkR8099HxFRFjnbPqQW7k8GzRrgs00/MX0f/iJDYzpQH2jpIdtUJkKOxrS4ouBUuc+BereuCYgG3S6GJmdWlTuNbEgirZawD2zyRHA/6jtVvYkbZW1pFiU3M=,iv:167VOU7P1Wspcyy/P90H5vpVLGq1Av5LHajoNxjJ930=,tag:SN1qMfiAumwOG8JbX7NB0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
