# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:kHNIbiFOA6JY/sB9expUFllPxsu1,iv:l0hB249B7HiMJyS2rlVo5h+tejuDqFK7TP0pMYPcMco=,tag:1y9mQs/5s8nBY69VXa8qCw==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1RQakptbHV3bkNuNTdp
            b2gvZ0JvOVhOMUcyMG1vN2YvUXVMZlRTWlRBCklIVnV0Q3ZqVlpWcERJdjVxUk04
            VWpDbGN1S2libzNZMkhxQTJZc1ZGVm8KLS0tIFBjNFVsTzJtWERJbTNIZmp1NVQ1
            TFVLLzk0RmhSUmlQTDgxR0F5WU9QUncKBWqxWV+3hhjeW/FVZvUT5lTHWo9Oo27/
            LxwB/Hbi/9/vBJddnAL/q7peA1n0d9VEuMP/+KIfi+CX69GflfGdRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T18:12:37Z"
    mac: ENC[AES256_GCM,data:tm761H0QaVOjQSPPHEeu9ggJUKqs49k1l+Zol2MBzko+VyHnGqiD2RINe6otwORZRO0uSLDDPO/ZzYA61LaCwc841oME5ioWeSQWhUpkUUZFqJY11JAcZOsIdJPuDRZZbMvStC+g0mKvVnPYcN9B3wcdOfXQVF7AxH5QbtNHKI4=,iv:oipQ/vXHIzY+PQWz3exCCFw1wtgT7nC+yrDNxZCo1DE=,tag:/Dg/KLrFCBCdwYUUSzuBFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
