# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:OkumyByWOO0=,iv:S9FpzIWrmIEwUcYHIGM3aMsqTCk8GKBiqN787tYyUJM=,tag:aFawcambBi+xXITCmITHGQ==,type:str]
  password: ENC[AES256_GCM,data:KCA99QrPkGY=,iv:ZUjd53CKMn3Iar4vr+EzZkqj/APRarfsq8Ed5zI3r+8=,tag:ivb8cgszAtyXlFBIbiD7sg==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:lc4vtXUGsTo=,iv:OHJiAwOjpj3eSAAyaPzgKcR4UEFUrohJY/LOvYry928=,tag:8A/7o2mn8lyA2llkHT0URQ==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:39/QMFslUZg=,iv:jI5IRgx43UCFDSvSSzEIjdoYlfz5XgCVk0Bn9bjRUCo=,tag:+LUVRfizKm9/MDiIqNFdvw==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:Q4i0MZ4=,iv:IpZ//iMu+nUbhLT9gveOuS8M2MBg+wQ18IF4yrsPMOA=,tag:bSwkeI4J9puXgqY84an2jw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:42g52HGSAy6wa6LkQ++pJQIUEUJtc78=,iv:nBGCfdR2cfGa4cyntXk+Q+00fgnSSDcEK9e0tgMri7Q=,tag:fmGGXQWbr0t8mtkDnpym6Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd3hIMTdBWWM3anV2TCtY
        UHo5NVFKdjd0aXhRSWc5eVVjamwxU1c0eEFrCjA2ZWJRK2t5dEV1SlJnUlNVYUww
        YlZ2ZkNab3BDbHlOekdzeThVcm1WWFEKLS0tIDRlU2lKTTdnQ0NlVnFQc21ST0JR
        dlI4YUNoQ3ZhV09RQmtwZlh3VkxYbUEKO9p+xEyS0T+DwqYD/q529qxm/Pzv0m2T
        Ojd84raNjlU8ruRXuf1SMX+KVYMDGmYpwb8GN1kFtpQuCrNAYCqlvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:cHp7YNt0S7xxGtXIwK07771Zf1PvNHoprFphdEGGl1QGJE0TfyRco5ZzaasCNV6K85OtiEFo1wCQWmqkhmzgGNUylQJ85G6/M/Q68LqST0Jj7fWx1ehUAgNadq6odaMpfS6NgM8ANzoH2YtD2gaBVJLB6RrGr3QcyJPXD55AaI4=,iv:+N03M84lCMLSaTwqKxZo76A+SLEux99iJQt8i5IR79Q=,tag:37loo7IPeD6hEm6btIfA1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
