# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:Co9ulhR3OXU=,iv:xG944ODUoVAOLmofs0NkrYPQSa4iYfy5KLamO09MAug=,tag:n/7UuUyjD1n1fApXS/E5+Q==,type:str]
    password: ENC[AES256_GCM,data:Rl23BrWG0ks=,iv:To+pkc3c5MBNAAzC9UZUJ32sPSBTeX3tPGbMrURPsp8=,tag:t5+5utLr8F4TtzLwEO97cw==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:GzK6sYFIkx8=,iv:pejno2T/8dCDhuIJrrUkgPihcI5zdGW2Gor8nyWT7UY=,tag:RNsNgxB0vTczdJCxBTG+Kw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Uol0Do9TQEg=,iv:fJXBMsnOW9dNqxSHoUVz0lLIUBv2W/edVmOCoyUhOso=,tag:n3+jFxM897KNLfkSuIZQ/g==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:05:25Z"
    mac: ENC[AES256_GCM,data:1D7mT5MlZRJaEONS7GqsC+2G/G2qkxcXHnmFhLaJ9Sz1qsCqahxgd33YWzLmnCk4jhgTvt7HluXJp9eTIeDiKzb01AhU4Zm0AtJBpEYxIH4eidCPWz/HguIeLDEsJIbZ5v1asL/CR5ypygucLm0S+jNqQSKiRsyFkv3UFZZNE8s=,iv:5fBUF44uTA98Nm0/nE7JNcgJXBDpMtK2B6Am459wwT4=,tag:a/yi8Gem58m0jqQ3s8KNGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
