# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:5TQvdh8=,iv:4jxrVFUgfXXB5HDvKo0waU9XYMlK3ULavzLJsZw9gac=,tag:PVaZHsZEooAmSbSN2MmGLw==,type:str]
    password: ENC[AES256_GCM,data:V/TONEHumnBuYN7X,iv:Sh1Z/ZB5Gst/BwVpvcZD5BzeZpKGe/b+wGM2Jh03N6g=,tag:FACyKJ/Mh1Ryr72D2FTg/g==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:NB/apqo=,iv:j/wOjBLl2YrYK1QeiWKVCEj/1Zd+8Q0MfN4XeeqsgOg=,tag:u6E6J+ZScCY1gRBoDG1M4A==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WmQ2pvCBpKyVezjP,iv:AholAPez3zI81I1yzAzRuIfGmFGCtFc0P2M9X+7kD48=,tag:djh7LGNbu/YrzNNQGcLQdA==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T18:36:55Z"
    mac: ENC[AES256_GCM,data:V5/NJ+b9IGMd8OEWSdVR/xpJGJrqDRYaenPK1Q4TxvLSdlHT5rWtbsruA7jnufyygTPxSq/v5manz60dKj8bpCll+yG76nW1oYlmv2JGC8NvWDaRRMYO5cloTSTHyTYclJpNBL1nBeCFpGjM9tg6T0aJxIHSh22lAR7NhRuhqjw=,iv:bk/W+eeRiku7qbIsgZXe5fu3PJeSwCzO6NVjXqCkQTw=,tag:irC+83FElBar45XriM0RQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
