# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:6iPdjncU4Mc=,iv:Ecu5KT39Xcwxalfie+oOCo4j5T/gnTh+tG2hpaAVjEk=,tag:s2/aEEmpZvEtTq3qFQF86A==,type:str]
  password: ENC[AES256_GCM,data:2A9v7DU1vFI=,iv:LlmDvTXBvoj5MM3rhaDGCqicQvQlkzxwmTfM1CMtkso=,tag:a0lUJ6bVHcJKxqr6PFVtcA==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:A0zbHcOZD2Y=,iv:81IQBT4Wbg/3X1ZOPpE5Lb7MhYH8e4UfAEoVKSpYgAE=,tag:ux+Dip7KumO6ALxHc+7sxg==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9A0ucEPaPjo=,iv:dYov0uJseusdvkjBqhw/ZUuuejnL2teOk4QfSqn/D3k=,tag:VBMBMvcLngNNr1dzOCSD2A==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:9UY3bhY=,iv:sW2M1jvTBTS9RSsfuyCMps4x8aJSs43oF8pDIRX7Tcg=,tag:dpLT3VWIAZ9vN7ykSzPXGg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:k+PZLi4bV3sgZyRQifyFkFA7Fuu2mUM=,iv:EDUvX3yJlI2pAN73KWIGPlPJbaboxP+r0wlLS69m/2s=,tag:gAQgILyr5y+pwKQK9QncYw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK0ZDcWpqRWM5QVZhVmlq
        a01SbktmTWtTdFB2QmxCdHBSM0w4SUtta0RVCkgvbkdCejJ1QURHRDZRZ2xCaDdU
        OU1sK1pLRTFUK0gyZk1zaUNhRGlrODAKLS0tIGQxbEh0RCtwL2ZqZHA3NGhTbHA4
        dzZoZWJKQkdRMXcybndrajB1WXRpcmsKkUiVRN9NDCkAyuzvg1h5VrbdgA+hVNB9
        62if9r9AtLkuo1YrBG18nWjJAuqtQ4W+tZZhLv0J6MZ1XYYxY+s4CQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:t28hW0eZ5I4PPPYME1er/h54TawjaRxh7g9+PU45XxAuymCWItjO4AIz3Wa9Mub7XSOqFw5KJUId2d5sOxKLloftZluCIw37qYa/jLu2j0TUfOOVwLwwJeC29CBkxsADCIdt0IYnNux4eH5KmVYXHokEd8LWVAZ35IIN4iaGX7Q=,iv:fmhujuAMmeCT+K2EN/3MxIDn8gZv1j19AxU62wqzZxc=,tag:SBuhoFfXNwbqT+eJsymCGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
