# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:7I5G9449EtE=,iv:k63keqbkJkchEtqzHW5XK0wZIgHwZ5yn7rV/2JhWXgQ=,tag:ChCXAbM8DY9QaFc/Lz0UcA==,type:str]
  password: ENC[AES256_GCM,data:Dke54/iqLl0=,iv:2XLnKUrpimIqyFpwdPbdM/NRmh/81xZGwSlsWK6tiCI=,tag:/ghFoOjiDPoPR2g9mh9Erw==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:a8n1tDpF/E4=,iv:31MofyBi++VF7bFVzScAUglZP73xyaW7FL4oh5QN7xE=,tag:UFbr3/F53T8waAHzr5G8Sw==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kHDDvq9dS38=,iv:3vGxxs4d2XrXIoLmsfCO8llUfAVPMgB8TLkfh/9OGac=,tag:Ei1NLAg/sFjbL+ACbB94dQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:jWgbI3s=,iv:wn8GZrUx+3+vTk5qgKNfYCbEGXcA/FnXhriJQvMN8Ew=,tag:vAf07vLDYkJFI0mPS5zoow==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:2RJnt8GrosJ9vpq08JEmSiSLM1NxSwM=,iv:S1biNEE1N/17cklWlGc9/2KUjhjXtJglf6QqcWdWYCs=,tag:1yp1xRI86AtUOh8rcKzTlg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVpQRWNlbDJ1d3lCcGk2
        b0pIeHVyUU9meXN4MFNaNEJJV2lJRlVReHd3CldoWUZxdnQvTlU3cVdteXIvTUxD
        K243ODlEeWNGRWVVSGdwUlNqOUJZZ28KLS0tIGpYaGhqNkJVcERpOEcvTlorcURC
        Y1Q2eUxvOFhkV0tGOFduSXBjSExJN1EKgDDroyWQafZhFoDWABIoSYjvgoiHF2Uv
        k+TjNO3YPM2VWu4FtBUFbhP+DJgjePujKdgkOmCmEey0Fvbkukuu4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:wwzUAwc23AKWroGPjlWoHiGSIW/OzBSUp6N1QDsmBVPqjU+6at94/39jLslfdh3nyGapq6wN56gbhWoQ7oFfCsyxE8V5Hobu7BjkByjF/l+TqCa37A+Im1XE5HO/A/UtCORJUxUpTSiF1eah6VRwEF1iWCXlUIoOFs2qs+eNI4Q=,iv:P3gegBGYS3wOCKF2kwmFh9CRGlTI92yB5BGOOQpkwFA=,tag:eA/yWdQjvvUqBsSTAA3joA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
