# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:kt5t6pQcjNI=,iv:VL3iJYTjrBM76gV2qrtsb67icjR6wo0cVTBb3vrWP+Y=,tag:dP0maraGWJiX+YzDK9H5zA==,type:str]
  password: ENC[AES256_GCM,data:Z5FEDhEbKqw=,iv:LMD1PIjhGPFVXiEbXCbP48OE7ahdUfLv3CkdsiCCMSQ=,tag:AyNAoG9KqRYCidLi2Sjb4g==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gVmZEXu8kP0=,iv:QHAeBHfvD07FxpIJt9RjG0Q0/Nv7pKTIpubtJNl5UyY=,tag:jwlikfuhsGQCFZpAwfkK8g==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wU8B4iyEfas=,iv:JAl91u0FQHm6xKA2bTMreBEAkij1P7HVB/ZYZR5Nkk4=,tag:xiCdW7GDm7pyTZFrWqa7sg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:HwMhOSw=,iv:TCw25aZzPcNMNYFPb4RcWzKEnFAMlk3npB4w3v2NNdU=,tag:lKtLl28Y2juuV2X/VxT4Ww==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:urUz/keOpH9cTZ6tzdS0LZgY0QABASs=,iv:lkRDFz/PoN3SW+sBrWxhXcC8ZguAFwCL/DqnoUp173Q=,tag:3SqonvSZMdrgdpzHHSD8Ag==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjFCdkgvbUJjVzM4Yy96
        d0lJVmpsVWN4TDU4K2psSlFPc2FYNnJ2OXhFCjNTM3o2YjUwRkYvVFBETElGenRZ
        M3VrelVQS21aSzE3Z2lsL085M0NqVHMKLS0tIDNoaXBmY0hJdm9YR1BvRDVUbVJS
        VHVJeVlIMXArZ1JHUCs1ZmJHdGdZb1UKnlJ6UmZNelGqnDSYRlnXaJPwx8mJyleH
        YR0K3swcrwUJoPa50D9/Z08ajSQaGupJcLC97Gq6F25wJ56mBfshBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:T2jnRt3X5a05LNK7wxSTqITwWicCwT+rhEn1HCoYS3bnGxx4m+/7cPyn5SXAekPIjQaLfbr6Q0Q3O7vTmNAq1cxssw1CBh4b6LL67BZojuELbvKsptKAeY0Ez2Y4R7vVYPCQ2nc3TYRGyBNXXWbmqPfF0FRiU15C0AgzFTI+7a0=,iv:N6LYVcOQ7P+T8uJgM7zJgeTkhDqwhEL2CdtLBi/gkA4=,tag:waEnEnTaKGri/UKmhJ+Aug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
