# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:/mz+7/34pTo=,iv:9TZwBrSIAFnuQZPij/l3k5ha3zoDHy0/Pd17lezLJPU=,tag:tBV6u5NJqErxwX2pMYLEMg==,type:str]
  password: ENC[AES256_GCM,data:IepvDZZpkGg=,iv:c5nzWy/j6+noYxxQ2kp3sxT57nOObGNX5ZoEuSAF8yA=,tag:WyFbVOueuXwnPeHflo0mtw==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:nbAPUya3ICY=,iv:Qqd2bj0MhBR5933J/6FWb9MsEhwp/WzW22gmCh7LAwM=,tag:8diYKuplgNqJRPuF6dOurA==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:j350qn3PQTQ=,iv:P+s5KiUzjSOJ0UNkFyVX4EOyAzM1yZi8v0cYjPGjm0Y=,tag:/XKwF1G3RLvfPvwKYc2wUw==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:XNxJ9gk=,iv:MQUvU10eYeQOJGCVpirulJB7tfm6O9xdr8GQtj7E4Qo=,tag:/e3XoAqnaBggKipgthOztg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:slwoOnCnbwwT+ImqV1b3GWQ2D6GJS7w=,iv:34RcGpGkNccawMuMa6oduNkWX69Wcm1FbvNwi8zA3X0=,tag:AtAIIFy1e1vGjzvF4//Iqw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1akVueTZJbW0yOGQxRkJ5
        KzBXdnhEOEhsY0FpL1EvcG5PS0tkUU9UV2lVCkF6OVoxbmwrTWVCdXBRWDVnZWkw
        clRNbnNMajMwcHJWZlNRYU44a2ZycVEKLS0tIG1QNHpZd2doVlo0VmprNlFKcDV0
        WDBZcmNNVEFDbnhVRTMvN2FwLy9DOG8Kfet0VsLj0vIJSe3fl2GuCNsuQrga//1G
        h8aCbOWuyCY0G47hR2Tv8zzbhGiCfDh2820Hszy/A+hh9zH8JxlHBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:EyevfuRHxq07RG9+AQoOfRXlWR9k4ZPZmBV/Wkx6R+fwF3RdzSNvbmajHQ1Ysx+cQDlAsPUAIEiZeVsyXkUJMZq/kz5SEk/GgmPiDNYzPWfPEPVKeonHZlsauffEzqWo7hcrz+uZfg5vZ3jBdeB5ifoSJX1ShLf4vn9QuuEC2Go=,iv:yb0NRgH2oWHG37M7tR0TkuiN85YU0hwjcKcDTZLEvdw=,tag:JjpScRhZbcleaHg4EEo2ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
