# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:FvVUZ82kg/A=,iv:wf8CqHIxntgslANgueZODHHXtCkXAky0TCH+FYlmPuE=,tag:3kQ7zl8xrLO3PM9R8yuDDA==,type:str]
  password: ENC[AES256_GCM,data:Qr8vTvbtczE=,iv:FlGQhQVM9IFMVUD/1POCWdVqf4/fo3PdiT4Ea7xtntk=,tag:qPEIZikui7U2hUlenuduMw==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:8sa/XL3avaE=,iv:z1ZODmTSE+LUrkBRPK7q7Zffh02tumsuqCMKe1gkkEM=,tag:0AnhplGp4qss/T2ji4FsCQ==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:YaONFvbG+0s=,iv:+FucK99g06NOgm/StiyfnZR+UOcy/fxQSUtsdddj55c=,tag:XA02nTG0XZikmwizNaRr5g==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:w70NK18=,iv:TNunFf72iZNNQgz6kSYQDPsCHUFJEb6piM50fppjmXE=,tag:fWiv+aQOlDCCwPy3EIWmrw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:oLfkouybJsNJSeFH8Lo6jlgzK5hFXHw=,iv:+//vqe2wBxH/5ozf0iJt2L6agzICa5/xUcOf9TnW264=,tag:sSIoPrjznG5gLuOYCTpiDg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMkFCUHVQSE9GdGNtZEM0
        RnVHeTJYWjExYXQ2U0NwYlBOWTdHWGpNZmdVCnhWS1hWOTR1U2N5TDh1RVA4SXZ1
        WlVKTmF0Vkt4ZHJkTUZLdko2UC9SYmcKLS0tICsydWh6YkYvdDZ6TG9sME1vT3FF
        TS9DeW55OEk3emhmQWlFU0p3eWNXODgKhtOYkXTiqixXGcYrWA2WQBIgrWtqs0mU
        E3K63p1C7vOVgcwaDKrrZPuv4H3IU751JujEfuNct4b8xyIIqb/LRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:30Z"
  mac: ENC[AES256_GCM,data:o167K4aboihnFPZvmRlBwSJG2aJJoRcYHHk77s9ZIzOLFRi9qR9w2wVlromwRclVHrSMIk8MYH+xxcIVRmusW1aWYfCghnDRiGKJp0YTgSyTVrPMxwDC6fdJ5Xh5ZkmbaHbIuM/qQhuzqjNP4CPbO/gBk5DXoNpDKJQxrhhePY0=,iv:JLusjjyjp0UlAK32UHtLa3L3TzTuZw/t3r66XOdCiLI=,tag:hvujig5pe2nZsWRIXy4edw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
