# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:RLHb4FtAAnI=,iv:0U26qOKf4aFSlWUC8F7D/eznVi31cd3b8eVGmv52p9w=,tag:SPrnM1iuzJakK/QRZVSdmg==,type:str]
  password: ENC[AES256_GCM,data:+VbUkXp6/hY=,iv:bEry3CTuaAhbS2Yj3OQ2AfrbasPergz4GixR/+LwV6s=,tag:Pq6Il3OnbN8tK9UoaKS59g==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:yU9byhoOQ/M=,iv:JAplIbBTMcgytzZ/aXJriNYRg0oXmv0L6wRaY/S+zYc=,tag:ko1afdAOLctbr/iauGLEfA==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ahuE6fQEHGs=,iv:5LAC4I1PhJlzu5RNsRokDh/+PfOaIc/+SvTThWuBrG4=,tag:/U64QToO/y2wU3Bc7UXkMg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:vme8qh4=,iv:UK4alxdFGtXKiNvAyNXJhtVifklcFK2CIO8CTXrUDGg=,tag:GF5SSYKfcPRcFkluxhlPKg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:So0Dj0qKDdb46z5SySTH3Fun5rsJ3aI=,iv:wp/di0LjmUJeu9zyU1VCUH1n+mQKf5Z96kCYyCOEPt0=,tag:02fshXRlKcVlIl49i2BnJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTEFLZDkyYkJrMEZRcEdL
        MVhpNlMzY3U4Q3V0RUxxZTVDaDh0WjMxMUdjCnVRcHp3ekE1Uy9KYlU3UXo2cml3
        aGV6ZEpiQm0vU0ZBWVVqbDY5eXJUSGcKLS0tIDk0bTBrL2t1VlRNL2xvZWMvNnNJ
        QjBNbEhsS0VNUklXbVRLZEUxK2ZqVFEKvefayRvTQmc/4p/DE+3VQDoqnTEBNvit
        4lOYyKW8bAWjZ820mwC15i3kSsoNGdUfpjwmv+y+GVV/ja8GaWUcaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:EecMCuUDlzBWMFy2fp7fpzpwXumnNDDObRl4+RnRO907Mqi7MZdby4sUBIXLB3k+ILEyPceRd1Yq+7wbzxxakA1nOx5pM1y4BX+v4BY+11dpYU0vDyDO/9KEugC6qEvRDGZIAirMYdK1SXd/n2ttSv/gaMSgqDxMOIpnTtom6CM=,iv:pqSp2Rd5jj9HHdTPI7vYH7/GNKBPI2PYZePLhln7Ar0=,tag:MIS9gvmFsXt9dV3JyWrVjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
