# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:PlMN1wzJezk=,iv:iK7KsFcL71lzlErnZKTuVDLq94zt4FhjQ4kJUTJQAEs=,tag:661dBGS76MS6cGgZTi9rbw==,type:str]
  password: ENC[AES256_GCM,data:UKDtgd5Q4X0=,iv:wVc+A9vuIibI2VFlCtWiBheYfwTjhv5JERGzMuFGZn8=,tag:RHYffB+dqAtnq/j9YymXlQ==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:+l3NB9zTtUs=,iv:VHj/Klnx5Xkh/MSTFee9Uwf9bRPg0fwCBMhv3f0DjGo=,tag:T6oUlJYOl8HyXn0XWJfVgQ==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Ieu09nZiH/c=,iv:k7s88XO4+CvPIN82TLXonHNdGCbpolmvzkix6OuuHCs=,tag:KslqRBRAFO100R0xnxfFNg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:KdtjKV4=,iv:E6cMd8PvyTXhtnDRtF6kV5WKORlloBHDUGw4lpcVNU0=,tag:uKD+iixoexJbqTCWd8yd+w==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:dse8MsLRwVLlLvZEc8Q6xnew8lAdADk=,iv:u9Ti2TdZUgiIDHANu0IPnG10C2srnOBCpNTU2rLLb5c=,tag:o1ka+3fIgxMmeNRFfhDy0A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUWRUZ1NMZXJGSlNpQVFB
        blpiRXo0Z0lkZEZYS1psZmE4TjFueVlUSzFBCmNQeWFIQnhuVU1Sd25iUy8rbVZO
        K3lMU25jNEVPcU9MUE9mVjMzdmlxQTgKLS0tIHVZb2VrT1FoZzNzODBYRy9TNjZz
        Q0tuTnl4eTdxVVZtMFlvUHZrUmhoMlEK1Mnv9RXFascOAKQqQHRSsM+3sH3indm0
        2jxoRVajT9rjHPzjDW9Q+LcxPd7AQr6Gry6wD3/EPOsQDd+NWbFElA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:me+v+QHpaSdUk1PI5tXVndItJTmrULPeBucoNqhp9huyxsPSYr8oRj4ax4HEZZ9hw3uKOZ34nuDHpA6Ye+FzwLTjF8yGc3KVsErUA3tA4IrcgNg2H+hAY7JUhKGbfwn+Mkdzj5WT3fTI5+Qen75yR//YrD7wpoE784l9pLEHDPM=,iv:FLtauFVnWykL5qoqeeL8CxhDa+0rTV8rDMWOYdHxMxg=,tag:zkuqxJZTHrv3o10dzBHlrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
