# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:JKWfPik=,iv:HEurX3UL6foPgVrSh10HQ9Tsqv8zSnK3nWewBBNT7c8=,tag:dm3cY88UO0GZ8y5jOne5dg==,type:str]
    password: ENC[AES256_GCM,data:WylAsBtpvw9np21i/5ihef2CeKw=,iv:JXOqVLs1GOMkMAGsdZFSlzhl2K+Pg7d0DA7m/CF9HqM=,tag:6YJYJFjYtZ8VXfVl5hSngQ==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKME9JYW41RFFLV09pbW9S
            cVpGUHlNOUd0RVlNaWJDcHZ4WUhNTG1JRTJFCnNuR1VEL01idUM3YVRHMmxRSXoz
            TlRWZEs1YnkreUNtM3g2WnRNcU9UdkEKLS0tIGRLY0JwRUp3ZFlWVmdyaVpXbW44
            N1Q0SkplaWY0MGZOVHlrbmF3a0JwRk0K+QluFETK72Bgy8ufg31pnCt/GaqfWHtR
            /LgGN/s/Cw0R5zc/iQdYfmR4Im2Q8+0zJAWaikHNpPZcohLSC6CoiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T19:46:30Z"
    mac: ENC[AES256_GCM,data:oOUEhNXZDdYQVLqKDfD2EAhgU4xKRcZyToZ3vZIFJGkMfy0Ry0pHsR9E2CSs5mhC19QLLZ7GyGgg/qbUqIr9pjNt3BhxG/ldTKuZIUx9mXZLcZXQxozKsYE6CcFH54mmAl765SnQL0ZiMKClwNOC1Mc3NgyJiUbSaTOKrWMlwY4=,iv:DhLwQWM6fcz+cKPTzMfNZebhR/+CQOR/+t6uaUwq42o=,tag:z33V7wB1fu1SNKs3CTncQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
