# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:h03uj6H9SlM=,iv:ANSjzou6ILIuDXyBbNwBgemaZ0fQZ2AR6ABQV/KyDBY=,tag:NjAT59m33nkipsA8ezoCcw==,type:str]
  password: ENC[AES256_GCM,data:6UF7uBN8Kn8=,iv:VObVikiU4pSoorZoQuVzjlse7ijxGLFvfnsoB6bq3L0=,tag:sxpSv1RfNnYRW+Tsg8juvQ==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:To6VvbjFg8s=,iv:wUmF/KvEGRXJx+BJO1P4o/+FF+dG66kM3QzwFTU1L0Y=,tag:S2nJVaaPAiRK0uOzsI7Avw==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:IdI90h3v3V8=,iv:pIHXO3c/OzHYccW9vL4kZqOoSDpeq2m4i4LjZatcUig=,tag:0OKBshP2KTSG3VC6U21Esg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:Tw1yEq8=,iv:mt/FhwXyRpPj4Drexfw6aTrx+VVKtH+HWyJu9n7yLbg=,tag:yrUhoa33oKA8RXNSzQ5A7A==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:PGYaDS6QRZl4YH4c1aAheAFGzJh0h6Q=,iv:BPIzsQYvcvWstCD/Y2vgIxZsRMDwREQONBw3K/8Pny0=,tag:JJRjJeHGYUFVZs7uF98VCA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZlJEUmVkWW5rckgxZjlm
        RFFmZXBjbUhsUkkvWDlSK2NGbEdUamNCbXc4Ck1SbkFlOS81YzJ4UlhJRERCNmti
        WDBuWTUrK0JJS3BNWlFHVmx3L0F1RXcKLS0tIHdNMWNzdTFFU0ZiNzZLTHdlZ3Fj
        eTRabmFoQW56MkttY1ZkT0dLS3FHalkK3thLau5qVMrYWGfd8o7p/QOtIW6gqD9y
        yuMQ04HXC2tmE7hHDiCcPQjLTUUy/A6CDGr5p+RASCu5dUBzAv9Itw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:00Z"
  mac: ENC[AES256_GCM,data:Mi5iBI/PV3gEK7l25ElswYskBMFY2rAN1AVxQ3fXUlJVLXcUAkMbadMat25Jg0q0l+gGbkeH5ZM4Cod8lZMleN46//rrS+zVUdJ/H2L2U7vW5WotF96Asq2kJfqWSeESeO8h9WR8gnRzhJk94SVYACMI/BCCppT4MlbM5nVhVKM=,iv:StM0lF2d62HD8P2fpPctjXxonEk2XaYV7al2xD3Hq4Y=,tag:M34MC/lYF8/26xXNlafcFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
