# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:JWSo4LWJd1c=,iv:mcsAQuW3YqyvbNk3h4/f9nkWT7aOCdx2PCF6Vy1VKpQ=,tag:3A3WHFvbWlqBej8AV6yx0A==,type:str]
  password: ENC[AES256_GCM,data:c1O8ONG0858=,iv:Z0ZQ5d3TiRchmHBnIlR/gAqI9o9YPdCmK2+SJuoWgMg=,tag:9FyHv/AUn/aC21VCMB9Fzw==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:jkYF1cS80OI=,iv:JcjNe5ckcK9qYG6xZEvqmgh8vunOVGj+MufAOkZ0vOk=,tag:3eZuZlUc3lLWmjzCM1k8Bg==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:XlZv47MhVWo=,iv:s0fvM64eV+mqs9KMoCPN5QqvXN4Z0qYFLnaEYFMbNGI=,tag:2L9m7JJ4Q+9xZeGHCk6BoQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:Q+/cnVI=,iv:olylBXkTmtWv+3bJXZcCxpEq/C5B+8K31WOV+caZ8zY=,tag:GSDc1lhcLdizt6cXa5Nj7Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:hwcBXPk6CtIRdQRdwXBDp3wPrfA0NZk=,iv:qdhu91OfnRbaRqYGsjfJLyHgpqbKok/cEw9D6d72wO8=,tag:OGmXY+VV0Q5h7zXzrkalWg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuclBWWXY5T2JVbkhVSU5l
        bnBxbjAxTXdJNlVWYUkwY1pLL0tnWWwxWVNjCjBjQkJYZXM0WjZkd0hqditnSEJL
        a1pYQVpxeDhTTWpmcXFSRlJUazZnYzQKLS0tIHhOZE00MFZ6SGVZTFd0eDNlRktZ
        cnliT3g3YkRBVjlLSkxtSUp0MFB6NlkKkc6aVMfLKOuc8WQnhL2xUc8ciETBs7xO
        y4QhlqsuGVGms/OUVga2m/cr7M12NOkFFUwQ2TLiqSF7RbcddxxcQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:ex4oYgPui3iU3JZuI597Ewh4jWXDf6MbZR4g0sYM6bi39d9yun89eK9uHNUYQS107K+a6QVNh0kgboE1cU9bijBHI6OMkaKmyXcRvf2mcELsolrN7prriV7DUZZd3UBT22MYogvr+0OUH9nHBEs3pENFYbOq3mNDpdgDEFFDYFM=,iv:T7l96F5S14vdrXWKvKPXot1sijIlaBX66IokDQ2hvhs=,tag:XEBPqKWsikIvj2OdBuM0xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
