# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:5TQvdh8=,iv:4jxrVFUgfXXB5HDvKo0waU9XYMlK3ULavzLJsZw9gac=,tag:PVaZHsZEooAmSbSN2MmGLw==,type:str]
    password: ENC[AES256_GCM,data:V/TONEHumnBuYN7X,iv:Sh1Z/ZB5Gst/BwVpvcZD5BzeZpKGe/b+wGM2Jh03N6g=,tag:FACyKJ/Mh1Ryr72D2FTg/g==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:15n9W94=,iv:8ydnYujMAGVaV9VyL78t8bjy2jKCaFl1qb0NhExWUD4=,tag:5XFjPfeeJcLpQwrzcklpUw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:/V8ZVwiXHhtsOqHXX4qGabwb4fiNkCk=,iv:CSdB1HtRaYRt1/Blwb2s1Uo5sWFW/XsXhmIMaLDzElE=,tag:5qiOjwQ3G/2S+xfidBZk6g==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T20:24:59Z"
    mac: ENC[AES256_GCM,data:C9sNDcawaI1n2Nyczd9yyg0QI/RmP5j1vQaw2y6v8B8dGuBE6Cod/szToGVfbcZbqC39rOmWErDZo/UOmE7W8YumY52ZN3n6yhoJME8/kBk/w4tFm4Nv26xRPJWn5bZzS6TwPcPiofcLWrR5pdbHbaZSiKgP8TKrw0eA5b2RXfg=,iv:i2iECOnny9a3drTDuNlrJQWyylqYDcX3o2+Xr4EKdKk=,tag:Aos4qsT8dCVt3qtUbWcv+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
