# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:3aucq2Galio=,iv:EOYNOLth3aB/az1oLqw/ba4ktufMRj28S5T75EvpCIw=,tag:7xiAM1tDzsB9cG7OblCw+Q==,type:str]
  password: ENC[AES256_GCM,data:59/U/zpYdfk=,iv:bZxKpU3oxNqzaWm525Z1ECPzLObxNoFTX1X0XQIXp+0=,tag:LYcTJ5sDA25Q8oljkVY8Mw==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:0XB+XAWT1Sg=,iv:WwMjY9v0szyXlCWXTaREM1kWnWzSU2JdXbMo2d8sycc=,tag:xwDZMtSCEVoyjKKvcdk9Ug==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:niWDGBHEQF4=,iv:SYGjGkNG7fQ0h4dPknlBVYy3PpuTrIujmp/ZDOs3lts=,tag:ZijM+D1qQHPanawLP+dOeg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:TcZ8Jig=,iv:LShe2lvWtlpgRp8NNTnTk28xgVB4mL1lToFukGcQJ6g=,tag:qn/uVSs8NGPc6L58O/yrwg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:3p68ZldElMwTeeOuMBVUp1n21ioAHvY=,iv:Q7/88xNG6ZCrzNzezjSsbJJ9r1Fz+Gh1H9OPjbrhwVA=,tag:xgNFpyHBkQqKSLwaV+yw6g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWtqU1F3Smh0V1k1TUR5
        NUpOckp0bzgrcDZXSlBlYldzeWhoUU9vaG1NCnF3RjR6VDd5b1VaNUZFZ3hQMzBk
        L3JHdkpyT0tlUGM0Vko4REkrTmhvTVUKLS0tIGNhcTRsMllXYWgxR21tbjJOc2lx
        VzJxYTlTcU1iMzFQdmJpMnNwSlNBMzQKrUq/aB3V1XTfio+8E6x+IeNcHCfWtkuS
        tcAQZgDTGl4JI2QCl8ZxWLchhVGpfialSIrtIdVB8Ra5vXbAz4/j7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:ordwuR9E8tIiZmuK3lY7WUn9WriOoxHaPy6swA9/znxXLZVA7lZ1JgwmUdzR6ZPpOBoQy2aPd7ByUrSwGdgdw76bVub2NjH52iiukBPcr5UcR5AV3qD8m766R1LUUJnZFb2zBCnbTlnzQFjlbQ3qDHb544lLXWUKmy3Ja6HPXns=,iv:dtY4h0vO69b3aZZVVrbtUHQ4TidxjDjxSW2kB1g72ZU=,tag:QT7m0uM3C0MRA952CHOHPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
