# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:cm0dBG7AP6M=,iv:eDGesduyyPpwVrTzq0ZiQzyLjiK9T7qL/jn4z1CS0Ng=,tag:wCozv5xWq7GJ+4yksr4ugA==,type:str]
  password: ENC[AES256_GCM,data:EjJ21PnQt2g=,iv:D4a0TNehXVmnrgMZQudVuEExFoRgfdqMJHCZD7IORaQ=,tag:8Ljyz3gOLOXI2cMNqk6NUQ==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:DMq7E6p6lrs=,iv:aO1ZoYz8/nqG5GsmagyMKuXJciNxlcQPWNatbQK47MQ=,tag:H/wsv4fMQVElPkNd+IAxQg==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:HISyHRcuI2A=,iv:XLZNh9By0ene80g99Ng3oWSrLfXsuZa50Ngkh/4CfmI=,tag:+/hy9RwHgCqrfLBP87bXCg==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:/mv4120=,iv:am0AA0FLyi29yRfLRU7FvPBwN82pwykE0GnkFnNHBY8=,tag:bZvbWtmjQXPwlDzvrtqzCw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:A0cdUmX8HUgWYLDT04a6tbFYCKyay+0=,iv:rbexPueFyB7gW46UbE5lk7J29WEe2nTay5WSa4vMvKk=,tag:U4wr8zLJvNPtb0bo3iE8gA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WTBITmUybjQ0VEFTR2dO
        Q2ZtRlE1ZTVjaUIrUXI1c0E5VmFnK2NOalVJCnpxVWttS0xhSDJHaTI5WXo1djk5
        d2lrQ0djTG16bDYzMytOSDFyRTVZTTAKLS0tIHV2UGx0bXd3QUZIbWRnYjlkOThD
        WUpJZzZnOFVTT2FrSnlxWmFQZS96QmsKlvqN+gWi69El17JPtir2pOtkeRwT3EPl
        XdF16kB5+Tk8Lns1w+ei0Op2KgVEDPqJwdZds5sedJUgdbE+Rh8sOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:29Z"
  mac: ENC[AES256_GCM,data:DBc4TwhobxgsiKsB0jaPE9EI0kBWiY4yqNtHrVzggqNyfbPI1C3g65w2QlQf9te3WRwrJRAhmmSPxLQoB27ZEDZ8t1aRpZyQfwsZEgOeSpw5bzCeBADDWO+GnPxKlV72G6qRhIUtxc3id/bweEJBz6DKn8SgsJF7GFXYQJ/FX5k=,iv:o3f9PeEalwHCjm1qTtjbeycAGdSRQaWAQsRckgGFddg=,tag:LPSmCwmdh/e1CPN6plIACQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
