# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:tI3RE/FnfoE=,iv:upqQ8OvryFry/BfRf3WYzdzJ8o1yx2LlucpFquhlUhg=,tag:PRUK1I1IEBGhnr0wSWFPbg==,type:str]
  password: ENC[AES256_GCM,data:OZHEOBzjLd4=,iv:cJxlF3XUQHe3t/Mf2BQI9rAaq/Sw4Ji5LOiLTXN4mUs=,tag:kA8ae5oWCrFtIfULSFQxpQ==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:8IaEjDacedc=,iv:UlEfYBOB3ypT0PhmrO0VPXJAhRfR6zDEtuFuyktNH7k=,tag:ZRAd8nxRaEa3srJAx2U64A==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:1SRLAeedwf8=,iv:hvOxS7pE2NiBwYiyfcAkVuxMFraXdHQ3EQwlYd/eoMs=,tag:0FmQNx6q2/dAjCbJRRQfgQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:czOxHkY=,iv:us6fRt9wfZ2cdpYT8hDenWzGaY1aVhwcdIGUVIQS77c=,tag:nRCT+0rxwrIn3v0PbhzxTA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:62YIbq0ZIubNyMXehxGeyGY+LR/LXP8=,iv:hZGuYTE8DyQN2WGOdZ9lEqepaWQwHEB5zAutg5aOl7o=,tag:evfS5kcBOlyfOXBBxTjN8A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcVBNOExKa1JZOUVBU2pR
        OWlyb0NRUDgvanZNb1hKL2lVajI2UUtkVGpvCjVGUlk3M3NwYVNmZWxpL0t1eTlJ
        RVJ0TDFQb0YvdjJab3d4ZThyWlhRbUUKLS0tIFEzTVFDTVRmZ1BwN2p6anZyZVlI
        UnkvRTRkU0pNN0VXZi9UaTFLd1JMakUK19xPDtPMmnGvXnb5vkDd5oICYqC05rfY
        kNG0cT+GziQTuQFGr+owN6k2MVO+v/eYGp91qmwvC5PelxAm0leLlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:fmObya/YOzX5QwLHc6jYCKp/Juu2RGupDCJ2L0eUK/R/YAGUzGZMHu+ec3lzF0eZLv6Gyh3Y+Mf/saavr9CvqOZlakSKfhRcmLGV3hV7E1TOgruqnjgYfdedB/X8ARE+O9MKoEWk3jMGiZQzrkKiVmGzPF3XrFyy3ulxSc/jkgc=,iv:izlSkPphZGzziJYJvveeKNQ6GUUCoz+MypcYXYVM8II=,tag:pTeUX3EiMjAGzQtWh1143A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
