# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:DOaD8CMfhpk=,iv:JAhDpIbIJfg/r7UQSZbv2J3h6IhXNRKZAqw4ssEzUTU=,tag:Tf+oKIhh13Ione1h5FacEQ==,type:str]
  password: ENC[AES256_GCM,data:bTUE9oVfpQA=,iv:UZjk1zAyLhvfBhR19SpVnC44dVR2rfvjjGfr8j6kLQI=,tag:4DJRCfuj9Q9XMyiDQ8PQJA==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:D0FlYAEkAxU=,iv:CgPkDz9GhpE80WxL+MnYDSFf3oHORZTCVyneCgecy68=,tag:3SP198JcfcFqEnnq7EdokA==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VC+SjNA+DFI=,iv:sYaJ8HADpWj7n/s6YqoDlsp1YB3rYl4vthbjoo4XDCY=,tag:eJshdcf15PUvBahXpJbQ9w==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:R3zws8c=,iv:sVmmB9qbmFEBR8fb8Vk8cVZXEeW2iRepp6jvZPBTD0k=,tag:MZkP1GjqcEvW2gIH8b5Lfg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:4R/7PeCOdZtbHgvQuuw6treG7iqNAcE=,iv:rVy2LM3BvPYN1tL5qmneoL1V9kA+K0gmqghWcgcx1kU=,tag:3PvuQdgzjwY10tKPK6xbHw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcGJWUzI0SlloeXExcGI4
        Z0IxcktCc1hiQjNtajZyZGVRNHZOTnlkR1NVCnk4L1lDc0NsbzFra1RvS1JQMm5i
        OTZQbk9XbHVYUDBqeS9aaEg0SHZ6dkUKLS0tIHNaR0JyMHdrcGxJQ2c5TVNrbVp0
        U0xjWlJmV3A0S0ZRU0l3WElFOTBmZjAKHmJGVdSQhCA0C7dWw7nTUJxXZ4sD1lZA
        UAI6zOMPageVZTCw4VBfuppXCLRChJf4bJVcph1JGrwJgurzz0Lk6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:nWhlfBKNrWPAJ8A4oYSdvKqY6HKo/TOt6d4rX3ua5Y3lI6TBfcqBJpabMgsjLSenUvo2ouBdd/lqvdGIsgF8QaeFBAEm8+spx7yAMizT0cfO+dDXUWSzeriH1020FK3XYA2n/yl595gfXwZEi7O9KVx9JZ2ogAcfgzdLEWVEmGM=,iv:Y0gmAsbyQWStibdP/L+kpf1x+nNy1ObJsR2VmNWe8Jo=,tag:fdnigKbigkylv4+AWI+kVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
