---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: csi-driver-nfs
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/databases/minio/app
  postBuild:
    substitute:
      APP: minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: true
