---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./grafanadashboard.yaml

configMapGenerator:
  - name: nextcloud-scripts
    files:
      - ./scripts/cron.sh
      - ./scripts/post-start.sh
generatorOptions:
  disableNameSuffixHash: true
