---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: nextcloud-data
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 500Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: expanse.internal
    path: "/mnt/storage/k8s/nextcloud"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  storageClassName: nextcloud-data
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Gi
