---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  storageClassName: nextcloud-nfs
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 500Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: expanse.internal
    path: /mnt/storage/k8s/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  storageClassName: nextcloud-nfs
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Gi
