# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:MOg9x58=,iv:jbzcwXerRQlfr+ePW6pvdChK8YHnrIxdGRtHa2OQ5c4=,tag:/jftkrv7bflMhHNyFBarxg==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:qaYedFXXrQFEUriAdl8bp/cjGAcBkQAT4tcF,iv:53fkiIxE7ID62zwkaX/NTyto3S7BCKe0U8c2U1N2MhQ=,tag:Qte5u/gP4cw4FLztnOGutw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XBPYqulTdg3B,iv:IbJP7/IvZtIc75GyEn7WeAZ1+p/bT01y2BEN3ywr1+I=,tag:s5QO26vMNfQcfHzQ3v3CJg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gM4j+WKoGRBrX/JESuouvg2/Tvcqxk8ktf7j6VF4j369UvgIX2e+vFLnDtQ1yeWtjAmMyl93cA==,iv:I+tz78lC95iHCihtUqZON74oZdyc3INWWz4O99c5PSY=,tag:E+NWj27y+9u2L1GRY/qICg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:c8nCtkUXR3I=,iv:MLY5EglfZJlBn9IX3tnktwgI2LN83LI1i+n2s3Ze9WE=,tag:tpgIW7DYB3nO6Q91LJptAw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gogl5x2ipCE=,iv:al324z1mJJVF+g77PnbYlILb3JEMgMQj1/e0wgCAbK8=,tag:UNDtQQLVV8/PO+CBZrJqUQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ARcM/g7PxIM=,iv:d7mCP2hslOFamUTZMLJACqwqPFifzXhZ/x8JmGfPenk=,tag:vUXNfJj3Z/WgoWQRc+r8Vw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:op8uXQuVEGw=,iv:krC1/tMUoN5w9zod3bKK/r4NVRe0azSnTLbfnh45qUs=,tag:TAOa0G+jU/0vf+jB+d1b7g==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:XlT/IuLuN/CXDdkz3tI=,iv:Mz7XxA4crDJgxgnZm7fz+xZ8aLX5hsToWkQKGhBOF20=,tag:l4MHzeAHsCxRKNLR8nBkLg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:5uRw9miYuQV93w+l2EPhqgSJRw==,iv:zH7JYluSoJHjtia2UFTfzmk79bQELnhfQtGF3X4eWWk=,tag:Q178+XooCsNfDGDmDqC1Ug==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:q4Auo5DLxm1oyr9ts2iv8IIkLg==,iv:ZiamMVcjpfjgU5GE9ivLWoAmU085CnLCrm1tbS5wsjM=,tag:rlJb2V3EnPc++jkza+XlmA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:+9czAQuJW/5G5gAEApEZGw==,iv:FL9Ki3PU2nsgVrkf4c3f+EzEsrvWPVS97I16cpBA77w=,tag:QLEvhWKBjDNs36P1N7aK0w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcGMzTXFMNStRdTIvd3px
        TEZNSnFPcGhVTHpuTFVjTVljR0J4MUFqOFhJCldzR0FjbU0vRnQ0L0tMKzJoN2wz
        R2NmSnhoN3RTVG9TNm44ZmVhblZzcjgKLS0tIFVFVmxSanc1RXVkL2NTYm92L0g0
        b1FRYXVSL29rT1FkMUVKK0dHZ2FKYnMK3rx9UjIUecM+wf205l+yuf+2q2f66CUV
        ovB4U3vHM0OFh2f8WM2WdzAk4LDF2QF2Wca/kdIs5rSztStcI4OeDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:MC4NUWs1C7JLI2FcWdMi+VVstzpDh3ELaHHQZOa9tKbw+82JY1FyzfUJ/rhzOcUr4VqMjJBbFtdQRUVZz9XGq/Dc0doE/2ZePDorrndLIv6t5qEclg2iyHMdhYRA10KGjf582DfBFu9RV3jSyrrQ23E0tck8vYxHMeeRyubV+cM=,iv:W2HUgQnpMg9e6xFcYmp/HKmupOkg2/yfgbHkBwZykzQ=,tag:TTdeaNKvhct3dVlfFNBJkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
