# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:xRjHRFk=,iv:lxgCDeqMzazpqqV9hWriLWX6EQBs3K0Hk2Jju1bl1nA=,tag:Ba03oBDvJ49zCll++CUkMg==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:jqj//YeAdHXvapXNfdI3ZOveOEMZvhnoJ0AG,iv:cg6uVGzPFEEANlzT9fzI2i5eVDvqUDp509OTzPEVN7g=,tag:L4CwQgEfMH8qhXiFDcfPTA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:F8W7tEUb71Ky,iv:P3irkGx4hjzX9ZjISPLYpq6MtFNwv8kRzhHpKkuvyyo=,tag:GiWMKnVw9I5thKHwZ/LVGQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3zD85xX43Kd/rF07bo6kYI92BVabR8Z1I/SSCl01OZxxbAur7fNTwHFJ6UI=,iv:KDRapEPJFgrSljtDGpxb8LgFAD/8pu/UlRjxeOXtq8c=,tag:cnRaZoAT0yVoxcGFuIwO8w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:sGkEESvN1nI=,iv:wjFvqFyFv4cNP8xRicOoJzhbVELwjpsPHClwJ34N9vg=,tag:kreTgvSRcwRPfEwfBbIvZQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:k9W3UBdWgTI=,iv:Fw5XraxUuxtUkp9zv7CAuLfUcl3X07zHC4pekbaAJUg=,tag:gIyyeFJiZ5SlD2P277imTA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ljwB5sJm+2w=,iv:nXRFzXKr1YsUFwf+zTN8Ylo3pGdBKfwwAV++K04cdEo=,tag:KILG7E4m4KLg13ig1cCzNg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UmIuX5V+Kp8=,iv:sGBYS5xvMRaPyhr0gGVJF0Bvv76FOEY9L1InhjPtUYs=,tag:FB7CJqD7ISdcbwUwcA/BQQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:KfSyPEk/woLqUll3zho=,iv:fYmS/9kq8Ds/r1Fn0/YGya67n8Fk8cMW/2/vdT9QWd4=,tag:qLlouBUk5yMcygyCBCL1QQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:YiwV6J2hnPvq1fcJTybc428aEg==,iv:YuheUqaSGRkYH0olRHyl+tfqEHnAbojAgkphVqtzHtA=,tag:FZBVfTepay6i9z7r5BdDhQ==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:RT/bRrXs1+H2MPWjmyEGhz9tRw==,iv:rfwOK1gZz5oMXKh2pXdoKGA65+HUjWn2Gavmjo7Fv9Y=,tag:dUOFv4C69baWCnAc3O7+Kg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:dcMinXkl7L9wk2tJsClOEA==,iv:cYUNw30ql7Xmk1vIF0fsd6J0hHEJ41Dua8IJFlfL+9Y=,tag:KIGyh+dCmmB2qMzRLoNYMA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU0FVSGN5SFViVm44SlNY
        NlZ4eEpGRlNGOVZVUDNOYUE0d3VMU3NIQ2xFClEycVN0Y1JTRkkwUlZGSk5RaEwr
        aHZvUDdjMDgrSk1NLzdJM0MrR25YQWMKLS0tIElpV2RRdk1kTHArTzVsbTU5bVkr
        L2NHOUMvZ09wdzhwcjFOL05tUVlzQzAKcjuMvY3KIgY1Bi3gZ4DROWnOTi+U6aO4
        fJ4/7sYeuRcQBHr2QfLH/ZWGM4rQA9xHy6Qt1oIbMpqrxVcDu/5ORQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:K+ZptbdZZaym79iwDjx6e7R6SxNsdfWp1FGzooPYnvgHeKGtaj1kAENw1n5EPfZ6u/6S0ONrpDQGA2GfMAID4CGEJDNNFqQyjMLZSpfhJrX3YacADZvcZzLlo9U2BuMvOnFL4enMVCj7q8hnnOZMU0XAhRcv9Th/tDzs7AeUyN8=,iv:f/dLPZPargQO/i8aXGbdgYldIr/LWDI2T7j1nYB6M8k=,tag:eVYm9AB2+qTOrcoyPTnihg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
