# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    nextcloud-username: ENC[AES256_GCM,data:orl6R/s=,iv:FN0BTLIgQFGuaJEZ0XC0qnjAqxqlFsq/o0zlpIb3FKE=,tag:H7y3rytKMYu6lzzEBqQ+DQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:KFEF/q1O6WSXlXvtiPAbN5NXKH5IbrzY1nHd,iv:rD4gbCrDP/aY4rxV3MIVfGCReUKmuhCFryiyh3je5is=,tag:5e/7wgP1cwVWTZ5dwlKOuA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:L2VdW3T0ZHT1,iv:0J/adbJK5EBwNcFYuKFTFZlED/KPddbSYAEm1iLGDZE=,tag:ZIMP80CPU5fIQQH/Pv/hpA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cw9O2oLRZHy7wLWzfCyydygztVfVK+8YeUDWgtzaZ6ov2APxeWFTbfvJJ1k=,iv:ugLblk2JcP/CSqUCwktpJxNW/vs7wwIrPSbJHZQRzj0=,tag:hjUIBTixZk9viQmrBG1MlQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pns+jP7KsbY=,iv:mI0JS2OQJyVhjWvJmJ4y0mFcvxCc7Cm+6HOswfCqsVA=,tag:DWnKaFDEbmh8ughKDN6Yag==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ntMcTL/ZWdk=,iv:iZTE0dzCKhZ9PgHw5uRnL3/2D6BjSkiyIFiSB9GDdfM=,tag:PEq4ZYN+VGBPsDWVSEhd6Q==,type:str]
    INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:OB8=,iv:Qsy3DUt29T1qV8zgHV+TvDXVkPX5/hu/6bqSZ02sN48=,tag:vepKJf25fGoyPEYuLB4BRg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:kcg7gDAuQGI=,iv:Fe1V3ouTeRvODAOM30y7Qi0nileKzZKUzFzC/Cxj08M=,tag:LGPxOJ1z4AzWjOnaEK4/iw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:+30vlOC+vFM=,iv:Rmjf3QKJb+y1NQICIZ3CHN8IMLtTKjuyT6FUPReAVIg=,tag:StFM49ByHe9jYJGR+0nTsw==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T15:19:23Z"
    mac: ENC[AES256_GCM,data:iEn/yFV8UqDpX6rE0SEQE3Md60GJfYDen/UTn+HCM/8vrAJQcEAyR+K2jZLrSZeauT3SKGmlJ3tVtcpVR/cwjhmCjmxKJCTYjkDJkgvp1cNPpIy/pVLd2oB7taepZ+Y2areMdwDeeBuUtMA0Qax85kQg0347hOCMwjwFjaZ6PMc=,iv:/plP4yi5gY8ZsyVMT2RzwClPmR61rCJWfKRYQiVNXJo=,tag:/Ue3DJNvIkj4OvvU4nBTFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
