# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:UhQyoBI=,iv:JrX14NTyWXAHOdwI4MEaVVV3zY6zo94wdwx97Cw02jo=,tag:IcuDOyt5kh2VzBnO/EorJQ==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:loqdbgQkyOpsCWrXXCPUsXiKOIVpd+JRNUHp,iv:XuKmci7TnuEIoXiGKB7wlu9Hp2+4H0KvgJdEupuZtk4=,tag:3E/Q0z9BTRkt91rgEzenRw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FbuYPnOuI2Xh,iv:LCIRuwf21/+aMx3dSLasa2dPKKMrq2KuYPjKuMz/uB0=,tag:4pDZ7fsqRLdtYyBz/RREtQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:J2kI36KjSolryPdfty5Om6O4XflNxOjOAc9CW2FPBamvPz9BIF6tMpibCK2Jc5PdoDT/zQ12VA==,iv:dciOPYlaOqenWkp58z+ocNDw+M4XB2Py8rBwZgiHFTc=,tag:zmYG5BNUrrhKMqxWlg4BVA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Lk7CIjUfVwc=,iv:nfWDy9k99mNmor5PNo4lQ8CrBrOVEye5AlbP7e8LyDQ=,tag:j2aD1HuMLldoQxAYrHve0g==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Gd2I27LN4cA=,iv:n0WN8p/eUCrek7EsqurGwthmINbzZg04FIXEt5EVXnk=,tag:BZ18AVvWPBFGp9i3cE5obA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:J4Z3bPbpnLQ=,iv:AgvVrDCNBwJGktlQtdJYsJ/ZT6HeTQLyG0wr3qjvqnc=,tag:+YwwUuKNIBotK3ZYCCMSvA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:83lnHB3FotE=,iv:R+FFEoRVVlyGfLx1ihq6nJMYQCKRsJLvH+UieOd9Cg8=,tag:wwDDKVTyUUmkfuHZP0rYDw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:OW4QfMYIF+7KHjNupw4=,iv:DTlVSQrEe5EDZdcWuIcR1gmss+ljM/K8xtqJ6jXPnCo=,tag:t3eSXvpCzhMXSws+k2ZIlA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:djvKm/g55gvJgd78gNGUJCCxzg==,iv:rI2RjCdztoPO82kul4TAwfWP+zAq3baI0sctJALh2tk=,tag:r/I8PbBsCgLZY1JQLj+2rQ==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:Af9it47oAs5Su2BYpTjqu2czJg==,iv:KhZ58tPIwHz+owPHoESuL0TF3xyRR8BOGZkDUzYlBIU=,tag:yJTf7WOzNQni7qJGSU2AgA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:uKy/YhT0VNHCrXQasvtk7A==,iv:fpW2xnEaZXSTyfp4eqBtb29r7hsEBGA7ezH5U/QzpQo=,tag:t689kLJzGgGvcWgwG8wZ6w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTXRaNHJjZU9ieVhpM0ZU
        d1FXV012RTJkNHdqYmlZVEwxb1g2QmkrMFE0ClVwMHF1TGJzUjAxd0loRFd2V1JL
        bzIzZmhWeFB0YUZ2cGFWOXJxK01haVEKLS0tIGFLNkRRUkRZZys0V2Yrd21nQlFF
        bWc4dGZ0cmlxU0N0bklUYXpIZmkyQjQKAh7bkkMczDNFhY0jjaU3t3wvSEeNhkqM
        wUSRdBNdRKoqxCzN7UpB5u3Cfq4aHwygbw5tdXzlJ1akweMmPyrNYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:SCXWD7u7ydc/9fC6Ixf7DxZCeQ0+/qB9Ow5dBd8ZxY7x+jjHRXYZ5OxvzU7CrvVpjTBuFs6ll4nx9+VpoFqHAFv/gE9zja/4oZlqBF19Hp4S0Xj6NLNFJ8dE1ke4+oVu8dCvrljqu0VtxB53nHnaF/0mCpLFZ133o79IEvTV3Mw=,iv:NYOBmXzrUhcsaCCcFrtrZjO+RpszcAGq8gnwlCMWTXw=,tag:V6gMlQHgEbXpMNS1wv3PhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
