# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:0M/FMOqcMO3QLBGiBQ==,iv:putSboMnW3pYxAuwgOfgJklTTSfqdUFRfjVnMbLs7rI=,tag:V3YawLrqHJwmD4JdvcD9WA==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:FeHZQXak,iv:QOt1LvBcAmqaU577Jo7WrRm3k95Kl2hlIZYUnbZUDVA=,tag:VczZDqWdlyhitzL/ZpSqfQ==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:oe5I7e8TIkRoctk/kwDEXauY9V0S0WON9gPl,iv:5PJJnYdh3RzpwGHuAwz4bjcD0LkgWr3jCrXG9lvHALE=,tag:MmOlJSFfvvEbRNZG84AZJg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:rTnFIvrxSKih,iv:JSzfzx3v6vOfkPdc9grjv+vHqw+O4uRYjz+Je1Bcy+U=,tag:TMOPo4GjyiPFaWPp4murrA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:Evcpz3HZnfW7waIuFi+fB0cka7YdZnrDFPmoVrd1RWCIt/PuYWJ7PjKb8hM=,iv:ME0GFHbRISOGfG++qnTPOgbCM3H5co1QWIWkjXnmtSc=,tag:CXUP+hGVUMNOIfZKvmX8Pw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:YhKAINu085M=,iv:fQS3ql+gYDwKbGMPJV4sj+k93CDwRXQwRfJ0cpW0ai8=,tag:eLnJKzQw3jevp2PdeI6S3Q==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:C7eNdFoQ/08=,iv:hrswJggSAd59QxYnCwyc7pWEs7oiwLbyysm5ZIHApwA=,tag:Ip8RZcLYu/dPr0Hwh2Xb+g==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:pvoCh8L3LaRD32Y38ls=,iv:8JAKq6BIx0TrlZER9Wco445LRdgDqmKao6b+TZS/n78=,tag:mDVqNwm1H2cBz0napDRiwQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:wHllbuRYtzXZ,iv:lUmEp9wMByNo/JH0BdSSD8H5LNcmqqxNMaSAZN75IEk=,tag:8S5xcuwKPUnHN8/YbolhGw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:t3i8re0umN4Yc3RNQCluKK6EDg==,iv:/oq7AqCE42+z3zEWlwt6jytq6ooImgR4ycD2SpvMWb8=,tag:GrQJYKnP3RdxeyW5xN7qvg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:dGmjGXHRWxMGQ9I7213v/g==,iv:p8JrLwqrkkfqZ3V3ulWSOWUErd6T5KtobvLCQ8Y67NY=,tag:GGHgZIbqixXs4rPi3XLwbw==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:uW04qDLq8XLL,iv:nznKcH4uHLvr3/XDy2Wu928K17biVnSw2k7HdbP+Kl0=,tag:2ZguoMNfoH6z4zFjvbhttA==,type:str]
  COLLABORA_USERNAME: ENC[AES256_GCM,data:fAgozU1c3V4v,iv:Z+yV8Afg1RZWOMoGJAD5V/5/Kf2cmB6jgdBQM0jbMGA=,tag:t8L4/yX2sASjblSxR+Xa9w==,type:str]
  COLLABORA_PASSWORD: ENC[AES256_GCM,data:QBsA5NtUBOj7,iv:TJ6+0BjjUhH/zjrlptpz718h5ItilVM98kL3WiN34q8=,tag:LUd9VEqexWG77xj5kwWbhQ==,type:str]
  WHITEBOARD_JWT_SECRET_KEY: ENC[AES256_GCM,data:SbG4uit275xBCRrFm+PVv/PbZvDW+rwylj2Drhi2LMW5xggxDA==,iv:i4bdNtsxJl/V/G2pGw94JMJHJP3lZcjDXUIoLhNRnCc=,tag:5AqIa4wXeDvJR4E9gK7+KQ==,type:str]
  NEXTLOUD_WHITEBOARD_SECRET: ENC[AES256_GCM,data:1XmNyiLzBD42IdYrnJ5AURLBdODSWEZIPmAQHZU+j6UBwxPmvg==,iv:FtQFCcOKOhnloeMArRd6ZJIFQKswS+qge7i23PognQI=,tag:2+Chb5ykd+8jmTgxDaQRjg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU2t1TDJ6YmFUMjFoNGJQ
        WEtHZmNaMWg3bG1McCtucmNZWEs5TWsxNVM0CldIaGlhbFhCQUJXYlE0S21HZWZ4
        b0YrRmtlbkZ6Mzh1Z25NdjV1ckVXaXMKLS0tIGJzV0doTGpKS1FuOXliRVFYbUZU
        dmlseFFxeUtnOFZzMG9iNVh5alhCcm8K96KUc0tyzRLqgcYyBFVtDt82ySwwOes1
        yPX9Nxj+bMzGpt8fCAD2LVDx7nZNGbwmOD01BGrOOScO7vF2mPsyPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:xO0w5DYSIErMInPdfoupS0m5d3MSo7LLgdgnoOKpSeY96QgIGAH1b+JUYhMq1yKLvN4wKYGo2rb94vc4ULL/MjxpxlOjTgyL9IONjJuzAZW6lj4Hom1YqB4VJlvGPDRXEzrlFNqbNySy5/GgfG0w2xcBIz4M+Ca8IL2f4+uq7EA=,iv:rr+G3mxczfsJIYcLRPvylmlLa6MlB/C5zhrC88dxp4Y=,tag:7w1PR2CH0Ev++uINT8korw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
