# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:Aoxq69s=,iv:5cVsT2psmaHlciq3ddyIYp29Fo6eTxSlS8EChA7MW0Y=,tag:IF0+8s2saMPpZ1xvcJTngA==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:W5ODVKYQlIKOp3vcFttIQfc298Z8/zzQ5R/K,iv:B8kNa02CvRmj7YJIsld5BOCFJy8YiJVGXdgz6GWMOiY=,tag:YeL0+J6ZJz4/GHzereLLbA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:L2VdW3T0ZHT1,iv:0J/adbJK5EBwNcFYuKFTFZlED/KPddbSYAEm1iLGDZE=,tag:ZIMP80CPU5fIQQH/Pv/hpA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cw9O2oLRZHy7wLWzfCyydygztVfVK+8YeUDWgtzaZ6ov2APxeWFTbfvJJ1k=,iv:ugLblk2JcP/CSqUCwktpJxNW/vs7wwIrPSbJHZQRzj0=,tag:hjUIBTixZk9viQmrBG1MlQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pns+jP7KsbY=,iv:mI0JS2OQJyVhjWvJmJ4y0mFcvxCc7Cm+6HOswfCqsVA=,tag:DWnKaFDEbmh8ughKDN6Yag==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ntMcTL/ZWdk=,iv:iZTE0dzCKhZ9PgHw5uRnL3/2D6BjSkiyIFiSB9GDdfM=,tag:PEq4ZYN+VGBPsDWVSEhd6Q==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:kcg7gDAuQGI=,iv:Fe1V3ouTeRvODAOM30y7Qi0nileKzZKUzFzC/Cxj08M=,tag:LGPxOJ1z4AzWjOnaEK4/iw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:+30vlOC+vFM=,iv:Rmjf3QKJb+y1NQICIZ3CHN8IMLtTKjuyT6FUPReAVIg=,tag:StFM49ByHe9jYJGR+0nTsw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:hMrLddO7Cn84DXAsAfY=,iv:Gtb5yrv0x8tvLmNuwWu5fcoYMfYRSBX6018v9LWd3HY=,tag:SPtyuHxYso3U/M90X1UcUg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:chIXB9J1GUzKahjMYuFrZPlIpQ==,iv:Uj+Nkue6Qz9cN/teut/LwjfbeMFU2ZF9uKrbZ1TNfQ4=,tag:R6zU02Ani7q1eNvSWO24zA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:4OoalosT0Ob6iPQNOhKvW0FePw==,iv:MkWOG0wD+kPFtCjWU0drb383p5foyLbxuEE27rcTghk=,tag:DroyYNzAnwihkBNSfr09Aw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ELKnKUQ8lFLqAnsvemLksg==,iv:LZT8/ffNipM97yVtgjlwk+EE8dUnlPWyIwRaceSeJLs=,tag:IDvzGGPyak+KRCt/bt46gA==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T13:34:06Z"
    mac: ENC[AES256_GCM,data:PPsjl8aaO3AlJzXfi3mHJkBXaCvKtSoc5uvlxg+ReDJZQFGrqVWWnVKWLf8O9mDPmwuUquXLnMpB6909Rw6qk50vA+2+CY4RfSwKbv63JVhT9To1NrRypcECgsZeB3XH9UyuuMgiAGjpSkL1JHLbIfg/WG6vbJgkGxUnbD6JxwI=,iv:L8rn/elAjfStVcW/u2JrdCVAFwZKuH3m0p8dcJOb5Io=,tag:Hczpu59xTqlH0LyOqLzzKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
