# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:4XOhmAA=,iv:3BUVmHdIBDWu+f43s/wCxFomvYW6qvZF0uYpcDy8QSY=,tag:j7VTRtU83AD7VqGlNJCtvg==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:8gAiyaqJEY4aLBJkViBEPwRMIMP03o9EWH4y,iv:C3B8+OXFhp2n4NNfiK+gJ8L9mprMjOY1y8sIUKJhAhU=,tag:gnbbkQVdB4dlYPGJxhzNUw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wonpSGSL03F6,iv:f0/J6zxfXK3uj/bWdtIwivnlZVzqRD1WdmHes7iIg1A=,tag:06KPPWd67Q8d7NASC5B3kw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:065Gm4m5wqwbTS3XiDhxlHJ1R+2ICuAHCXOsrpTK+0MqE8nCZJ/WlkU70fk=,iv:HGTSmAQ4Vk4Iw2wlUh1MP8GWcDhMIBcIVIDQLs+FC54=,tag:tDVNl1LUtJTf+VrBC/kmdg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:tCrgkQTidfs=,iv:SzuMctx0vI/3LUPCzdo7d/xfGKss17+bX0OsEeMt0mo=,tag:Uxu0ScU613QS0AaSX1FJtA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:tXVu6gyrma4=,iv:er9KG8gx0NBsBCByLBRCkQJMTypOWdQXEhVKBTQxo0s=,tag:gIdD0JmhhlZ3MmZjAFVBmQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:o6jHSqqK+WA=,iv:Tp/mtQpcQeoAiATDO3yKwrCRutCd5oGcTYIXYbI/dUc=,tag:zrYKD0YOyzAFVYLnj3DBJQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NPJI3PpVZ3U=,iv:BfH0Ptqd0QfiWjftY9bvq0AmQyp9q7c/RKOdGK24/eM=,tag:2c7/SvoLBQAWsCBFoMXwow==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:gDcfWLo2N2yUOHROhq8=,iv:/8a7TMlm7ZnAtefpRx/OprASzvf4OXN6F3KwAfYTtzc=,tag:Z3pH0KRBWLpAbioTZrXvSA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:Ql6fS7pQCc+Iado1LRgntD6YFw==,iv:9pR9BxTHFt9DTG2UC5PnY54WYeXaB9IhvVHIH2L6rbM=,tag:ftRqjKvvWDbk2b0zw7ojzA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:HB42uqiWHT53KBTsvxas1fxe4Q==,iv:2uG2Fc4lC256mNN483O+qij1csEuGh29AMGqLnZ5xiw=,tag:oQcP18Zgd8n8mzfVQ/nSBg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:/eJMsOUlUnFJX7xsdFOyaQ==,iv:BC4R8o6ZOP98NkLTsS0WqxLZ28TX8t+2YMgoqk9qZmQ=,tag:TodqejqB9SI7b2wKNXW5Fw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSanZ3aU1ualUwaDc0TlIw
        NG53Yk9pQVRtVjN0NXFMRUwzaW9Jd3o1V0dZCmhVR0k4Tjl6cllaZFFXMVJQblJj
        RmloZlhFd3lnQWNuVGc2b2ltb2JJYkkKLS0tIGxZYnh5M1ZOdGtsRWU2R25md3pI
        b0tJZ1E4UFZoMm9DWGQxMUxsSUJ4ckUKIKaWk5+4Ky/vylmsDByNtQc33iT4mpjm
        EOYhEr6A3KmGSMhDQDk++x7DWGPb1cNHQ9revfV5c0Zytt6cJwmLSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:y0k6dzkf+FKn5ZRkb+Fz/ITksS/2tzo040eI5K5+czFAziICnxc3rK16aaVH1UjWDAKxB+OXdl5BByXFVEwHSKeXNJn5Xdw3i0sE0XUS7PyIgO5DSnCOWHVme1yPDvhcYo0epvwYfQDvcJLDBk9K97W8dS+QfnxFZ4LEsTfsvSQ=,iv:rIz9S2bFXqfL2aZgvxsgk3UbV5DIHP7tvraR00qXWss=,tag:JaRuec9yZNyVyCp+xD97og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
