# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:ZEpYtX8=,iv:50S6YxlKDrk1ht1q/5+zw1JAaIrdGNPwmGyYRT9gep0=,tag:IvqM9bmBEKqzFvW9el1XZA==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:CZ83MexjcSxgNQvHKWNxH6hB+he1fMvE8qtO,iv:Ro0hfh9VaD3JzehAS5vSYEB0izFL/fC4EdrQ1YtwPOE=,tag:kfTnV/MnKKkfRoIGRD3IXQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4dAkvcLCejal,iv:Qgy1x+VhjJEX3eTvFqgNr5SN/fgRDptt9FJLa4NqQ7w=,tag:v0PnbmHMXtvWbfnvrmpFWA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WEMPj2HkojR3Zd8TABoslVU9EO2AqUlqsSP039YihSDg9CaLDv7HTMwDZPrQG+tJCDdXT3FRqg==,iv:LVZVE2Q1flHdEkxVbNVaZffe2iIR1pIBfHLkF7AAuW0=,tag:AAy0Pz++JoxmoERD5sUryg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KnUvDhyGRHo=,iv:a2FpY3Jz4cB3L+d4H/328zIH8NTafCcSowzj8+Lrb+M=,tag:y8P3MBoEsC6Qndg1JozChg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SOZ8WwNa/Jo=,iv:h2+mjl4wBdCUvwKgJ9P2a01ePYXgxFZg/w7ic7n3HcM=,tag:pHX3MVVwTE/+rwSiUR24fQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:EWYHyJTp5fA=,iv:kdNMMxO8kW6JN8jw/Uci2bFGVzWdNVX7h1MKvuqKdus=,tag:zNA6JGDYeGwo/rZUNQLy/g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:cN3m70Fg0Is=,iv:HMlVfhd3h7HXGtPmrVth5dTpXbUH2dq7Gy80L4dX990=,tag:z8btRPVyiHlgZ6VpCLS7qA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:+lwyQGMUyPS9PnhVr0k=,iv:IEqmCMbQqhAzp1X+tiTrb4f6zKy9WYAokWi1CeAKXQo=,tag:uYxwfCnW++MctNj9o4ORyA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:MEer+DE2gU2tdxYleJr5jwM+fw==,iv:AnVRNmWUKLUzuGyVMR/AHpLHZRQJRyyq7tKgjpbn9Bc=,tag:nGwEV8tHS9FOxEXkck7vQA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:UdXUBXvcCaRejhelTH3VANVG6A==,iv:2Xcjkpet52EfN6IvUi04oL9eqDB7jid8HSig89D9CBs=,tag:GmaymRhE/GSrtySOEBkFsw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:lEI9xFofOSfUI/x/sbqyzg==,iv:jLdhL702NQ+z0nq8AdxzEvd9MQn5Jrc8ZvQXmfqZHKQ=,tag:uajtUxOCMiQyX9dnQQdiYw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYlUzUXM0YTduRUhBZ3cv
        djl1cW5BNW1QUVlNbWkyRVRLRXRYYXc5M1hjCjB6N0h1eS9GS3VORmFqWGNnREFK
        YU5nRzNSa251bUt4WTZ1MURpbEk2QU0KLS0tIEJwQSthTDMvRmtZVE5vQUczZ1hi
        N1QrdWlDR1Racm12YzV0cS92VVZUWXMKuGP87JWIdtHRGKRiy5hk/V37A2vXsp2Y
        Xi2THR2153pnOxY15Bg/iwQS9P2EepQ82wN1EaYYl6+Kl3GuAH2F5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:hDW0+HDB8ol5pQuI8vf6KNt8qe5FSZ3gCrtG/kGhBUSMOK46jG1rNvyBKqecMmgxKHT3tooTv6m7ZjKD3aLf81zWDmUvLWXv7ofMUYNBg32i9E2LjFzGYBWuo3jN0oh+Ss4HirF85Wxi5fzbLWoZj4KrbjT0g6yWMk3znkWDdx4=,iv:y+8w1cA6YgGDF2/RC53/PYkwen1zmcXnjVjxlpzQOnk=,tag:agcTsnG4eQ21lmyZWqlpxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
