# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:6WO1p/4=,iv:h9w3IH7yWSr0yASU3H6UcJ7TQN67xVXw7sA3enXZYkE=,tag:Fqyi5wi8SX8bE+cWIV+aww==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:L1ECQp/W8/2tgyABEutyuSVdldlA7Kuc2zTz,iv:x7EdqJEfY246vwMMG6fI31hkxwiBiVCNiFVEoZeVE0Y=,tag:0RDBg5qvvbwbLb2yIYCzMA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Z2Lcr/tBymxv,iv:xVBindVRx/hLPXMUtSEBBDuMkmxYI5HXXUhNEPXoBlI=,tag:S3Awts4q2f2zEAVsk3+kaQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8GZyGpOq4ccva5OI9OVG9bMgbDmeHppQsfYVJKCu/j9K6ZfRpALBu4nbgm266w387q2aJANIeg==,iv:zCSJsseEH1PXXUye+jsk9l47f3Yuk1GGhfW8YRrD+iY=,tag:hpMLettWi4hZj7TtUoysOA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:6AAIBG/WIgI=,iv:VOZkfo+HLg6INcHFmTdiHyF0k2YlWJ5nulJ8C69HbJg=,tag:Tgp27PXMGZ5qYPweSpvOYA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:G22F9oo525M=,iv:VwSzoMxDqkpZFx9RUQUByDOQO1wSajjyhgua45VgIz4=,tag:X8UC+iBe1mhioqun6fk3yQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hrwvr5wsByw=,iv:5nef9Ugv7iClTxA7IyiRM0sSNg6qnLfVjj8OBVhsMMU=,tag:+bezDJArg2LsNpi36DkMjA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WV3iwHe0M7Q=,iv:zacyw55egXK5byXdzmuTpRxZECWVAwLY0HmelCLefvw=,tag:z8quVWDxRfd6gsDmnvT+yQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:qpFZOwI3d88WD3KIXIg=,iv:8jZzgHM1R6RLmV8c25r7x3o6KxMJWFjKriwOra2FP4Y=,tag:wpwglUYDUWwiBT8xe2Xghg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:VdndXnrX0gFE1M9ki5WrvEkZ3g==,iv:7TqL/iHMhr9PtGBKTPQ4X7Ck9V/HayWXPe9VuEH9C9c=,tag:mp0Eou2NfeNjG8Mk9ch/gw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:3vQmUrCPQnzljfBbAO5W+7CNIA==,iv:VOFagsxlhJoty4gNR6aEekwAvsrcx/y6xkX46IT7abQ=,tag:Ld2/j/+wPuKpJnK1flQ1dw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:+s8dEyVe4KSyWYlNpJ1QMQ==,iv:8indpOT0eE38EFvRkHaKo18QVXsb41YMUrmmCeVAgms=,tag:65viHkZwJVYM7dle/MFyXA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeGw0cVpBVEhiVkJsMUpI
        WW1nMi9MZlNZeFVVclM2SktpM3M1RWJIQ3d3Cjcya3BWU0hwZktVMXJicVpienFh
        NVNlZWpjb1hseGQ0QTBYYk5haWt2ZUkKLS0tIDFmQWhBM1VwUmxQekRLZDZsYWRG
        Nk5mRlZvd1BjRlZPMnlOOExYN1lmSTQKK08CPBtMWCaXVvhmRYU5Tqmf2bQ/Gjsc
        ayHuJEO0fMAaNqjvzcVSgXg5v+/CVDGydoJT7GyMPvWqDobFtM5p9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:V49LWAadNtwNRCc3IAisMyNFPuzQYu4RwYRdZg/6WQkanZaYd7pbFqG0xIkCeDoNpBlCe0Dcn911Yg1A22qzqPC5g5ty8t3ZJG19tCyBoHqs2mKC1m7gVKIV0dgk57qHLhun/l43R2mci4/dx6vVubT/DCtqCNi4BVhF6A8Ep8I=,iv:XRaEfyP8V4RxsV/WeQxTQ5A1ckAZ+RQR1Biuvn+stiQ=,tag:+n4vxQYMrnJ4sBI8yijO/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
