# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    TIMEZONE: ENC[AES256_GCM,data:Ltv/0UtHbX9hNdtbgg==,iv:btS69JQaeazialBJbjZaA+KxtBAIhRe5JJ+jeT/Wy8k=,tag:i5fV1+OqmLCPSGZCps3dmw==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:zIAOhcu3,iv:kbz+JTxkCIHq2UwBhrwSz/K+/0O7uBNINaTte0M9oiU=,tag:tcc8XgQ+KAIWHxWVl+EuZw==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:dhpXgWueCpzXfQ7I1vd2x3xx1hGb6ckekwqH,iv:YUH22RDBQT98FWhkcen9X8o9YZ1qvn2IuYF27gsLgp4=,tag:z+QqDdiQ0KvW/9CqxbYlkQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sg8RJ43tT/lu,iv:ZoQ357SbL8TRGl9RmpyM26Z7Yw8XJsBNiR97cIn85KA=,tag:clDTCyHD/b5OnhKBbvnjiA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:Dz3v3l40iMtpDxUNuwncRiTE9OG+nabkuDz7tkpPXH5ZaV6BIu0BhbRrqfY=,iv:aQqTSHsR1TiGkE5tWxf1LfdsYAPVkD92szKCy26qnM4=,tag:4xkVtRHTQO/MtyVZ9JLQKQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:xayYvVITsO4=,iv:lOXKlxNsqqjdrIzDBwy2p+YZNbEZDa7nQRbEAjtmXBQ=,tag:t30i41XsPCJS1fEIwhr12w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:0hShHd7BNPI=,iv:+VKC77jB0xkPJPbpaSThWSRpYNoKJXN4VS31Ch4HrVI=,tag:1smcoxjrg3BodabNWEc6Hw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:fU8kFTalbXK4kr14s0E=,iv:EL7DSgTQXBY2b5pRvoukeCqOdlN4OGMZmUgTM/JFtjs=,tag:TvvZfwtz2ilHBIhhrzP+dA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:KjBPfFQmTwVk,iv:Ln7fHq5Joe2rcIo3bG6Piq/mxfLFzqlDL8i/WXnryq0=,tag:vCRq3nFBGWO6f6WSzI2q4w==,type:str]
    MAIL_DOMAIN: ENC[AES256_GCM,data:Q2cBfht4vycR,iv:Jz8mR6yhePzklw1kVL//SUP+Ajj6IXfZNb1ij7nzO+0=,tag:YC1+uclm7HBBNNpG8mB6zQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:c2UxCNG44L/65w9AKa3XEoiDNQ==,iv:ytvX8laFt6N+eVV9Pc1pUJIV9GI4RaK/U6lODYhoY4U=,tag:KvogtVlnhQqguYaxWbvNEg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:n5wTFjmBnlt/8tFBcSX2xw==,iv:kv2vLQTnaFQ9waWY9lpBVqy/aE/KJT3YdFd5wYAgm2Q=,tag:nvkhdeZPW+hvFPbtrcUY0w==,type:str]
    COLLABORA_USERNAME: ENC[AES256_GCM,data:Az5ApARapApS,iv:ORnGsc34K+i0ZZ3Bc4NUzvcUZPBh5ofRIVzUDGXF0Kg=,tag:KJutUEGYCeqKlzw7HqY55w==,type:str]
    COLLABORA_PASSWORD: ENC[AES256_GCM,data:gvObS29rKlRo,iv:UYgcDBfCiIx6sIjgAKKqUwMmtVDbWruW5iulxjz1iWk=,tag:GC2Qqz0ehw70EiIL0uYjwA==,type:str]
    WHITEBOARD_JWT_SECRET_KEY: ENC[AES256_GCM,data:FSXzk5Hy6eshISGsR5LNYP3t7ukMGQEjGfPylxXu4Aft8wzJag==,iv:IU+VQb0Gq1TQJXVxoV5Nv3D6CqAQxCllyKpLl2jAu0A=,tag:ULJrK679ZMKcv0DEvs80nQ==,type:str]
    NEXTLOUD_WHITEBOARD_SECRET: ENC[AES256_GCM,data:N+fFftXwfsMTWkMtCI3oBOdi9auBcmCsPyDUm5auH2Rbz0RXeA==,iv:kz74JRlT6qWLDrQq0DSxkMvk3oiL+JIhk1aROTBRWoo=,tag:lSBeioK+DtFqGk9I95ry4g==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMnQxaHlJQTdLUE4yRmF4
            bGJaajNjcVBhUXI2alAwNHpjOVBpUHB1TFJBCjhERUJ4YmgrbzNJUHdyWkluQkc3
            Q0Flc0VDNTJ6dU1SM2ZiS3UzUjJNQW8KLS0tIHdjbmdOczF5cElrME9mbmtJY1Zr
            VXloSjMwRGEyUWV3KzhEL3lQQXpGZXcK2jwAde6zrhEUctSmWl+cK8/lJvJ63/aY
            L5MS6leFg/RxYRWS48ea1nO5Fhnj6uNHt3U8finI369lZkZsOik4VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:19:47Z"
    mac: ENC[AES256_GCM,data:9T7IMqDjUDZ6g7nFl22dvktTnLO6jRJQ9BaddcrDekKJ/GH/kVBO3F8oZOR1Q4ql4v9csQoOvvVA5ezPiFzIT4DK/d26N0Zsh6E8pApuFJJyQM37jb7YJcme1HTL4jH20Ed7qqoIRTZxiG8S73esHULeVOqk5gh0/+L9PsXk0Hc=,iv:S9blNfBMLFUeCesF6DTvU1ncCEkSFikjodeSu33ie0k=,tag:POL04sY2tSBhGRvjWfghMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
