# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:MsINw+A=,iv:g9hCNOBn1r6MLCGQCJsASpqU85nCJvlHIFbVfajyz5I=,tag:UB4phy+puXcR/vIWc2CEnA==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:7nsjbbXf4eFI6+idw2QL6jgILtQf1aBRuGOu,iv:nCR6rFXyeSNoSXKNvF+m7qWPo2aM1EWzerotpcuD0iw=,tag:9cGHQ86ri+Q+fBS86wrsGQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:+RqVBgfyObTo,iv:0pJiVvgErhYk27tp0gJuPdF3AjkOlOykM8MkzNgWpZY=,tag:032uT2Ud9M740Pifa3ttwQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:zEwRfHx40CxzfaMCSZCItGMYmPdVxOowiOoj9jboSZwJ9tpulArWpWfrrUzwWvmlnQ5LdHfieQ==,iv:UkwHm0Jvseb2o4dlN8euxB8cgrytS9Qd33Sywt+/+BE=,tag:8OxymDrO5MKpWJC0Wi5ipw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:5BwtZ8j0dwQ=,iv:ZWCkik8jPop9cru4YaTdgyWVmnbuaOYqlTUU5PgP86M=,tag:fOwD8RQ7WAFyRW6tcu0PWw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Ax4t+gpI164=,iv:EcbDc8G3RWe0uENATW2jwlwvnbh0f7JwP0M/OU6cOlc=,tag:n737mOVPTIkdjtWfVbO+Pw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:CPaTlL0xFgU=,iv:gOEd02a4KNm+CgqGb7aFwY3RpMQP9AYY+tezp/P42Gw=,tag:F7rOnKNgWSEvYvO15SkNjA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:15jZDtrZLzg=,iv:is2XpcZbR/zonnxat2EwKR20VFtDE1jNDuQNGontN8Y=,tag:qooFmziqHc5K1qCYeoFelw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:JPU6Wj2nEdHuv6/TsGU=,iv:m+fD8yYuuoWPIRrHPmorHlGNlyj8dkgL2ZblKdRLTQE=,tag:9N8SYpw4UQwZOBWugiRtKA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:hUacNvt77wcoOE+o1+Zh8nsIrA==,iv:QXGqxgUf2qupd9BxedNvh9W8IUpWXad2QK4lMk1oS6Y=,tag:7O+I1y7ceWtmUdblpTqoMg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:aI4eCa0WQCfbyBaEtNcVGSWqsQ==,iv:nGVtfP/TtmL+HboA4dutK5gWeXrpWh7tCHEkh7WaFVA=,tag:sFtUScrh+FwPgfDwNZD9Mg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:PUU52R9DTnYM7GSl1Yh9OA==,iv:352jR8XHmIsKoWRCEb0E1hy9bIiUPuo3JJ/r8tLmvrA=,tag:fscerowXxsWHp+yoc3WI0A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTkVMZGI0OWIvVXdtWng4
        VHJhUUNGdzM5MDBvYzZFOWVsUCtrS1ZvYnpvCjZ1UWkzUDgzUXZnbWlFN1BQTE5L
        bFBBUEo1blYyb3dROVE4RFFvMEJCT28KLS0tIHZNeExiWW8wRTAzejRtVU94TmFl
        U0VsRlFkWTZpUXRuTHpWWUR1S1puSlkKwRtASeYOhwNnFIDVO+ggucy+LHnzth4w
        dLS+KsikPV1YKm/q8MqkECu34wp1SAM8FfS1rEO1htEYZamFNj7Ejw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:P3Y3+6LWvio+Pb43GxayMY8MHhZbuZzfD9Y5+Qy37ivmDJ2uPxsllYLewaLbZ0OvwJkxQWroxJlel1pRT4iFcOpMCX9DDd6Ds+Sw1ekHT6wPPuA05PenZeIjqoPuZ/sfpw/yrJuOtAhhh2B+4otZO267gwV6rpvkDkyqNQHvYQc=,iv:/aaZOA1wYkfiiNpooy93QoWEJ8S8egre/9mNh+DT25k=,tag:20TF2Ucba31+QnHR4h2FvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
