# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:f13owq+GG7Zr8Af4Cw==,iv:+3x+RocuOCBvIaNYTqEcLfyyIbnaVl+tqK37GK3bYsA=,tag:FnFiLMiBoozWI+vzJbsrEg==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:v5Qcn8Gk,iv:g9P4TTes2YRQLKIchBjttCeJ1zufLoZbNDBqnvv0WR4=,tag:uNzhbZ/Ko72iTtSWlRFVgQ==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:BgptV98sJa8hiBgwKgYa6CDG+H83QiOijquj,iv:SCLhhwvQMnqN3e71fPMhGprsCxAJK9PHDSOU9QqcnlU=,tag:RxcPQZyTBfh0uIAPeMtEjA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:V2uWCFzEQkYx,iv:CcooUMvRVoyf9ga847snQGmZd/0YMyK1vTLrivOo2DQ=,tag:PNm1AI/XPQ97ASSV32h2Lw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:IdN6GtuF2UQRpIvl2qz+SfEUKXvnnOZWVsixFTl704FwINj/DzTfcUlc8Qk=,iv:4K0Ofa8iFxtXTAhHYY34zE6C98EIkeVPMpeVLjkLsRE=,tag:Fcb+HsBSFAF68xS4PMyy9g==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:P8O/jWwJB08=,iv:Ugg73r54zE8fYUNXddGtIl4hx0DKDIUe+LlhiA/C7ig=,tag:Z91GSvIWHixC+M7SS1yYNg==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:wndJHTMF+0U=,iv:RhnqHaB+FdzEORAaesMsP+L+Qdrvw1CrAbtmg04W4ig=,tag:WdSPlIN3YEq1FkuE3njkUg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:mQDJot1zKWGW0rWPlow=,iv:++9tHs2BARPWRDlEZ+S77NV4F1vglz1AesQAtw8IWXo=,tag:/EnAn/QOhMyRsIdw8/VUyQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:QAFgZ+YKKrjh,iv:F47LHjwp0HqDhTDa6LWORs5GwEAuAezpM5nA9Hb1JXI=,tag:w053NqMWpQMGp8ScFaWBQw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:0huCpx8rhGpDGk0CFmL/2SQ+7A==,iv:YGmouGfZDEyOEIw52ntVIlMmpy54iiAaoedhUIssRyc=,tag:fDvaGOTioLyflsLu46d4/A==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:c/+JGFyGlR+7872T5pmnjQ==,iv:s/rh5VIDMnazfPfEmNobEsUvOmi42JdP+dFTa6DQJxA=,tag:lJyGgYB/lfjmcqVbjFWYhw==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:FGeCQwL8J/UC,iv:1brP+ozwsf97PxLTBLWtM25Oiwad7FBLR/1lM1N+yjU=,tag:/VBDQlxJki5CUiLtVODZJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeXVQRmhXQm9KVWhYZU1Q
        Y25XT2hSdXo4SVV2NnNuV3VkYWZOdWVHeWdRClpjdzRXRm1EZDhYVjFmcUJmOUdR
        L2NRN1ZsdmFESWROakJKN3FocXprRTQKLS0tIDR4KzJXVVlFR1U1UERLWkVVb2ZQ
        SFJBQ3hhalQybjFDZW40QTYwVXFTYVEK2D5fLP2Ln3Q71QGIH8Lsd3KTzMQlN0iT
        1/9ABSr6rkBXjBdKeQ93s/PrxKXajsyugqycFktMaroYaf25kJU6uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:BcJmowjMQz0guyRgJWU01XZfmZ7S98Z52eSISgfuI4VOPhrDmc1VRL+eOOMQRGajd4UIlzo/uKubB3Xmuj9MmqiKB+3l5uyBc+DImQakd7XvLXsBj8kGqT0bomSHQmXH0wtjpTz55ctMKFbhja/hqiNzOa3+InAQg8wOGGV2+RY=,iv:92W4+i3F7rvWgK7MBjpbtKx63dIRblk/Qn+WmiMMq04=,tag:8E8yBnDaLlWf7+0/7FAWtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
