# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:RC1o13oyQ8p0JddT/A==,iv:d5SKSn9lWscF0Dq9lVbtsEyX85djCQ4vXNqBlylaOa8=,tag:DKXeHbtr6TIzfmMFqiSPew==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:1BSu++8K,iv:TovXLcyg3po6ObzEL1YkgLr/BYmDqHSuTnhdmOJjKSk=,tag:sGWCkmz9ba4Dq2Qz3Shmmg==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:xFpJEWuUOxmLKdT73ScyGadQ9QG9mrKYKcid,iv:zDckbElnAmUqENqxYZmuv4I8GhpLJL1Y0OJScF80G0o=,tag:DA7BcPW3pemo+WVSOt6OQQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:nUNw2X4k/nej,iv:hyJVxrVevdNM7BJhx7YwTMtY9NhbjZP741DvCE6S3dc=,tag:VqZUwH1/xYFq+6OLlCL2Sg==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:S+xhgMDzcJK2Rk201BV7FXpRKGpEdfUY3x/DGCtDGaBeZ7l6zdz98NIaKTY=,iv:0FmdErggMZVZa5Se6MVyffc/E+u5RT00NouNqiznXhk=,tag:EL/69tv7bCrCOq9arHCL+Q==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:WWbyPwW88kE=,iv:9qx2WJ2YcI+5Hw/UKF9ED9GRg0kvRmP5BZrI1h3q6BQ=,tag:l9FLvTc44FZzPHJKhedFkQ==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:mPT6KqwENK0=,iv:UNJJ+AnEAVycYANehrxVioBIGRC2yqRrvLaSuJoXNRw=,tag:l0ms8EGeMmwueQS7+U7luA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:Mb+G+Coj5fXcTYsizwA=,iv:7pBwlw7Q1zwKjq13xkzdFM5370alpoQ/Tx0asZU02Wc=,tag:FyYen6I011Is2hzvUXuBIg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:2U4vUiD0qRJx,iv:7Jlj/jhqNiqVtcItxZ5pTLPR6O+2/9aBYUxZAvn4i1M=,tag:xPQ+G3r1FzFAjAklBDzf3A==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:AR0JHfsNVHQxri+qfPsDyHTTcw==,iv:YfSyVvw2qBpbBTvMvTE9Nb0JXJPJ7DHsC5S+CcUmP5s=,tag:+J4CfAD/KV96JCK7lkRRFg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:rU/gYV8MolBjAXoll/HfQA==,iv:xQvRNaS4RY1d+575xVUARoByGrK92ecNEDHuwAEDc5A=,tag:AOUrjxPfhKcHqUVvYU/KDA==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:vO1mpH9ckNwX,iv:492wLJxfZNHUN9y2KsTfNctmQ9RrzlgnFGNnk1juJ4s=,tag:PNmDxPKs+duRT4gKnqbj0w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNmtueTJ3V043a3Z2TXJw
        TTVVWVhFZ21BN05maC9teGtzYmpRbFQwRkdvCm1WNUw1UUxUbWpEUVBlOXU3RWpu
        K2wwNWhrRHFLUjBzbnB5dVhobVhEMFUKLS0tIE5sSmE1Qi9LcWp0R0ltc0JDdE9K
        c3pkei9lY2xuc05xTW1YRHFtNWV4RHcK8FPQ92XOerC2XYYr3oeOwLb7jfzuR8cB
        F8vgxPEz85evTrF3F6u1rjxWKFYbYEpIrMxEUXNAahA6Nq8XWkO45g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:Ft8eCaxHUPP7r59qdT5AOcGO3HaI42+TzE0GmShafy8f7MSfWGklCZcbKs9iNutd7lKZrqdmOml3lph5q8oiyXUGB84rpBWB+8LIkt+7Me9wcqze0KIFA0zFZhqGKDUYDs09M07g4J+URY2ikHPNtC0+uuaZXUiLQFRtBi+ziuI=,iv:2XRPe+EbAi+aey9BF5IIMs112ofcv6lI3ryltmeuhek=,tag:fMgcxDOE/3+6M4hULwGToQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
