# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:ZljpDu++FRvFmDAiWA==,iv:mQ+RZTlHa+WY/2AoGf9hUD8LObH6O011Ok6GLIWbI3U=,tag:vxr/MUOmutDfXnI+qESe3g==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:lcqxNpCl,iv:92eR3Yk2oQJejtNEsOnXQEzqWrFvlE+3UPjhCYNhTo0=,tag:3GFkdq0/wxQysxgKbgDWCw==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:aIYTKPDVp0qObaz7aubVnqoSrRV5VdLi2bg3,iv:bqa4bW9gd4t6iBtBtZzdFB7qR4w7LHb3bKMJJ0pJOSQ=,tag:zYXd37X62yee4S7R9lCgFA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:pVDjUJpcNSxM,iv:OGXNu3TFHQ/hoWVdCVwW/bDg6zcIvbmq5dRaokx9zYE=,tag:a3GhiSphrYdF3022CAEuiQ==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:4HhXoEcAjc+mWAKucAKt1hLJqp876vvNd2niZ+9TCEMpCU0fBJQvgMkXMzo=,iv:RrwIkFG6oShuIH7GC68CnBMY7llLeYPlpyWNACZEccU=,tag:IMfGZ3jabDUuCp968EVaNg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:KoplNgxx8QQ=,iv:OCYo/ZQFLhTW+6BENORRzkRArqq2XKvkGglr1N20yfk=,tag:d3ri5FsaNrQQI2M2TMDv0Q==,type:str]
  POSTGRES_PASS: ENC[AES256_GCM,data:Zto2pFfUCI8=,iv:FEa94EdQ9Z1pjkoqRKzA5CNoeOTDBfrake1XrnZojfI=,tag:Mw+3NClIZf+v5A7dap1ZKQ==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:oRgBjPD91VQRKIcL95M=,iv:a2kpdGJTgEoyUPN4LU57CiyreXl/+Ywbf8YHWB2CJzQ=,tag:8e/8CIlO317WiZHvDXgBbw==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:YRrggp0u7WUa,iv:YpFqgdpxV7DJBwvUMZ7vzfytu2f2hJ3dPDSYRJcbKMY=,tag:y2fG6fKbQCV45Wo6afF4+g==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:vBqIezZ2SPA+ApWPMUvnOeOEuA==,iv:2nJwTaV2J+9mVMw1SW9/vpmUEWtEsr/LL2VAFhaC0WA=,tag:rkoFnaNAR5H+LBe38jlRxg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:t7Sf/jv+fEeG8b0K785XSg==,iv:BSLoteeVmYjxWfzHp+57dd/a6xr96HDBwSmUQFK0B44=,tag:bmCQpC36msoqDbqkGi5naw==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:2mQ9YtGsrAhq,iv:Ury6hhWrNhFRBWMpL8nSYgChpa1eOW5B99MXM+XeGUo=,tag:KqLZZ2nU/Qigt4guz3HqNA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUDQ2WWhSOHA0bzRONnZU
        cDljM3FjalZ0dzM2OTExYWMwR0g4d2kydWkwCktoYms3enIzME0zV0JtZDFqUTkz
        bEtwWUJtY1lBMzZSTHl4bS9RQlBzQ3cKLS0tIGJST0EzZytjUHEweXYrSlAvMDA0
        MUU4SkdFV0gzQmlKWWFQTkJvT0EzdkEKUbQ8Bz9ldH9WBMEFwDj6EqKA3iFLn3Zb
        xbt0E/6yh+aTBtdX4OhMMUIH9L7vFB9NTr7sDkcitcBMK0a6Y1yxPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:lK7OkrZK0enZICyo5LxMo8DJbucZDcwj0Y+yqgr/iQVra0YM/9GxsetzpxCE1T8Xpru8WdXvn/jQ0XwaeGqNZiQpPuNHy4GyBLgzki/Z/Wt1xpI/aXxaoEQ2mSPPzJ1x97xz7PRS2y7DVSDaDSsZUZ4zLDcV4+pC5OtzfVlL5Lw=,iv:u9ttgcy3pszMWUQSqEt3noUHg7JklfXgmBklBk42fqM=,tag:N6DnqIW08MfxFTDmGwRMMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
