# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:xZc+wtw=,iv:XZdlBJihvRAqEVMWIRb92A+coOXyF2DQDp7FSNV/riA=,tag:ru5YHPX6uVFq+bRPiUfHCw==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:XR1IvJ7JRYSxBUB5nDvtlwDuTgXiCHzARaq2,iv:FBAnc0UBDU2lmr1k7+VJtesEAzMzNOfADPS8KeiTk0M=,tag:RZAf9mqYgC+Wi1TPoZd0mA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:3Q+151T1egxs,iv:uo0dNA3X9t4whXAcjdKbiDXnG3pzg4GQa9AT1W5VUrM=,tag:Yxn/Cb9mPuroctuPq02+wA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AVodF+27qhr1ft/AZBNdkv2aLDGs5bK2UVxy8YTigpcCYdV1P+IQxYrbv+a3gEEDNffgoYyaaA==,iv:qc5KQ6ka2LtWVAExh3iTLDcDV1Vtsi1C09Hjobo2i4s=,tag:BT6x3XIKBkfFaM+3BriqnA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Q+lvRxpLj3U=,iv:Etzvajbn99Tu8U3JkSla7Rhae6Kkr25atNOrsfl17es=,tag:G0uzdHkX1o4tQ/q/sBZIFw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dBCOoyKL94U=,iv:xNkhPYOPZjLiBOP00EzKaFxwuC57NorUHz5hNRcoV60=,tag:XAfjSmERLdNAaRV/2kdqpg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:EkOBcUghafs=,iv:QGAIpT+jkpZQZTnajfSwljOtVVrKf+zVytFvzVD2GoQ=,tag:3a6jTyOn71zSpi17Gba52g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:stSQwqc70xk=,iv:IixwWqX22PkXpXyYf28fB2sCbib+ib7tWppG6IFjx40=,tag:qDIramU8sdQjvYy6nTwqDw==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:vzP/ZsxKgtmIlbJTlWc=,iv:DAUfW3xHpjdVUgzJOHKQme18XABUz1/pxXzfrhKgjpg=,tag:WXlb3su5szCUJ31yWzcHhA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:Hs3DRtXqe+3axVfiny1308VeUQ==,iv:ITAQslMm5zqt4b4r8Q1MlO2eHrcLejS4hu3WmDX5IaY=,tag:7pjc3UUaOD47TD8TA3qRSw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:hAjquWQjgRv1hpJAJZPJAXLPtQ==,iv:AimUprEpBzV24GkR+NZccRjdztKp1K7mfh129BW30oE=,tag:ocw59LCAb7IPKE47Jrqg2w==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:3ty8r1pc9hMJIrkbI7rtHg==,iv:hmYT+K1/KoHpLlHTdeuo1iaVDiY0yJi3oi+6JOXFIuk=,tag:iI3NLuNHNL9W5ek90Sge5A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTjdReXpjNnNNdzU1RHZj
        RTdnTHl1aWw3amhjWXgzNHFoNldIK1N4d2tZCm5mVFBBWXpEajUzSjFJaEE5R3Fl
        Q25HUFJrdFc0bGFCN2JlWkNZSENYMGcKLS0tIEY2ZWpBUkVKYll1U1VSN3RscWtE
        MENpdCszbENHaGdEN3QxUXdDb2ZWTjQKyRhlmEq7bn1uxRSy5ERwzaqxKx/EYx9X
        LmH1iFvGLNaJevngATupL1lWEQ8pAipOYPNWrS1NkIfO0ZdCayJawA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:nbww4LegGC2EThZeSa23T8QcRyevEt3VLntIKCLDUNU5VlpnMfgGCeAacnY5XjH0ZJ5aSL4VhgvO2QUpQFySQ92JuP1t9b1vvss5tQu45031PaGPi341spcngexG3PsThWk0aaLlGjyR4PFyYPEPmZ4zWN+xucrnopCyl7088wM=,iv:5WMTFXGzNE9ZY6uO1QG7/dFM0ZtLH8pRCLH2Y5JG69c=,tag:XehQOvdmYMBfT0ZXoPI1+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
