# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:TvfpzAs=,iv:eq3pJURR9d2Z+TcUDyJdevwB+SnQ/75nIDU5DCiGqu0=,tag:I6iYSQ3wcncZQRIkrOBPpQ==,type:str]
  NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:42mdwbJFU+4MD3OWOSUtGCTFxxMOyOCQlQS+,iv:HvVh7EwFc0O+q70lgvo/DgptQ6uuraMD9TE3MYkB9xk=,tag:tqCPZUaRanmBBxj7kjIBpg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:IxidQOmwKbbl,iv:nFCzHrXe2dTYAO3M2WI8cjgGMd+k8OcHd3+ifYS6lsk=,tag:+E5mExsz5e5FBQMtmFRsrA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:hT1l1CfAZfe4HBJLilKm1VJP410Dt8+JXqUmaXFgGXi679uToJziU1V7DxA9PuP8skcZoO5Wfg==,iv:zOGFQFhLOx8LyOFhTnkBIiMhhp+AdtoS2LGihaGyLzY=,tag:DPJhxpKRWHNP8HuksaxWGg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Ziu0vMfyjH0=,iv:Keg8v3D0CTuilablb8IH60NcV9tzH/VnZMTdDprlbiY=,tag:5btrLfnb67toQWaYcHVCFA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yZsKjfcpI2k=,iv:TCPYbkC35JHZyqzbsdyXEJzA805DXU8kEuPPcO2C8oY=,tag:mQZBjiRb68Q/zwKMkH+Z9g==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:TXAlBSggHbQ=,iv:f/TFdUJ0/YiwOoEGQObuLruv3OtSBLEvztN0UzVE+iE=,tag:bwYRwDAxdE4iIwwfVboftw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:k0mxYAoIekU=,iv:Cu+qJNXux6trWhJ04FevsR9RQHEjn9gLIfnFXBZKfKA=,tag:HTrohFO2BLFEpoTDyB0PfA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:e1+iuGaslc+GsHx1zK4=,iv:rhl25rp01P2E1gMzr9po+gFLR+ELzPg9oqWfFcSCjoA=,tag:q91cGgQ2QA/fHFt/defHYg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:CD98QhWDTilSh/tGjxvBJjPUEg==,iv:rJQYQjjKMJFx0bHqAR93P679y1PJtuIYiAz4QyMB2K8=,tag:C+HjAyQt7apD0jKfslyT8g==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:kxOhf4L3cNQePE0OTze8CWkAYg==,iv:2KPIamewBlSE1jir6PdOcASr2UPUl/GzflRYpyhyE7U=,tag:QlhmKI79X1O3R768Y//jEg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:1kIL/b37U3LYuMFaDp25Ew==,iv:TTZoyPjNsXqCTDcSqHbVuPaMYFQju8/wWl/0NrNCZ4g=,tag:6yYtWcnnchV0bynk0vpygA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVkZtQjVzZTVaK0tMOGU0
        UWw4dEJrTGljUE9UVXhvWXhxRS9WM3ArQjBNCmd4ODBhazZydm5vci9iNEJZSGlZ
        S2xjVW9hakkvc0dDcDBRTzN2UDNMWmcKLS0tIE5TNi9qL25mVVExbm9rWEJRdmNw
        aGk1Wk8zcE8zNXJHQkc0SytNd05URHcKhxaiwoEWHoMIsJ/Cm/5fzt+IZRGhzMKd
        CAxsXFttJKIXBu2MmyjZEpL8Pk10M5BkS8+UVdTS72mULkvUPEXSNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:/y7+ob1NAK5J/TeiDrud1X4dybKAtcqsw4/CfCoopFO8snyLsgV6yt7LFCWZPiuH97dbEUeEKxMeLq/bqUcd5cLasaKTWWNlAcqii2mOJvyiL0nsFwSBVlCyY7FVyzIpvI8sRgtZBfC0VF3BS5Pg1RUY+zel/mIpUPZcKYVRsEA=,iv:FGZf0eeScMqQCsAFjtF2sBPQrc/UGgxRpOD7B7i/mMk=,tag:GQbXwKoI/wzTfAnd7D8fYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
