apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nMd8Vb+ndes8uuwCA3J11rTybpnNLsd7S8nAQ+uhKnDpjsu+4pxS5g==,iv:rP8G4cuSVZsnpgCvwb/YSD7OkS/gTDT5qrDjpxwqLuo=,tag:1dyMtazP/EEVvqF7UDc08Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWWV4WWRXUWxzVWc4MjN0
        cURqekxodVJyeHBSMEw4UnlrYkREL0RPNzN3ClgwRHpTWEFxaTNwU2UyaU5laHpu
        SmNXMllqR1RIYjhSNzg4eXdhdVhWQVUKLS0tIENqWllQU2pSbktmbXp5bjJEMnZ6
        TWpwTlFCME94LzYyQit1Z2crZDlQbjgKnuaXbEKGElSsVIeku83AfRd4N+8KWRez
        W6TZkgYX7sFE9Tw7bGWjwtpcq4nZfK525oSL8YkXdr6RXnEylzPfDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:nEv5pOcB0iluD8tP+TI06mQgOa35Jf8xgtHhJDXHxkpSSnJyahL+645j0hy/GvzfmTaTIFpQYkQEyJCZN6ckQMjA0fMWFwOsPo70jDxj0y4nTyEtM19w8+Mtix97gAlT+oKwvRw+orReDce4XMD/w4L2gxhKFCpOd3t6pexcQvk=,iv:xsH7V5DSrw1SebgHn44m9W1PnV6Kl4c2wbVfVgb4kQQ=,tag:xEAzf3VTn6udkpAkQ8fLKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
