apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Juhg6/LHegmzx8S7bbVi8LfnhjjEKiOIxZNPYHMdz6yrjgcOxuc87Q==,iv:d+U0COnRWJukNi/Xju3MUv4M1rwiRiprAhoEfejMyZY=,tag:CT7EOHPdhMoe+Lr1BPuvYw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dXBKMXJjaGFqdW5ESGJ4
        ZXI0SFJuMGtTU2ExM3J1TGF3dEdoVitUWlNNCnRrUVpKQ2cwZ3RPZGR6aEdZd1dD
        RmdsRWcvKzloK01QRmd5WThIM3cxVzQKLS0tIElvRmowakFZRXRJRy9uM3YyeWd2
        R0gyTjdBTWdJS0NDOFhEMmVVVENTN2cKv8QZXjIgJTv/E2sTqNaRl11RjAhc3UV3
        4qXCnoWkLiVX8PUEG34t9FpvQBOEKIVMqExCDGP27wzFpip+NzxZpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:SOAXaHANx+SrJooHBiQyXNoputdmvRgHMGc14OU52wBMCvOfjuLDYC/mASp0TtfD5GzJY5/vWbIpq+cFK9PZjaACEzCZfnrn9bDdsENChzuVE01Jf4YgSDSZt+9jOGpFo04yuWPgAtcNE2FrIQYZ8SPFzGEv6S+d+3oR6m0i5Zo=,iv:qFVXcAwjXTgJ4o4Ub7A1GmksueFU+GhGn5RUWtrVLIg=,tag:vAQoPS94/28vkjbvdE2Q2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
