apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:YJ3MSz4dR5qRa49fyGJ6uLmpe2II7RVNrHi5brDi/7E+N0v3o9lfOQ==,iv:O7G32s8pG0fQPFUn/L+QVSYwWSBZrh9zd5gJA0iYVGU=,tag:BuBeMEGwuvVMPZYaeL4WMg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXpwKzhuak9qQkNWWmhv
        YVdQSGowdmFFM2NiMFdmNVdYZStLMktRVjE4CllwcFEvRmxwZkQybkNlbVJQcjlw
        K0lBT2haMDVpOVlNMmliZ1huRnNMbkkKLS0tIE5jNnlZUGRCaU9qT01jeS9ZVnE3
        cXExYlJPYXgzTE9HMWsvcW5KNjdBWGsKnvBSIplyKtbvwFDOm0ZPatyIR74OnZGi
        zuxyYMIp1XMPoAMsin3Zf72/mc0LwgxkmIcWXdmt3ICyGdVg2kBSKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:46Z"
  mac: ENC[AES256_GCM,data:GV3f1jEm55MoCrG7mx0LBCZhoeVzQ3I7Y+70ovM9x286yU/uf9fsBNYlvmCKEYWTWW2VggixRZ5WDEZxNS+B9fEzTDY0KKZ+9HtkU6tP2BBU5Sg3MuN3NbvgHEBJXfYlUqFWVwstDaykr1DZXQeLAku9z4YA6+TGdVyraCVo7ww=,iv:G8UIkG8kqiyK/I28/VDvcLTk0L3uT4BwDSNhUMQ+vGk=,tag:d3CY0PUk++kSsssoC9Gy3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
