apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:R3EeGp0PvbBp9/lXmQAUpKZfxmCz+qEktoF9fWrDIMo4SaqB415LTQ==,iv:5oZznYYyFil55cbGNoFFQv/EGGU1VGvyRsqhieorrRE=,tag:oKpzDnGUplw7s1OOZrqDOg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWU2YmovRFBwQXRBYkJC
        MUU3bldVSFhOZTlXZnl1dHB0ZjBrZ3pSRmtVCmlxRG5zekszMDZRZnlTM2Z5ODUx
        c3Y2NTVsVkFKM29yQXgrRlU0MDJ1NlUKLS0tIEFiT1dpak1IQzkxMHRsaXY2bit5
        NE1kcmdKdFdyazBJNHhEbGdGYVBONXcKLcvixvK9YaxCeTtSpe8AfJqJX+62a9fT
        DJLXD0oJOq3jAJAIhBXoNZoUkY2INhjHBbR6IiQa4ulnVRscPY7E5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:xgDLKP2wjHG9xVq5R2xJc1exN6YPFnUU6YzrVWqSVXE2Nchq9UxlgDS2dGw83KXe2j4MOZ1xzjsQXxly3YwMz6p4rL5Bkj1ZRFz+MbWINw64WfA/WWSUDz7pR0iIyjDGFpq8gL6RxP+IGD/hc7eMzNanSY2vcCsYR12x9U/NTQY=,iv:lPgDuV8yamHnyMDt3Jx7ed/ALuQZJJxFJIIC131C0+o=,tag:aE/X89VA1ITwfxDijunq9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
