apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PhEeDiRjeZ/lgiEhLpHLaVAAAgXKOxcC8U0NKFnMxvAP1wX7z1lvTA==,iv:iuSR8/6FSEHABJq+EiY1Y9IB7ux2lup86BmYJLRZkqw=,tag:fD+i6Ej2El9enKhxEspUOA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZVdvbXR3VURtejdGaTRS
        NGdtUXRhUy9abUM5cWpCelM5K1JuSFU1L0dVCnd6eDkvOWFPbTQ5SVpHNnFWd1ZS
        dWk2RWo2aW44Rmp6RU95eEhxb0hqUkkKLS0tIHY2RVArQUVwUUpoUEl1dzYyNWR6
        UGdLQnBUTFFpN2pRSGpWbnlWUUhzMWsKDcciFGOdSwEgon+Ju/99M8tws2lm6gLq
        RN/Wued0zYIGe8c/QPYVoDfEZqu8amBTERFtT2SbcjlqEgNx11ffxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:VDZTJ13f1UoKxqnQfVe/3COKSQIYuF1n1u/zAkcV1qYfugetoRRP5rryPWhPM1z87Y7Dl+OUTqqxqtF1g8lMpr0UcwgWddX8DjAuh9XwYt51ddplFrA2OuCTbHa2OMKlI5sDdKK7Nyq+cYirzvX/gIH01wb01mJG9z8DCpCfZpk=,iv:h2HaOG6IHcfJLb239uruuSiJ0jU3/LAk2lpfk82SLCM=,tag:qitN+5mEVslSPAPe7iA31g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
