apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:S3ygho2vZZG16wakeFK98CK0XHt8gMhHmFpX+GHsV+E69vwC+HFWvw==,iv:th5u7gXcSzur9u3+OXDT2TcQpFwcFiDNSBOR172QEIY=,tag:MARTf1WRP5RpzyWdWM/ZiA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QlNqU0VienNJUHF1TCtR
        WnZENjUzTktEYVcvUnBxeE14L0FISEcwZGw4ClNxVDE2NUx0YlpHeWpUR2syVCtL
        cERHbXVvbUl5WS9MUlpvV1ZvUDI0QVUKLS0tIGlFc1VhT2RBN0kxd29OZHZsekFp
        NG1ESDZuWjIvQW5zNDNkcVlIUHRCL28KVLgHAJrRiJEecp6K7+HTIher5nuCcdg2
        EmvGT+gYBJ60ALn4g4Az24CnVc8nbnQPnw+FlyIt3zqj/0qbq6NovQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:/cv41XIWOsLCe+7ofDHpxJURaaLDRl84x4/AZS3IxKzovs859P8VKi0sa1KSdy8tLG5emcgc40BQDRBTgmMe1RESRwUfSzerhye6ADwvLxeem6gbgnLT6rqm8spoZL/hKVDhYP8twrAl15+64TqCrWQtPStBGhQh1CnwZrMtaMo=,iv:mxf9mTme7eFSsvYje7MaicGD/AJ8zLWwcCujhdQDm0c=,tag:RzwdfqoiIbMLe454UXfKQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
