apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fkfNpNGwhkE7atVZ6FVIZH8DXkW0ByL1aQpLJgsWI5GGXiFWEUnGsA==,iv:hrMMfwNW5jr05ya2mrjloRH9GSHhDpSwoJl3yZKfhlY=,tag:BzzAeVyv8Bo3lnW713UqCA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVDdkWndEREVFNExpMG05
        cm94OTRRWTJjMzZxTHd6clByaWs1S2ZTN21zCnlHdG1sU1psTDh6NW1sMnBkYXVL
        VVI3VzZvODdWUjAxSjlpQjJLU2VDT0UKLS0tIFhpeUNaOXZzQWpJd0R1K0F1YmFv
        ZUxoTEV4aXcrZ2R1aVE5Unp2S21kTVUK/7Hn5cncBLytVPPigkB1g1DZHI9XfPmj
        g4jTOwnBM7hfCESJlAk8WydAbo0w43Pck9NBsLQeNYy0/yQ+lbfLlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:FrNnqJ5YOD9tM2Q0jFRkPWGUJTtL6AC3dYObg3H7zdgvLoNGoL4TNIF/ze9LT2B+3rwiHoALLeZFQi+6nDJaT4DYC6lr4D3wmXonRIRRTgJfiVGLJa9YT7Mu+9Qmzty0dffuWPWAWBVsSjZmzTUtkF5eGvyIKhYkYce0iUQi5/w=,iv:rtUXrhshXieVg5KdugVp5hGP4k9CYWywCt/wDC6OAt0=,tag:TN3fN9YJwnxyjqPvf78UvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
