apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KzLfrexBLx2tTncIBOQqi1PwfLLloXLAcnZEsJtxSMHZ/HYihaBwTg==,iv:bSNeh0cI7aQiipBtd50h9R7yc9BIcwv8fcd8+uA0j04=,tag:ZXcM7RJqOSG28BRPPMv3Yg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYkEzQkpZbmJRK3lmZ1Zk
        QkFYZzU5ODNuNHdIa1Rya0MyRTVhd3pTUkV3ClMwYktacGFvT29aZ2UvSzh3cjY5
        dlFrOUZQZVU4Zzl5NnpCb1hLTmgrNW8KLS0tIEVDOWNaMU01WFFtbHpvS1gwcFBt
        QWxqQW5oMVNjaGRFTm9ZVGVVVTVSQWcK42pLnuEvRBIDfP6912HYOMrZ7pxx7qTR
        keKswKY4BUTVU44GRB9x7DllV8grwcNRZZMxi9rlbXiDX/BHhrvD1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:kA+38SBGbKJ/nKcFxtMZBSxZN0D3luGgY4kmbCEfgXJr6WqOhj/RdEOQLLhuC/6bWYJSGKGVAsPU6e2abDonIstlBEgcGs/RnxxLPcITg5ZR53PZ/KDatiE8PBEjQkpIeKgAEeXN0tOU5T1AFAmPKJNBns7ImOPwtL+tOYsHiuU=,iv:RT2H/LLm8PMnxBen7GTfrBNGy+KDsilzKnqF+CujeP0=,tag:77v2ggYMzaOkzLm3Pe3udA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
