apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ttb6bClHk4GUlyIAgb9+8gWUpK+ay5Gy3vP9ivE1k/K7zdZixv0t8Q==,iv:OHTW6QNL4sSrRkAP1tEkaYJNQHFlAF9L2nFH5gkC+7c=,tag:LDY+MAm/uAahEMvuBeZ+Fw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2RxRUEzb2h6dVk0cmE1
        dWxaWDROQnVROTB5NGdURkxoM2lURm41V0ZFCnNkdFZzNjFMRy9WUmRUY25YRFow
        ZjQyWWVFMDJtUDhGdEZ1Mkd4bHNaRTQKLS0tIGZ6VHY1MHZOU2VRWkdwdmdsOEwy
        YWt4SWc5bzhOSjlTbjNub21HNGpUNUkK81yyaZU+vRABXgLwlLcoGncMZ0SSRbMG
        pfRLQ366g1TAN5WiuUbZuQkJqsnLKtOqlqDVPIs7Dsk3FgDN4Nfa7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:rAno2YETpAwL8CBjOsjZFJPILW0WBEbXlxpjTfJ0ooXZV+scBI2Uob0HrBYUAzchw8VTMbZD+b+ErM7iIBrNoay/MgLNOKlfgvhUUsfp+BQQVV3QbrXJaMkSsQ6RuzFvBBa6Y5d/zAcRhMSl7E8KDcu0laRvk0pr8Bn8E7U94Xw=,iv:GJ08G+0FhynSgb9QTZLU9qbDeY4/TyGFrr+BnUC/hUs=,tag:m12d+wp7mahnRBSO5gA+hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
