apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:hktNBpAARh8r1EF+y6L9NQCRtL5taDtc1hB95j5XitBJoKLdQnky1g==,iv:7i1Pw4hX9XlF6OGR9I903/MSznNc774mVQs355sVFMw=,tag:/oUMr/lRj9c1yalzahgMOA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN2JJZHZtS0FRWktsd3pL
        TVNjdnpJdUtaV3VwVktDT3ZLZnpCMjFNVHhnCnV4enBPQTdRcW5EeWVXalF5ZERL
        UWwxdWNNQXUrVlByVjZ0cldwaVlkRUkKLS0tIE9LNklIT3VwcjBNS29LcDlYVHhI
        MVN4SGRDbDd5UXNUR0UxMjBBL2FHSncK7IMcmSKRvRVPCMBATNCZSd+Odjdxbkwa
        RjRvtP+/sZEB6/CNMizHAIInM/iO+pjQsNpdN2f5MYJ2DpTE3zGFsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:dlPA2j3RR41oQ/KQ9L4RWwFJjjeBF2Z2dNmOpVqN2I+4bFMFtZc5ceWvXpeEKkWFt1laTIMhee+6WJ1+k0+/XZlznfZuAz63ZGHlWdlmq5aBGxdXjSOcuvIsuUmY6jr7/tayGe/do31q6aRXjiCJsAzi3dmOLZa4otXq8be8xyo=,iv:CSSSA/wyoaud0l3cIHWfpkEHLEJw4FP6A38HruU16z8=,tag:SWggoSnlRoLQFyT64Cni0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
