apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BRnqD8C6yucouLpK5SiD+0lTh3ZNd3B/XgafdipxJ5eHR80ZSyCj8g==,iv:7H5aQuindxe/RAlofcYJ2+nP+3Z9P55BqL1H9wUKkes=,tag:0M5jOwdbJ3N0HMAyLZ7T4Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSEQwTUZTdHZJM3dkanQ3
        OXNZa2RzSzk3WnpNUzRqSTIxaFhNdnJ2ZXdRCmpMa1RvelhHRE5aM2FKYmg5b3dW
        ZlFENVNOV0xMUmtuZElKNk9SV1ZyZmsKLS0tIENTSlZNbTd2dEVqNWxlZVY5cXBW
        cXZvL2NGSk9mRndJTlBtTFFkTEtyancKEA0Bm/0inFVS/3uqVMPWZxBo2s6qGvF9
        SPvK9G77xjOKoBCv2GRGlS/Ubop/jDXeMkAtJ6rM3BducX40wz8taA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:CU64Erkw2MV/KOBNOpHqivZ+1n7frYm6TrVaqpXEfxHVo63CnX8q0uSJFL21EXxOdBe/ep9TWOjqrC3gGGIY5S8Dhf96OvQkyeNtFPDZUdSrZzanWO8WYWruvz2X22+HDYNRk9rZIWuBehhikMD/jmSYENwmFIVuu3ewh5yYzuA=,iv:6XpT2S35XVye5l3lZVo4Xi1vTjkNaowI/avEbun2Xgo=,tag:H65ss95f6T+6TtYzNJkFgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
