apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KNriDc0OgK19AX941cMsfj+PddQNQdLPbyLUbCFlJt0TYcruuVkFzA==,iv:RYDIdNAa4GR8Mn7HWKZbKbcSNh+kvk3vH/ZkwQNXTo4=,tag:Opyuk57u8onV7xzYJ9aQiQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1RVKzRKbWhLVHl1NTFp
        SWhFYXVrTU1IQzIzRXdhOEpFY3RBWlZKTkFFCnJ2aHFKMGpoalo3aUN1NXA1Q1Nw
        eVNFS1kzUmRvVklBamtEQmYyVzhGTFEKLS0tIGVkSDhIWVZicUx1djhpMVhacGpQ
        a2NrMk9WMmpNMW1nSUNta1NHWERldXMKRIEjLVwdH4JaKW2TCha9fFfIX9uaulaS
        z/TrYpDxPfQf34nkizk/ZBr+g/c16NfchmWLVGTsF5/bN91OQLateA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:JFbVUt1UlUCb4f1bdX/WzsUIcsykomK05bvJjG8f331/gwnyZDrlN2W4Ebq9IQNGDC0Wv2BqWiHMFaUVbVVSdZ7ytCTd6jYRNPXtOMZfeDtj5ME2eitS6Z2pqpHhNCDx7CGkKXBGn/Bnca0DhW7vepBrBQg8F7ToL9/7lXvYuEY=,iv:kuYZOyfa+AdjH9VsvjI9DMU5EnlNgvYtgsI8KaCnl2E=,tag:IwOx/F8xkLQNpwH55JzIow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
