apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6e4iMPUmeFHEIcCD8GpMTU8srUPtpc4b3TcNwXLxsrqZpolgRq+IEg==,iv:k5/REzjVCGqxHVaSI6QsHzR1+3obk/2q84ZTbB2iUew=,tag:gxym1ef5TY3GDUJh0lhb8g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WVJRYzFiU0d6cDd2THhE
        S2ZiTU4xOHliL3FMUzVKQlJVYkRnZmo5R1VJCjhFMGFTYTNReEM0d0YxemFQMDFK
        VmVhRWViNURPNXp1NS93R2g0VXkybm8KLS0tIHNDeXJ6bzhvQ2tKY2ltVms1VW0v
        SzFYZXh0NnZpeCtQUkgvTk5nZTRwekkKvtUB2xIENTmopWvhUBQmObRfGqpoSy6U
        VzWA1Hz/NPekFnbVeImaCLX4BQNnZYx6z+zbp/x3ItTqadZKGAb9qA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:CdjKXJWGi0QjgAXWx//0PA7AOsTG+NszU71xdskGD+IkyR61slYWf+ri+x0L2liSPYkbWiPUUhVtxGTB6kSsXCk4EVjBbzRKumVmHyBCQQpEwy4CldsOk+wZFlEWuyRmHYHFCpTfii/qvV++nSLZg1IVgGUyRa+v2Hadnk+4r0s=,iv:huJdNqj7LlVs2aQ+qNJUOXC6jS3Op+/Bupu8qKRW3rQ=,tag:kYI1HiwAQjFR9dKEoCggJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
