apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:m+loGzJVpFUO44uiSp7lov9F1Im6le+qUt8HdF/kJi+rWoGX4iRESg==,iv:33+plNbzl0QeeYv3m6a4Ug1POI2tNL1zY8ud2OMWEhU=,tag:0TBQ0UyddKDnDU7P3Y+XhA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eVFjejhqYWhpWFl5VGtT
        MFJwSlBobzlFaFMvUVYyQ3BrVjU4bWttK0dzCmJaeXVnQU5RcVJmTkxwa0RMSkRV
        YThJZFd3YTQvV281cW53UVdCZXpGMncKLS0tIHd2eHExUmwwVHhJaXlaaUt3cUpC
        MnpwZnNqUjVnNG9HTEcxaVNSbGpMY1kKSTJQ45xZl+fGWgUP3dn8Tzxy6yh2PoPY
        hAXKJFG5yU4Lm16c7ScAp7wCNKf8i5n+aYac5e7zvtS6iDN38ndtTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:kmCj/qxg9BfaRd9c1dQPtUx1TsPL5zIcTTbJHW3UCQMp0JKcPf4gHAcFB2N0nbCbKl1EE6RbrX3/LG7u9BiUQwezhQU5ZbrjDExyuEWcgrODwUPPAlQodnCUKmrHjN8j6kxAFBzL7OeuJX/3qu8thtfG+5ZtNdkbBmmpuo10owo=,iv:IJbecAsPmLac2DajkJuO7ij1QEKWwelFV70Q8K/5mvY=,tag:o4eHrxhiofkPFw3OP7v1bQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
