apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZDZ0vF4d8RQWPCfr54FpNp9n9+p8xocUJeDyAmSVWkDQWUeqwNCe5w==,iv:2ja3McHUmYYsuUB9IPtQCq4gDY0CH4LnFjL2ylCmLuY=,tag:Gml2w4vNuyV4eTRC4weakg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK0lCcHZiSjh0WCtCSGtt
        Q0pPVHF6ZldLOTJKU1BhbDF3ZjdHWFJGSm1zCkxuN0NwelFpWVcvVU9aWjF5SEVD
        V01reXRSZDR1VVdrSjU5bFFQQkFBd0UKLS0tIDNLZndEMW83NnM0R1MxZmcxUGZR
        Y1F6eUkrb3dmUTN3Z0cvYzg5QnlDbjQKsMMLjNs5IwTUpQbGQ/a2pAS3TSO1xTr1
        TFmX6UV/wGTf0T+NjkcRc1UNz1QuwCv+qnN11apG0mHyEaAcitVdZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:qMYf4NPHCAligLm0MZ1EJlMWnXPQ7w4iy5ENdnjxS/oX8Psv0zDKEmFX998/lJD7pKGD9kIyp03TcrCIWunr4jOepuS63vSPleNh6EpQrN/aIz1f5IocrTGBis2gjNBmIDnRfa9iwnTgKrEXEgP4LTjjZ9KltTdgv71sRhr3Xr4=,iv:yjlp0wbwoGwUFeHfyk2ILovxScQlkCnHrWwEWLMt6fY=,tag:ItZYURNgkA37ex7llI/j9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
