apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:CovKXpC+joeyzZvz8U9hgj64CMW4Tg323dAyocX6jOfCI4DvxQJOhw==,iv:HUrw0jEsUQNe5WenqLlHxm7kxj/1rnoWblCwHNxou1k=,tag:+VB3Y5H6xqi7tjGtS5KP4A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVnpJeFBleXpXSDJuZisy
        YmhGajA3bEhyaURGNmNwNTJtbVEwQXJBTHlvCnBpN21SdXAzUjB4ZHovUzdtRHlz
        QWd6dFlDTHQ2N09vQ0d4WTlkdWdtOWsKLS0tIGU1Z0dRMkNna0hSZmZrZ1lvVGVK
        bjBwTFVXYlRKZ09Nc0JudHdWYWVoTFkKYlzB0wjCarncbI6PI7vLn2sdc4+hSNJf
        co+3T+AB3JpVz+AKsVJQAXuOglOuRFjsw7CYnUCscnVlD8S0WNevJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:mJcbDroY4TTN0+IsVYXLOPT/OgVH9QzBf3XmqE7/t1hnqSP0l4m7K9w2r1wMziFy4EVOy+6o08BkvqkxDZcKQ+aa1PjzOy5mB9ZfpnLnm9rGM3MUo0uRexUwrAiMh1lSQNKz8+5JqeQVQn3hPcq1QtwqZ3FhwdNzZ6z196hxWIk=,iv:kqIZVWxoxhyZArbm52/ZEcMa7k1rFdpist46xQZR0Ek=,tag:nju/69WJAJ3IdQnEA8bnQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
