apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:a4JDm8VSHNWIUo80fL0pJ2HQ6yVs4EpYq4yq+CtrsRE5PWR3Eroe9Q==,iv:cNwpITN96Gabu//uh6GDl/uqEkQrgDEMCV4Ue/Xswws=,tag:baTUhLoP9ZMwmYpL0HP1ug==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UVl3TUJCN21yZXQ0WlZK
        dyt1Unlrc3ZwbTdPeXB6NFQ4YzVjTEZhU1R3ClUwcW5CWG9Yc0lkWVM3OHQ5Qmpa
        UmRBQ0dmVDNBeXhjQzFxbGl5MXArbEEKLS0tIHdQbU5ON1BjQTkwMGtZVzdnSjY3
        U3N5Y205ak1ZOHJzRHdGNUhoUlFHZ3MKq8NvzFnZUM2ap9ko02fTgsl1PlUvv1FK
        FyuZhZZVP9ICQvajm1D1TcGX3wGG/4j72u4f7r8PWB2BxvE7Fkq7Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:WHLA6ow7yFE43XddQZRW+MA6AOK49KTtR6UXFTt6bFiyqPIKzEShWuVSlklT6OuL09JjAHlkhEkI1diL+IIX4HRGyms96dNjlbTUYCuNPEZz4emG+YPBDG3w3aUDG3JU64mohAgKehI3TpzztGThjFfP6Yhb2lGfCVn9a+hlYeU=,iv:m0K5UeVCgMYtwQwoYOluGcmuQ36UH94oUFuSU9u7Qkg=,tag:RiUmT8hqTOOdz8sEBC3Byw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
