apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vas975hPlpmgKR6TJCR5DjpwWz2sR2curE+BOBghhIjlKuCIJkvprg==,iv:FTOGFL/Xad0X+Gl/ftQQoNSUgmhSSgctaRWEA7VouBg=,tag:9+GGp1G6t+vwLjhHkr6mhA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUnNjOGlWbitjUmJSUEs0
        bWgySjg5Q3RGUmc3dkFoMEpWeUR4Vzhhb0FJCjREWEdyVWhqM2pmd05xQlN0Q2c3
        K3VqbVdJT3NaUlVUSm9pNkVBUXM4WkkKLS0tIGxaRnhRT2RMQng1T2N2QUdHcnkv
        SVZ2YTZZZzBNV01KMS94SkFpaFZmQzQKShGZ06kW30zGDjygqhvDHjjSdjwgN/ZS
        JVvBUkI7Hr7Ih06TX+jiEXNJQWM14jAKAfVoqwEIrvBkNtjZbJGkNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:YSCaqNwotFvEp3M+ud3XkN0ChVHSMi+uRZjWLcQtU7j6yZJraP8xNX3BQyiNSGghh1+c6Ucb+rHpT8NQxI4x/qKUhb6N0+Oq1FTZJeA1omxSI2Dl3QyWKHd8oElI/KlV2ghwTdCYrDlmMPgI01hP8Jym9h+ToRTNj20zQoiKHY8=,iv:gL/bYKvZmXkY96JJ5eg2gFLmCIwYYuMT9GWChsiXUrw=,tag:8w4nYVV9NfTjqT1B5vDkfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
