apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iMTeZ4LQna3jXG2WnY/YCwwvmsvmRJvxPNtLD+TXz+PhgR/kvi/jTg==,iv:CuAxf2rgU6uNK59huF9Th91prSn86bNKBRLuPRBkRuc=,tag:mTXAdaCbPun4eWO6NEWDqA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQndibDd6MXpIVStmN0Nv
        RE0xOEVlem5PY3dydm1jSElXSGxLZU43amx3ClNsaUxlOE00Tm5TV1lSMzNEM1oz
        MmdUSzdZblU5T0hOOEtZdTBVRTZnR1UKLS0tIC9yUEh4alg3TGg3Skk1QzVBV09C
        Nkd6NFYxK21WN2dDeDY0aHl3cS85SmcKTD4/ko47GtsXK5gxcOJatBqaLR30/Eeq
        1tneBMIDfWSR53wsxluN9Hud+xhvNlsp1keUuzeCLKPnyLzu1QBV/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:A31vwIU5PtozaDrmIvtP3gF7AJO7/OJ3wJ6g4YNt+Q13pPXEyhtcr9KlFncYSr6aDCPZL4WIgA3vLjXGg5GF+hylsszNbOMLrcbH/xYfxfudYmVShh5lbRXB8LCduHp/g8/gC8Q1dHAkhDXJH4pGR1qO+c3tQ0YLHL1LGIjav1E=,iv:zHKhlROPwQJIJ+uvvjigRbhYedYClUMwccFsKutR760=,tag:e3ApjIzyoksLvoY5YUKRUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
