apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:LOqZjRUNtlhr4pWZ0jpgdO94M1ElHYBA5H5IXgHnrxfHgPVH0dznhw==,iv:sRvuhZBWJGK/T8nsXRZJ4lVGacy5/IP6BcHqyDDJbPE=,tag:w8RXd2gRaTNIn+KkDW73Bw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bHFCa0xqUjN5OGw2UTNk
        VE9MNnl2bmtFK0Z3QkJlS0J4OE4rT3JVdkVVCncxYzlIWnFENElwZVBNSFJ0bmRZ
        UlczdnBFNXBpdWJENk5tSUs2WVppdkEKLS0tIEFnelM3RjNwckpUWGNNN3FpUHZE
        T2ZnZmJFQjZ5bFh6ZW9acUxzZlQySnMKhnUdGjKiYqtgm3BDQZn23CMKvdD0S70x
        xuABS4vNb2fb1Qh7pLDuXnNK5OrmT4MVXW7T68gGUQHFQ3ztl8Riiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:vvK0q9wJjdZ0d5DFpbgh3nkN52+G8Bhwed763rwg1zA5THJVU5NI6Eq4isZHcUecHGeZMmKuvksu1zilc7yNNut0CWQ/tQmEcFIO046prW6jMt9LiL6vFymDmtQiOm9wPwQF6/7mQr+jLVQ4Oge6wo8nAJ9qtsu1THusaMbJcck=,iv:5aQLRQztPw8EH2lwKdk/tZyhePEhK4ZetmPYe6Vvty8=,tag:CMRY8Mg+dCemR78evGzcyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
