apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+pXu3SE4OXOAN8ej76l6Xgff659SXuPvrGOZkk7pND81ENzgsHEmTA==,iv:z0HlEWXmQofEbptBlSgbgc/iX3FflZxxPPVOset1of4=,tag:8CLhxnIlRV9vN4CzK93Raw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZDVtSmNmUVJSaXlLTmMr
        Z3NKSzFJY2doc0llVzdnd2kzTUF3RytDWUZBCjVJUkd2NkhjSit3akFUVlMralgy
        SGFFbUk1MzZia3BpVzV6TnROeTRQdnMKLS0tIENrUC9RMVJrTkwwUVBybml2UWVL
        T1E4Z1ZIZ3I0aGhYbGpzTDBCd2RsUUUKjHZIBAJg82B9O+Fj3liaLrUkNiSeevIK
        mEimlfKHjz+lAEZWN3Wg2aCXAehSmRzBgoZqSXTxwHcqR4JtjgJs2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:1eMJtP1NEIy3HJPyX/5eyP/b7XBi9iXFLfY6McVbw6aGHyAhpmJbCL5AZck6fqWZoYf2UCKB0ny83nw9r/ps1A/7vhGP0mYbM3mYv4LP05pZGfGrRNxpnh+yROOuhjUMYhgKySb2+TP64zu1ebFBZ3XTzrX39k+wsu+SGevUBqI=,iv:zYj8/vKoQN7W4fuk9Wwx1sTEkshX38ItnvVU5LtDEUU=,tag:FwDFBLgJJf1s35BczPkNeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
