apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VHUsbrciiVeP52Azb6Rg6yyk0CzGPENhVJ3HImxbBlYpsGYn/3WNjw==,iv:2EWQAk/omMNEA4Q0L/BHDxsiOcNNbWcLal2Rvdqikwc=,tag:4kPqTMIv+8Hv1GHU5+1Jjg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVE9ESUZmOWdjV1RYUmVJ
        bFp0VjkwM2ZlbTJ5YWxUV1k0UURXekRFdjFJCnhHUWRFZGZ1U2Z6TzNpVU1xSjZU
        TkFXNWZod1cvdWc5SDE0djVEMFAvQjgKLS0tIDZ5WERCek5Ha0FaVFVXZmRINUxi
        YXhJcHRCUFhFL3lyR29zT3ZDNGN2bDAKcuVICjpr7qTGfMGVmd3SxxsoTUXvCFj0
        zY7KaJJWKOPRlsdwRR26Ahj8kkijx2uRJ03NNBEk+9SGPJ3MC57bHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:O4b1dv/q4rQSXsvP2dPS0awdjOhmhMhRkrMdCY1rGqmKcEotYgdnewJFYgVJUeT8/8fDw8w3FQsf7LU7tx3AnatfJKKgkpybSwDi46rNaKzphd8Xa/0hkPQDBn6h4laeNsywSnFIfGiP6rZCJgD0tK+BDr7EpQuW5OcKcLqm2Ao=,iv:UmDFWwju06PVF1mQrbwDETeQTpBlDA9rr2ix4YpTz7Q=,tag:rS1DbvLa/y4uypanTtw3ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
