# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:TaFittHC78suSN4=,iv:1lEDLBOhbRLgjvITWoFtjsba4MMJ9gnm9DEjCEHd1G0=,tag:8KhX/aT04QfEGxwk/NhMeg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:LNzmOIUYP1W3kTXQ,iv:7vwTiGrHZKLKzJwwpCeTFPE+xW0S0N99pnfh1EwDDFY=,tag:S7ssUP8GFKGgtqCjcBx5XQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:E48bXzJsbcQcj4SNCJ5vIMg+TzGdgMEO,iv:tu7WMJ7kNI364P35mgcFlrJc3U8+lKp6xzBwzAkdYwc=,tag:k5Gc/6PXfKx9m0iNHYoFBQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYkZJeHUwK1lyTWZrTHdR
        aFVleWl5eDVFRkJUc0NNaHY1L2pVZm5XQVJvCmdpVkpLQjJNZnNlZ0pRdks2Q2Zy
        MllMQTNnYU5QcFBTeDU2eGtSL3NxaVEKLS0tIFZ4WjFHNUxEMG5tOE1sR2hVUzZ2
        UVRJL0M2SDd3dzB6TXo5M2NBcEh2ZWsKO2yF4Gs8sSBE7cPAwTpoIByjMRXwoxfI
        uloVWnK4Y2cMdQarnlfeAJrsng6hfBfkqflzajUPSFiX5Eao+IJRhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:mE4ILfR/dsBqc7UnF7zxKCwijB03SDvq9CJ2tPw3hfhdlhWXTXcGix7J19rkypx4uy6jJCOOK3UwmxaDTOEpeeyxOokacJWlFPdyfPWAG3OeVzCqhLfB7aO6nu92dj3Dlsoyk3YMtfcwBC2t9FnMsU3nIrMPcVZR9fjjeYMNl74=,iv:GYFRbrwczBegWJwBontsJZcR39SLa35FaoZ10MbskVc=,tag:gl9I8a+GaefbsUIAPFQkiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
