# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:5+qu+SEMeAA8N1E=,iv:GYCH6uNZTE2/oxb2CJHsECT8VBhmhs7T6QBrwy+U8rw=,tag:LsMhQiFY6XAg3vH8TqUkqw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:9w6763YE0ijlPIt+,iv:r7UkNxHvejXefLJzSUZEWucdZ8oQTtOaNgOgwH7K4zE=,tag:YfVOa3c0x9LWsNy2Vw+IuA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:QLfSP1Lr2MsmMqyQwXiwVGGDGVXV+Rr0,iv:/+vOrvaDVPzy51MIElPEz3TNC1rZr3t2KfORiwN/f88=,tag:Y5YtO25mxnJcK8bLCcnBQw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITVhiaUtJL0UvOFRqdjlR
        OEFnUm16Y3o5b2NmL1dlbkRlM3psZHRGUUVvCjFpT1NPaEYvZERvd2dBWXlPT0RK
        bWQ3Vk5FOVo4c2Q3SE5SOHBuKytBL1EKLS0tIHRaSEtreHFlTmVOSk5jOUg1aC9L
        OFFweUpBc3owcEMvVzU0UnZBL08zWGMKoWpaa57d8NEa61yPXIDBtEvEnnXiDPKg
        zggjrAenIUCpdQzUxxEOubLYfs9YuzSyN4cY8uUq9g8y6BJsRnH3jA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:46Z"
  mac: ENC[AES256_GCM,data:yV9C/ZuDIRJNPl5KwoEAH0w2q22shO/bViBB4+JKM1zhCvzE4bCAYBTmFqR8LsnNmTJnz0Y3xnoRXk+AVTRUi4qOvJhtTACj0uNTxCcA29M5eL4uSQKEc0pBzp9ho3kf1cK/r3neQUccxVQ18CXufd3b493qVBTM4goC9FPJUFE=,iv:tSfOsSGHvBji31U8qDHdFnA2FWbBpNO8eWG6PVcIzhw=,tag:9dY//LHPQJJis9YJSC0hWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
