# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:7WC8AsNxG/MZ4dw=,iv:2U5zPaFw9B29xU3shLpMEV2QI4GPLfKYl3TR9N9eQw4=,tag:Dig66Xn0We5Njnl9x7udLA==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MCOKP68XcpGgfIwo,iv:Adf+U60im/rnarCrznRzNsa8TTEYdNjsYM819D8zBOc=,tag:vW1QWu832Hdp/fu+Ezy6dQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:u8dmTj0uhH3hj0RiaJsdE6pS5Cjmnu5y,iv:iDEJvhixNmdoejYa8z1KY7O+vGEEjA9Lv7b8AtxlFJU=,tag:9qJkcF/td+yqhqsm0Vx4yA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQzNxZjNmKy9iU2Fmcm9O
        NUxCWWl2WkNPT2h4aTA1cHhGMy92dTRYNTI0CmpxYUZxTC9Gdm1Uem80TDZLWWFp
        bVJhU3MrbCtGRC9uVSs5S1MrNjV6M2MKLS0tIDZzRFJqQk5NRXlham43VDlRT0Qy
        ZU1Fd2V1ZXpTME9BUlVrejBjZmdqeTAKvxIqTE6xfijOWZ5V/iJ72ENyqWIefyWT
        i4LqIe2UBhhAni3K2PIK80S84SGCELG2pR8b5e1oHWcs+/i4b7M/Yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:rSLem1FLRjSOJRPuAeuvqwsbVd8uPGNnTIvuT0wDRg40vBRnc7R0AqahVyabEPX7H95x/NTRcX6+/DGoRLhgL4LU91OrK6h88gSm6j1Qt9NaEyNqig4dEYj1ha0JH6blYZLQwa0eLNIz+dHv7y/ZdNUEKbsjJzNIQeCNZgWgjy8=,iv:QWsv9NTYlPEZw4vlhZJF2uAJIvcHNylokV0Cw+N2g+c=,tag:mQJkGHvyZn3Z5kIhcVawQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
