# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:PSg3JznBbkTrC2U=,iv:mB1k4P0+PDKK/PG7r525/jQiYhkwyGugjxMWd4JwQYo=,tag:yVOqpCJwm4zJbjsth30MNQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:UFcymdNIKdWUmvfR,iv:g3ei4Y8j6csNJioMGlids0irQQa7PJv6VGxGzOzet2Y=,tag:gLRL/vA5fNJnBUYnI9SYaA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:LT3dsQBVuqnn5GvRgxu/8MzXeRM5F0g6,iv:OVMIAswQdeCHokl8j8fwWflOSxBomFqH1f5DcPL+hs4=,tag:S7EdzbZO6eeESCV1d98pXQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWE42cjlrY05SUGRhTHN2
        ZVFyOHQ1ekZRWjlsMHRwakpGMEZ1OW5zRXlBCnZFY2xOTmFhaUc2cmc1ckRhSGg4
        ckFUYllBWG80bytXa3E3dFplQWhXU1UKLS0tICtxa1lxbmlvakpSYjZZU05wWkpz
        bS80aHZBMHljN1U2b1Q4Y1lFcVlENDQKzb1X+Nso3JljwT7MkWq4aPl/XVvzCCYK
        0w9fqwRbe6U3tCPYp6qgGsgKJCoo4eV0g5T5fB3ZrIUA3FaNBL6wQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:hWo/hiBGLuBkq571vgmEzRIrwWcwEyyWlHL1IVx15q+ujeaYYRN/MycPwzwXVfeJ3xlezyhlesbZjIzCSL9v1o9kFADaFzf/SqZHxggLYykxVjr1278nf89TYlA280qlTsI7Pbi/e5neoDOJYPaoQqbVy9jygNsgUc4wugsa8+M=,iv:0G6JelDYsvcxM3RtkHz0zJLyCwWBpdXxC0Kz+3DM/xI=,tag:q4l8AbT7pziN2lpTAVPCfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
