# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:YSgJliJVUoUYWGk=,iv:Dn64NbVcoGlUFWaYlLgQsgctZbXr/Q1m0QMAosjwG7k=,tag:I45tVJOmCuqjvJeKI+GNlQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:6GNQgRDfX0aDCqhK,iv:0Xs7DGbc/bpnvvPmVu5W8gJKnhvWYya32t6Elhk7Wzk=,tag:ftH6HwdP4H7Kb+n8Do4VJg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:76wPCEV5wgsaKS3vWzFAoD9hsxCD2pqF,iv:Ya0fsbeKsgvOZ7G69sIb4KuqtIhlN7IxqczBQOF179E=,tag:+cnXzc5gIfXFGEu5eubGxg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NjZmdDB2dEdpZE90WStP
        UlBKc3o5aDFFclRhQTlVTDlCK2ZpMXI0d0hzCnpZRVJRc0lVZm84V3VXNmg5V0pO
        WWN0blZFMllMb0hqd3ArdjZ4YlFCcDgKLS0tIFJnNVc5cVBWZTRUVGVkdWR0RDYz
        REcwcEgyYzB6MVg1STdRNkJZMlhPb28K4twJPEIt8083PY94G75gnp5uUUwDcp0h
        D0XWHd5ciEQ7iYHBxkweE3KQlGPjDExd9jnJC4PqfgdWep5qmo9adA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:05Z"
  mac: ENC[AES256_GCM,data:TsoJj9eD/TF/ZE60776mpvVAFIwgX+E/IiA1ncAZbSk0QHalmM2fFc8v1sj2NPzWASqnxKMsA0CQnp2UIryjWVrKdThxFJ93kU5d2EnAvk7qR+1MLsTLTXOjYkgeEL6Buo1R1kACBc4uRWSTxHGUh/5MpaulvQ9dIlpecyMd68M=,iv:VWE6YaVgrSZA1/iJt3pkwLW1CydQMysxwrBvxFxjeyQ=,tag:UaJhgRKjFOpWvnDA94qzKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
