# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:mySAVh0dCBAp8yg=,iv:jzsP//dpcv9g3qXgSXk8MkOJlcM/V/R0GgvKFWbrUPQ=,tag:rc25LtT6RUVI0wvVcyXtCg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SfmV7C7MlSoOfDPy,iv:lntnmeMTPIagXehO10QDaKxh666HH+HAWyVi+AJtzHQ=,tag:XjTmSzJlS41zO3R0AsKreg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:eNyMRO3oJdI1Obps+064Rb+wishQ1S/b,iv:LY4K//2ZVhyDxVIwrsJnDHUuHnUMALltpy2b5PHGe0M=,tag:dSILaGuisYzos5z3SkJgcg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWGZrQ1RGZHhweVd2MUhj
        dTlrTUJJbFNaa0JQeUlqRWJiWDNIdGZpUEc4Ckl3dTBHelBIL2ptQTJBanloUjE2
        NWFIZU1FNEZJZ05najVGQjdGeTZNakEKLS0tIFlXK05URDZQanFubVFrWmdUMExJ
        eXdMMTR6bmFZYW5IM0dvQTVVbE5mcEEKLd0QxVtD2+XEztn5KDbcG29ahw1SINxL
        u4kzoFwoHhlZjObTDpvpK/eidK8zV9LCMzMj8oklQ7uSBI8RaiR19g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:33Z"
  mac: ENC[AES256_GCM,data:UN/bKZogUTwMnxwKBm10HSrh7/VegfmQzsXZMUlJ8EFo9zPfyRp957XrzoQIwPV2iHOLmvt0tPZRt2V/jGPn1QUzdffI9j0CVIa2SBq9+6V6K8x0ELXJBMW/pbNGtUkhcM+H+tsNLS5sFSGW7S4IPhlhQq4eMmQmLndthML5t0s=,iv:aT1PGM8X/iq4MvtAndh7i5jblALwZk+lITDyG9ksp0c=,tag:fkFNRg2X9QrD5Xk/F6pvyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
