# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:0MjYZJCgYFvWdFo=,iv:ui2o5rAui3w/wBmohTk+EaQCRWuKU5cuP31cBUL92WQ=,tag:4ewn7lsI/+aOiFhcvTFmEw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:u9Sai1G19+jyrEdR,iv:+4EhEI3+qp6kOU4xNjtxoL5xnqmNBNheITJwVtEZ2/g=,tag:m+OpFJhOHnAMxiVWfqYJhw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:dYrcBF9HYSOHq1XOYQCpzl2yJwV3fiuv,iv:B8e4BtoJV3uP61qIN+7qwEOoyRJRGIPwrWBRdhqp4cw=,tag:hqyqjAWyQD3SloLTqCeb/A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZTRMQnArdmFJTnBlTEI0
        ZHo2cTJoQXpwN2R0NGxQVzgwblh0dlJsZ1F3ClJIdjVaYTIvTFNVdGlham0xbzA0
        ZU5kcllRNGpUbmV5QU5kNFh5U3dzUU0KLS0tIENhYS8yUklxdHd1dXk5MVd5SFFv
        TEZpUDlVQVkxWUZZYk5vWExLY0tDaUkKvKbjauRpYy1UDevyJQWFcXIiPyR/WB+t
        PzFmElPG7sgC2DB7fnGmxM3f2I1l/J7FFL9k6MbZoCiGUTedY7Hcdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:QTgLcXif1+6HwG94LF7AV8fhyOMKMVdHZxY9Tz4MO6IpJzUTLiUEvK+hhwTGkGCFHhGI+yiTcSqTF6blpDJIYBMiGGnQt8WpI1eNTSwLxNQljh0AqFQbZqESLb6RrBl/fgBO/H1A/LEeleFidaCjgx5Tjcv9/iChf6bzeWKVeXQ=,iv:zAcHgO6XG9cQWbOJs6ck87bLrub4MjZlL/Kn3N0LjK4=,tag:OU0YT3fUGLTxMHwBmd7fBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
