# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:N/5HB0uFByfH4IU=,iv:kDAN8SCFMJ4rFc3VlEAATT40m3PLr3EcntVPyxHkLsg=,tag:bzdieBPoO0jijZ/KC8Rgbg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:eKrABVoUq166blMs,iv:RF5vgGYVfRmdqb48kUXtE40g48HkWjh0OOELqgQl3C0=,tag:SjjB73r1BAcJQzQ+lyNuSw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:u19avJlT0EEkiy/OIdjKvMfmE3mAaWXK,iv:4+qnlSVEXlQ9SFVVFU+hsleJWIVpFhhmnmApSOt/qEs=,tag:GhcjjDKOww6nvvnFNfLpVw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUk5LZGxCbnZXUmpmeVZD
        UUtxeXloUmh2VnFkaU42SXVuNGduQWlmUVNRCk1KOHR2OWZMRUJCUVlLYnhqTVI1
        bVovYXJZYlpVcWdoT1M4QkxsdURRVXcKLS0tIEM3b28vdno1TUZ3ME02YzBheWNR
        ekZQWkpqOEt3WS96aTFkaUtuRi92L0EKfahbUbyeA67RvynXPv1fw34UDGm1uIB7
        FqQ1rtrDI8zeroDOHaapoPaMIKSrU0O49JMYfshpQ3Z9XEgIC4VwlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:03Z"
  mac: ENC[AES256_GCM,data:BDcLNjTXlcBYT19szCn85HFSQlbTkLznx69cgfOsvfRoLc3zB/I0aN7sqe0PMWxnOy6p3lkl+hTP/5XoxrzKrqi5eP+HEF599/1c80H/cFu//gMQMdFZto1mUTJwWXSgqW0/7ewXS4upoyB9Woi/wyu4t7oYGHF+ZM5Fmq7yV4E=,iv:b7wnOSD6e1dCYfgg2dGAPEbwV3Q6LRyY+aMcQHOYAOk=,tag:2BDHkCHwT4ikpU6epuzdjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
