# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:nbLk4PgQP8+yFhM=,iv:sOBF9qqEYIdybAz8x/yoOthJl2HZeDQasT0EhhmbiPE=,tag:2Df//43EtPWZk/0ObfMXOw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MmdriW1Tr7+d2fgK,iv:j0GPg8Y7HLXBHI56jfP6KJKlG310/AuzMFbQXJfa8d8=,tag:R6JkP3UyTjK2/lZpYoMHHQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:/5/gNSG8TN8wp+yyyg4Uidg26vyAodF1,iv:QiXb61C9/my+UBdyxcV0GJJmBrp2Ahobuj+Q7jbQBR8=,tag:dlODNpCw/KcByTV8GwTN4g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJazBycVoyNWlrT3YrQjdw
        RjZMcklDWkdpL3o0VWRjUldMQy9TbGhINjBjCkY4M3ZvUi9Zc2ZPQnlUcG5nK0hY
        VTZ0Z1ZNeEgrTTNKTzQ0NkFSaytmb0kKLS0tIGg0d1RzVklrQ2tVMEhNd2JlWkRo
        aUZETlYwWDlERCs4ZFVoV1E4N0N2cU0KntahzF/x2HHWymWq5ije6V4s/lWDiQj0
        Z84lUWa7fy+0S+Fg5n0b81fCCkpF76KsfX7Mfo1U+rQtV3GAOzXFkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:Z+D3efNkuAHsP9FfblA1tyhR6VX0nTBrD+7xurUyKGDxpvrCWxAiGK1QXmnRJLUuo/hCoLkyv0fUaZLm/I8QkXryUWYxPXBUOO2zq+Pgau5QqvQmEAbvTsboQzb/yel0oz0/KqP0MeACpJvlN6tWianFi3Oao2FBXFR7YxrL9Es=,iv:Ezv8DtI4Ev49bZEVnMKdAXGqoAuYcSsrg+e4xrimYHo=,tag:3M57hHvX0tiLLviTevv3xw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
