# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:zqriv0UFAg6Dnqg=,iv:HsC/kphR290xblzOEGyrP6P4zm1NU9qOhqjLUzzmA5w=,tag:fTiszCGDTk/drtkZL0o/Jw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:TfwTt53OOPCittzN,iv:z1PqpuW3iMen8wFtHYJgFKCHhJSIAr2vofD+u8+SonE=,tag:b4aP/uwb3FJPOFgAkiegDA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:GS4HRbeRFIJ7papL9lg/Qx5aFaaGamed,iv:vpqfrmGbYPG2D/7EfeJ32/1BqEUX6b93EjQ2PKCuLFc=,tag:sNyLX1EYA0WEWlotHWSj+w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla1ZCUnhTbE90R0FiT01K
        c0w2L2tISnlVaEhHM3hKRE9zaTB0aVkycndJCnhqKzJ5OEhBK1dhdVdkcHV2TjVr
        VVg5Tkp3ZExJOGdkN2dpemd4ZUl1WkkKLS0tIHJwVzRHb1FXbWxSNjI4UnZHUHFG
        bVJWbWxqUVFzc3UzbG94TnpVdnl3NmsKip9DqMBLwtyoFb2gkgHPVILy2wmA28kg
        MIoubX8umCPqaRj7+qcF2d5T8PW8bi+6iHvI6d0fAPG+2Tz7Laf4KQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:V0d6+2nhvdERCbZKk2Hu4bliKE7qfAjig3Jwg2VHoXXGSEvDiX1M+FwWhUcLdR2sXQ3Z6cij2+nCunYRAm1v9msDnGsPfhREJJqmPaZMv4BCQdTFkUTW1DihakXAnyKrGSK8/uaUqwIdYZfKd/imCTm2l8066wBeBrM2yOa5kmQ=,iv:gCxKrk0MpNWmkG6pTuF8ZvioIqw86fTcg0m2cLb+r5g=,tag:cKAiKM14fwOVFj0edOV6Lg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
