# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:xwhCMD7O5ZUgqBU=,iv:3WCuUUHwegESpKr53Vn/j8sgs9wGc5hWp/ReIdQdLS8=,tag:x+dgqXot36Mfw+XdPP8Sjg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:3RZrAmI/tINqDN+6,iv:E13/krS01jtKs08pGkqF9kV/4Gvs4VvHaad2qZpXV+I=,tag:EzuaIDER3OQdVNYnN80Y6w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:h2blkZYSFcPQY8a35Pt+CJEc1o7FTGEl,iv:CSTrHqXdvwJVEEUzu8JMk3AdCVHjVZOcY3ShP9rMalM=,tag:2Zvzo8EZJ2qDrTwQQ79Lqg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSHRucnNLa01NbW5tNVJi
        cEZGdXM5aDlkV3o3Ymd6VEtMcDNpay9CUGt3CnNwOU1BN29SYlFlY1VTS1VOR0lu
        RUFWNCtodnY4bXZXUi96Q3FVNTErUU0KLS0tIDJnenIySXd6eStGS2VtQkIxd1pU
        V2ZEa0xGWFZYeTJ3TXVaUHVIdlMzQlUK5XHhqE/VOoZbOEL/Fvsi6Vs+/6kbtMLY
        ne5wYK29BoyMJPho1UbJz8fNelsMdoq6UwBZXYAHWPAnGrcS+HMcRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:HEnrKRkOILprK/0k0nwocrgSTPG54OVmkwtOhB+f+YUazxQMkYuZclnrKItvJhTpoxeeg3wLUi00bpP/P9yMJv5OiPkmL8VCpuyXA23WyWD3aRra3MEI+mwa9BeVBj58xcleh73ipZORIQibfbspFVgZfzwXHci72mEB/5eOdiY=,iv:Wqdslf9ihF8fevpnObqlaxMfWMOBgUzlbA96pNfjEm8=,tag:VQ38k25yuGDAIMu3/zK3rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
