# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:OIsSB+G1eCMU6No=,iv:Ey6VY5fyQqcQJjX6swTcJJXnckDfglndcjavQPlxn/4=,tag:FqrvIYpCY6TbD3/1YPI4pQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:W02asEZL6sgrT3pL,iv:dP7WfPz262mLJUubbEga8QX0QVMrUE+fSBBFqeMYvfM=,tag:XsxOupgtCyjXXgpwDeylYw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:HRL8iPHE124mFuEfgA0BDDTceTcVU7WK,iv:E3rVIljx9egCjpBiAwmRHLxxcZEc2nrocY82HODu3DY=,tag:+1K4/8G7BnCZ+5SxqHkylA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXJlb0dmSW5LcE1mVkhV
        TlhteHBwUkx0MXV1UXdNSlZpbHJjcjdNa0ZzCjlWTFNJWlhJZWN6MllSbzFPOVg1
        TzdOUTRTTE1oczBzL0ZWelljRWlFTzAKLS0tIGpDSHRHand4SVRyT0VaNTN5MWI2
        b0xKL3gyN1QzWHgrY1plcUxpVXVXNUUKeg/DoU2ltTRsyG0bMK7qxHPPvK4vT9vs
        HF0rXSs1p4VJDfgl8bMP9KYAZGvet2pzzwNDac7ofJXO7F2UXVRqYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:wlmc/ZNFA19UFwPtBd0VONUbURb65jo0TctRkwuKeRXHQ6tbYpwRaT5Mi0YEq0esi9yFBQ48346rFWhyIMTo/Xd9izp354LbIpQ85EMgXEEnRdhalGmrn0ettAVPTNQfKV4eeKWhgroKxm2KX+lu1ND04FjUmud00GDsFDVvcN0=,iv:y5Qk105TT1kVCuAzieo84qIzuhsvdputvWlZ+6wE2ZA=,tag:bV0+lrFnGCNcXnvqCc/u+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
