# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:zebetldy+maQNdQ=,iv:GC6Bu7AhyrY4u8hEP7gk6uBCeyTRr7i/tweNp12ydCg=,tag:xBtSR6jt8Rd2TC4V8Zv0NQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Y9hZTxMvG3+AHctL,iv:unHPr+En+QMuD7Wb4SCRzJfxnnVWFZg3IPLtFAPetdA=,tag:0ovHaXzhvybqTEJUFEJhnA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:EKh+hKRnd2iZiWcIBZLYW/E1lM9onpUC,iv:w1YvmgWH94hkuWPcNoHcnsEcsWJTnlB4cJk6d50UhIE=,tag:wBwjWPP4XFPAEH1rnKwvJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOEg4KzZIcGU0Y0dKK2J6
        VlF2VXUvdkFnbkpTdmZQVDR3a2dPQTE3QjFjCkJ3Zm44U1VLcFUvTGVIa0ErOGpY
        dVFyenVhWmFwdVRidVBBdE5vTGVsMmcKLS0tIDJpajUrSXA2T284R1lKUlZjSEJv
        Y2Q1YmZwTit2TW1YdlpnQk4yOU1aeWcKFWjOlg9yhnFSeCeyYHRcN35YSn7AISom
        R1BTBO2Ht4xhAStsSRyufpapFv7AcLaZJGsPM4u9rrkhSItZmLoVqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:YRUNi1F+jGt8hzIZmwFPT7nplNFihhcJd2KV6ikX+BIvXNb9qQ/Od7fnQm5/xSrc0gN8L2rD0rjFwVkMxxm4DbJ2EUpU31nCATDmK+md8LWw6uTULfmbeF8oNp9Gby1f4dr0I+J1XGDJETmh1MzlXcRJnZTz4u1ZHOndVQmwrDQ=,iv:emcWBQwdaUkP+SQqA7eynAFGjWRgU8glK5nvaoyLYnc=,tag:jl39JKSHOY0ZvfJpmSXOrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
