# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:lMiWSVU7tC7aL40=,iv:cKcRCbd3oPHEo3nUF55YmXCAVV9RuPqafqww9o/63WQ=,tag:FAwSo833Wrwf4dECJiH6lg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:EKPt9Y1D+GlpQVVa,iv:sUnT43X0yRdQxkKU+RyeqYaNq7S8RHyAsMMGgYHhdqY=,tag:XOkkXfV4Qwrn0hGwarSlSw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:MrXkN/wz5raQd2tHI0mnCMY4WT5crHVO,iv:C81vlVFk/LhoSsfHCH4ty7qEb8eXOcCEMOo6z+U1RUo=,tag:2+XYr4CAto1zfbB4USedZQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdnNoWUp0dFZNM1BXRWJL
        OEVzT1JORjcwU3Y3Q2VTeWEvWTdmZ29PWmt3CmJJOUdjQlc2NUNFZmh3c0xGWnpW
        ekNIbDNTZWlqYVVLdVlrTTJBb3p2b28KLS0tIFFiM21qL2hidmZtWjQ1RHp6T3lO
        RUYrMmJLZytuT3E0bURZaldEclNrbVkKgXY4ibviWlZ8/jzlVZXZwrq88NgG7tSz
        czM+FG1FDKCqzVpUs53H89V0ENVU6Yy0Sx07/vZUtCZZWn95rfCcvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:JwZTImpYiYO4/D/XbiS1SYc0Mwyy6LbtHHUK2m7uMQkjhx5HW5NR0M99gcxf0c2/+PmipJPR3jdiuAAWZ0Uc6qV8FTtS3vuCRx/tcEsS6UW/Tow/iwaorm8gOv0hhVHjK2u0vCLMQh78EobVL95vUuIxtQXJc4qCr16H8mpkAjQ=,iv:paAKYGJAD//H1oBMCU6d5OBxRDZ7J5KIl0Q2LJLTclE=,tag:ESStgJZiv0f9WI/CuLha2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
