# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:6Ov853uaVskDbR0=,iv:Vk57nJAOrko9vcIDyMzOCj3B3gTLSQgNjnsALHzxb+k=,tag:kRzmgrpuyzJAghZIW5pxIw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:vqt0jh9ZdrL/D+YX,iv:clggg/mDvmMFy71tjLCBKmpUXsU+aBOLwDFXT2RmB8Y=,tag:iIgKmDxr9wQAjMIppCsVgA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:QWN4osyzduJnYV91pE5dObXMGWfA6ZCs,iv:UWXj0QsMdrKzwAFceW2gNaAFx4IV5FXpaJLZGIKqP8s=,tag:dDeMC3jhQhLxjcmhXYFopg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETmNKV1J2Ym5JLzYyWFRP
        U2MxOUtDa1dMZlBqS0xGK1VNQmpIbEFmb2tZCkJvNzc0MHNoZElNbGtFeVpPSUpv
        dzZObEN5ZnBjR2tKN2JSYmtLKy9vVW8KLS0tIFRKSVd3cHRJR3hlenk2YnRaOUFR
        NWlWMHMwdzllZllqdnhPeDRZNDY5SFEKMhAGJGhaKm6rF1y75PVLFs5R3hxuiZgH
        b62y1kunAmaK22RlIoX3LPRzBsX24irXMDljziUxQeSwnyl1X0sYRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:87BXt3MI8kNAcylVG/O50dh8ucxLbKBFwqWmVdKCiw8wutatQtJ3mr+az79btZi0ra8w2Og1GIGMgtk+ZXmqGCdZknV1dWXX+myBciy5Xxf3IGwwUv0g2lyh+r9hhgmrHvRYqYpKmfl7k6hUl8JYPiRWGsrVEMtNudR4MFjRfuw=,iv:Oq39NX/qnq/9uudxeH5DYLlcwFyqE6qEt6wscnFwxAo=,tag:+SFyCDvnlulbjss0p+OCNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
