# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:9FmktBRtwIx94IE=,iv:bbacEquXgEgaLXWbvxs06Tq53Z7xhgtZjkkA71DsAko=,tag:aksnmEmpZpJuHbIthmzlDg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QhN30oHYfx4rxutC,iv:kM1arJSnKMwVq7fKW66ZCNh8KZsbVGcWk7lDSJaNq8Y=,tag:SJCqWYiY3r3lTYLxerlXww==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:guTFJpVkSpHeyRHkVD0GSbp+08riWOs1,iv:B2YKW/vJxIXOp8wJwvCkqhwYBxr1AhQGWDcFEfXaUu0=,tag:m6Dk2ykRN74cl860t86pHw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcngzMlRGWENUQjFTUlk0
        cDlMNXZVbmw5RlVmSlNxQk9uTVh6S0psTTM0CjM5OC9jTEZ1L3NFNzJTMHpYTnJk
        bG1adFNGcnBXSXZrVk5mNGZxNVJOZGMKLS0tIDBxQUYxcndCRmVRbWZ3QUhDeUQx
        K2s2azYyTm52VnZEZmYzUDRYbHFiSUkK7o0Fo+sMYWsdO+MGfwX735/lHyOvqy9V
        +QErpnsksIuoFtbAFLzK+jETorJMO0ZTTJC9sv3h1agDRahmojgxWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:kWKnHDyydNMRtAX3aR0UU8FN1Q0bGHXNVoSAmEu8j7qx1gWOggGcDbctqgnpcXJxu8uvECPgVp+iFQMic+L9BrWLJ1TCODMYX1WmlfrEzEYgKx7RYp0mnkP/uzQE86uEwASDnObnRcFpx9xrlos1qZ2/IlFEshCbZrp4KLyo9sc=,iv:0IxvzA6jJuGnQVmUWl2fnQXMEgN9qvyBMcAdy2KCKXw=,tag:SsbdlmD7iEXfwTyzLtSR6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
