# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:2TAvOpvZ8JsJMqs=,iv:iHQkqu8dfEyg4PSzW8jvonHtHAsHnYnKg+h9f4J5VPI=,tag:SsEhkG10Mm+QTnyDwFptdQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QI4aPKKG2xWcwEXo,iv:VUgX/pnjC6icquLgjPAEhu+4hejIonG3eYAY2sl4K1c=,tag:lMzFmZBpQj97OBvMgZeKrQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:ESYpssx7p5h9Pzx9Nd0aH2zaDK4L/fz2,iv:g/qiiXzFJlkE6s9wLa5tQg70/y1x2goMxwNw6Zurg9M=,tag:DueMprEB85MDGeOyGPDgPw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SUhBVCt3U0F2SG1UaVFU
        aHpnSXhKTzZoaEZ2UVVORGhPakVLaTVHQm1VCmtwbEdjcXV3UW1QVkNnMUVwVXQ1
        by8rWndDNk4rc25IaTJoSFBXUGJNbXcKLS0tIGIxTWhOL2EzcjJydTJhSHh3ZzBu
        MEM2b0FEdHJKamZJcDB5SS9rMzhDU2MKHuzgkei+g4PhlfdDXz/xGkdbJS4lils9
        Gc/sHoP1wtVuBKzebJe7SGlnrFyagvFI8L3+d1YfFbh+22wld5rJtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:zIx7V30Qmt1l+JDgtRoPmtF6gcyDYhTRLQfmLG1b+c8CE14vKW+62jMXQ+Ff3Ncap7syNJVvo1lKcIp+1YRA4vka8OgYUWbm6SXcz+qvxwizETos42k01XxAZbd+PfdltKY1agdGgbwrG/unvSALJ0idsV7TVr6UO346GQdp0r4=,iv:MQurLDNnzO9Lgh671QGxW5+D/AN4WVFHEhFv79byThQ=,tag:x3RT37hivwlz5Mt+EnZiOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
