# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:WWiD2dIZAIlWZ0Q=,iv:XMvh15l3/KfR1wlVdTs2hqvXA8HywTYnQFdRjC2TDic=,tag:fkQZKkFlJND1c7JMQYfRUQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:O6Hx1x7aeikuouDx,iv:zwq+pMxzmHH5i/QQPuQJHqKSEKU31hcJ+2UmZd8UIwg=,tag:xEjkBYXvHJVgRFlhiifTnw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:h/7CvYA1sGPABBQoCzdySiPaMe/bhCL4,iv:JvKQ54rCdzXN1oVFrdSkGQQ36sncuxDPLwwvLPt3eMQ=,tag:+7V+jU2S/qjegWIG5Qcu1w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Vnduekg4OVVOcEMrcjA2
        QmxSYlltb2dSN25jeXJpNUpnMkQrNXJwQldnCnd4aGVwZ2RJZ2tLTWErLzE3VWxt
        MG5JdHkyMUwrS25LQU1tZzFLL2lxOEkKLS0tIEZyNy9hL1B5YWpKNEpnWnVPMWxX
        ODVXTlEwei9YWDlvb3pPRnppdm54QkUKP7XwKfdcPzP3n21IXuDlq6DeyNXf6zG5
        xAZ++zJFxBOmFQiZsqRw0ppop/HnPGRa8j3iCp+wO3uadIdNF/fB/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:z8af65LVDBEs1oDvbc+m4E3Hv8I1DUgEbFEHG2ifG+uWJcLiRfmB6KMLB81hIV8/LRVmlHS+g7f3AI63L5Cbaq4Lc6c3EOFrHfQr4iBBQ4g/Fw6j5ojCpK7D1G6lKQo/T+vuTxo/W1fT0xwcdsirR9XsGLk8LQ3eZTDlAmDv+Og=,iv:dv5knTI6nRvASI4HHZO42qzP02ak96g/t7AwqFag/Rs=,tag:yAWw4m25rCgTmiEoB2SxIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
