# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:zZsc3uD6E6eTfCk=,iv:UTA3FZ09DazXVv7vrDwnZK5BIqGWV8aaDpCDsWJmxNg=,tag:rKYHPo19PYX00r0epB3Z5w==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:fYIzsDFJk1PaVA4m,iv:wtEzc21tEQ86gZEvLtKbEuWglpXI+aWD+L58zxPBnO0=,tag:SoBPTHCtSe4MJ3iig0PitA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:6Dfnt9+XGMN7RsbVtqSO5CgvqjL1ARmW,iv:jQqhRm2JHVIYGsiCWtKsTDdjbtBzYb1ZkthqObzzqfc=,tag:MH2E1PyNranzwOpzra8F1w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMekFhK1hGRVFjMFFMdlBs
        L0RWWjNKOTdCL09hVkJhU0FWTTYxM0E5elFrCmx0RC9RcVB4cXkvaG93c3R6dVN1
        ZEFjRVBrVjhtR0ZKb00rWU4xRlhOcDgKLS0tIFE4bFN1cmo1T2FCQVJ5V096eThO
        aDJEaTZuSWlzT3pHT2hMaXhjOEV2RUUK8dwUYWon0n6Y9MuEk+Zr39tzzBamQrfj
        ejMVBYsJT9/KXabKQnmDKPCJeol9YnTGvfzcReTZ2TpsE6x6DC0L5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:z+zgvcx80hILkR4MdMbsWegUpXLeLM+LQkBfe+h7HOC2US+lXIUn0rjJix9ygVkWV3EEY/8Xs4Q0cl1VGxJm8ODVjz7b237G8nHKUKMalmk6I8GTKg18tlAAmcd6CY3pU1vfRQBO4M7QWSOcWCVR/rA0Mlrv2wr04GI2CDW/ZPo=,iv:siP6DqWp/Ec4Y9xf8Ht9HZg3LIW7GZuZjZ2BaaqShPM=,tag:n1PYuXIIVLL8BmZa5+ZEyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
