# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:r8CTkgaLM3t4l3k=,iv:xPjtMG+1C4vsyLYZmQdXaWWr0V9k00LcTGFt5tRzVG4=,tag:6tTI0O2ahw7TJE/qrXGyYw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:PXqHbwSBCNTBIHgz,iv:gkoGZ3Y/HAk/yuaECMG83ZmMXuc6Uopjc2O6zskwnwI=,tag:MC/6Jro0I8Nh6wZQT5WnXg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:tW/EcsSXoN8vsjJNAf0b1RKqdVTPWCWB,iv:rU6DmqbjXGRyclDOAVGWAIw9zJFHrQ5cTTZI1b0v3Tw=,tag:480PQt2+J8yOK8LvzCERmw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraGt2dUVML1BtcURESS9G
        akhFck5lcnBPbHZsdDRkWmJCMkJxT1ljRTBVCndPRkxKTDI0Wk84a21wditIb0lp
        b2ZLKzdtZW9PQW1Tci81NEpJNy9xOHMKLS0tIFZqVW12SU01MXBVc1hxRGkrUExK
        SjY3d0xheEc0SUJPU2JMSkdObDYwRTAK3vlnvXAx/M2tmHQkVbdt4a6o15tzybeP
        LYIGMvMzjCj7vqjzGxjHiJRh8ozW3/7BN/WmygavBtJUw4CYgYdKDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:JPgE8R+HU7oXOGQ6H7SPAZ8+FYawJnaOS4Ww9Ic/pVtUTZvsWh2Z64aMhraNTBOHyH5aeiNPhDUlW54Vpq0s5TmhdH8qeX9NPymu4Gz+gn/385KXQjjSOKd9Vh94XAobBpm7rMWWJp8U7LIjXXzlze8cWAFK9TAF4m+2kVs9ySs=,iv:KckL5sK66RJS4gG8i8Y9EDKJGbzKDamwjqwGYFnSYJM=,tag:Wyyv2EneZ3WN5WgEc877ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
