# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:4xDnkIO6lHDmSTk=,iv:4xdzFFVnDOu3CkZfqD/TQCarbh70VUpbke5Hr2YUmrI=,tag:qcpIdp6kv/HKDnb7qXLYng==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:/PZ1shVxayqNAMoA,iv:8i6p/s7mAtuzIxE6XwXs2lPsW7AQKvCaAFgXp+qKuzA=,tag:g6T5+0xOqrZP2N/fOcDbAQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:+SqkUArZmMHWHdtVlc9HkqhABAyQ7vKc,iv:ciy+23icIhGknZjpeKQMsdLv6Hq7mD579p5wdEaXUic=,tag:D0GzDg1ynDtkqLzt2URl8g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VnQ3RU1KRHJrTTVtNlBV
        MFkwOEFORFhUZjVPMU9iNW9VdEV4WnpwdFFBCmdKWDNETzM2UXo3aWJwVlhHMW5a
        dUFaN3FRTnJHTVA2NDVRNDZnam44UGsKLS0tIG8yekJsdU9mTm54akprNkV5L0Ex
        WHlVRFdVS0tDMnlibkVDc2g0aFFaZWsKRKZ8mS3zb+7mGRSomO/FjEtemCnb4Qo6
        Oiv65YVxXZ9r02tjmiGboN8rI7G/gPITRFFexfw1cuyzAisU9Lu2LA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:55Z"
  mac: ENC[AES256_GCM,data:pCNrKRzId7cn3s2lkfBJrou7soS/rrvl9iY5PCGtt+Y6xWAvFyPVxYBdU6c3PmcSzqEp7qjZlm0Ubx7tqTkTjJBuYThTKK9C1068IFB1euYQGQym0+Mvxwng7K738zrSqWXqiUi6zw1vt652ao56HloBWODs2DxzS2hdL3DV5xY=,iv:EbiJS4Srijc+uSeslTEmHnIw/JvBjVL7jQ5WIIq36+s=,tag:E+ptFldU2Od5eDUb7zRm/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
