apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:CwdmLFKXu1L29MeT3B4=,iv:wxCg5xYvT/uos5SuWo1/y0wHiPSqypFSQ02v8VJv+7A=,tag:hD0USnPMdgXAIWUE5lnmfQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTXFUM3FNSlZZckRBdzZ0
        ZU5RaHd1ZnliYVdOSEdvUEp2cWtKVHNNS2pnCi9CeE5qRW1xNDN1YWg5ZUx3TVdQ
        YnBGUHpoRjE4VEpjWHhwK1MyZ1Fta2MKLS0tIGlzUkp6bEY0NnhSV3owTnk4OW5o
        V1hObVVvRFdPeGZKZVZ5TWVUQVNlWEEKJDl7EplxWYdjHuYBM5XI2H1nvr5+82Hx
        i0AGduJtJbNGBD83ogH6Gk6WlUJ35KK1o2/JOdSyje+3Fj1sj/dTGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:33Z"
  mac: ENC[AES256_GCM,data:OdDNg+DnabdKL5Z2xw4KLrDgd7jL7mm51P3wcxw1klDAvBELGrI8aemy6MEX6JaIB8dR40xMzYZvoimH4yXC55ZIXUAXj3MVsdkhgexlftQaQiljRMNH3jpdpDtfRJXbkaSvRI9ds4qFZCeFRiN7GnEj7ZFXzdT7g10bCsAWfEc=,iv:DlBS24QMTrUNB2+vdd2116CMNZQ9UYlSPRZS64p8kIk=,tag:shlPVcsVYh9zTCNx4EMZQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
