apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GO48oIxnGiWPXtf6ZOA=,iv:wYQmVW9TLK0J7Ovpzk3PKHKPI5igyKMs4iz4Bz0gaFU=,tag:dvEuVroA2RFvXc0T/f9qmA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVTJDSUhidWxWTlV0T1RM
        QlE1eG04S2JtQ3laU0JTaXgrNTBFUURZREJBCkpudWlDbjNSbk5rWTFXSnJOcTJh
        S05nZTlMc0RGN25BT1dmb21lVCtPK3MKLS0tIER2TzRVaU42RGxxMDZ3V1U4VUND
        RGE2WWhid2NQek50WC9mcDZMa1FVSkEKEZyeDxh6qt0Ov3avLebnENRIyQk1s21w
        IzQp9O7CzTcj4eG8StHdFEt6SZlklVsSWb0X7fHa7iFhT3IuHJYPig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:05Z"
  mac: ENC[AES256_GCM,data:uLA0nMIrffkRk27xbQPnNhH3iwTjpogzgy014nUvA5fM81RbJNwAZafzQZV3kQhpk13ANQsXERqO/NOwzXCBneZYSJWq+gPM/sTIdSZojKbesM3jBVH7bMKbn+47dm0qXl60ky9HwuZkMnU1O8rQ+7nLuXPjqvPsCPPP623XRMg=,iv:WXFFUcVRsecVD79n0/GAfCGSwigZxceKF162pt3gFGU=,tag:O/Fs1nXEJLp3Ke0blnkilw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
