apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2JgCZVTd/iMPABE+kFc=,iv:9J+Fr0ifdenkg2ruCA2iabS9w/Nf6xwoXKZ3yG6w1C0=,tag:Vb8zgE6GucMOmVeE/ibFfA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaUc2OFROL0xRRVRuNXZN
        aGVVdkNlTDR1Mis5V1pBc2VaeDZsT1hQVEVVCkh3bjRTQ3FtdCtnODVrQ3dZZGpS
        RVdjdUJqQW14Vzh2L28zMDVSZmVGamMKLS0tIEpRMTUrZFJjN3NiVzFqSFR2aG9h
        cVQxbXRaUU15MFE0eVROYlZVQTlDRjAKjorxLAxrH5ct9za7a0+J9Zpnfl8n5VC/
        sW8PsR2GTwB+PIpo95qv6mn6AykP0Dh+ljrCb3dqWEm1yVZrafngIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:Lt1FPJH3ofgOcGRgHCv5PWeVa3ihpVTAFOWuq7gpdHxR1daDkKHKBGqcAvwcMgSpPkOAOgftaAzcvYMhaWRcqHVLsXaprr8wIEe+uhzP4cq3iMy4gZbViZ+i3cC6hRSjgbSgdIiDaQ5jaQWmA+Qm/eHcQaXcimMhB5L+rW7DTTQ=,iv:Bj/Sk17aX5BIc77ESH9d9l5w7OC6OWXkwhsYsoEeIR8=,tag:VhmfPsPbuoGb8SPExj3BiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
