apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZGkGrhdnNEtOMBh5pHI=,iv:FPJDEpteqhuOxl6iu/15obAa3LyiTEfTCAe7tqWqCWo=,tag:CPdiUevBD8YrvhWE3t6QTw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUTdGRHF3Z2UvZEdxajRz
        amFpTmkwdEkrZ2VQTmloNzU0NEZKR0dsMGlvClNidjB3Uy9Bcjhrd2ZkemMvdXlx
        TEIreThVZEd1Y3NxUXVPM1lza2luMG8KLS0tIFJUb0VrQ3JwSHQwdCtvOUhGTEt1
        eEhYN0h1dFJnVzc0N0tEUnhhN0pYSlkK+k7Z+N2iZrVTU1Wn4ZNTD6Z10fvmp11W
        jybxNpDaDhZdyJy4TZj7zdasvSYqXh72BSXVJKb1VrYb59IMKyL25w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:941uM+OejME6PpelK+jjYJaA7Up3T0ZznLU1RYBfenncbGzHa5R4mqtTyKlhXGAmK6IQH5uzwjiqkneYDZqhqQ7pZbdM58dni5PACKqKJZBxVpMGvueiSM+f5kfVspHukuy92A2/GR5w5/z3DkgxAVtucPYkapIvjnb5swUFAAA=,iv:vvatrFnF+e5RGZjYpx4tzZbcLj3HGEv1A0yhozFtP04=,tag:lyDc4MnWTXfG6mZY8IUN4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
