apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wtJfAr43O7svRrNCe5s=,iv:bw9HgFNTUuNCOCFiFcCUIX7jxOPcpXRRn/uMJjoD36k=,tag:TYZHih0CO62+ymD+ulMPcw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkE1VFYrWGFMM3BEZjBl
        S3d3QTVsMHR0aHFqVEJJMldLdkZWMVd3VEYwClVkTXNKMWZCQ2lGbVFQV2F0TDQw
        MnRtbElmSmFsclo5VitQVitWZ1Z2cncKLS0tIGh4YUJhbGRWb3Vxb3lUczRUU0Vz
        dHRYbDcwSlJjaS9MeHlqZ0VoRFlRRXcKhp+jM0KbclpmajHzzOf5W3ejTsFPmRUm
        QWZKyoi9Tkc2hIbSzA8w+6BBWtKCtSr39MlCKlDKh7bzSUOYc5LQzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:iBSyvnBEfn+U2jmDMEfEPQAH8Om79ZNs04TWZowFY5RI2A4hQuC0Ywp3ND5mSvqBvkZsYro8tLHwYnIioFV5bzrOQb6Pi7VQzDB788Mna+zGUPT5/lU6mmHLfh7HHpbCreSWzdMcqpC4z74aYdFiO/UyRHRB1ueWtrF7go2Y85E=,iv:XSdYvXf1t5m12aNbrPhztfvOy9XQirJv2+YXhe1QjI4=,tag:qsQOmnnGLgFAqdxUj8mIIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
