apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:IXU7qz+gBUd6AcihvDk=,iv:bd+eo80gaOPUa9sD5F1IkfljsMIk7uecNmCUJaoJY38=,tag:FGmiP5SbGGB1Q0Ka9t/LDw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY3RRa2tkZ29CN01qSHU5
        MWFxdjlmNFgwdHJaSDk2VkxqUUxOemxWNW1jCnIwTlFZNVRFSWVMNjFSQjg1bDlw
        dDNvallZZ1BzMzZxV2tnZ3dqYzFmZmsKLS0tIC9xV2pPT1B3MHJFaTRqNzR1RFhv
        ZFdFOUZWd3oxTWdSSVBEM0JYM1NMNTgK10CU0S7T0DjgUqA8i3KBrZUvOB4adMvz
        n09pwqpsXk+IPRayHJ6L2crgxuFbJiwPUZnw/6/v1lxpNEjHQ4cnrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:cfUC0TUGix8GnKHaQCxOTdXd9eW+zXjDnEiZGB70Kx4hV6KiTHqEF1E58O79w5WDIt1z4FE9vsJk95MC5lKTnqnEV/QZI9F54huPIo++BxBEE7xolZkXzPIT4RMcDKAkj9QHFzydHDZbFRL6H2TRmzzlB9yURPyQ6p9kMf2rY0w=,iv:ae8JbWQ16sFfyle+ziLnZHYmu4EtRsuJ3bN695lbj2Q=,tag:dXaZt1oZOJEdh/8EzEcfmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
