apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7U9CXBU16K1VQPAYJ4w=,iv:OQw2v404NSSUk9LEfPV+DB8ODREK9AxO8MrfGZy/w/I=,tag:WT4rQIgVYiOsu6elxhVCcQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeENKTHRCejZjMmhxUVh6
        M0M4MmsrQ1MvWXdxSWxhOG5TdzZGWXcwRHpzCm1KL2ZhWlhPWFNNczBmOFJ5M3J6
        bzNKbGdCVUVKNDZyazg3R0tKVzlpdUkKLS0tIGt0Z1pwTFptRU43enFUcnk5eGp3
        WlRQYk9LWVN5ZmFhb3RhUXo5bDdxTEUKM+jKTfuptsHC1nbi4ggqMj3gdkqAec8c
        LTHPbvTROYpcIrvIj2PCoe7I7p9/NfhqoDaaCqrjzJTjZ6O8W3/kQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:3p9QXxMWJ87lTvT3T7gUF4XHbUT0CoFTmyV9woCC7QAxbhbOFCp7xvFNiEOmk2E1cAWMRk+bUrqPpbLWOfUoVLFjHmH87nN02T9j2J/PtKKjKkSAzKJWQ4VnW69H55uCQMKJkTYf+vV/ttZbU5+KV2/RQaBH/I9YX4kSGL3ZJx8=,iv:xCU5ePXjtc0upMlKHpQ31lC0fb8T7Mz26wwgaRzLdD0=,tag:dN6p2dA5UWhBbWmw/9CwYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
