apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:86nB/1RRBlMvYOL0oVc=,iv:9KippZa1tcbViJ4a4VD5AzDXizJmMhnlDlMmVplI7ZY=,tag:BIhpVhs9fU8AaIaGCOO0vg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOEg4elB1WnZEcEpQQ08w
        UnQzSW9CUVNXMmphSHhSSWRHcE9QVGptTFdrCmFKRU9pUmZMTTIyRGJpQlpOdTZ4
        MGs2QnFwbWNFN1lNeHgrVDZyWVVTZzAKLS0tIElOazZIekRwcm5wbzhhRXhRYktV
        UWc0cUpBRUpiQjFwSHJaS1hEYWp1OHcKIzmjLTmlstFH1Vh2M5VbkG57WcKVo/5A
        H45EMS6TJF/N36cS4bCvBADHQAhmCYi8wqUGs4CXlr4pCaSHlG8qRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:gVCQqMcDJcQm78erjw89P0U57SndYf9YU63BT0CjeYz1fns1fNrJYhyB/RSVlgr1cEU9LRzfU1GkkzYgbkeXjysTRU2e4u/Io1giTdGNk+Ffx4QlgG3UJKvnZTJrntf8P6NLzPagnIQNSUk669oejbSHFmbBKml7UtYadD71AXI=,iv:pRp9gLcsnVHaFvL5zL5/20geKUe1N77fYRbshwBX+z8=,tag:QHi04dB6v7rIwb9/4kO/kQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
