apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2aWx/2P9nHm5GSug4UU=,iv:K0bYm0Ybls7fRcKT2lty/Kh2L7P/AD3OIQD7YhKyMCE=,tag:P4cdPYjrprLCtwskgYyfrQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdmxuUzk0MU83L1dUa3My
        aHZ0UDFWZEVPN3RuLzB1NTl5ZlNLNDR2Tm5nCmU3VkZoaWQ1WFlMMjQ2N2N0T3pG
        Vnp4by9CL0lhTG9zZEh0dzIwQVdHWTQKLS0tIFJ2T2FLNFNLMzJoL1lJQWVieDNV
        K3VlTVUzYnNVc0R0WSthYVRYeGxBODgKJlO/Qo1n5AD8I7ReOgIX3ETgNCqGyBbs
        penJv3YH7NzzI/pUp0WF5kUj+8wexojjv6BHWnbULe1N4tgnpiOndA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:YyRBAYYiloiksJQq2Yl6VSI6lMZLwlMD01zkzzGFIckxeuGJ1uvpv9kqLoJgrX1JDooojkIwwqOy8ZHlEAfLAl/oTgN5vOsERjF0NWkaNQDZN7dwbvZLJhK3GdX5WYJ2PTz1/i44sVmQ9b3StrT1cUINkApYX6N/+jsFhaCeOyc=,iv:sl0uNOQ1QnsgbKmdrBO6QRbO1L/mNY7f1CmkGeKedS8=,tag:aRQ4LIJZjgoGlj5kNg8fiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
