apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:iNskx3KNIBd2zkQUqgA=,iv:bg8ZWNmuon1Vh+T6AQCgQBdj3ywT4dhyIkROjG3eYuU=,tag:fC22iEKmX3cThsZe/SvA8A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxODlLNEtmMjVodEh6VGph
        VWdidDZhK00yS1dwY0FxVmNoWnkrS0FZazFjCjdNUVcrbnZ2RnpoQnc2aStJSEYv
        c3RSWFJUbVIzMjFiQmhOSHBSenhJdU0KLS0tIEdZWks2d1o4Wm9yNk8zOUVJZ3ND
        V3lOU3Fyc3ZFRVdINEt5THhXNkVNcEkKDgNVkZsmjb13DLno6SfbBQaW91Brwr88
        hzj43xUWHf5uhO8HOREyXmq7zy8VM3/XaWgpL8bREtlAJg96CUJYNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:jxUnos2/GDZzjcEU1rDtFeUGuBzSb537W/88F4ZO4er/AU6Kb6Ze+0yQla+Yh3561WSF8oCtAl0dXUdd09rxnwvd4Ri6yriKGbA8WCZO6kzqWlpQRa7A9Dt2UuJO8acuyn8I8ZsA/vSTQX3Q6B+6mga967htAOPJvhg0u4+PGyQ=,iv:8lt3HWSm5bh75Rg45eDmJo00Fxq+5Fa/nfvoBZQMkzE=,tag:PlZIL1dxXna2wXuVnp05Ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
