apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:299U8EhNwfhKTAX87c4=,iv:vDLRMT3n9INHZr+RJk/sXM/FBDyiPAn7wAqL0FzKiCw=,tag:hWz7mPOQ3MEm/UqbnT8jsA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T043SDZWeE5zRlBvOFdK
        TFhiYWlMU1VnMjQzUDNTK21QYlVtdzlWOVNFCk9HaWF5bWFhYUZDbVdEK0tZVWpH
        dDBjTU5aS3lhNkN1aEN6WEVBaVZ6eHcKLS0tIHBNS0tuTTBIWlQ2Y2VJZzNvbnlV
        bkFrWG9OUWJwTkg4dkd5YUI5TkVvQjAKnQg9MxC226DF4uaY+smhXP0/h6UQbyMj
        OlvWsDPqwe2tySoeVynQMRGzh8MZszRmNaY5pg8zof/uhVu+kevO5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:03Z"
  mac: ENC[AES256_GCM,data:YV1j6MQSNQGsO8bAU+PBjcr6eOCRzA2Zdf2qp5JWe8Orja+oeXUtjp1NEbLCSECoD+w85B2o0JkKdWl0l4QT3lG+vyfDa/OeDWSUTSdXePQdYbPFfHLLi+Fpoe9e8udulFcrDBGeJaLsaL/JijmSb5LFGA7M/E04Eb3hWnOsQ14=,iv:np+UlEK/IdSRcDJ6rosm7qRR2vshl733BE7EWnqoAhw=,tag:/P9OC9TKGy3WTmsE1H32vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
