apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:QgwsQUnBLEPSggV7jqc=,iv:ZNC0QXZo1AjEhi+M9sawOfQMVm6SNyWpuXod9EKh5YA=,tag:NRyXYovqQuWw9wIFBAT5bw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcDNQVmEyUDQ2Q3VZa0lu
        MGc1K1ZTeW5DaUltakVJZ2F3MFRsWWdJVjN3CmgrYTlRUWFLRkhkTVRQR2J6a1g3
        VjNSczl0cXlIUjdSSkwxczZUQVNOWncKLS0tIHh2anNIdjZvZ0FUYVlRN0Q5YTEx
        T0dnUmJkM01OV09kOGRKQXhJZ0IwMmcKiwwunbircqj4C6vL3ppTEkPzs54Avwuj
        bixfSwDpaCscnYPkgDGqrPHF3FSD6wHG1QFduYHecgGmi1WTANh0Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:QWnz0Y3IHhTr/6eOW4q2ugm4RsMvyhCsvS+GVSQY/4ruWVIQJyKyPg8bRKD2d3KkCnSzmzbJOcZStXm0k9hftE9qL+jxL4E1uOj+gpPVSbqPY508ReyVCMoOzfUOqw26aMPzLJ9LHgc84S0GCgh/cn3mnWfzOWwKmZjJuCfSWDI=,iv:lTWYqXmppCFuE89J3rMwqrw1x88jnELN79ZnInB6LRU=,tag:6I9xY81rXkAY997gfnvumw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
