apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:WWyDxUU8Z1mb6uPBboo=,iv:ciR2qCkt2h/kaoZF2y2sjCzl1l9ZavzjS0teCOO0a8Q=,tag:OHvvg8v4UZm2A0BVN1zQCA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVkpYTERua2luVVhBb0Zo
        cWx1QnkvTGl0RXlZMkU5NVBFSm9EeVJMT2dVCkwwK2VodHlxMzcrU2txWjBLejg5
        bTZ0RnNDeTRWVHA2eWc4b3A1bHhsblkKLS0tIG53enpRRmZEUUFqbkZCaS9HV1JR
        Y1NQYjNKT2ZEQ2d1TC9CZFRBOVhtencKWzCT1oUXt/v6B+2q/3UO4CU8bEyy9MvL
        fArxJfs+ZAOQs5qq/UEj++LludppaUi41CQNSMM2mYHT7WLSLMPtAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:d41WmOjbiNJoL6Aqe2HdKTyMSN/9hPXGXYocMQckrcqi8g0sY2KeP+++yHTbAroR8AuFxCREvMdAwrdDMiH0adqqv+T2QAovyMB3Do4zAjyyomNUYZgVX9UfsZV6igu1q1Nr8F+GuBOrORcWc4jk54mb/m0g1fssf3uuNoPPs8s=,iv:cjYrhTPOKLoH2Rg2fFAS32bhKryNaLOEaauUTcXXIF4=,tag:BP0RcPHb0AwP+wPuPL/9FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
