apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mnVrh6AxWCKPI11j6Lc=,iv:KcQX0vwUS2SNeJC79/UZwiPkPzJd4HeGI3uLydvTYig=,tag:U38ozH3mpsDTjgqPtY20xQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSGxzYnYvUDVyWXVPaWFU
        ekZoQVRJajFFTzZMaFBjTS9wSE50eGlXakdnCk4rNVZsejhWMU5MeThrTDVnOVRU
        MjZjQnpxZVhzY0VOdHFpcEZmb3NiRzgKLS0tIERlWU9zNlRDSmQ4eWpaRVE4bit3
        NEFVbkt0ZFJPZ3lNL25ZZ09CSGV4amMKnEKC9+q12Hr427y9jGC/wpKGsGqPkKJ/
        irdWN50IsZdoXZPbLLt11yt6CbBLE6AjkZNpKC64AzJZRgPHzIS9jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:eSbXYIKm0tsnyBeL1TBhVHGSoEv1uoIvScHJCo7DjijgC9XQ2oJ01MZWyaWyIT1b1FDJlTd0uNsOW4m8Cs04d+IeRYcXcpRqz8ltQ3k913VJCi1nZUazDHGpaff8m42eTLwsFH4m04bMxD7MY6kUsReQnBf0kSSp8hrMetu8kv8=,iv:acwMZNcykS584Ow5eB2gK/DCNQHjqWNjDdRTgmtpv+M=,tag:g6TWUfZacIDqB5ixFC1cEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
