apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PkU4JRi3X/2rhvTY4bE=,iv:SlxOVEb3TTbIVH2j0Ac2K/EywrNf1JPwSEcXcuJzW58=,tag:a+t6cV7z+A5q6M0xTrqgbA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWmYzQUI3Y1VSR3VUdmJU
        MWhOUG91cW5QNE82SWgxVWorTFJHTlBvRlJBCm8zejlJMWlOMXpIbE4xWU5yc1Ur
        WWg0MTVRT0k5ZHVEMythUFZuSzh6RzgKLS0tIHBZR2s2Q1hvMVdjZGh2Q05XeUhX
        c1ljanBhR2xlUnBIbFIzY0hCNHBaUFUKrmlTRdjxilCh3r00MoMR+cICA776bQh5
        ID1FDqSFaSQy3UYVkXvNuJMK0neQfJK8LLSLAD+xEsIXj23QX8aG6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:w5GuucutMdDtc2ynHMjdlInfsJ+CmjumswYwSpRcy+Y7WGSVXHA7/ifRdopQhHkrJbs0TZyG73+yo/3tVQub/rV1i29u/vUdFdNrZQ6G0EMM8fFFvWE53PzV7Dl8dKYrfKeUQGQX+88QHvi65dRsEGaXSH1eGTxXzhWVDbWZDpo=,iv:4D24Iawh8+/v4gwmJQwTs4pzK3tJUi4cPKm4Nq6/XvA=,tag:olb7SQlW/TnEz215nbjXqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
