apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:WoO6aEz+sU2fWT/+/FU=,iv:LANmf6kmvK/VFv4au6FQ6z3Bh+uw/mk4KpdZsLgD99Q=,tag:N2OTOf8gh9Jomagkw3EPew==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETVh5M0xxNmg2M2dSSm5T
        S2h6R21hNHgzNEtIS1JzRTlDTVlvWGxydVJZCmc2aVZSeUJzcnJiWDl2Znd2bE9o
        UExlejhLeHp5NUtUdk41OWRvUkM4Z1UKLS0tIDNtVnowRWpVYVY4MGw1Ky92RE1k
        MjhRSEZNeElqMjlwK1dUbm1vT3ZPcnMKAozPXdlFVIDA2R9MJGcptoIEGOXRjVQl
        1SsH4eNMlTQT2Ohy2BUNoBbazBU7EpKgRjkPQ9UVoWBUrrqGJnDbCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:YPk36y4bpbEAvjaNn99Hbf6bYfQg/O3i5Xew6vbbgc3KUTEcYsf9On28Fs+FI7qN2irIs3fyQBeT2yRxsyhTvAG2McVG/SKvu2ZXl2HWbcHnHVPdL5EsjNZ6+XH5ilBKQc25ZU374wqkiegQdEibyMSv4A4iuRWFaVnCpVH9qi4=,iv:STVnWD8Go8IP9aLmApMZeaHKyGmQEc5mRHc+A87PADA=,tag:g/ygBkLVFAN2LWngmv5Gpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
