apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jm0aAFmQYj/TPBDR1nc=,iv:J+fkOACm8jeE45BtmZ3v0QePlw2MQh1MqzAv4p9B2fQ=,tag:KIZIKIl6JfQGQPjoQcgArA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ukk5MGdiY3JCZjY4Ry9h
        azMwcUNYY2Jvb0YzR0pZVHBHYWdrNHJWZjBZCk41WVN4K0UxUDkzRzVEaDBqSXVL
        c2xpcmhjeTJOdVM4cUhVQ2haYW9xKzQKLS0tIEZ1bWZPR3M0Y2dkMy9TSXVHenNZ
        aG1VbkMwNVBqWElFWGFmSTJqdXhucm8K6hOXZHttsar0U/rk+VfxSszluX1CpEVQ
        8VdILTOmp5cKpfh+8Fj58WW4Yeqfu0y45g3/K3f7Aw7swGFRH6Vlsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:GB26RjB1R3zKsKx4oC1oUOk4rv7wrnb9v1jbRaxkRnwnqPKApft9PQuQAuESq6kUa+IpU0WA8N6+3t2WOR3yQ8Pn38nolqVu5YoUhdINMO0OROhpYhVA2nZum+WOKLJIrpQeuwNfhoJVlRLKID9M1YGf+l8XE/cOqDAKS6K/Irw=,iv:ALdNxpAoW/zsNamsKdvPy7WIbz6C3mai4gg6A0Ve6SA=,tag:YhLPBDEtNvOUsqEFPpzWTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
