apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UqP5GlZkfpBsETAdHuE=,iv:pxTpEikHm4/n/B5rWp7EwHq3sd/MMD9yrkMZ++CGXOM=,tag:dqlLB9mXVlS38h7EohGweA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdk1sQUdvUG1kSFVCdklo
        azg5akRDQnJKemlmYzNueWRLZXduSVd6VTJjCmQ0Q3lxZG1TSEZhbmQ5OGtiVUtH
        eW9PaUxZTnl5UmNOYVo4YVMyMXNDbDAKLS0tIDRUenl4aFlCbzBNUEp4a3FzOVZD
        clIvblVHU3N4ZmdqRmJGTnc4UzNZQW8K/nliuetH+L+kq1OthS52EEqPqdLhEUpv
        2uZoINTgH1JRgIjjNJNvZ1fKU/g3TBI+u7YQA3YBcB+u6v40AIwfQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:55Z"
  mac: ENC[AES256_GCM,data:vL+Sd2LyVLhpU+0LKg3MWrq0wAbaq9J3qRmc+rgderXc1kw7TUyolJuOrIjgTMCL/V8MtRJSGXzej5tLjLJSxPAKvKlCPhBtuH+OoR/AxN1etaqyRdEwladuw1XRxK+Z5unGLhVRC03nd9SPiW8XHO2a7IhQgIsHeBLp3A58dBE=,iv:6zBdRrjaSeL9B1oHW6/cLzpAfDd4PaetLXNy3gxdBO8=,tag:bXY/RgnRfsWiiTc/LId3ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
