apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:89A7rlwex0f+obIKH7s=,iv:XisgbAOP5TQi4ORGnJS/KtYDVctaRFa+zuGZ5k4fR0k=,tag:j3BfujRBvani1k25Od/gsw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T25HNDVFQlFISGtsNUNk
        emtEUzhXYkRjSU5xVHlvM2lnQk00SWhUWjNrCjROaDdXaGxRdTl6dUMvN09zMmZN
        WXp5cCs1Y254T0RGWlVkMUdsemp4L2MKLS0tIFNSRGQ2YmovYkJGZ3JKMEc1SURj
        dHRZbTBDV1FuNTM1MzA5dUlIanRqUDAKBkaX4j7Wu7R900HMfhrA8x8cKd4z9T3O
        H8dCo9V4rFRC+yiRjf4F6jJO4mZgkYZck5296vfI9Jmyw03qrEWUyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:T8s1wXm3kNdrgxssXo53pqJ6T4Naa19QZ3c5jxN2qp5XDRsMJLzkDu1mHG+ZVIj/oMQQHCaJeuBJT5ZK9SKEZ9U+vBurNN02XrQ4cV//LzSIAdm2nUdkA+9inS+LMssVRDYqoyDRqfhsakUR74ODUupfdjKAxLa9byYbOMHqGQI=,iv:XEjXqfZAkoxMrvSxyRA4SRmxliJ5ja/5CvYagIVY8jU=,tag:eOm3MOWfWWd3aqeQNmzooA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
