apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:JYd8dZKvu+TbwgCriXU=,iv:+B0hOebcT/v7w1FNAEqh3F5CMK6+RABCDGYz3q6ukr4=,tag:gs0e4vG3SVdsA2LuKP/j9w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQmFHcWF3YTFieHFJUGxP
        OWcxYTVmMitqaWxlcFQvQmdkN3Fnd1lZNEZNClZ4SEMxR1pFN0t6VHhrV3BzWXRi
        MFd6Y0pGa1JVcjFvOXZUd2d4RDIxQmcKLS0tIDlETmRCSUpuaitYK0d3WWgvM2dN
        Ukt4d2hoYVEzckRnbVVvbWE3b01meEEKxl7aSchoSacotJAkDwUTn2QPLzuNCcOV
        fjHzMEufA1Fp2WwMhmP1Oeu1wWrB/SuvT6UuCkcmT+pd885mXrGjDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:ckE+2hRi0Y3BTyAxcBrGnnAPzcIa+B6RPSe18L6voAsAt45wrSs0xkEQGoZFAz0DUoYwL81cLtoEDA8vEwExbdSHuk61o8IfkKXo0NYJI7ML/bhN4axhkZ7VVOOCS63D6bWHxpcscv0D8g6/MABlQGV9tVeatv8YNdIlJKixByg=,iv:Bl70menM46MVWbbQKymS/BC0v64XKj1N+dEtBV7rS3k=,tag:m9AgSI9U0Bb8WfuZeuMEcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
