apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bTiR+hdf0Sd/csMzjnA=,iv:9es/DKqX5Japa2qimCLJfgGu2u8boXYSHRk0UUJ+rJw=,tag:qUUKsGs0SX1ZlWZ8Df6WpA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMzcrdlNlN2krYXhXbHZV
        R2V5b0R4QTVtZVA4VGxXSGNsUFRtcXBvTkNjClZhWXJURVg3djVzZVFxZUI1SHll
        bDRFQ3JPZHVhZWdRWWV0bU5QdHhyUHcKLS0tIEpweXdJOTNtTWNGZml2cDlCU1FC
        QXNubUNFVmJtbXZ3MkZYTmV5eXdtaDgKTBPMy4GpV98JiNyAw8jhxBVKLAUKIL3A
        zBBBQF9X72gzf1cHhZhrnaqDUeQKZD4zPDLIz1tpXvIZK4iBJ7N9qA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:Xb2W6h7EA4xmgBqwCvD15C6oi2cWn0pC+z2AulUeL2WWmLF+JpEYpVpH6wzDDIzEvqjMZqnJ2s+gQ7p28N+S+wLx5S02uQTr3NksQdk5fGAj8949wryV7h+coljuMdw8vtRmFHgLa6TBzVYn8BnNG/n8LCjf2YEHPZ0DXtB4iIM=,iv:d7HcHASUT71TgVEmBkqwaaFTnvwKr12W5QM12s1w2V4=,tag:p1lY5WoyUMu81bHgF6Ef6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
