apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PegbRV9EEyt7jyvO3Qw=,iv:XtqcSfUtRka7ioHmqBzeO/z2P3UhXT6Vub0sKxkq8GE=,tag:iTXYdYwXwD17KnHRwZTZeg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVk15dkxhZVBCN3pKUnZt
        b0hhODZ6SlB4UW1HWEV5bmFVV0JPVFc0ZGdNClVoWHVFKzJZNG0rUmE4K2NaWUho
        QlFyVzEvSHZUaU5GRGJDeVdubmlLM2cKLS0tIDFubmIwS0Y5MUQ4N0F3bU1wZ2NL
        cy9PVFVzek9hc1ZjQnhkYUMxMEx5eVkKPC3YxYbpAVc3evcfImsdPGqZ1HgQh9j9
        D5sQicfZN7X0FmBJ9CutfWefa5dtqqTxnYyu3M53g/16JatBC0J01A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:6i5EnRX1vNh3IO/sSLySoVeK97DKyInIbT+V0MXtaVe8mH8aNR6LgNG1Pok6HsSHrkjZG+UXu2Ch5HMowVIUvN1mCZ4QiwQ04Udy2CfqtCE5xQi1l+T9vBUryPu5d+UJXATUCFcNTWKof5vq/OVfzHpgq7cwVwtrQJSLpeJ+unk=,iv:HuMtkTmvS2Nj4lUX31luU5wGm3wx1v7EYfA4khGO3G0=,tag:7Favh6SLJCUs6moPZKDuTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
