apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+fQ1MkTk06bk8ELInJJ1mjJujST2hH1XDubeW355054=,iv:CORdLrfXuDDdNhHUxSrdR8z/xHW8tIU5zjOBpGtUUvU=,tag:8REjq97/12BeSifL0jhlWQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMDVSaHVhaEZibVdTZmVs
        a2xrSmt5ZzZQNlBDR2JLRDgxbXJPRWhRR2tFCk95a2R3T25rMk5hZU9BQXNPWFdu
        cnVHc2k2Qzk5K0xQS3VENlVnRzRzRVkKLS0tIHJQNXZRcFRQRTNxVUI2WXBtNHlk
        UCt4M0k0TytESjVDNTZLdVFjY0FUNFkKEtUePG3m6D+o02KSOwFJ3RYDCV9RWJ/X
        4KAD0Ghmv7+OQYT4gEAn3EApXERRxohoRlZjXwd19b/DGnG6mczSQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:mEtJKvMpGKtxsZYDVWe/PJyNk5Qtu3XeBMUsYJyjGKUwBv20L0On3MpB8eW12G/WzwhI0Vh08nLE3oCHEVubLpzAjUxZQn5ez6XpLSueIhw196w+3Cki/b1kv455+s3YSsKnsRy2i1U/XTscLI1ZwEviXmzvLsxrmeeupp+C7Ao=,iv:5DDjKk1t/Y9Bxx7JG8QKh22S4uaMQ7tI1cbRsGUwMng=,tag:/NCTs/QgFKOK/Vz+mO4B4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
