apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nBYRYZFjLDWehdBX846Z1ubIJPduNSAeBRjkrWqH5uo=,iv:eD7+GYEt559gZe+uR7rr4h9KWW5Y1GXpVCu2muY+hJ4=,tag:Wpcv27f3luyq73Izb9qLdg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aHFWNmoyK2dsdTJuQXJZ
        Wm1WWHEwdjZuNWNUQzVnMW1PYTZDQjJaSkR3Cm5pT3BxWXB6UGxQUHRieWJ0QnRH
        QzV4UXpyUU9SYTB3Qk9QSzVUa1ZaSU0KLS0tICsxdUZYUWRkaGVydWdPY003Q1JM
        MGFaSUpUTjdERjBhS29mSkdSZ3VqRlUKraa6RroEXBbklwZsLSmtEqbyfEetGMxp
        O/GledZcepQ3R4TWHGjEshMLUP375cUmuacTT+BfVTvr1OuqLQer4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:A6JH+eO96i06wItkODCEGds2vhYqDkri7ZEn0NE+Kp7EPm4+iKwNIXSORbUnr6Bl77g0J9pq3QuHDCciocmmPhGf4Esyf/XEuZV5O5mqHuJ/SnVKypLZ8mpN1YFYspjfqtCi/pDoOiD0McXd7EW9pJGnzTkE/0c4SbCpclZD9+U=,iv:CxNtYuBlfYBAEd+sr9RQEIjbrERCoVOUS/hV9jg4KRo=,tag:W7ZNskqF4WYxPjMR9yfwfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
