apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uPTjMPNXf+M0/sZ0QqlWOl+p+CNeXpwUyR009yHv2sU=,iv:fuEC1NHYWHbhuwk7joKfMyGBm+cfw2t6aBMswWxx1JM=,tag:Ywm3bmUH+doiOkBSzz2VQg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITkExcDg1VVV4NDRXNk16
        eVl5SDZuZ0JwM3FZanBtSkNNcFFmbVQrTmxBCkMxd1RDdDByQTlWcVVUOHpiR2ds
        cy8ycXc1L3hqTk9pd0pvZlJqZHg3UGsKLS0tIGVka2I0NTgwcXVSdGZ4Y0Vvc3d3
        VVRVelZSVG85dG15RkF0S09XQ09RcVUKEiUl8FchJ0zZnb42836AqO7ygIW3rCqk
        YSPi8JO5wHTNygpoPHh2jWanrvzVYoseNbtwBsrSFFPTX9sGzTqBfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:6Ym7wgipv90KYBG7oFcNkbb3t4Vgdtr2s12sLkXerkUNRhQbsDLbcXnZe0iKqu+znHT1p3cPNq7UAt0DKGpYVop/NCus8//o1OYbL21LWkSHC6pcwlp5VXO/rmeRwGHxG50SvTGcuk8KoDV9YYiLijmNcmwzcS2U2E93/4Q5+SM=,iv:n5IXLxgNfQ+N69ERzz0x2CVJXARKeZAAYBk+/oSIxbo=,tag:yrN/x5c1TLo1lMbRb+uKMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
