apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OoyGRmtrgMxlW3hesyOjZUoF0veW3loFBEeduxlWe5k=,iv:vLJlB5vFPcbBBkIvK74ngsma3m6yuGVhPOlK3F5Zhfw=,tag:88mpJshogf3+HOFnlA4PCA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QisyR1ErWERuVmg4ZjJu
        T3lwaHFtQmFWNkZwdmJhOWllM0pobVY0UVVJCjJ2OGFBVW5lLzFPMThNTWkydlVO
        ckFLeDNCMDU5K3dnSVVLa3A4Wjh2RVUKLS0tIFRZR0dFYUxTOVlpNlhZbXBpdUNI
        Vk42eWNyZmNXUitpWFVVS1hMYzNzNG8KrQEJSDtaW6WFrAbjQbOeztPExpnbmtUw
        Qm80k88S+fVLkT3I/wwk9ePnePMLoM2HQ34IIyMqTNOFyRfjx3+sog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:eKKvdbyiZJlPIt3ipqj23QGf4qO7CT2R5atK1AagI1KzpTmI51liUfP1k0xWb8n+aFlzsJ28Ho+owFZr/trKydnAmstHyxhQSnf7o+ntG4/oESmryxriAWkrkjJyaKsGNvMJnPfxIN7sLek0wSBRL8Ks1Apd4pjEPp23Ry5Js/s=,iv:JJvVd/xdA77abVanvR2QVQfbbj+tngPuApcTEEOiUJ0=,tag:1CKvvyWnHEeWY3Z9kddhZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
