apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QqZycADg/bphOvkW5aC0aRurjriimF0tVw8u2mIHWFg=,iv:WWq5UNRmk+haKBimOPaP0FYr6kBFqvh2XMUSTLfrk6s=,tag:nUXduAAonWd72Jz+/YwPsA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR0k2WERLYit4Sjh0UVdY
        bkUwT1NaeDd3Tjl2TXExUkRscXlQamJoKzJnCnlNZDZlL0xrOTZlYmsvYmMyNTdn
        YllhbnRRaEFWWnVKV0NVM3grN1gzN0EKLS0tIDRHeUUvMnkvRFY0Z1NLYjVMa2po
        RXVMQWtIQ0VpRWM5RWdxU1BaNDJSN28K0bFOCz4wqTbKjuin9GTQ+3wKFl7C/4VU
        zdfvN+7GM0Q9fm1Jg5GQnN9HpxFadRN3s2doiVc0TVfz7kMnfTdwuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:+pcnxaKXHbE8NPhKuosnLavQjmqn2hXy7AstMWb6AK6Q/E4mpxyagC3Ai9xi1puxcoUBJ621O72ZcCDc8Fx0CFRvdarOU/pQVTkUIBxJeXKvJx/6ETx/ZcqhP2bLw5S+yIg3Sc1nYu89y6rW5E0HSRuY8PcejI7JujCCf+l0NZs=,iv:OIk1LUODTlE1TpHqvaaAPpqGPb80HZirtT0pKTug5SE=,tag:vIGyCXcphvyrf79LQp3UFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
