apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GkobJ1NZ6SpvmqydIAgZCLwvV9CNj5jPB5A+aivG9Dk=,iv:yHTOOPCmewH8h85gTtnsRzbPf3RNsbfSlhjjshY7NHc=,tag:cfx7vTvJaqj2sAEvAJrmyA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNStucUhOMFdxL0tDd0F0
        VVZ2OHNGSjQ5Rk53QTkraFpIYjZuVUpVZ3lrCmNKbDEzOHlZRlRWZ212dFZPWDB6
        R2Vyd2RzMXROU0NmQ1ZoMXBRdVpCSDAKLS0tIDhQMjFJT3dWMFZTQWlNaSsvTEVz
        WGJyTnlnSVp1RFBzdERDUlUzV2RUaGcKtnsOxdFtwPYLBe2bDl6WZqJ2vM09ezw2
        CXknnUx2Ug8gAxxwGKBJkDShilibdaaq26+sR4l/6g91F1EqfmZSNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:3G5wHeqqWZ9cYbVnip1uldZauWrJEG2B/6UAbxTRTZ//7SE8hIqoG0TxZn9NFew1ZsiDP/spisNnoN1kzUQxkPetadvd+RNzyUCgMl09VIEYQ4V1Rkt4rUWJAH42ZgxCrgUAL7gKWxxDhZ7+NDjvOVygEImkYdvXq/SC5qly7L8=,iv:21uxibjy82tMtm06IK7om1ykA9p2ct5XSmK0eVp7NAE=,tag:0oQCuH6LuZ7iMLywwEWuNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
