apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jF3ll1BuXx8fYPMjrxoA3+Im/Ihjvxb123DhPHwjhpc=,iv:YBDMo3bNZH9T0dm/DMbQ+6FOdmiA1js2Z3N1/i7HtSI=,tag:DoKy7YwNFMvolsS0YO4m9g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSEVmR2xYdlREbkVuejZD
        UE9IZVpmWGZiOXVoTlh1RnRYd1g0cmxqV1ZFCkk2SUNBbWNDcUk2eE92VmJlK2xv
        R3NKMkh6VjMyQjB5RjRkSHZ0d0RUTU0KLS0tIGVJOThadHRyaTVPV0JUSUliUE9m
        TnF2QlU4ZGN3WTFQdEVLM3AvOFJFUFUKz1t7Cff/q5QX6tVKNUC6H+qYWuZ/+i29
        lB+UdXtVdqLI8mfRLLMGUDKwERfxtUAcICN3QFwsFocazrzB1z8KLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:W/Q49H6SUmpqLfI0NWILICJ/uM+XLleWw48H3hElKp6v6fAn4QMRQxNVgJpG2Kvf+sisXeNinmTWH2E4NkJpW6dE6dXU67w36ZnNYFzX/M2aKEq71Luod8fvK4DMzEsJeSJddEaj0YbIGx/htlysdJYZtGnM2VQ+i+r1/PNES0E=,iv:Nl2Qn975LMw7s0SwTwv5AcDehuZVkzQsUAJpld4o/YU=,tag:KsM3sjsgeTXOb40xznpc6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
