apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Y4BWsjbjo+L227Kjb6vwAc+OyJGRli3j2KdiazJM/IU=,iv:PCFO/fWmzj+5nWqH2eOtQgrd7kWjsR8+D/5S1jL59EM=,tag:exM/13RCZWMKUmvvMKszzg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TE5JcC9rMVh1VUo0VWhk
        dUdEWEluMjhmRDdHS0tIVXhrT2llRU9EZmt3CnhpaGZuUFg0bzN1TkJ2cEVBbHZq
        M0JrS0h6cFY5QzBLOE94ODNXUktsTG8KLS0tIFRNNkJxamRyZ0RKcXk1ZmtSeExR
        VWlDWVZncjVaZklSMkNFV2FCR0I0ZXMKCAFl4lYcG9FYGUzPhvDeLfHgV1YMXSG7
        dwN2T6BTLQeE+1wnlbbe32U1S3bK7WSQyz7EP9882Ka24rtl7hNy6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:k2CETSEHgTDngk6HWFVSkTx/63ttr+fXfPeDHE1hzRXiEeVkyKz2AnZe28HutSGTL4LZuGYAIph45k0a4Vaszkp5GmKXep9UUnCvujz6oOLAXPetgRRwL2DaFmCPoJwZcPdRo4x/lq10PkWG9FNgf125OYYrtIr30MIGEPywecg=,iv:4Hz2nY3i9QLzFl/JDOACVyhdGRhCmRpf0G7x9C0Yb8w=,tag:BwSQML/T0PXHpUbPjS7kjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
