apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:H207aoq78NdE6uVxfKwPthWLjRDUY/sxMF2+9VIFMZY=,iv:oqvG03HBvY7LftOtz5qJjEtK2l52wldLMfkaOlcWNls=,tag:ODXNG97gl72RLq14+SBNxQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdzB5S0xab1Rvc3R2U2V1
        eklxZDVTczFaeW42RHE0VGhMRVpVbkw1cHp3Cjc5NFREbUJuYk1yeUFVZTE0c3dv
        ZnpMcEYzNm5YSzY0YkcxTFhvV1hISTgKLS0tIEs0d2NYQjh2R2F5aTV3Q29JaXZK
        Qk5pdVhkaXB1Z3lkdUZKYlA2VmZhWjQKshs952hA3uhRVLaoHUY749z4Ulcb+JV+
        zH56N2k5VqUhHwP73DEDgv2ar9E09mfGxRWxia8PuG/F2XglM/4I4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:giLsK+Tkm9XVRjNPoWRiWsQ81TQaCZbH0G079fHCfJ57hK+VUNIbgyEieldXCgLBTvFWrIXRcLcLTD/9qSLgSFg4el82tJxGZ3VyA6J18fwOrvOrshkpCnMvQyDhM/7YLUltzUN61TqnI/sS9WuRKJaHAjBy4nrM2zjDV0tguoo=,iv:ygroOguNNoKpLy1WXokEU98aYE+03kNOU8tXV8V/ZoE=,tag:v1J1LnwhartGPxjY1GFVoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
