apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:4W3zNw0I9+SVPJE2mmAirV8ni40Ch5wVGP5MH8r0cR4=,iv:n23W3S0EM4c9r4EH6kppPglhxCyLXA3TJlxMBt4xJCM=,tag:WO+m8i79/jk5E+TjsvAucA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYUVPTU4vckF1V09jK1RW
        WkdsUUVpazQ3aWhOQm9aNFN4YnRnakc2cjFnCllKNlk3NXRmU3pSR0lQdG1qTXE4
        V0h2dzljajFEZHFhRGIrR1NqeDBwR1kKLS0tIEpGUzI0Rnl4QmhkLzZTaTNxaURQ
        OVlWNlNXcmdQSnJYZG5MUXJRMFo4Y1EKMTrZJ//SeEe26MxPftZZJt7Cy4SAKxqc
        choxmSp59nKMcmf/CwvJbxEgj/5Gw/Z85FifJ8chWIgLonPYEpx9+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:46Z"
  mac: ENC[AES256_GCM,data:IsfcQVQEBEVJecDAYhcZE4DNibv4hcDKnwefEJx1oGoDN9W91KlGJcDI6OUH0tMu3I0zufgfAwZty6n/A3RafMPcLtUcIpL/mi5s+QHKaG0W4BwushFAhNPU4Wb8dvrSjJPDkwo97uJ3NZlhTZAoWWdEOwzYjyyY3NysgsXeHJU=,iv:jQkwdGcs8OW5hnv+NlFYAxoKya7m9Desu6R9oXbbaQw=,tag:Gy8PMuKphY855z5y7/Fbww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
