apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:y2EhcpbRo7P+gEWw/m70dqH+ihhc5U8BeoGQwdw3STs=,iv:6410LPL7Kq4yJj8rf+/DCJU5Ws5Y9BAypijdEsy81Rg=,tag:G0XfzJ5BDytQFw2Cm3Xwfw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcHd2VVI4bFd1UXdPZ3lt
        UEtYMHYxaWQyWDhRZHhUVnROMFV3dDlGVmpJClNqUmxGRTFaWEE3T003UWtLNnox
        eDMzZy9mVHNiSTJMOG44c3EzV3VrUUUKLS0tIGx2engwRGI3a3JocWQvNGtiUlJz
        Z0JXckhhWldob2ZoN0RIUVlnOTVpcjgK8AWXSlqcKTHM4O1VAdDSqwal38bZH4Zt
        o9S1LQXMCM4Cdrfv+GJcKIWgh8mivSI+GQIPWWWB7+7BSnTD3AabBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:L5w8C9bTdNVa/QXXXsLnTfb02tF37guSiKgm/gik7CjCpwOzxPmesicY1EWggdhW3GbgLb5IszXmVlmwzHuVrxtedDyU4sJLtI3okyuUc0zVylqvvlMkrH73boUsnsRlwjoTEjJ4UDrowDMMv53P0Ch0Nx2qs6uw4/EKwRs+FSw=,iv:hyDCodsepsoiJwq8g+R9tDY6QwQfK+k4xBkXrXJx4iw=,tag:XsRhXkgY/W3RBWC4KENB2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
