apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:eB3ZxR86jbManhsUNHhGRD5Aw8i8nms7AtkoThRie/U=,iv:k/4FQDC6Zq/TtcKZlzv75W72KdIlzft55s01//OcCH8=,tag:Ix0GCfdDIKPMtJZJ1aYsDg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUU8yeWJhNUJqOUxOck9u
        QzdqU1h2bVdsdWR3cWE3ZHg3ZWY4cWpDRmtnCndZbXV0WTBzZE1CKzIvdWZDQTZq
        UEJ0RlNydjkzczBkbm9RRHZSeUZhS2cKLS0tIDg0dEQ5SVFDWmJPT3ZOdVZrWlhC
        emVHd2VqRGtkRWVrNlRvcktqQkJhTlEKvFsPGwnCJyvtklrRNbnaUSRWeqIrluGo
        0N0r2bwiQi3wAazWNE4DtXcJMTztYua5xYrXxGWaB2t4I18O16d5ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:C+64X401jkot8I401hZ0Aj+mQdNgeBgxLCeFVcG/L7aglnOAX0hPHAYY6oJ1y9vQf4Rh+uJLEdKIkSZHODjhtYVGVw4Afl5l/szJ8cSvcWap/Pxh2kQ/P6oW4ckD9ahO587uMRSDGRCSnM+8MpGhwJ2dmfFBkeKVquKUJblEaz0=,iv:gDRa0U1nCTh2dI/3lbQKF/v15YI1ecT1hA0a/vIFOLM=,tag:ObOXwKKJaFbw/FeHNaMmSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
