apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DF+PfcjV1PvKSqQGy5v8ODkfQR/I4r3WsHSPp1QDpxE=,iv:1mkj2LMH0duY4sDSfo0QvMb1d2a8BpVug3XsuiqlRKQ=,tag:dvkSL5omh17bSTvSrroqpw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQloxY09QcVBKNThpSXRh
        L1U0Tkp1bDlrS1FQMi8xbVorRGFIM1ZWZ2dJCjRZUE81aStvb01SV3FhT2dGd3Zm
        VkpJNmpHeEEvaGVyWVNqNUVhdXVGWWcKLS0tIEZXZWpSVVJBK1NOYmNnRXl6R29r
        KzZxd256UUxtakVFYlpCaWVHZ0VpVkUKty502AhkPaCOIcSnLjKHu2uBRz76u8iL
        HFPL9g5FB5g02nXSxIZOqMQhi5NQSmvO/t9zgyuSON5HpRf+WC0Xeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:wdvZBCFlHLOH0EYmqJCrKYKbZiOoqqw/lxKONSIyV0ZIrIMhUkU20BapLRlTeL0jYRFCZmbiXfBbcUquKVDVXtfFgKWoel5JAKS5vXLDetW2C2WmXt8m9jf8ZvTMY2Bso4T/SpPZFSlN8aIPkijs1Ay5nvuZPK2qd434MaxA+w4=,iv:9JbDj4RfQNOfM6qbFK+r02vogCfmYhTd2PD47o/S8Ks=,tag:NkfN6IgU7dTKj9is64WupQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
