apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ARiQd0mSTmFEH9O2zgwAAUdbeomLb6GbGC5tXFjArzs=,iv:MDcyI13WEiccLQtMRIPzlhf2WzayfSNQS4AU/2chaks=,tag:z44g06o9P4od0mJHr+mlgA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbXE5MGpYOHMxRHcyTmZD
        WHovWkV4WE5uNDJMQWZNdW9XUmI4dmw3YnpJClU0dkxoZ0JMc1J3SjJpZjRkSDVo
        bm5kUlFWSWVYUWc5cWpqSVpJWitxZHMKLS0tIFBvRE9VcjRXUDk0KzVkRThIOGNx
        bWRwRGNJcVJtRDRTOFVFZHVrR0hQNlkKh0wlWv62hyRnefK1dhu2fMlPZruDAUmp
        +m/taJScEopDtTVPx8uxB9c7+E13K31LMePdkIKkd/53iB7VHupJXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:Nr7+4C9s7CDi2ABNmurfVs2VNp8LhMeFMjL02r7x5cSE5B3bnIN9XR7nAVd3OGMyNU6wgbSS/EYwrZk2+bonT9hmArnxN0RqemL4/dZE0zc0ezLCyOphD9UL7ONoKtyf8NvgenKZSaBXgyt5qj0EGHewBRIV/Rd9VtGcONgpsmQ=,iv:oWe8zJq/VnzwExq+vf7eceJmrRHhYwj/0s8Mh9P7HLc=,tag:GOEn/lsP5SKcsPznSMdKhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
