apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:4/KXxSt/TJHVNox050Cf1Ox8MpC79Vn968caSCT1mTI=,iv:1jll5c1zYGGF0YTWBLFeNKn8jfzpAhNKFs8sgmbtdP8=,tag:cqpLrXgNF+M2sVyByrH3Dg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3blRmM3FRd3hzbnArMnlR
        QWI0OTFDNll1VHJaTzVaWWJ5L1RVQnQwVEY0CnYxalMveitNa3BtNFNteXdDcWo1
        dHBnd1ZMUmZlZlNXSS9WN21MT0pTYmMKLS0tIGFKUHNnRmFmYmU0ZXdlZWJNejlW
        RjlQdFgrZVBmZjZleENnZW8xbGRGSzQKzv+G5FgX8Lg4AYLEko3fbpvG1IvquHph
        YmXY8IYCMi+opCqcMyI/uwHp3s11CirWZkoS09pTSe+z87toe6zYjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:QMe0cf4fRQ1FLPpQeiO+sD1Ucz9QCUdZWZTHLnYV+fOM2jPFBPq+C2et/gXKzEmW5rD3fKwsHNVitqtfDKAZLxdlm0Yj1FtLkVGot3sxJyHfI7MSYqmWQaABwYcIKef/cjvIolI+WpFvISLZt88MPy0KutcNjCSKF/SEcoPyNXw=,iv:h/SAepwNO6e7AUMx8F2WZZ6MGfBkb52oHvZfEgbRVgs=,tag:LKfSPueE9EWt/10pJeGvvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
