apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vq8SPH1DeSOmUnrRqTc3QKNeH48IGeyhLCc81spYqFE=,iv:b8U8zO9D7dJzt/gp3F22Gvq6Um5UkOkJ6fGtG3zXY84=,tag:QdqW0rhxJ36isJYDY1Wr3Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTejY1OTkrZkFEY3FqOFBX
        c0crMTV4N2p6SjhXRG4xdXJweDZJY0hid0VNCk05OUd0Z3hSS1hadXRXTjdzd0h0
        SHlKNE5aOHhhZ28raW5GSnRPUFpXd1kKLS0tIG9aTmZvMkl1TTdBNkw1RE8yOXA4
        bGhBRjBzdzN3S3VRZmFvVlRFZUdjLzAK5iCeDM9bMsyelwdUDULeCVX0bwJWprk2
        WOT47cTIHqwpKDfv08Gni8vAU/gJgdqZzCXmTNAzevTEWfkJixKi0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:9np6IMTDLnz44XriK/gjRSoQVfSzyx77QYPhjJ9lJRmWdA8iZ33MSelRzg3o6TFaqlaZ9eG/bYdzZvAT8pswTGFLWdy+59SVWIAa9VK7rT9t+ALrpE06svhjUlku86U0BYfxi3StKSLgqR/0sNhemkPNrP1bT8ojlKegk5RSDxQ=,iv:jnIv9PCdWgcPm39coXsDeIS7EKYnK2T/tlsloyANoQc=,tag:qKlaYsPEMbOF2najpRmYSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
