apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vJ1nfuXiw62z44E2IjluRMfj5OVZHGy5UNh23nEoJTM=,iv:C4UCIJ1xHOa+McPCCcRpCkAQ+9r/+5cLPFPQ/itxT30=,tag:e32p0+qfimgRgFQ+yZpZiQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SEZyd3lZZ21hNUtadDBZ
        cjlnUjRMWDBwR0dzTENSVG41eUxTV1VxMUhJClJqekdOK3BvcXpmRURjU2xkeDZC
        Vm9YU1lleWV3Mmh6K1ZPUlJPTUd3VFkKLS0tIGhnSlpFdHhXUDNzSHNnb3RBYzN3
        NG9GMlhFbVZsK1lhQ3JNdHdIV1JXQUUKpIgI5YPiFA5G26QkPuOfUvX6nGWp0ZBy
        uhO07KTh51LrfJTgRwRMNbBLIoUblLiI8SwVYKjQ9eCxs3Zny/e9+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:58CLA0lP8a5YfcRyLohPniMv4MXKJsVduQ+1NNEspWB+KFBzImUMAGupfVrSh5FMuJUQSI5xMqreVDfGWkiedWXkMvCe3sKQjCpWuCCoMZjjxdFqHeXQA04sViP5LIa4YzYyMah/r2BBrYLQ+hdp1TDgxIdxEvq1GXVqJ+MBrcs=,iv:cFYgQpG2KsPd2DQ4t8ig3S3fChm5LxgvO7zkFmZ8k9o=,tag:MYOnbFZEYlVJs7HKNejX+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
