apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:erkq4+v/UdTOpVNAe+U8iKUUq6lMmCJf9SCHuIQi0z8=,iv:FPu2Oxc7W95HAdxgIAhzsyKJxwTJcvJpBa3WEqtx7fU=,tag:2WuOK0f9kpKy4Z0oUx+FJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTnVsaHdtNk1UZEE3bEs0
        N0hvTUovN1dKRkJRTW5PYUxnWnBnSmppR2pJCi9iYzgxZjhuNjJETFgweTY4WXJE
        VlprUVlsQVJsWEhRYmM2NVB3OVhJSWcKLS0tIDU2WERmNjBmRjd1Q25jRnlReXJE
        L0IrbENKUjEvTXFBbVZpVExMb1R5NFEK2+fMgVbyO52VkjjGVeRMflea5WXocP0L
        9Frf+RlwI5pCfa1S/JN0RXSyKli7fypuyVAer+1XWRWqWZz/Anmcxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:GXGlZ/dgrjSxUCqzkt+hlXhGgOpnJT3JadGo6E7gFwtH13O21ItyThzj+qyFSQLuptuiPd33W+L73WzSLtF81WWA+8rWiZtLxCy5UEnddtpdEFAc0pLB69fITMGkDHABFg8+HZpAvvtDSDj/iz0Wz8V8bjra6sD2c1TNfbCL7Pg=,iv:JU4whQqJLnYTeuTlg8OUvrIPn1twdK5AwD64i47Aads=,tag:gqYKFzhbmpaHdnuhDnKq5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
