apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xbue72WdsrQ54zBVgVE3mq1EViFayhTyf+0nwWuy708=,iv:5OQuEKQGLf1OCREW09j7UcI009x/Blp82QmtPub4oMA=,tag:uqQMkD4zmkp/naYKYD6Tew==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVlY3NXdSZ0ljZEx5MWMr
        SFFlTXpBN2pWQVVIbWtmT1owM25UbU51dlYwCmRTenE0dklZN3B2TC9oVTZPWnNZ
        VU9OM3ZDbWkvbE9CM1RyR3c2ZEIxWmsKLS0tIHBxTTRsdnQ2cktQWjkxN2czUjRW
        OTk3Y0RuTHUyK2FEMFpoSTZCbjFwS2MKILKRCU+T+PzW8Dlx9QbMBd4G0Az2xlSW
        F2G1wVTEMUC0nZqn/xMrbdIBI7yACfirLBrMaoI615HojGwqan1L6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:2lurig6NUpbxpmGk3DGrYspAtuU+aN00m1nXpUgbn0ZYH/c1+ENsbkbhCq4y3RJW4hg/Pt+OiEjj8r1joezmJxg4umfs/x/ygYxrwwEDLhJX8lBNTxWYMFUzih8ZW1E5ISUOKCF92Zh5/4vfFBKpY66lCJn5BSoRpWNS1eh/oaA=,iv:zedHOPyOIduLdGPk6h3rLA+yIaonBc0vbRBn+6UCjek=,tag:k4lB5JHx4VIjMFxp/oBmvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
