apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:o5BNhzWIUiqbi+QZ9LNuckgJGiG4TZHCukeaMXxxrvU=,iv:pP5hGztWOrywHyURxeR3YYc9oV9oNRUJMSwrDGQo/go=,tag:+20mByqtM4b+CU5jDoHUTg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWVVlNFlYWEpZUlRoRWtn
        THFyTGEra21NNW1UWDRrdmdwZHJyQXJVQndjCktZWTRhSWs0N2lGVzM2cEtwU1JU
        d2J4ZFZSQmh1d09BTDFDVzh0RUhHU1UKLS0tIHZuckRvNUlQcm1vdnRybHJoMUtt
        NVl6VWlxbEVucW1RRHltUGMvenljbzgKQDa8lCi1WiCpC/MjfEwUU+xLiy4MHfIx
        DbRCWTxi602jv9XlyP7QUIy2LG7VDKMyGs7nx/zS0FlpI4NxIO9liA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:dTCglHw7rd7D8Cl56mg+I6ze9LraCXHWNLSjCTmaXfc4SKNvmSFXTfpLJxxIui37RJv/5vS6ZOvDnW1nv0uVzW107NeLwRubbQuPGnQN22uSEZgNJPon2FHV+Sniy2P5xb5PMY770f6be2UkTKt2JsPqQ2e6s68NhQjOKG4LyFI=,iv:OzvhFp1kreS7WVi1jvd3ngUtk5/YKE+P5c/z1PuHm24=,tag:wI5f7Xs4vy1K2veuvC9S8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
