apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uk0CylBEF2QPrvIjYzyacUmI1BIPvS6wHhJcsm+CIFE=,iv:t+ndCUavBENUDQ8dnzltkkOrBYqGwSrj01gnxTCd/7k=,tag:IUIT8kDA7d810sIhIAaijw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFpXT1c5OHdBNDViU29D
        Y0ovYU9rMHE0Q1BpcVl4bmp6NzdFb3lxRzM4CkNpcDJIT2lpTjdGelpiSkpNSEpS
        SGpLU05DMUIxS2pJMGd5dFArdzQxdmMKLS0tIDBpd0p1Vlhkclhta0lVNHBpeFN6
        eWgrME9ScUhlMUFXbEZic3dSd1FBYzAKUItgQCUzDH+LnSjIdhVj1gUW2gSiQn4S
        aPN177gnz6wj688RKAe062nCu/aI7+952lJ5HaSK2P58Y+bLI8O9PA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:Z9cL+8ND4emojhAhw5Z7j5Mj4YDrJ5j1HjcTL7DV0xdpiA23F3pZWmzrh1kMbreayEtoKQT2SxXzrbWYok/hZroU9igCg2/CZD81qcyKN2iqJGNG4vIpLj+9/Tu0eNuMA/xjToBDnpRhYK5jBTYhqo9GXYZZeMd/GiR7u3iLVwc=,iv:YRbr9h1/d0yOTe97/CXNkYPbZ/HGcUUiN7nmRmGgQug=,tag:8ThYZ3GL729Xv/mQPzWvqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
