---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/databases/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres18-immich
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/databases/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases

---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-pgbackrest
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudnative-pg-pgbackrest
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: cert-manager
      namespace: cert-manager
  path: ./kubernetes/apps/databases/cloudnative-pg/pgbackrest
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

---
# # yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: plugin-barmen-cloud
# spec:
#   targetNamespace: databases
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: plugin-barmen-cloud
#   dependsOn:
#     - name: cloudnative-pg
#       namespace: databases
#     - name: cert-manager
#       namespace: cert-manager
#   path: ./kubernetes/apps/databases/cloudnative-pg/plugin-barmen-cloud
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m

