# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:tIMz9JQ++cyy80H4,iv:tbp3SwYe08+LGeWtO5zzyyFIB9UPXDS84aXlhXm0EB4=,tag:HCTq19UiO+k9zHyQJnc/9A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbnZUbFZtUkQ1cEYxSkcy
        T3pqK01BRUpHUjBaSjdrVENxZWg1Yyt0cFdJCjhKQzBDL0JYTDRkTzNCR1dscHBM
        aCtucUUzV1EvYTNNLzBMUW96NGNTWlEKLS0tIFVyZnhmWjlaMkVjR3dSUFl6bTJN
        L2dRcDZVWFRrUHE3RGFsc1NaYlRHM0EKwB95Jwqd2CEyYLNC40rPzGkg96T7ntHZ
        tjIig8gYOvy8vy0BjSpW51/uCjkr6wglW+AO8T3ARbYa4/WsSSGvCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:CcPHpszu9ewqCjSebU/rvTYoeg9pjOvjeMui7dwDvy5uzu4KYVjsv5qQSUxm7KKBnV5wWhDtvLdlnJNsCyfsIhOV825ZJRFwlYlvDdAeEDkHg9Yw/dpI3ORnYOJ6VH1Q0tlh3IwJyhymXox75VYGTW95sRdTLMz6QBcifAqqffU=,iv:nw/g6EUYCzD6zbPp2GBb17ujM1eBoeEfbw2SFwRbAOE=,tag:PV9kRwUYWVyILgqbYgUJ7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
