# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:DanhQl53JA7BElLi,iv:QOp/cRsHtsgw1SemQS60qn5HQgw9v37bG3Pq9f2Ymn4=,tag:Q8Ea/HvSaECfCixaAftVJw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdnlqclB6SUNHbjQyN20r
        RGNFdEZIMlJydXhNbExDdTNSNEFMNnlOY1UwCmM2ZklLdTZKVWh0Z1FDU3ZhWk1y
        UHM0Y2dmaFYwbWVJaHBTdktwNEdoZVUKLS0tIEsrVTJyZi9XeFYzUXpaYVRwWFV0
        UFY5UUx6MWFEbXFEU3hyWUh2Z3JrT00KNGafKGlqdHn42Tsscv699D0IrixLjZTi
        T0hD16G8kJ6dqLvNJnKh1J4wilW0d0rNCpcITNJ99hIE2s42Wgozvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:TCI3qlHAK3PJXoALCXP8LbcRAXoHE45JhLUXUqsph2UWkCG28/LEE49ZYF/aIGKdZPxAybSboXoZyT6Md0PmjZuSBPYZSSdL2y/ZLVSnTbUa7NOJgQz6pu57jGCKWCJTUMbYArhLyKlL7OGRe/DHaQLmB7ID/8/RRoI4/dYjIAg=,iv:9HdU4xm0t4u7trvXdEflisJ7Np9TWgbz4MHE266b7pM=,tag:9AZdk/L/v+Wl0BD4pNz3lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
