# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:21tNoKy8XIP2o1NL,iv:3wtlDmKCA4eLiLRhXokTZ3uUE/OXCpr/f72VDqUxBNc=,tag:coCr+k2UIa9v/VBeYifbKg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK09YMWtHTE9Ia0xXaWxt
        SjM5cVdzQTdKS0NveE53aWphV202TE1JRUF3CmlMV3B2ZzM4VUMxWUdGeGpESisr
        UHI1SFRneC9DbFlNVC9vdlRKYTl2QjQKLS0tIG9BdE5JbVpYSUJyblpxQVRGZjBQ
        MDZsTFRIM2s0N1ZmZkpQc2hTSllOMWcKdxc7ZWcnRe/BxVgAnO6MO73V9M9KaQMt
        GjyOaJkZi44XlRNkxTOxoenJI1A0FOxgwYHO27x/719KETmT8fToTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:fdnb8bgENCPUcT51ZmPZoV7kaaRF/AeCM73LjzmuNNb4ioQjBw7jsXOavQbz7+KeQaZocagh5Kwd38J7F2iHSEfPUsYMk3I192rNfV3h09ZwSEnbPCbOlMFokYs+nmXngDFH4tNBmtT0FUHrow9pGP6Blnr3chl/0NJuzZGyGh0=,iv:eM2N5tW2A5JT+I50Y8XsBItKCcVzqYDAjlBplys+HjY=,tag:enTqGf++grjeUkko9Oab6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
