# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:4jLDdahMqtq6yMPn,iv:o0/9MqiSieueNmiHR/iBXY7V/vCgwNdeXTTPC2mj7Ek=,tag:JrpOir0bt71Wt7xynS/pgA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUDkxTk1RUXJBNmZVaGNI
        c1VOZlZmVHljVWRibG9FSXpZcmFHZDRkWmpvCmVUK0V2M0lzWDVXTnk5SkgwRWh6
        dDkrcS93bTRnMlpXYkEwSWZOSy9MVVkKLS0tIHMrTlg3V0JOTG9OdW1nMzhBSnNZ
        eFhCZ2RwdjN4Nkl0Y2wyc1dzbzVVUE0KynLqNxusEaSCKozH5CF2Yj/KZecqxvKM
        JigsroXhROO8aU3Leae2Uh+h4ZIcTYdh0sVxn6DqZQcTeTm6o3oUrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:+u8Vv4e0lHxWClOtmHMISKWVsCAdiWYdE7RGG7Osh3rAeIzQTfwpX57xSPf/hvgqn7XAMX13i/3XAhUf0rWm/mrlW+6rG71tuX9QFDbrtK4yzpzoZCnXlPoB2PQPRXHa+6kLlje+p6gDG0/hheA1TZt81EpYMAinJ7Cj2Dzb9+A=,iv:jnODdfRdfQPmYEK8JBMIxc1bgRTpdEy97+zkKsp+3cE=,tag:/cG/YtMJGUPnjBnh/mypJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
