# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:LQ/QMV0zG1uG2pvR,iv:d6oWq/hfsrKc57Ud0YFDPigdA62QALrRy6r12uGU+dc=,tag:b4f8mW3mP/YEZlkmy/SR6g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUnFnS1VWdjRwUmJpWUtW
        VUdQcnZ3Smo2RFdnMDh4U0FSbzh6WEV0dlJrCnZhN05mR0lwT2RkWUdYWmVFdWQz
        RXJtTTlFUWpDNkZVYXV4TnJ0NGNNRmcKLS0tIHpRQ0ZsZGNNTHlXQ1o0YXNSdFgy
        K2h5cm5SOXpoNkVkNFNLekhqRjVPckkKdKTVAEjnoBTOCJelpIqqJXefN5S+Fzm3
        Akf/GfokivdHcg0q4DmpqG2vjJbSF/VUgeu1b0BUCmhoSrEuUODV9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:wsDA2P91+3EuLVP9Oz1F8dHoEJjr6KKQzUY43FwxPOaUp1xx7EIxHzxr6lF5jgeMN9YH6g90sXRk4AWtNkrt2FQA0ijvwwKrxcdOmW5UWUD2uUw2/AghsJJlC1EiE5CCvmYyFpnQ6Qq+LusX4I15ghrJ6i0TnwYtsiB8GOhZVVw=,iv:MEdkKYVDzJhobECsCjlQ95SDjAgkkIWaRN0ZAvaAsGU=,tag:aLaYYf5mSHLP/7USAQpyJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
