# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:46voHx9ZGl2fzJCc,iv:EH2UQlJI+1gLUabuEp0+Y1BziolvYVIo5ocF9ZmN6S4=,tag:TmNC0/38JH3vcMZ50xA36w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWEJRd0RMZis0YnFKTDBI
        QXNFUlBKVUtmNm54elY1bHZra05PWE4zSmhjCmYzRmdIRXNQd1pzUFAwZ1F6RVpl
        aC9SSWVCOVRNUjFHWUFLSDJRZDV5eTAKLS0tIG82WTZzM1BoOHFSS2lLQ2h4MVFm
        NUloNjZxaWhnL0JYa1BoKzg0bCt3SGMKuQ6uOEVS63TEAEbFC/u37uZLmjBidMVZ
        9YgXKSmU8VbxSRZ+/Q6RlHNQjdyi801/3CVSLI6nHQgmv1+8tNYvkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:qPTNEVXgZXP08xX14equmMdu05qPMwWUywdVXtB195TYBWmaTGuxEfCGPK8EE+qLolZYRa1CDgsotj5nImb0jLwgbM391vrC8pQAMpHj7GfFYBSpx4QtbF5YkHeAobzzWFtYw+hsvVIKsbrzCj3wES1jhtzxV2pafedbKWcWG24=,iv:OWnRmtLZCUwZcad1O8qvfIIzbp+6h1snecsqhOYP2Yw=,tag:iFbwn9uCKaR4dBdtI2TSYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
