# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:FEeXbWbWPJsQyVOS,iv:0yKTi1x9a3dM9LvC0EVtz2FjDYrtlxQUFATwSY8oqyQ=,tag:ZMPEHTHY7FTizvg1ERMM4Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZk9zTXNPaXhOMEUvcTBk
        Q1RiZW02MVVkcnhVa3VNa3hYNS9KU2FYSTFzCkZQcklkMEpsRTA3L252RlFYR1BI
        TzVHRWJvUEM1VlRIT0VNOXkxanhsTzgKLS0tIFp6aEYvWlNSUWIrZnJvSFhOL3pR
        RDhtRlRjVVpWYVAram94L1dTOS90aDAKVehJjcXW4bHlsmTaDVqQ+N4LTkAY8rsm
        SsNwYITmGzkLIJuu/Z6tT+T1VnPnrSmEiPlBzHDBji9jo6LabrT+lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:3gc1t3SMT6OcuV2LNJ+JjkJ1QkvKCqcBwqcezxnfNc5YV29fthMeg/LHMcjQ3FZFY1iQirNG/4kWSQLM+FtcNIMWozkPRcxyhWd9GAAR+VhatnQn/lcs0ZS+kIMoQIKRdhyrLzTxQQ5PaRMhbm7/0Vs4gkHun7VM4rNCgwCDlGM=,iv:yGGv/ps1HhlAoyBato88pz7BDGgT4rPkNMKivpNVuFU=,tag:HGS65jrJRl6rueYDTkjJRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
