# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:yAOqq4mRh1kM/Dzm,iv:jDlo0BFKLoCQixkrRngKOoBA8ISks6+UBj4/QfNerk0=,tag:T1I1BqnybQRtEvBqSErxqg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabTUwckREQW5uM3ZGMG9t
        akU1Z3RHRDFBQTVHZEZSS3ZVV0VzZEkxMVZjCk14Z282REFHdXdIcDlkRC9jWisr
        aEV0bTZQMmxDWGw4bzVKU28vUG1QdEkKLS0tIGNTMW5EZThMS1NNYSttU1R0Z2JL
        RFEvYjM4UWwyM2pNdTN3ZWJwMFR4WjAKyu2COYl5hPqIK2X7FLnL20b1+gAaFFh/
        jDaSCEmPqYBe2otbbJe7sJ+4Qy6eUtEwW35ENFn6VT3ZdOSKlYjRzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:dBLYMT7LYQNw/pzCGIWDxSix/7YdB5L8/UMik5sqi8yK3UDk7+JoNN2D6Rzz3YR+CsBNH/NcqbvtzIY9aC0mh2jqHqQ1XtMuz3SKj3yt4VMv+ocimOWDnDNUAZDwOUAvKG1f9x84U0l0uru3CY7iV8E2rmIVK7HS4YKtm6tkaZ0=,iv:S0hFabTgocV92hwMvzwQEx4zimCBzmb79FXDbKcQK6Q=,tag:OqD+WuqKa8HVKHzyREQHmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
