# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:4ETDW8con3MFKjgc,iv:G028qiQkXhlZveHTMMyl2EB+Db3XiZ6j8j+x4VfGqYk=,tag:JpBi2c8lhf3rSpCZYL9pgg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMG5vbE1Db0VPVXU0VHBz
        cnRuamd3REcwZVFXK09RSlUxbVBBWG95Z1R3CnluSEhIc2lMelZveVlZaTd5NFVH
        NWVxS3NKaWhXOTYzTW8xSGo1eFUvOFUKLS0tIE1sUytUVjdFSm9GU2NvczUxbTVz
        aUZLYUl1VmRMWm01WEJIMTUyTHdQTUkK1hLV3dNwBEyL3NIM1BCmA8MZ6djKwO1b
        zIw3asUtmCgmzcTIOxxOL4XYU2jIBbATLZkf+mw3/JajbmYb1qAzZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:VIiJucUAYvPrrHEWYltF945J0ipbtpJVbSNOgNnQKpy9izYKfDkAfKS9/2Zi13Esd4GGJkonBhGY8txNJv0yfhipCGEQQ3YQDZOtKmhQAstjpoP4ZTtC1nbBDBb8BTVZIu62nKG+GNHBsxgHtEjKMbPdBriH9m9oxM2FikB5Zhc=,iv:I8vLiUu+bT7f6CR0RKt0HcDG5W+VJD+bCPKkNXLtABo=,tag:0gImrg7BMMC+Z3fowjhWXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
