# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:zwe4Ep/PSWgTmuiB,iv:/3xV6ZnNeVqiCT8F4FQTUdCjykFC4r1g8O7B6A/GlZQ=,tag:kDzFO8Hhu92gqiPmnXSBYQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaGd0RW1FY0NGTUtVQ0hw
        SGhwemMvUnJBQnM3emdYRGNRSk1uR3llakQ4CjBGamQ4ZEtZRlZISGZrT2xodkk4
        OEV1YThBUXBHZ3R2OEh5ZlplVUhZd1UKLS0tIGRiVG9sNy9GWW9FMFlrdUZ4L0VG
        cXZEMUFxb0loZG1mK21WNUc0dS9xVzgKDfZaII+dyeZRcYvQrPJaiY91ub4GuRPG
        9WbZ19jckS3ZXD61RzfBAKPs83MQZIFsxkDy3mZHwKDaVQbpVFwb2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:zPCqX8IaEckyRvtfEZ/VwEv1l8ZZaE8phXwWOVyLC3M8WBDbHoX6ALPhUMhOXt4Iphj20GLQ8v/tzCnq/GBH2eYgeOLXSn4EyL/E0hMIhi+SCx52X9Miz9WuiObs3Sunvz8PtmsDuIs/tveEfX+Mpf9JJ18e0sGJyTZn12adACA=,iv:1SpG3OfKWjU6r2sGJf3dD4/N6r3xciFChkOeMpbBzlA=,tag:kkKKR+Hv9GSODnAI4gW6Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
