# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:VLXd+pNVT6Qv7E6c,iv:LJQOArJ4fBoEq+cAsuEnDRQbLUSFTExh66geSnk8Yk0=,tag:QTQpLKscob/t8pE6xSWkFA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY1RyVW4rbFNpRjFJZjJN
        bnNYQnc0dEtrbkxuSmpNTlBXNjAwUi82b0hJCm5BZzdwWTVocHpaZldrV0tkc3Zp
        enY4R0QrOG9RQWhEbTVvQXJMdm4wZGMKLS0tIDB5UktLRnJBNkVrajlzQmU5NHYv
        WU1CM0s1elYwRmRtWFVwZVFha3VoZm8KWEIHTe7Ii2EYJ6/iCwbf9U4WYYC3DC+n
        b9++j24wieuJHwcZbc9+g6iu33nQkm4oS1OkgRMZxmqbEwxfrLuvWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:ItBumbvAGrqU2q3FLrqrJQzH26OjemwTzff05YMZCx0xHGFnllJKEFsDk27ixjllKrjlJSp5quU8ciloWH0vg5vStgjOBZOwRfdLV1H9X4BS4cnFcwrcAXgqlJcsP0zgdJQEraI/vJATbPIk60CqfQNG6ANfk09N4xYHBnLhohc=,iv:KmgAx+gd5me192xII3xGqCs5hG7Pql7cII+B+Cg1RX4=,tag:z7pyZUSOLxsnkBaNXaLZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
