# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JiC6YVXg+++HBilH,iv:Ml0yqcut6cRqQMsVorCAdSQTV91lkmXaiah1SY+IoSQ=,tag:Xbp9B8yPd70UYxMVAiZcoA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadUY4a2lZNlFzSFVNemls
        enpaK3BBNm9xTFN5amFSRlBpclphWGxPQzBBCkNwN1RLejhFejBORzg1eHhoV3Jl
        VlhUVGhjcTdINHpQYjEyMmgybEhVRzQKLS0tIGIxbGZGaFFoalNqTkdSUmwwL0Vm
        OWNSVEhtQUpjOEFjK2c2VU9iZWR0S1UKiJ3RcOFskSu1QyBB2Btp5zLit8Zo3rjJ
        Tz8PHLej2Zb347qPuC/b1kVDpKtrFapNgB9c4mTVDqDeYJT8Ao1j+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:tqG0WLj+F0FPFkQevDSikM+fxY1nPJm9ajuZkJASRuXE3kKpbIxtLukzIFEXfRQ+jeORsl0lxvDwruPUrEKnbWUg499WU4VqfTOipY8FpfXYMMlYN4nZY7v6aEygxo4F8XZt4AZzObMTStiNnVYZkcG17Z2Lzs4zrgbazZhowPA=,iv:xomjLoqnt2+GgU2MCv1OLoVaQDEanGPFR03JZJpEnXU=,tag:p+mVoHsj33+hGBpdAoZrYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
