# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:UeZs6Xp4kkpVyQEE,iv:xbpAaszDz0X5xTgiIzpWaXjrpzom9lwV7SKTbgMQx9M=,tag:Sv1r5pSQAzgAaf6EMFSBGQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY056TjIvUHhrL3UvK2lm
        NnA3WGNZRUJkanhETWs5Z2RHR2JWYTBObFVnCm5DZExaeVQ4NTdjL3dkK3Qwenhi
        czZXbVhiNDlLOVpRR0pKS3BlbjIzWDAKLS0tIFVIdEZxSUVzb0E4U1pDUTFldStK
        L1VxRVE0M1ZsV3JiNUhsdU03d2U4L0UK9n0IzP2Mg3u2SLVxwm6mNfNtIfPCxEvc
        5JKx5iLCKPp7KW0r3YDXKhpY2OgU1tSJHipLL6HEo5oyThg8fdJT9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:05Z"
  mac: ENC[AES256_GCM,data:uffkPFJ1SL1+pN0jOizuV5sl+ERrF3glKY6xn4IsNlj6bhFm4Zeg4w6aBVSvu6DgecqPPipnSkbPzAUxHJGTXB+IYmhSwuHw1dsimSkOQb+D7MPqsi1fA7byERiHjbJKssLT4gplsNKMJVHR8PHPnI83g6peaphXuGlPs/q4HXg=,iv:Tkim5HIEqadz/DHh2/ZWPYUYpRYcq1+h0xpdNcjSsro=,tag:qyIZcA61ORWH4CdWNwT36Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
