# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:YO4gkUk3SsP9+8tx,iv:MED5rRv2af3dek2nRuV6xbfcQFo1Vre8xZpoHOGTpoY=,tag:mjASvvBIUQjjC7Mnd/Iyvw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTSs1N3ZTUE9lTlNRc0ZD
        WEV1TFVtdHp6ejB5QUdiTmpZM0tLODRpR240CjQ0UkZITnJnTDdvRzY5Rkhtc3FL
        Ukc1Y0o0ZVE0dnpHZXE4UDU4d3p3VEUKLS0tIHV6N3gyZEtBK0FNRXV5Z0pxOWdh
        QjZjVVhNVzFEN1g1VDIrd3YrZDkyNGcKn7VY69mPFpF2papSSfpaZB0iVaBMUz4W
        x2nY3b7+5qm65E++1rbaMX7g/mOOL/SAkmdLtnR6jGoEosRGv8PUGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:8UWj/9E6g/Dcd+MNbkOIugx8T5SL0QKUe834TbQ3GUEb+KRFay3CZuEdedZvP78+cLLiEbxhlWApB7wn+rlL7LTYUKQAef/4L3/rxm2CEetyRici8dS5bFbYTM0DLtvUtHYHg08zuz5MTWHmmj0zuPxHkMsGBn4bsHquz4Vx5u0=,iv:MSRlYOXHsvAGtBrZbAy06gcKKBSV0b6zotbxOjubtOk=,tag:uNnghTMC8l668eq/lrf9lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
