# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:yJCFxDO+LHeBn9Vb,iv:nOwsXYyChQEvb3/ECqs0VGIgsiTS16iOxml1tr2KDUY=,tag:o597/A3RgOsFJF9qQTjv6w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMVdmTnc2emlldGhoTkoz
        b1lKVXIyZEJYa29vVkF4eWt0eWdhK2VvalF3Ckk3RzNHWjR4cCtvY0htR3NoR1FQ
        UE9lMlNsN3B4N3NSUldBbTVoQjdsZjAKLS0tIHV0UWl0UEdlM1Rpb1JXOG1kMmtQ
        NWsxVlZRbGVFeHNyREo2NCt2THNtTTQK3qcFtQgF7BIPfN7n1fSMxeJP0UPwURFW
        1v9RiBoFdijZLxowCE9jDXCJpI0JwmwjZkpGwVKYYMrDgxrIK3zfDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:BgFAfqEB4FxTORrLut2AXCGh2u/gocpul/SU8SB9uTIQWWm9/gxImMICl1M27L/4N5sq9ky+us2VKW1QfUfDCslNLTkyR0r8EBjxLdWRksE0bdKc3Xr8HEhER09/2yO3mOOFtl44uBZaWTMB+jHKUwEV71+cqtnUFXvCwYH5Kh4=,iv:7Id9grTrI9VKbfcD0hSInN/fbZh8aTQClUEaaiUBj9o=,tag:/nE6Qiooe7bONPR1dAN4RQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
