# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:QXZ1EygSeTMe9YcE,iv:b3EEdDuz469hENvOeBbAcwfh3XWIBWTm8E9rvK1omm4=,tag:+VPzOEJuVUoX0HfwsgnomQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYm1QcFJsT3J4cmFyNGs4
        RkxQZDdwTkRRRHRmWStLR1BEVW5FK3FrNm40CjdlZ0lKRXlEMkZsSUNPb3N3eTRK
        U2NjOVpWNGtFdkswam92amVGRWFZcmsKLS0tIGZtZ1U5a0xzRmdWT0lTdzVWbGlo
        WEYxVE9YOU5wZnZwbkxOKzYzakJ6dmsK0gl5JeS1JEQ8OV75duZQNpJgsJLHBTwl
        kipa1X8edFga2l+sB3obxtnq99VBAtpxwAJ051+V8+4Lh4sApRzerA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:XmVAgTZZXnL/+SSW/jNN5f9ywrhJTYILMi90Og9v69eKCXPj0ZAdn/SUsQtGDC1Kapb5+Vi/HH5rSSr6mT59XGcvUinAy0/5YOwo7AJMEUeJi6Qn4lTNFFTj/2MW987J/KQnngyz1QFmzHjAQXwVBzPmtawPTAbJvQRDJKC3NKI=,iv:lGDw7F1tVArO1OTXtXpO1iNewX5NJYAeCzBr/6Vd/cQ=,tag:YUnHcEHGF4Xj4kEOpuZ0Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
