---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
    - ../../../../components/gpu
  dependsOn:
    - name: postgres18-immich
      namespace: databases
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 1h
  path: "./kubernetes/apps/default/immich/app"
  postBuild:
    substitute:
      APP: immich
      VOLSYNC_CAPACITY: 150Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  timeout: 5m

