---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  #- ./echo/ks.yaml
  #- ./atuin/ks.yaml
  #- ./opencloud/ks.yaml
  #- ./n8n/ks.yaml
  - ./immich/ks.yaml
  #- ./nextcloud/ks.yaml (https://github.com/budimanjojo/home-cluster/blob/main/cluster/apps/default/nextcloud/base/helmrelease.yaml)
  #- ./vaultwarden/ks.yaml
