apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rPmIzc7VHW9phrK4JLrnF2ecQekZ/1wvRVUIpPlsn1nGrhaSVMXZ36ylxZgfKVbc4qt8IWUd6ghx5RhJp2WdQGUF4C2gJ8TlLDY3ElvZvtY+UHPd/z8//RsUSbTo40y19JjHnmAoRcGQE9o4bPD7FJ3B/qcQYNDKUtN1F+o5YpMZjg4tGb562CwIXNY+sZkuY5YPKb/L3hya+mBr9DxlNPND4ykjd2+QQ6l+YtGX5OYNC6oA,iv:YvBIV5c7r0qg7NHy9+hx0G5bIJuOvZV1uW6dlaDtL54=,tag:t9RVfxDLmWOza4beke26zQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2lnSFdCRHZWTURPWUpx
        L3lkejBvdFFlaXNJTTNGeGc0TVc5bXM4VURBCjlWRWllZzY2R1pSazVML2dtM0Ez
        d3MyemM5ekFYTDdqb3lQU1VaeUdEZlUKLS0tIGVPUkdJQmxZTkxLNUZDbmxOQ1BO
        OEZtVktFbjA1WkpRTnAwZHVueWtCRlkK+9/OmOjU86OigSzFu72EatMa6IePBMpj
        C+s2txlldkDSCCDGqQe2pn4ihM+DVeKMRsHJW7CNOE4Y40TkK/KZWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:8rmjrIykXjrHzjgjYCM3hB3c4h/Ow6YMaWPkxEcaPyoy30LE9VvJVicoXgJsBo/HEG0iSBai2VweUCd5f6SFM1dRfxLh7BwymPW+Kh+hZl/Gw3gr4fg0135M+nzM3zFk3f/ITEdLI14hiOxH+iAR2nTf6sbrxe25ecPr33Mqd2Q=,iv:l2w4fMqI0yw/gOO8naD8+5EhZ55zyJe1lkEoqjr6UOA=,tag:nk9LbGbMCCfc9sNvFMtw3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
