apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XMqZg2MrjDMvppVbA2iVtYo1Fp88HxPOQPU0kiLgtMqSUp1luuHnT0cRr01qCO7HfMi5cofD+O7uOmee/NovH9zWUsjGRCe/PPcAoiJqY6DLq7XHt79GtIAQ2IPidRBPJMCn19Ss3WKTOE/ACJlmF1xVg7OK4XTMCMLyC7w6XKlYLm2gDaaq2YM23r6y0tE1hGhvJuFOSwPnb8CJyC3AajWuORSraG7fLef1OQRH+RojFf8t,iv:ZEQA0Ix5uLZflSuGie2qSQQYl2UpxIxrq20vkACrU9U=,tag:lbc1ORUctu4EpEpVDI1wjw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS0ZFeVJJU25ydEhpZDhq
        dXlaOWlKdlRwOE9VdGdadDQvZm9QTWV6cmtvCitNb2ViK2lFVG5yTWVmd2FzYzZp
        VDBlbEZQZ2ZJaXlLYUhTTTZSc1prdUUKLS0tIHZoWTAzVWdsbEV1ekQ2MEhvb1M0
        OFRPeDArQXl6WW5wVWRieGttelFDck0KGgVlNX++EBp6Ho9ohmk4Fnm52iMkmPR5
        29miiCFWS+G34FdMb/dQd8tRUyW7fhRGapWVjWWQ3lFtnUL5B4FIbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:+DMCaF0oHDyhINHaq1EedXX1aSMU39hDtynkZ0SLowCHDkbQDK7FWTeopuenEhe1xC331iTZgXB9YqfmYKbp+MueqyPRein96yBVKuP3AYYsU3MgPYApUxDJdvY+q2vj2Laoj4UGCc60nDulYglAydp/knltlDvc55/nf4RCW+g=,iv:UZEp2O0ZnZLfJKbVHnmUVWCdI8Elaa0u069JNjo7nYI=,tag:iMrBUq68/XTE0mFLC5DifQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
