apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pYEbvpMnWanRTuaF5BbxoZmIHV9mzTqphiwdNhHTiLviRLrJNxn0fYS8kfMSUEEYnH75MX9uHaNKBtH17OAGmVb1g5gyzIvbnm5jfUEw9KIDGXgDtBbybkSOl9SmPT3At9NEmxDiYNwsMbO1crGrWVPrJdLagrt/P3W7yJhEcTnfjczGbdIFY326Qf6XggeaC5JrIrD/KI69/J6yDWx/HW0DQTuFyzFUSDJyrMB9jqBPzzFm,iv:IRR89TzCDuTP3vkw9PkChFLCCuamfSIauEnPlT3VtJg=,tag:R5KxFX/YoVF4FkajjoGpJg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eng0TFJtUSsvekFScWtP
        MXRJbTZhSVgyMVQ1STV5cnppbWFYSHZTSG04CmR3bUgxdUN5MFhsaUdJQnhkWmVl
        dkZwdmtOYzdNQll3UmRGVlpESDIvMjgKLS0tIDl4VEVzaEh6UThkWHp1bFlNTFZw
        VFlyRTBtMTBiZU1NUkNwcURYencrOHMKuZWMq2yTt2ne6gqBNvS9rIyYB85djFeu
        BMyUMYxtRIlUJZe0bNTgJ8rBMPOd9PphL5k5gLI3l6k0CNzmqjC3Rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:zi97/rtmlJeLzzES07FrnxW1oUA9BHfQviKfnufS/stO6AQ+3benXG8ZZ5Tj08Ct6A/hPiM+1hOKTNNZX5n7wUuwJEoRxsWIdgP/TSFOQL+zUjdpAWT3QL6QcpslSqqeDTq/4rsfEuETA9v3FPqhxI2lgBQY1sVpeSSXZkLnYqg=,iv:iBZd6n9C6lf+QTuET1qttCY5yXvgkK+UiXvTKCLKoJo=,tag:95rN3wvY1AlF8GihWEd/sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
