apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Nl0ZCU4CQr5p7IOnMBbmT2pEceMbhnWU1z3ujKr5qL09dTMgyjTtiGg06jhkTU1hZvI14K5ZXHb8ttNd4eFqIhrhd6pSFR0iL7bcq3lnLr7jTKRVkA8CkqtT/L4UUDgZOV1Rr7zGziGVhOe4zhS7nG1yCFa6sILTt6wFb0qHHkrbDGHbtKN2HGS9yJpM1OndOpbVoGKQDLTz7GrA8z37/Q0UaT+UfSEda//1vcgENQE1pX4l,iv:Jqs3AEy30uZ1sJrfaMthBp4ukZ5/SmjeQRHKf87Ta4E=,tag:BOyz7keAKlfCfcQmxcA5Nw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NDFBME1iUWNCR3dkYU1C
        V2tFc1Q4K2V1VzNpRncrdEU2TFUreTBYUWhvCkFXamFHVng2V3MzRnFuam85MEF5
        Umh2NytjM2sxdk4wQWVuSzZNOUxJNTQKLS0tIDVCSkptNmltc3ZNQ0w5WHZ2Z1lw
        MWorZnV4aFRhMXBtQ0lMdlM1TWZmbU0K1oKWY5JQgi8HmtcFxAL/rU6M/XEp0L7+
        NfCvhsE5aMffOJREYpwKbeDS66wc/1ZgpV2TdPGC7YqnGsSdbQWZ5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:WboxlTV1PE6YIUF6vtV5VZ45JqtmtzDWkjHW5PJtDU+4VaQ5CtQj+1bmvKRh0Kzg8/bjEfaVe01PzTAs5t6h8ewjohv050S2WpiCMczEg7JaEstlqdXVwLm7f0863dPtncBpxYAz1NsuFnHeOsifuVBXm6YZQSHdvWnn0e2Vvz0=,iv:8a56DnG0grQHtFuXLUddxWa7lIPNBK5aOzoyS3m192Q=,tag:3h6sMW8RnxzjcjOVO0UJuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
