apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KYLnPNWB9GGt5d2vPSxaidct5M7nJBYma9iZ8B28E696I8EedPBl2E4zfe3aHXQo7OojdA5dFFvL5ShPl8nnczBaisqsJXc3HZjGeEYysGIZT5CpyDnkZXqnIRVpYi/6LEuIiiqM38bzp3I/XPZ52Wr0jvxmIXaXuXKnl9VstGphnKeWR/IXW2ttyZA3nv0qwxBqGzcBOqvfyhvsrnL3+df3izITNtpobCY+Hvx8gnH5IIIl,iv:HB8D/SwJJq4LnIuw2CRk85g400h67qm5F2V2qS2ATPw=,tag:U5Zed/diOZ+y/o3LTRaEXg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUE54VjhyUWwrVHNnRVJF
        eUxzSktWVUlKd3IwK0hwOXNsYUdGRnNsYW1JCmlhMWphT3J6blpXT2lBREwzSzZT
        OE5hR3JybllsK2ZONVh0RzNqNWZVV0UKLS0tIFlWZFJMSDBTRnhtQWVUcTNaMWpa
        My9WZzVXeXpiZ2IxRTJ6L1J4L3p3THcKL7qljd0nAY//JM9cXCEjkxARZlcl15+1
        ZrcLILnu9kYOFSdCPq0m58nCWNfGVQc6QNe0Tpn0gBD38Q/ODtf0XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:7z3ElIazZDvL0I+Fp4IwCboWejzdAOZZQOUFljN6hLw8Fg508i9wEnhguJVkzTNRK7ln5hWXhxqFx85JwUqxAT8kPrCzHhNlz9xOzrpoO9MhrW7HDZowCW7tX8/gpLZGznOOtj/QfY38rxIwcXkj55sIBz/V/JsSyUWTrBJ+l8M=,iv:IuukdfAvgNm76M2vm6ZaOhQeBLevF/5c/LBITpwr/TY=,tag:2+Wjr+cmtEeoay/0va7dwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
