apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ecelxLFbTHCZLTb0LYnksF9kn5NnQ32N2hnXXmv2V2sEc8OtnE7jdVRTXnDt9cGQUpz3tdC5IwiJBSKKdVZg9gTYmcHMf3fRgrBdN73cCMgtaWZHil57N/hTJur28gSTB9khiaa3Bztpi9NqZgvdXdy5C2djTlqd5D/4YcVX4hbbedwK7IyATZEY/5yg2OWxP+/glMKhhwzOgQF51TLBbimKNArV2h9MnJyhCesSNKYVcAXt,iv:Mojimu0XlqGk+PMKlx3kKVdjlNBatuk1f+YVOwjSE20=,tag:wsU3/hNITyf6mgYcqzgiEA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWDdhNlV4bHU5YXpxeXBv
        MlBlSm5Xd1BmOVdSVVd3YTJXUXRpbTdta20wCnU4KzdYN3F5Q2dqSFpvRGNZSHdq
        YXNXMURQcjdka1dGMGZxdjcrRG82Z0UKLS0tIGZKSDFGcVpEdFBnZnhWTUtvOEdQ
        ZUpqWWpUNXpGNVNLWWNyUlRNQ1ZWdFkKxjUGGQHJCNp4+Uxd6aDECTpUXbPKK2+R
        JMqQMb5ODsYQZIwIotIWKDObXde/LUyt91uzPgFr2S1RXcLzceeuuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:ZqoWjWtOQDhcR+t+h4Ai01rg3piA2FW9+TORlA2TpeDMSM8ZMTxY1VISDX1aJAswCclPcGol96j+457DFYRNcdSUoPK6p70LlxltU0c5m8Lq/DRfyniD1WUNo+gzlut4xRynsXCrqpalUFrk/9UGpZXDhJgYkJG1KhmSvuPNur4=,iv:EZQcVE2wv9lT7ofh9Fhq4FCYRoAiD0RYqofC+HPdFTU=,tag:isodb0qKOlhAGb6hk+7soA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
