apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yt3I9j8UZQknvmVAS4/Fq5UgOMUCLEyxL1M1xsg/vt4OIQA9r9wM0tBedUVaiFiDbGlxV67AO5ewqhZRfkLU5bauCfBPoZ3z41cw8fDrm5gI7p/zaXRkbIl7NEzXctb7hfOew9B/qt+E95FfAtZ2OICRLp4QhCMmGwrfhFBu7ny5k5CN9pIvbRh2jVCpwpOI81B4t6j83dq7+56qejvv/HbXKlRkmZ43H1KxAUqCjxhXO69y,iv:4qophT+zmKyUZ/SeYOuyKUwXuflJyDM38q4IvuDzQOc=,tag:unIVQh7lGLuGMgQyZNvYFA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTG9YRDFIRDZYbUFDMlpT
        VE5sZHpiNnA4VWpNaS92cVM1SDNHZjN5dWgwCkU0dFVUZmJNbko5SmhXTEZFUGQy
        US9zT2o2Yi9pR2FJa1NFdm9uelVwQm8KLS0tIEdBa3JNcGpaVUNyYzRXZmxrejR6
        UHpadi9iZFhjdzRCanFHdDZYWTg1MWsKkbRVkVYtDlZURghOcvewfzckd3ZKN9TV
        kQUZPxrq5FTW7krGFP8+c52sodGl/hZ8ozj8rdhod5EqDBWHxDGYmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:W7v8XpXW+m4Gq9mLa+YHJBwKzSnubQgzoZ60Sxt2WN0JOxZJafjh6n8MCLOdGoNy95uG/nKV/mLzxPHEBnkscXLnXb3r9K0xydaRjNHI18r8s4LdgB0+SCexxtKiLKTrb599acDXazQ585VDey5aWZ/sR63Q6RGjBnzWLGK7m5I=,iv:zidy5kKr/c/WASHYV4+JYROH6bVRkNzuY3FtYUTLEtA=,tag:DFDxm/ijNi2Qd4UVEcGqaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
