apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0z7UvLsc4Fbd7uG/kIcaqOvYmBpZWDaQobpUUzNLTSG1a4ty7lolkvFXuJERSdypf6tyAr2bFd7A9J+TsaWzkehLHxBV4GnGi9w+XV4ub6bEG6Iv19063/F68/MJMlPSsesI5DJw0EKw7+U2saxD3FjUsebk3uQtwq0PQmpUabw42oUqoQttdJGErz7fjq0FdtbShknzzjYZZcs77c59zMRPHnpjqkXVOl2RoJHPqUhizI1q,iv:I5CggTyqjeK2RGww4WoeJ6SiM43diunfUWnThd5eYOM=,tag:Mewyn/HQ4bD/SVAceWrpxg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTzIzODRrQmxPc1lIWkl5
        MHVFNTVHQTFrUEU4TU5NbEl5SEo1VUZxVFJnCjh2N25GQjRVM3k1a1RoK2FkajRX
        TkZWUTdkNlNaS1F4MUd6dThQTHBtQ1UKLS0tIE9pZmk0SDc0cE5DYXltK2dUREZ4
        OTZaWmVGV3BYQ202QnR1cktTZnIrU28KTMcoUWswRPLMn25AeT8zDA7okOF9/Bd3
        uCfqkRRmvs7TYFWwsqlDse5SUqrZwYU33KuTqpibhwzR2rovIqwNXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:Se0YlU/wox3ryUx+x+SmBKVnVetm8QGK8AavJld3EAQYMhgockLvXb1AfpUS+NmH8MSmSfJuu+pgMoWgwJRFzhX+FO06s4zL4dxhQj4/gW/kp6YyVJk3yCy8JX1KD2awwKggCEfR2m9mS0l733PcoYt2c9SrH/ymFrwEc2WaabY=,iv:JaxDJ2iAWHb6ylK5z2SNccohih9Iv6YWzO7LwAdRsB8=,tag:7enXBdxiRFFmINiPFJ0Bfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
