apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fAdOQsiOXKEDkjLCOCrIr7coNQO1/nk3Y7i9ORRlQF7DeG3jSJ9pNI0cyAHrc3hVjCWNHZp2qZi0CtMk+5qRaq28lV+4Kdd7pdbWsMatQNTTViVhQXPhOj7wNEhMltKCg0MR+3tl6sXwAa8x29WWbUaCBy1nDi0BUSqO9ImG9x20UjESA4Wjm8+eU8gaol8JnX3k7+LCXGj/xGZ3rH/LNKRylXRPFi5iR4znq8pE1QEi+HyL,iv:i8XqD66GA+5s6xTzjuAsS8VswvFsT2v/+wbiSvLay+s=,tag:SaF9LGGaDy9ecz1rn42zYw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bGFYeGU4OFlSMVEwMFVU
        VENvTUJZTk1CdGZDU1VXaEc5OFlaaTJsL2tjCjRMeXhLVlJ6bXNDZk9XY1hDclVk
        aDh2eXRJSWRTTkdzNFN5cThEQnZUVVkKLS0tIGxJZVFTNW82dGYzRTZwTVBCektG
        Uks2eHRwL2dmT3lvVStlWTl1T2pEdFUK7c2Bq8/JZBEEsRBDaFxkOFiQJuPCkVXv
        bBLnKtBAWTQ5purW0uMQFXN8UMSS43mRJaUbQFvtjv8sjl1r65dihQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:1ObCXwbTPS3/9IKZlcIwfo2rqO7gTbGofT5612fHakUZYb/DDB5xRmJui6q/BOndx5Vf8fS0Yre/SIZmbckKFBLPzCYCtwRHziRKzxuxEc4F4A5zDD1MqlUb+N9o+grSCpS1p7NzPYfstFEPv1Czwqv3E2PhgnYe8enWrL9xswI=,iv:AEo7um5E1I78wqtLflEsjfwpMf0Aj7fcTumw3g3YKyI=,tag:ISVfYMbqBuvyj/uWuRV41A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
