apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pyVAys22yvebW6NhyVxshIY8HD2xyMedFUdmZnI3VagtyCkZM/7+3OmXCZH+sqLGQjYMFeDz9Zag+Nvfau6OMTLKjeM8KR9/mQRQI/p+Va0bQI0LhVSqi/g4Z7mNb/7tkeI64nKUJBHPKyNOAOH36GHQxFy/eoydp6mdYo+KCpReP/dUiL0LyikWhAK7Ixvi31sIa8nJU/P1+XnoDjq2Jc8hWrlQZENFzBgUcpVKHRRd4MMl,iv:ZekrxoxKVMh5/1z397YVXX6e7M8Wmj+bohkeDYBmUFc=,tag:h8l974rSF0tl+DgEupgPvQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucE1Ncm9LTFhoMDNEVWs1
        M2UwTVJXUHRuYlBMN1RkWm9BRnl6Vi8zbmxBCmU2VWs2TDVXallWVXdVRFFOWnVy
        b3pMNnBoeDdycFVxZnJxTC9zcGpadnMKLS0tIHpmS2FmQUl3VkdaVTJkNWVOZnJX
        NlhUcHZpYUdlaDE0SmpibGRjTlp1NWsKJh3QmUYyZx1O7Cj0/FQXDaSnsIixbVH8
        EcHC4gwlwwF8VyMiW5hcis457PMTgXMZNhDS61Xh2r4XVaQEOs8VdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:zpb3x6KtPia01wpy76FywMaiP/OiQd6zRt2DaQUA3LGhoJslSCoahv3aIVeaCIDFlFobPGzaWEitFgPkDlsCodl1lLnO1NaXspIA5mH/3ioMJegleZmYrzJyNR+mrHGmXrXisXPnO9IlOVOfADFuyeRKIcBVd/cVq6FYHwQ3ae0=,iv:sIYQGJquNU7Db7oCuXgFvX02d/dr7GQ2HCOkAUyiahs=,tag:rLzp+FzVCMv0apMTqzTcbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
