apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ly2/SJ8kQQtP4vS2uynj7wb0+jq750Pd7yvHNZdkRF3xuK/yUXz79ql9w2sApd6u7CkDxuR2AF4zIGYTkpkwAnejYLRfC0edQ8EjleF4nDQjXeEhwlvGeIxUALYG6CdIfsvTIvNqoDM81RU5eIOqLQCaPBWhKKPoxvHIluA3TaMCcnQ8PZZbbggOPAlGi7u/RgVhe3f6EKJLwmGm3HY6+JRUxNqjwchXbee+39jH5cy/gw6o,iv:VmUsHlvNe1FRq8qPx/kDwvN+DalANFY7r18kfYRJmMM=,tag:2prN5jT+SJlb7rDegvQKNA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WllBWXpzNWJmM1JFMGF0
        UTAxaFoxWXFTeHFPRFptMHpLZVRsMGpOZ3lNCkNiWlFWOElWdDlTQ0xZei9tVkx0
        TDZQcjVVUUhhSDhYUmZHU0pZNzlQcHcKLS0tIE9aaU1mZGZZVkR5NUo0azFnY3Bx
        ZHU1VSsxK3hIaXgxbkZDQXA4SU5iUGcKu06G8oQjOXa1rAkUSZub66OGx1t5V2/l
        +zj/2pZZhFjW4Xv4SBlGJ6Qa3xLOf1Zvgwc/v6BRpHMZxt/63mjXUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:u9h51++sKWJ26vSRPRYtf6qTtYV6SbZpbB7r0U5AKLzdykjOBNUoqs4mMUPa5s892/ZI7qfwoqdSa6EvvC+Gf1Uk90QdGR0W6q1Qt7NsoLDO0K6mJ7u74gJS7f8wVSKWzhtDTsKJdNCp6yjfvy7HHpWsP+5n2MK8jZI43eR9WR0=,iv:rXFMgEuHpKbsyUXIRwj2BF/ASWR7BMUNfz7s7RkfNRA=,tag:9wU7BsTmpBtwwspcs9wU9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
