apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4eNu7fEYjS7/HFY2Dv4zXrj8s7vB3vz15ob5j2ZcNWBYIvZEc2vrTHEmDj8goi6HJI6xEt+R+Tf3+2MtK9bVj9XnfE9InT6dguF1r7jxo+liy9GZOMowYB1AZaiHVDhFtUvIITIQbaFgp5uczfM1LLmhy1Hf0ZTEG2shXMvwxuiAxFcssOLEVTIASISw2Vvy+V/sdZ5aCehpAvKW1wNq47PUwvxYpPnlHr47tJoDCgdb+RHP,iv:E/kwUee//Ag0wgeGqoRW3lSuHTDYt6pNIQc3PIwy15A=,tag:RLGabqvKdv43H/bhvVUY7Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSUxmZDAyd1FDTkxCK0N4
        dUUwUnJDdnNXNks3RVgwN3h4UUNMRU9oOEYwClQ5Z2FtTWpHNFJkSk9yRWs3N0Ey
        ZWk1MysxNGN3elZ0blpBRjhMdmxNYTQKLS0tIDBtaGtJZlVhMkJ1WXhjMzdxQURH
        NmV3NGxTZU5TWVA0cEVXUlNJMkJTR2MKfKZJPYnoKRGh17zQFpS/FNjYgyrLchS8
        GX7YRYJCPYMAEf1DAdpRB20pu2MT29b4eXJ1jt7uR9TYaZ0FC6WXhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:aM/xCPM9/oYC38xjTkBMYDZdiLNARJ1QSgx9lDPtoaOImXOXBKDGZgpFPUKif53fjU8xa/h1HqpLCPAiU6m+BLTnEbICxMWV/dpBSp7uzS8/GaOd0JTwxzBnLmhb+2ZkpIdRWSDYvG+DSMmtAhyHmg5P6uDTpD2R1vCr3/W5+t8=,iv:pc0FVJ6nuzA3IFjM/cJDigT7SDO2BaDCpu1UliB89hE=,tag:TnLGuTXsKAuq/fQLwwoscg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
