apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0HcO+T8mPnkmgbuGrgAPXQBnrJZZdbOm+1VOOwX3TBC1faqAId/A6w4NnNBbtjLs+9TCnk3I2xaJ6iMbSMh7UtZBpjYCgE/4I7eko2SeKMRPshLbDO0gzcPpMaUT/j6B1Qyf0/2WHbaUaxqwrZYSgGpficpizwCymo65jpxqCWE/LSLEH5TR26w6PXheMcCv7uhSuQZToM/MaBm5v4r8kmZC8hOB39nPOII6Ejmz/ZJq3GiF,iv:xbobOVm0UK6QsD74wYLXxOQipKdV5x7loB3BZE48HqY=,tag:AEYJiK9ym9ipG2dGZb+J3A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TVhIN1BrVnJtbEh5VmR6
        TUNGTVdhbGNQcDUzVTV0Ryt0a2NGSEFCOWlNCk9jWHNWamN5amxTMW9wTUhxK1lO
        Y0ZXYzB4WlYvUDF0OTNmZzREcEQvcHMKLS0tIC9VaTVMMFMzbmo0ZlMrY1ZYMVcw
        dVZDS2VqUHN3a1NXU1crWERhOEhubHMKDxCnYUl35eMZU4/BRuDoxzqfgLi6PjYO
        jI3bUyXsS/tRLFCWVK7Y6W1SNdnokjLACqw2yg6HqLr8+LwXsYivFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:65khl5BZkj/EBGlCIZpynsDRjyx8K2QT7xxr45bw/B16VKh1GKMopMpr+0LbvwknNe6zxjIhaH5NP2AECC6IjijzRjIjXrRgukYTaHwI+OR0ksxKXi6iXRhWyqyeOCyOgRCx8Vj5Dcst8G3m8pelVCykRgleQ3qRs2G7rjcvckw=,iv:AiaFTsWm5vXDv7Op2987s5t6g79QCkobvnNAQ5BOcPc=,tag:KXa5wJJago6EtQ6UfMZPFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
