apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Tf6FNd3uRjmdiNq9pAFxvaf4zP5vd30EFI0h5/8SkwWjSaeaw8ndFC7mxKvrT9fPBfrNKVM5aKbRrvKOuIwMzaC4Pu2uKq+yFDLa6ap+OSjoMxe0dFLt9mMGMztiRWXIMCia/IAHwnQ0BXSEg5o0+1ax8FnszklP90Yerrc0iWm+urdP89TY+SR9gpYDY4WsCXaQx9J9u4cm5dUkHM9iEu2WiQYAvQ/vlqR+bJy/3zL9hkN3,iv:Fs9CR4aqYinioEC32tAAY41ARE1qpAzu1Yxqo258Hro=,tag:dpq0KI7o+5k+Bv7ZSKZHAQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbk93ZXpielZhZ2Y2MkEr
        elBqYU9qK1dUUnhsSmVGa1F2STdmWUJJYWljCi9wY3g3L3R6SS84WVEySlBicnZY
        NDZGQnVJcE10dmtMN0tUVWJGN3c1WUkKLS0tIGlibWlxSTNrbjB4cDRkck03aEUv
        c2NMSFVLQ1B3RFJkUXhWVTdraVNXSUUKh+XOfBXitXVBRruS4fo5bDWbDN6YAGZ2
        MebjAfj4LWiJQ/h8Z1pUuagTAxSQs9l9g8J/CT/TeZOvt0tJomVavA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:jjy4ttv7B3hZcR1amqwi0OD9WsDu7qPzwak+49oq0VunV/raCOqZ5jV7e/3xE9PdyoOsQr3wS3f7MRVwKSK/50Lj8M/p2yIHHYYHNjcWRn3fKQrMNgzWXAkuZ1lmPGYJzL+9pA/7Iv4pCZghZn8v7lQzM6ggMddxKIcrtdaFTEs=,iv:ddCyBVy3gjeKHYg6WKtjEBGEkeYAAg1HHyLIUHhROrw=,tag:kPqGqsKal5yc3D5wpBAnGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
