apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mEoFJ2jjwCSC390PhkBLnA5biFAV5NSlKiHWs/WIyxjK2OkzogDk4V4MN1CSAdPWF/VH1mzwC0e0svQ/z+6C3t971v3d7m6l3+wAx9D05zltaRmnJIqvPf1kjhKUwMDp67r73S1nJNIGfqYnCn6FUZmGIe+uTnoWtERzkbe9qs20XtbCWszYbobVHmtSwOJP2X9wAmkEysXV+pny707RsCrGBaCAJRUKsHGKnZZ2cQ/gSr5T,iv:ED68gbPgkOgIt3/5tgSxGScHu6IkCHocq6O3ijMTKJU=,tag:0AZQFOVSwBOlYg5RpmV0aA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1amlUZFp3SHZ1L3g0YXBy
        S2Y0NGU4RzhZZW9JZnJ0RXprbDJkekN1UUNFCjJadFdwS0dxbFU0ZGwwWGt5bVdQ
        K25obEM5M0xnUzQ1bGl2anFRM2lPaEUKLS0tIExSQzA4d1V1aFp0cWEwK1lCTlo0
        N1hlV25WVWFVRmRRZnlXeDluMGFHYUEK+cqg8c11x6+gmi6OGs9MllMKwgAdXDHe
        Lbx9e3WAAQzGsAkB2JvJUYyvR0b73nLo2vGqdSOt/xgcZcRuFbdrFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:9Sx9oqBOBTCWaRFYNxiYL43s86T79onHyn153N85n+3yFZkKWU4w1NbzL9YbtRZ9cuwk5zlwYPOqKIj1Py6OneXt2rR6dL+Y1yvFAhFu02pfei58clXgsr94yG4NYVFtTY4bJ1VEswiMYvXwMw0zucE0UVIowwScIZ2zvzhE+r8=,iv:Gme7QkRzx3kgCIN6aqNEKJ/jy2Wr2HfC5uP/c2XYG9c=,tag:uU8B3S+QnqtBFhsYP46sqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
