apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:g0f+FPKYblj8wn8C/zML9LeaovLYhY7ePvSGuxOiPnHiIZRBdwdV37BUeRp2h2g0FAqb0In3EM4zp9PcW0EYrM0CF6V6afB+F1hfUUA6TqFnFbzXp35EhJYr1YMAEFGp2skk2nxNPYKKt041+sD9aVhgZfWML21yBMjMYzcikg6T6pBOTwmWGg6/ebdqwL0hIrZUtFCFtPWcvSlQrr87MulRbVI++QnKN1IwAN6VNVaidFOV,iv:q4LdiKkMJo4iCe+oHqn9VkZxlh90AnhSWrxyB3YXkbY=,tag:43y6F1XipebC3M1egPNQ+g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmc3eXV0bFEvbjBCcUc4
        K3BkRnMyY092cXM0bkNwRWVqTWxDOGpYa0g0Cm94dGlNR1hWV205OHArek1TZ1Nu
        QS9leWRVaTA5NXk4NUcxZXNhdyt5SFkKLS0tIDJSZGNIM0NkbXZmY3F0M0pwMXNC
        OUlrMFNIb0xReHdTekV3QkgvVEtPaDgKGPPAwCQJuy/d28DEeyxhq0CBgwnt8NkD
        P/aT3XY+snEeqCENw9crtJ2+VC4vqxP24UgKPZgfg04Xvv4FSeK09g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:phaQR/PuF9BY4pOCE/Sbhb0N1q1fzXZDS1HRXdfqcLl8iGWPvWUr4ksubIyvQFI42pTt4+BSy6P0Df0mFzuwKouOxLCiGbsWfNa9blFdEb12gKDP4vGJNWz6niya5yAfoDGjV+fRkXc16Pec6BewTgzPbZGv48wU0gETgzczgsU=,iv:OMbKMP59/SsFE8IYqeQHgIKok1wOfP2WKOyNizjIz20=,tag:KMr3RW3Ni3s/7sIirRk8MA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
