apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Yweg5QqW8JhlGIcAyG6MeynGDULE8u8f6YSr0DqhnbQpXoGAxHh5zyV9oTY9dQsnNun1r2HZlMbdoYK6XyTVPn1qyFU86p6bF+zKvtf/GjT4GxXQmM7ukFPNlmSnUJjyN9D0c5dFAWpiSFLrMzdZxEiKjvtS71moTha5W8zR0OHJJqMOWVLiLUkL3bs6rXtjva3UCkWAyF5ELYljn+sVwnn60JQMFGqVddGk9TEISSRRmtzx,iv:DlDV5uopLqT56fJ3+1snK6vtswDKBMfl0JbADVv0tSs=,tag:hIZ0fG6aZznwTIqtjzQAlA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbjBrSHVMcXJVTlhQcHFz
        RzMwdUpOaVYvRUV0MklsR1cvTmtMSWdCcGhJCk93V05oaFNydzIvMU9vY3FnVGpX
        NFM0YW5SRzl2b1YvOGVwUE9LWU5nTzgKLS0tIG5LK1Vzb0sxSStTdTVDaDZlWjhG
        Q0hJcDRyOHNXdGxBQ25OTk1mU1R3bDAKsq+Odak9a0kl7NK/VNXqwhuv2PKpfs26
        zn+OQw9oKiIveGDQ4VkXCqZ57RiXE6yfYuJVUjZLfVeQLpyJGKlvgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:ntzqmPWz418MUCQChtNKOnzgFjsaTmuGsba9mMIZF2op6pyUDXQoHKnKd10lIf/7DTZM5S/Jzr22UdGN1NH7tOKBo5/Qn62Zzt+eEKIOWqu1bcczwyV/Lt1WJ4TyHsTFV8hrloszSuVpAOnll61VX/G6mnO7mi/HA8Mt4Dfl/Uw=,iv:m1ipAXhKGI4J8U7O0YTitJNxxe02l1kU1YF5QcOMeSY=,tag:94XG5B7I09eBZOmTBL43Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
