apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wNeLmX/9vnF6S7Qi/L1Ahv2sq7C362IQcnTpmoz/Unq8OEyOjuokoTphv3YceHFj/3hzJ86MAtuL2rcleXpYPhdWg+WlXELidQ2bMA5T7SGidy/zKYK92+ha/OWpO2D1pN40e83c6JC8JTYI0MsDh5Dfhi9mvYiGhJ4tZozcLrOL2cDjqOiRmLLuoMtiGLOukBrjpZiOWqiEfeGVDG6lQzL52tdpwCjfHZOPkOdelps5t1Es,iv:g/He2Zyo0r6EwFRhqHl744k6yM4/J1Rlq51I0dlVRLo=,tag:76sMTZbW3w69XD4nGw54CA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRUhwelFoRmkvZUxHNHFV
        YWJnU3Bxd0h5d2FNbHBkQkpvVDdFeUhMWUQwCldCWEkyb1A1WUp4N3owNUJqSlcx
        d1NiamdxL0ZUTnJDSzNhWG9QVWlVQXcKLS0tIEhlSlBSdjZMay9vRS9LSnN2cUxn
        WE8zRG1BTzUwNnYvZzMzQkJBVERiWnMKNTwdrzRc0/UuUmGrLvAH/7zqZXMctRnC
        rlsXATgIfEF/BttZYWIrWr9wSch5z2nE1mdPy+mDbykEpSYqVUx1RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:lxusKMg/EPcEl1xiqNPGu0cWSJtrH0ZOWNgvU96vwbVYga8LBt9ezwT9YZmmkx2u1QtKO7Q9Aj4AwtHouxeebM73nYAfIVFBMT4vF5pxHzPUxV5zRM4PLCtne44IU5O7QJHb9Y7tGOBr1SBen6rg93LKvI296ZQW2ezNPmZlbpQ=,iv:Sk5AzspIU3mWDSJfJNY0C0wLEepGPasPbPkV/uPbZ5k=,tag:8acmrfiCyWCPIL/8ViR8Dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
