apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4y3DGvonHvn6c+4QDtwptg/feRP8TGmrWwoEVzcHt5u7Xt51muUnRDzIy+xw80xxGNcSz3fLzuN/UoS1yDdh4hu24SLh5nxpLmdctrQCKWlfM1c+ywnsH0pQ/UGoZkUwp1GDlLPGcMVu9vkOjuospSb3VgPUUn5sW7gwNDe87mMavPD4ULlq9+6xmCZJIoU2hckF0LDWbU8o+NOhG4bE/pOh/Y7Bj+bybCziMCjCy1IUgjUy,iv:JX9LXqX0tmnkJD9IJ1ptZ4v+UJsVZyJ9Ceb3dPZfyLY=,tag:2PhjcTq3IaASfSW14Z1Ejg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc0xmK0hJckY5UVMxSlJx
        T0RodHg0TmkvdEN2YTZzZVFlSzBXVHRaWG04Cm5sL1pZakZreDBwUlRJdWpYTTV0
        WkZrRWpMZ2NvMzViSzV5ZG10ZWNzaGsKLS0tIFROeEphQzRPdlBrbmo1eVhZZHVZ
        elRVUFpmM2xxNUYvN3BaL0Exam8vOWMKjYlFErVGHwcWfhJHqIc3eP51g4R/FUir
        8BzlpIbovoPW2bt8aXmrOtugYltBzEtAK6d1I8Te+MXcK+/1gBtFIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:/IbbZ9JecqfnzxLOrCArlJAaPBgX78IDgU/0bvgECpBGHlijQ4fX9grQfzhFv6hF5CFKjdzHcxADetg5Yh/1c0BJuhINclasaJnhN0uwNuF2NEq24Y8POS1hIj03MSLV1ClCqv6cn2sTpizi26ybfj9qM3e3Pjx9lTsEmcHA8+E=,iv:hcnXtHwXWlZb3svnEfYE5cF/yGMQkUP7lQOi4MbySes=,tag:k33vD5MYzbkVvRGYQIlM7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
