apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:V79GNurt7hoda5kKekdYmkMi4ljaRJtmCK23O+x6mHWId8hkmKnMpDqbmUDil1Uh+MoOvkRIkowbZK6R6EIh1s9NGeKAN32m0d4UONYZJVzG1hmsL2L/luDZWrQ2xGhjKoawEwFPEH2ID0BTMd66e7+l522BPFbyMEs7621QhBteTp76+VuoDGZcrPvggHoHeWC0mv0oXGFtlTB7yL1wmWlL3hXeTWlyqdTQrz/zjFv56eJp,iv:1A3LhOHibMQrUT/VTT6RsrhRsacKpuVA5HWPqolElsA=,tag:5EY+s+F7ZWJA5DzRxBYJwQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YjVvZm1hZnRVOEp4Rkpi
        WUNGWnRHOEROazRqcGhFVXRnbDd6cDNGcURJCmJZR1I3NlJCTWdUMWw5RkRob3Jj
        WTlFaFZ0VzA0MTI1VGJQcGRFYU9vNXMKLS0tIEV1cEJSQ0c5Q0dxcC9BQ3J6TmVm
        T1Rkdy92MjErak1UZVl5ZEZ1M0VleHcKUicQo4WKBeG6rTcoTorjblhMD2esk36+
        mNPqCCeIHKSew9yGxD2IcixdTX1qS0csE8U02GOHICBhUwmeB+lplg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:uhlOn/CQavt3RyDbv7QmTbBhKpPQ3esPKdeYqRvoHYdRumjqoejds0TlhNIIx+2jZICW7aQx6kgkmMVf4uq6xcjvffF2ORhmTS7lckHa1IGrkoRQMlQk32ticMMtrKBfoceZJHC7h9XHt57NWm/ZQfpENnXGVhXORvDHg7qqcio=,iv:2COFK/e9yyb8C/FrJOXZgtsvTOPtBKuEsHeq04ZyMOo=,tag:vf2BG/AFrZlAAX9GSGxGUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
