apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WcCRaFhu1pY8wkQJQYkvX9DjbcW86OEWtnjiHNPip05FbuQEFDD0pudTpPCx1N5lgIRXOeKNqZlVKgo+hNm5ZZa5SMC+iG63iG8fVdIFlZX4adECEsmz4dOaEECkM+X6rxk2lphgKd9QmqapzPdiCSWFMQPvINzSehADSr9p2sA1cqxKpP9ii5/tMQVK/s8uhzjqvneQblg5K2fFiKbUYXSr5VPw8+fhO5/4aHO0h5yf1re0,iv:JTAUKiYdUej9+jgnBicSRFQhN9HSt/SOd4B7pqUe8rQ=,tag:D8UxouTZCclNhvLNTEI3fw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcnZKY2d2U1RwM1dlOG96
        Z3dxb3FTRVRVMXRISzBkNlplSEJHTWlzTkRVCkJCcWs1dnV1V3dHTFZUaUY4L3Rs
        RjVvRnlOeFlCK3p6NVZacFpEK3krb1EKLS0tIGVHdjBNNXpKOTIrUFo2MVQvZDA5
        cUJPMzNJd0JTdU93cmhxekl4Q01YR1EK+ZgB8vXuPxB0wT2QEodiDnZ+AhR9ktpi
        7ihFikoJyuXzL7Sjn2QNmL0pKxk7xCAtqaLsOasIoTQGtQ1MqaDb0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:nmP8X2hGzOdQbFoB7nW1peFMslXZJ3IjV2XWTAPevCsA2cbpBsZsM3ZhlaSzh+Lxw3xttrPE8B7oeqCNqDi+DNIGhCM5PDsOzhi7XsSGsLw8w7P+bTYVMHp+VQwj6QlqPs6F941nw5vdM6l5cWRituuPueIyRBGk2dZ3qJnzdPw=,iv:XlyM+0AdZRp1CiL5BYq3ZU3qqpCdshyvnCgep6lmI4s=,tag:V5qDv9OOv2Zmeu28JyVN8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
