apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yX4VNaSY29W0Z2WS/nYuLlxDD9K1qjI89PiOS6wl9YzGNhQo/rf9obyHA4VA1reTRM1XaBfWKFiYkw4SZ/FoOgbbopBhxUhW5MdIm0+CMpywl0hb/Se4j063r0qYwwDFAVejh5nFJcFHIqygY+B22g+fPtSTi9yrK2AABDZ8XiphpgZIwF1jX1r+eYhfD1zruFC4zOXtTk2XZzMCSq5MWtAyw65WX6ZFgi2f/Pp2BN9bnv+M,iv:hlgPEmJgRIDlMj+KvS3mvr0ki8qK/P4+431H4sfjTz4=,tag:h+PIpiIufzUY3LR5SANVGA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZjh3aVNBMFRHbGl4bTJn
        L0VYbXgwSVNUTDE4RmhkM1o4cTJMZ0k5ZmpzCnVyd1NrS01KL1ZWdnRkZE9sWHgv
        NGk1Z2NxZ3Q1R05jNk1FRnNVZFRqY28KLS0tIHV4eVoxSXAwamNyd1crRkVhNzZ0
        b3dJV0lmb0Mvb1MxNWdJbmF4bUpvTDgK7389oJlh1OXPhj3F83DXlmEoatU8eoaQ
        ek+Xq9/Z2jxZPi5MmD4q9WDMuP15JVZf2lG/JyeBj8EBy78dGYpnIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:FkZGy9RM7gwoykOQLuIYC1aK4WJeNDkpUbwYFqlIszH0JDmgqCvFF40/vkt151n6/pRoL1T79BFuh9ei9GaM8K1ZoEtL7jgH9RV2Ni08TxCx4Iu2tFAKMFL3M5+5vRa4PuE06v0APq2dFzbqgiesEaHk1Fj3kw5YW9fsba3ZXwA=,iv:ayKffrUxUK6SyqRDtNokaWNigIyUn7y1zulLV1O8lLo=,tag:erX3gC5YRjGKe8/tVrcNjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
