# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:W2qAOo8=,iv:43/9F/CElVdAciMFFXpAwTUKjLRpd5xbIBoPICwcfyo=,tag:ooMF9jANrVxWEZP0A8Vr2g==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:+GYN8MTJeEN+Fd9IOsOIwBEtibmiDEE=,iv:1Lguna6aBYb0P0gDkwXXbntAtOOvTLP0IlTibH84jMA=,tag:RUZhzYN4b7u8z0tbnkuxdA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2REoxcnZCMDVPaUVYMEta
        QkxpenJqUkRyZ0llb3c5eVZSVGRDSGZvOHpNCkNBVDlrWkgvaTVIbHVoK1VmM3VH
        Nmkwd21kL2VxVVA3eWJhdUJxa0hOSlUKLS0tIDZteG1URjdEcFh6ZDI4a0FvL0s2
        N3JIcEJNNWFZMHhZSkllcFcrNXJ2dUkK7BqfnpXFxoIXn25w7rA6b1I7/RCTl1ic
        /hekzQFap7xq8XITDkwbVGrCKTUPSWg+nNPZRTLMhT425VNJ1/x93w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:sn+c2T1MHHiyzL0PbDYreYLWOyR5bLRWTflaqbKtOYQ8J5kyfNLxoqXv8tlGRLSTp5o4LeQoSG/Abbtd+ECzRUboHOpdAcVS6h32FS/3fp4zsA8qP5GrvELD9XpcRytfyORdm1vNol4iT7cA5l0csD+0UZQxBuYRVru2YrlBmx4=,iv:hIBkBT/6altj6Ay6zmBwVnkDoKfBjxGOuMMQq3Ajju8=,tag:Ni7z3DpM6XIxqr7N5NUY6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
