# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:zHGBOc0=,iv:T3RhK5/myKxXEY7E3mDzIKPIVSZC6xkczaG5bF3NI6E=,tag:2DalwM1tdUvyRfHCKjaAAQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:hu2h1NcNHz1HwczM6C8g++2a8Y+vKAA=,iv:Qih9pAEtJnurjpDoID+yPIdmfYFr8RjCJhsEUmDAgWQ=,tag:YQFa7aTuDMcaFLGDG6IPtA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dmhNMGc3TThmSS81RHp2
        OGlkUjcyTU41cXRJaTIxMnVJY2JwUE8xUVZVCjVJKzI3OGNqbjQwRWFDUjdFYnBj
        YTRreGp5dE9JdXJpT3l5N1FnNlBWZ0EKLS0tIG5BdEJKMzIvK2t2anFSYk9rOEJG
        aldlYS9mekJ5U2NvMUxydjB1MjdaY1UKKpxf+4x2frygKXRrBCiKP/+hHNtPKeMm
        Ww8A/cERnhjB/7i5pfI58SVlhk7LnTBI8w9DEFFVVqKLDOOB3+UeTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:e9fUtMU6JrkZt9tDhiDAjq+RHCgX3SciZk6IFpWB6uo8DuG1CdLVxtYCzkAjA8O0L2ev6JLTCQlSECnsDHGAPL+RqrgzXq1ehQ4f5kxDvPa+EFNerjIAp5LkHuMLkNbdxpDyKuIpBLGCS4ReqgBPiAkWa3SfPGJ9ueCLsuXvNLs=,iv:r2BY/9jJtXtVEtEfw0162dbvZPa8P1R4XiggBLSym60=,tag:9i1VXOsgbpn3dTqOXdc28A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
