# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:01zGAOc=,iv:M18NONANti8/jb3eJpv3NDjn9CJ89mr8qPzcnIyqez4=,tag:bhYJn83wjA3iApQhR8gvAg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:uYiEIihTODipkGkRDqHYjCyEV5qdcTE=,iv:OYEhY3QK2IwfCF0ldtEWKTs2s1SHNmJGgAehEiHE+7Q=,tag:3Ik4U3/BHaMIEQkcmaQIPw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQVpnd3lBNXZ4aXBLc243
        eFJEMXczendQalZ6YUtnYm1mSGVSeWoyeGc4CmJYUVNrakhUK2ppaUI4RWo2ZjN2
        Vk43Yzlza3VlYVlueUxYOEFtYkw2RlEKLS0tIE9EWGZaUWt2eWJvcjIzMk0xanNq
        a25aTlFmNzNOK3NkVEFrME5UcFlCWG8KXweKjSbEF+I63O+muT5Ohkq1XZRyPCJ6
        us2BnwXtBQRzvpscvvXLUSHV+07K1dsn1TuGiBogDqKxu4EdZCQTkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:8ccfeur8/4wVDnhgpEAF5dj0fa2C+chmItYeW8iajP8n7xCtq13VlpZC5clYxi5n+NbLdFHQMFsCV9NwALFz36qHyaDsZu8QphvRy/CQT1GPLuYxCnGaEIsEFOZRmC5W2jt8OjUBP4u2uUQez0BYEh9sj5yzksQnRzoUl3tCFuQ=,iv:p1aI9HlA4oRClXLZlbQpjdKMvxfST7HY7HB9I7QPPTo=,tag:2fYAEkp10FD1rU98JHX2gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
