# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:wyt1hP0=,iv:b25mWaqNI0htSwzMIMVcbHmmve0uMxKFYSz/tbL61Eo=,tag:QS28zQQh5O/odEJe1CS4oQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:r3hJewT33K3r3v4ZjfXe2w/c+1vM6fM=,iv:6hxgal5q+I95TlaqgCJiO4QV8JpfoGUQlh1KLhtmvTQ=,tag:lmCWx9DVxZ5UYaJHZumcJw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVXVodit6bHVvamVqQmRa
        LysxR2thempFNUVWYkxlU0tLQ0lRWjlnd2xFCjZtaGh2OTg5ckZoYTVScjdHNDEr
        WVorSWcyQWVFOXlXRE5CVEtrSXA0Tk0KLS0tIDR6VmZERWRobGxWOHJrWXRaMHJa
        dERoOUZIVHhJSk5JSStWNkVLRi9ldHMKLjvN3I8DWwMxl4o3qcIPdWyBB1hiAfjx
        3KIwfNh6+vgd2PW6JZsjoOPXfB0YV1U2YKeAipn7/EvCAjSB08jp2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:29Z"
  mac: ENC[AES256_GCM,data:lKENFemgOOvD72wlbmmEtJzIhJf8qS6iWqoqYtGaTKuqwUbqGEX26f44PUqQwtMoBPaQnpikEQuXOWwVsZZTq6+h/BP+owT7RBuqzRFH03ZToC2RjwhWUOQPS1THXN0MYSFUd5dCZwISJjlcES1PU92iFBNC/W1IgshWF1xHRd0=,iv:NketxM7yVMSS+oFDvrb6VW0G5JV1AnLeWblxaf4BkQw=,tag:xlPIyEmtgOEqJ+QjzY+ZKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
