# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:qPRE2zk=,iv:P/g43Vu17tCrax5ckrltKNNVwf7PbO/0oPTihiBiHms=,tag:1fjTkrKMMURt/mdkp5VT7Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:G4CBVq+BwtZa/WbjmNG9JRp+uXVbwt4=,iv:MhYVc5wKE7AZ7+GcHntodlswmQBE4bkV7+669LKevCY=,tag:LokIsBCzaz7M3xWnGDFC5Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0ptKy8rQkp4YmsvRy9W
        Q1FxZUVYTlFjdTI2YzVCeHk4M2NLQzdweWpNCjFBdTZsR3Y0Zm96RzRBNUh1RVFQ
        VitYYVllYnBmbHUvcExvWTNzOG81dXMKLS0tIC9iaG9IOXR1bnFkbUZDbytmYll1
        ek5nWVZQaG5sdldKeDZLUXBQNGl3T1kKWQ8omE89C+HDfLJCVJX/VNdB0S++JziU
        SH1a9fiOBU8F7nkRl/E+Rxi6xYjmoCEMgXr+45F/fLhg+5yBKBVkMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:YXmSLDYhR3OmRfgDM6At0L19V4MwVWz5/rfPsj4bJKXoH5SQDWHlP15mZgZdOw8U3CQYRnClgvB2LW5dBtStY5qplpXiTlbi/tgOYDg3rBDWzfDgOmCBJu1FwhEEDelkEM2YZmcn8mv2DxEnGOQtBT+xPDYWMAhw3f/QCFwSOQg=,iv:cB46DIneIVunRRTht08H1dndmt562IBhCHL893+XXzY=,tag:LHu/E/DmuUpUdbym15stZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
