# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:McBlh2c=,iv:yOCH2yosViDZ5n7zz+mEeQxgHjxzgnLedi0p/V2oVMo=,tag:rJzl4ZbOtvAF47dShRNxjw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:ZEYp/ztQV9EXJM/JRaOqDyNGz0I/JwU=,iv:5/oz305vZosgoWMl4P1+T38MFFpXPzX/UlqzZ8mrXqI=,tag:LglLtYh0N+WdYhSktyGCzw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzekFGWGlEWTZGaFJDTFZJ
        cTVsdW1GZzFmY00zTjZVR25JSXNrK0tZSmdBCjFEMWxSb3AwUHN2Q0ZEemtmeEMx
        dHp1VVZtSXA3VTVDbjVaUUsyL3hpK3cKLS0tIHA4aDRFR2lYNk1BME5tQ2piemox
        NXhDU3NVdlJJZ1o4Q0FEVlFWTHR0TFEKEilAlZOr2HukN4lBK6wWuMO5NtsHoRZM
        WRV8ejhFgDwOTFW3aX9r5TwfGkbKXjGjiS58bq8mjAz/UgsxLSv0Pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:q8TozkNOHlEfIHUAd3oC7eVvyPVVcvtH98a5tvTleQFgss/zQFRy8AsCn8ZSUvNvh9eaeUI+aLEC7LNyiBxx2dBkxcLM4KGB0OE17o9PDeO6h+yHgFSFPuemFeIBDNcMvgiW1832pEEXndiUB4PqDzFUdhQoCdyZ9Y3LzeoTGcc=,iv:GJjD8Cf3olGOj2Ltkx/IZwAJ7g503DEGmxWJPjbCorE=,tag:P7ooNepK6Q+WyIwcgp/AFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
