# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:vz02R1M=,iv:cpHjPRo60bmmsxXxMmrRNBkF8pryyZuKmaRxBQ1cYsY=,tag:WFYf8eqUbMktgbgLmrZA0Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Y1yJUvrGX20A9WrTiy+Hnsumjk87anU=,iv:QEa6hyqrQKR7mioEcwfmYSyrUErzkT1312YcJkOdSZg=,tag:aaxA+mAfSp+uszUawUKQZQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUnF0UjdTUkh2bUExMTlP
        aFEvYVhWNUgwbzRxT1o3RVlETGREbTEzOWxRCi9NUnc0M0VjTTFKYTUwSWlhUnZO
        NUVQcmhnZm1XWDlXeXViZlpHUjlSZlEKLS0tIHZ4R3p1dUlrU0xKcWU2RGE3MjFp
        VjdwZnlxUWt1aXBwU3VOdDR1VGUyY28KIIkMeXeJ0qJPhANIlmdZZwOki6tFaFyk
        rLoXeXnNT0JEv3xZ5Wc+eD38kKBWN0Y5Ye8W7kaO1/EDY/5oi/Kjng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:jvfoYojP9fSq0Wy8mmiBkpVAFPnhn/Q0W8kOWlN1H23iVWNvRcR8OteJokyl19u6iZkJYNW1PzL/Zhjf7cj9tPUrz0CNtXYqDG/+gTEMrFKE5TnrAVQQMLRe4KW3bSYbU50wF4KHJvT0cNTcITNXh73BGpgDAq8hINyqpe4kkCU=,iv:nCdxUO1a2HRjCf9Mklu7dw5H1YL4DtTcZityW4JFJe4=,tag:1FJgQcN/02gnLL3vVm9DuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
