# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:MaBpQ4c=,iv:S1Q4MWA5YmnIeBs60mZds4x/D/E7NB/SVlgJOmXg+zE=,tag:g7MOyRSWEB309PkkupVVLw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:WePe5m5qsPWS97F5qUBDmWtFElTxMBQ=,iv:iWWblCNBQPuTW4VubfARs2Nk1SDGLMKXHcC7MVnZ4NE=,tag:5oWf15ZllnxaMZ5D6fJ6VQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibER3R1l4enZpR1dYZXpU
        Lzl4Q2d4alRXOHcvODdCM0RzbUtoNEZkMTNVCkZUSDNXZ0llWDJLajA0ZUIwTjVG
        UjhuMHdvYVJBSEFjQndVK21aQ1NpVlkKLS0tIE51M1BNd2RjZGEzajUzKzdSQjg4
        MGhzcCtyaWtuK0t4V1g1ajRyM2w5WVEK1Us2kGwuavlw5v6tVHaMt6hb9PhEPYG7
        1rOEhNshRiIbbsEM2vdG/w0sEoxzKNXBNnpvBqETPnwMmR0QPAk5Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:Hc2DlUXeBbrfNaDTgtZmmlzglvIhU8fqL+WW5x2TKx6qasZA2Xd4+OOp4EEiSxQcI1WFDeYYbWUa0b/eB+KSa0Ku7XS/noI0rbyI029jTZjEJVchBwYcEzDus3YTrg0pBPyj1xXX33qzUjxrLcysh7ZirHTBSXTG047p/7AHPdE=,iv:fIRKiaT4OiMHBy6k9y5OlbM635pXz0CD5cf5cDuOSgk=,tag:NYxrte4MYknlF20JYW6NbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
