# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:VnJVVek=,iv:qDFTkczmQW/cqCVTQGlfKU7ZMEXYgAuh6T7YAa3TXhI=,tag:5pzNWZLL4hbJ7NuQ5Yn9mg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SNEhfFwzd6BW1GZTw/VNBITYkZDXTdw=,iv:HkvU8ETRRs5C9f1CW2rugxXLhVx2ZUmKv2h/IqYN2Uo=,tag:j1tuYqNVOhotm9Hul0TtXg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVU5DWllzMmNvTndJc0tq
        eFhucmhrWFloRWFNR2EwYllaTkllOHZTN0JvCmY1cGwzQnZ0MkpYUHVWeFRTUnpx
        dkhVd2RuWlh3TTNUMVVCelhDWXRoNVEKLS0tIEVTWVNabGZDWWF3OHBNemxiTVVB
        b2NQMitLUTY1LzZ6MWNuczZReWxFN2MKWPsBz1FfI2huAJ5y1LeG/jh/lqP7++aC
        geXwt9gSpzbmPXhpG2dK+IBo2r9E6ZzbvfwDn1gCsLPIOhvPt0770A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:30Z"
  mac: ENC[AES256_GCM,data:NiRXtwmATHZgXNNHvCaCn8xK4hUlAJtXkER0nFimnCx23IVfc6v+TZMOd9vlAVnsEqicLjAFCQlwlDm/oVOdf0D9eKRvQcV2L07KQci/6xnkzKT7TILh3uyKX+jbH0S+WhImSIERwWvp56O+jR2MY2cCm48QvXC6WzmRfu35nl8=,iv:8jrVa8stpPkM+X3DjwcP20BGSUMe0JO9qYTfo6cA3P0=,tag:ilhJ/62qiqP/hPaUaFMg8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
