# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:idWWDDw=,iv:XIX/6HnHIOHQvZu8QA15JgWPF0QDNcNMHW+g688X55A=,tag:dJVPWj/0k6mteLVHnYQ1Fg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:5hkExJPClTWOkNKZ6PCZ/pbR2IdtK5k=,iv:rPovUvIzgiQUQ4JJPRx1/9yywqlDt9ANpfgXXgO4wD8=,tag:c6DY9OTi8yhZhQb3EZTAgA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MmwzTVhld2Z3R3M0dXZJ
        OHFtaUFibjUyVzJtOGpZdE5jVmF4RWdoV25VCktTSTRmdVk0aC9EUm5VZGMrdi9t
        OW5Hak1teW9sZDJSYlZGV2MvRDhobTAKLS0tIEFoNkZReHNiVkNxZkxMeThBM011
        Q1oyZFQ1QmlUY2RQZDRuTE1oeXNHMFUKAUAnZ2XMKSA+C5QBlb2GyUDw+I8f/Tbg
        rQw6bbawHTI/YsNPQDU8FqSFfVLtEBtNd+4/eFpOMuOQHlPiXHw/Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:oojU7kHNzlDtzAeFpGGx3J1mI4bXhZULaXVITCdQs+grF3qgHWjqkx24s404iTyxen+B+zbIfMhKt9FJmn7atw13li/JqI41nh7qKSZ6cgrNY76BaGDowQF4oikFwkKxkoHjDDKFRYRWZGuUqYHoudXa04o+W8Dl3b1zlDb+asA=,iv:4RqqSydDHpmW+4/pFLw8dvTeVSgQUSElz2DaEcZgM/Y=,tag:200gGKHTxohkvs2Wn5U4qA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
