# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:Qxysx78=,iv:T6JFEmIzojw+aeFso6GtjdUSmR9PY3UPVi8s3uLVn3k=,tag:jGwlRHY+Hb3uv6M66e4WTQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:JWYfLDCuFmZzRMXbZl/IMOLHGkP7SyA=,iv:/wHty22RUW1HcfmCzK82H/rvPeqSvsxqto3l18o2++Q=,tag:UUKUq3plR3dRdFhYpVo/4g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd2VvWEw1cXBNYVNmb3Bl
        R05sa2RNUEJyKzU5aGU1cFlaR2gyUERleXhRCkhSYzZxWERkbVQ3Zno5SDhmUGlk
        aUFaeEF6dllHYktLTFVyVWI4UkFMKzQKLS0tIDlhRFJXaS9wNmZqcXRoOU9QQm1n
        K0V4ajZsVnpJdWN1YVVYbVZ1Y2pIVkEKjxJysJ+HwGWrY92h/SERz8XmFDVcijJt
        cgNLJsSIt8hSCxyeKOTm0yKpIFP5QXD6UZBUYtfuoAFaewCnHvBOFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:Cl3fvw2nexlL+B1QX2R0/v9HdWeF4CMXoDC56O1TvgRZtPOqZq4y3nVyxopQqHgb7XMRShUWbKDjasdT4L/+RixoWMLmyyIswQFZ2pDURLLXNpYYziXWtm0LywHrpGwY/9u6/y+3ZPJ1jsMZZSTwW8Z59EpyO0G18VrhLFJyrJ8=,iv:MNOZn9S8Ryl7hz7UGPiRrfrUbKr0W+Zpp2zQA+ZBZe4=,tag:F9VOyQFGvjH3sVwBLsbiIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
