# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:HPOHr94=,iv:WrfNX2bjbfjRnOXWk01oBGvoJyw3WjOHKMoqwA2uxiI=,tag:T/XzxI+QDR2eolQ2yNvWIg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:YuW/Wx+0qQhPzgOaE0f4b6BwO75o86E=,iv:24KxSNn/aQEbtzC+8wuRlc89jI/irQNhietHJuBCDgo=,tag:ZROnVsPdG/NDs2iiQ7lVaA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzlNcUtzQTJ2NmpNajUz
        VktwMHJXTWFweitvWUVzdXhmeGYrcS81cFQwCk1iQm1zTkxFR3dvTWNnOSszM3hH
        ZHdWRmtRS0JlcXpzMmIxbm0vM1lqdE0KLS0tIE1DTHUzYVJqanNlVzNoQkxlV0xq
        MDlDVEZOZEluSkJyZ05WbGRtdFNucnMKvcwZP35nT9/tTTmzlGXRI8rOECfCihm2
        FILFS6HXSX6f5h64oAT7+utbxXqGffIlquSz7iKnSunFRsYcT+99fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:FBWrP++IVHEIkJkEcXroNy8oPDuo5S3S5fHjplaYoAqUAuusgI2EAIyROveTqTZdo5VLsAlASOcH86FazCvyDLcp4G0kF2HmGAGSYfxSPKMiqUBKatYzcp6dqlZqzJRDdF1TY/PpWhddDowFziTksTEhthGdOyF4DeErMMmNnng=,iv:R/0B0IpG0LBrRzJTmVypjc4Ch08idUwhnPK35ZGwZso=,tag:cKB4SugezA7Q2a6TjIwm+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
