# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:XLvYRBg=,iv:cB/wuCFR/OfHV/bLISB3c1ytdN3yi+CF7H9SmkegBbA=,tag:eW2J+QhlKsZbVR+XZn+9/Q==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:nJQm8DiviFy7wFjyF6k8HJXFqUCCzSI=,iv:WXd9BwjhhV1jk0BwvgNqvKB/T+lEPTz2BCmW4Tv6/dg=,tag:3TU+R7qucdMLuVqswT3Yzw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnckpsaVNDaEZMTC9STjdx
        WEc5MDBkNEl1Q1F3Uk1MT2lKU1N5RWVpRm5ZCk1Lb0dXOTRRaWl6Y1ZNS1NNVWNY
        bGIxa1czYnlndGE4SFZUNXhFOXJXWDgKLS0tIEx3eWluQzZselZ2ZTBrd2tyUWs2
        bzdUZDRFUExEd3M4MUE2YmtvOHNOMFUKT1uhrlPRF103DJ32syaXMdczmEttAhZF
        E2oMUur65dDymzvOCabnL/+14QxjGhR1wo14l18JIUyFZBSqBNhdKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:00Z"
  mac: ENC[AES256_GCM,data:zPViIGj+xDTNE6hIpxbCsSHKobTLX+hDzl3EKgyNpIrq8S1RnM3JUHw3Vw33pkA+QTWVVspR1wJhmAZ5m9CdsdbCCbVjsiV5ejsNgq8AQi0jeIJGtLoaoS26wKmwpCIt0a1N5TmIMwtpY1ZBCt7IpHVLV1AEZO/gwHP+um6jaZM=,iv:JvbVhw0XWjQmOZDSCOUv+7Y8BInSDGuM8JN33LikqPY=,tag:21dXERAWLnRwePvncCGNPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
