# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:+ajI8rs=,iv:6aety1vVyC0T6VeC1Nvjo77WCdqMxTPkEdX1z0r7Qsw=,tag:M6VEz7UKwVv4bvwR87E0rQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:XU0eQzeZlOUdU4YMeedYtlQWLFMiIzU=,iv:XwJzYSKwGdkGcDWEINdUChIDlOwZHMsRnHVXvcPIXhs=,tag:xEL7W6py0z8OwXYm02HaWQ==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3FoTUYxd3JLZWdNeldJ
            b3NLNzdCeWZ4K3Y5SlNqcEZLMk1XbVA1VWdJCnRJcHY4Vmk4YzVIdzRMOG1BNHpT
            bE53ZWhHc0dnWGVOdTBXdG5mTGFKcmMKLS0tIHUzMjZicjBhZ2NyczhwYXJYY2Zz
            cUR3WUFMZllHNlBOM1I2MlZUNmgrYlkKwfrIKMpQgfJSL06gjeA9VW3yA6ZxXR4R
            YLF8NkfPd9/E7meZwTCqzg6BYd/iRmRCM46AuDU28Hk5qpRgfKMDwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T13:34:12Z"
    mac: ENC[AES256_GCM,data:/ErQEO4jOsSNzQRxyYiG+OOXXtxUD5RSuu0hb7kCprjZLop3iqC9840eIh7RBxoNW4nkN/gz5g7O/ogsCHBeNEPXkfLZ2k/0jZ+VQ3KG252YmG79DysD68dSMU54LpSzIFF95GyEbylxlidhkbps9VNA9K92pkyxzTIUiePuXgw=,iv:ySblso6ipGi/CjFUBxzvOnwqOrfHRLnnULO2UG8x6AE=,tag:Gobg+wWSX9eNlEvpGYNnjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
