# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:gZM/VGo=,iv:Ar0GN9t5t6/oXav2DJ6OWQWWO/4s0xa2SRiZ8r6F74s=,tag:l+efOYsn27EscVwS4deLEQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:2XYYdjsvX3nZofKQo2REfumkitZXu6g=,iv:V6RAxYR5KyuUetPhS3egMeB58+Gk0vsR0DZT6e0WAIM=,tag:xN7WRjMh49ZKQaB4fNDaTQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaXkrMTZaNzZNS3RWaVo0
        TUovOFgySDE3SjBVUDg1ODUwZXpveHZmUERBCi94Q2pjUXA0N3lzUXlVN3pCTFpG
        bmF5T1VMMTR3MGl3UTg2aFNodHZyeE0KLS0tIEFReDZoWSt1Zk05cWJYaFZ3bito
        THFkazhKZ3g3SW5ZZVRSOEpSTEJSSncKKtokLcDVARxoTvdVMPqc/yPlFFzKx77t
        kfEztTJXZdBMwo9SbQINARQ5qBTkygJhfKydo+TTmDquTp9K+nLYqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:1YD1S7cCHeC5QtBqF2Mu3rAcirwQwQq5NJYmtD1ulqu/Fi8GVc5m54pdbBsPNjpVO1S7+KyD92/VHJu0hIN/FFd1z4WlIaJY25mSemv7EYGHPb4sDo+yai9yKEqoWpgYA59bQrgjkNaMI2Bqx79QR6hTaPxb0FsLl1tXdweeH7g=,iv:MQOc9KfjPiW0sDLY37jVliv47YHm2KNZZDAIxlbillM=,tag:jCROjR0TrvYnSmEC0OGcPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
