# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:5y6cL7I=,iv:bujuC8TjGds6gAFbml+LCZPObo7Wk0+SHyfNS3/ubIw=,tag:FvLbv/xs5S55Og91OD1YwA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:8jvl1SuK4v3rUQr3Nwpab1lEVkAG4JY=,iv:mirUYHe79QUARmt3KsQXIi852Mvym3Hto57gFlhnewk=,tag:/Ut37ZEfnDpbIJvmcJFwjA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcVFXL2o1bTB3NTRKYk0v
        cWJVUUc5RWdRNVpsSXFZTTczWi9VTThpTUVjCllLMlhvdzM0RHdXQlJOVE1pSW9E
        dDRETjdBcnBZb0krSXh1WjR4WGxzTzgKLS0tIGNwZFlJRTc0Q25URVlqbTM2RWxj
        WFkyWXQ2djU1YVVMMnF4ZWVMaHdkL0EKk4ZjmYx2Ia97yE2LnIV8uICS5bYQRDxu
        0JklPzXL0fi9BnUORR/M4z4ibtpKPyVrQEw+h2yT3bBdEd8eNciLgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:aTYQpqkA1dODkaJNejx3R7/0KfyKYkakeXVoXzRwxO+7uxVSWorNqxhpTYGVjh9O5mJ+Ok8xyaxUJfbkpMz9BQmrDhyT0ijospJOiqlmvS+ssC01WjZz38jCZgVF2zZh4MAZ5dxK5Zbqw/vKJfFmHKLdh2qOhBsZmNSI0bbsUIQ=,iv:8PYbIcg34rAGiA7AwZ0bPJ7aaMMbCWxGsKzn1JoAaS8=,tag:+kF4GXk3QzneFJe73+/3pA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
