apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Fw5Zcdq+ySj0SCK4phDn42YgqTywpd12i5TxOWs2ruqkUwXh413Gxw==,iv:hT/Ax2JjTCxfoTKxawRdW3gF29WsHVs34yxtslc6sPM=,tag:UWU+qnPMNgLyTyDKiiWkMQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVamZQMWUxSTMvMFJFb3Bw
        RkhhZjFqLzEyWStCdFNmRUcxaVZhMzVqemxjCm1pZHpVbEU0SjRrbHgxZ1U1T2tv
        TWU1Z09QeXUzWmFITVppQ256UmNMK3MKLS0tIHh1YVIrbkNTem9SV3JOSks5c1dB
        MGRKWThOcUhydElzbGV4T3FxMVFSNjQKprw3nwPZUAsHg+xKu6EYG/b5eEmOlIZR
        AyYvHyuOM4pg90rmbU1gosRW3k4gNwx1JwDjkhaaF68/IUqzib3FkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:18Z"
  mac: ENC[AES256_GCM,data:OUVZtadNNQIgjwSpWz66byDyXOd8iWs5hC8UqoD8i0MGE5uNrnEgsDEw5YYs0bHq2Ka3XcpDuyXPCYGtaBKZ9aQ7zgYhLtuUZBb/Kiqaasl/0RRJAZHVfHzrgMTw0lUgUH1+EOcS+BEwOJwFR5CNnbAxNlaOnk4LY+Mp9iCL/Vs=,iv:iXrb2tEn+6PtbMFHxRf6w/R7pRkEpXcv9nVPh7gdqFE=,tag:aTA27Uk/xVvtoLE9f57OkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
