apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JEm5s+zOS+jXEtSu1Ps0ATt2keIG9r0K+LI/IvxHjMTtNxJQmgstbA==,iv:oqWimse9HmP6MBvi5irzD8hzaDrlIJBH28TH/YnOF74=,tag:Nk9r/17qz/zIWkkK4qHsJQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMU5IckQ3ekdBaStXMFAx
        blZvUG1FYzdzMzQ0cHByS29DU2E0T2pXOTFVCkNNcXhmYVpUeVlXbTNab2t1YWFh
        aWhTY1AwN0pPalB2c3R5SXFZbURYK2MKLS0tIFVMNzNIMnl0USs3T1hiU2dQd00x
        eW13cUNSdlpBUGVKRThEUkgxNXhmQ1kKbrYVZ1nmMEnJto9UdXTjOIggEvi/8Jvy
        FZeW2nAEynbIToKONLMqqpFDU1gsCuML55TfZyLhw1P0QP91Ss72oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:48Z"
  mac: ENC[AES256_GCM,data:5N/v/ESIklwDkesaEruZKi3NQij9KkAkuCBDDdrXmCma2BA7iIz7AL74/ee7dc9vbnnNIqNRi8G0e98LEfnf1sOjJyQRvNZ/adbIbsYpZVMrWy9HfXbme5AVJyoB1PnirKoV2ZWzze+gKYyfcqNp4ZNy5Wazi6Ngm1d1EPl/2XM=,iv:76i6kHM4UdnfD0qZDpTREEZVxSbTnRPGmmT0oQOVEBI=,tag:f4VGumSVAytxoM9M0dYn6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
