apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:t32gx4GAwBhmfT+wuK9DSnDftH6N44EuUrpS4bAVnwZO/bKOn8OFkQ==,iv:KgKvtXUwkqA2iEqhS5ptMvXi8MF5mfPfJrDhRgPli30=,tag:Mc8VATby6+wNI5xofGBdBQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMVBHT0FNUHFrSXJxUEhl
        MEhrZmFWMUwzendGbUkwak5wd21YUWZhOFhjClIxRFRqR0tRSzE4WlZNMi91UlZK
        M0FsZ1FUMzRnRmlCTHE0UmZCMUdtQVUKLS0tIDBubWIxaEdSWGNwWE9Wd0xsZmFL
        MVYxWjJzdHdPQ0JnWVhhNTVXRzdMczgKZPccH3meRxd7WYQA+k9EMhYWGMwhmch0
        WCV4n1tpn2P5VbGwq4deFMZXNkMN5AL6v/sBPgIIKiKdvEBptYOTuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:4wTXGn9MQ9sNbx+B6S215wXHC+UOndv6+MEQoMn8fLfEb+QenIVNI7Wv91CXIp7BW0yIujiy9DFs4RiYoYNT7fESWeGrhPnfOvRlr9EVi8hVnCPbroa4tQIjXI2uY57uYNiOD2wiiCQYxVBV4lt/T+pRGWWP4pycb35Cj7ux32o=,iv:YWoVBoyQhya/piHx96KRl/OjBEehICycz9uknfwbKTo=,tag:7sH3n0V3jqKm+dtux+z3zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
