apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BX6z97No+ksxS63MjOtbnIRkaa8OefqoNLhPaZdNLpunbXiHo0Yo6Q==,iv:lcYX0ZWU8SumVYeAzPPU5Cx4Rvwa7Hbd514MUhKDYBg=,tag:hBuuc1uc4hrIsOqEEpUPlg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOUIwT2FOUFNLWnlnNDNH
        Zk03LzVLaHhueTdjOXNoUER3dFpxS3ZBUEFVCjl6N3ZaUHZoMEF3TlA3Vk9Ra3ps
        SXA5RzJvMSttelZwbHg0eGc3T0FzSTQKLS0tIFBEQy83KzJDM0V1UTRYaldmajJs
        L0NQcTByTGw1RWtuYzZTbDVOQWx1UHcKKWLgGl0zDEdFVun1RMVKdyD9tb5ioWbX
        mHr/7jZr5xKtEucUg52XXt5zI0pSBfM2y1yYUHxctfjo4tUfVVnn5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:MAGE0KLVLHixgEMh67lmXuZfKVyXNpKzZjwEnyMPuwqvwf5DbxSekabA7mhcVVIZ3fsTgz7LZwS2VEazyXQy8mUE1yH5J+HvksLq7V9m8MbISiS7Fs7exMGOjM0UOhoJLf5d1wp2MY3z/vAO0esKVacqFFop+u4+sDuP1ZLzbYk=,iv:oNByj8amVUvcMFP8Rpar/tB3uaBr82qPoY1nuxqDzfo=,tag:ZS4J2QWg70BFrWfhLZFkuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
