apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:VIR+0AgN8Ry1o9+rYPB0nuQhNomJEnRyUpBZCQW04IKpbt653tmMsQ==,iv:IQ5Kg5iBczY5kFmiLwc+snk/b5ceGTI3wVO9J7Ev8Jk=,tag:7Yc0D1OXAKiEtv4s/pETGw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbTFtV2h0WGhMaFRZZDdK
        TFlubVRNZzZJS3JHWG43M21sY1BQNytNOFZzCmlxeTYzTGxTd01LMkFMeE5pNlMw
        TjRrV1VZRW5QWkIwSkZBdmY1N3BhVTQKLS0tIGkvblJDdDdKZlBQemVLYVFvb29W
        QlNKMmdmRm5ObFRBWUFnS0J1ZHNIQzAK8TElZipfrweMvJmlm7lX87vg2v8MrLDz
        fFvS+YYTyNVZDyoohnylwe2FZA7G8TZZBrwQcxhzDjhR7kVwmnDxZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:1enVC647H0NNWHuYWjaXHNUaMcZwMyv2AqB+m2SqTJnYRHOaYbVwr0xHdF9WfeX0U27KPvqsnGRZMt95Fctj7m7faDNQ3Y+BRiRBWq77sMD3jqkpOJMtXs7bCHEcpK5AnHRtVLjnRhwF9He+makZJSi6cTh2pV5kklkdCXsn6es=,iv:2zmnoqTpB2x7H98EJdVMjnXCyM1EmU7Ch3knKt654TY=,tag:bFClPinL8lydTawaPFWWYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
