apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KSg8/xF2GvoIHkA3obJIhXGIOkxzLZRJ8g9PFpMYSRaLqFAC1tsiPw==,iv:iMm8iTToKBNKjPTZFnFyead1hgj8lDq/dzTuvIGvVvc=,tag:4B/Oy8ro7t7syjsPw/7T6A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHVSVlFmeFFTYVE2dDh0
        NUprWk1INk9ZZDd0Z2h6M3Mxdnh5K0psK1g0CnZzbXFvYkhLOWx3bHhUaGlhb3Ra
        Q292MVpsWXczS1Ezam5FZ3pRM2J6MHcKLS0tIFMzbGxpSTdDVUx4cG9ld1NqM29W
        bnNSdE1FZXVaQ1JFYUpOOUx0Z3dVbEEKk1humUw+Iv+IOvLK5te/tlddiMZ/q5r1
        oV0aJu0MUnVjIWMsN92HcFr3hWtr6da9shjp5/sEwf8d7UIBpau6aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:29Z"
  mac: ENC[AES256_GCM,data:7j9N0m6VjUdRTMHB5dtTco8T7yGw7lxfYInAGfmEXYXZLNLgQIa2e6J7r3ElcKVotfi76dWJ+/alGaJ62nlFTctDHPNUkPtuymjHi897hP6XKcrpiWX9HF20fRMjlBjjFBGij/5/0l04+27kYA/3yKXlFZeTJOPDaMMEO+3vVWM=,iv:NTWAuhJtehqI9acdiK/trR4qWlF1UDVqioCnHMcRei4=,tag:1p7DWTToDT8BSpBP1Ocw9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
