apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:C++9rCzPQekzY/tIcQ6DkWOJsFnvoZCGU0eKR0jgKWn0HNyC5oHZ9Q==,iv:KgP6B4nWkbijg7eZYRw/iM8im/dCb2vD1cDG02pkBhw=,tag:6gEw4M65wThCuURreipLjg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUEdsVEpWRHRYc0xlQmVS
        K3VKbUN4LzZwWkpoZjliTlJTdTNCdDJpeVhjCmlNL0ZpYW9zVFFxbUJuYmlEckdT
        NkxRekwvU2t1YldCMit0R2tiRlFicE0KLS0tIGRackJjb1hFVEVxKzcrSlhNQ2Nl
        THZPbWJNc0VMOXZ2WllGc3RjTFFqMHMKCHa3tadn9kn/yJy9z8GgmxJm+tDMxpeL
        dqAU2Beqai+wpeXzrXC/pnh4hSVNOJTsN86cjOKuabduoISQr47e4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:cNYtMLm2eqqyTkl2CTxnNo3snNB+iL9YhXeNrmR99SPLyxFH293ffK2a8reEePprxBnjgikUuJRQrFWNAtpdjRyxJQxDCsqM/U0dg9XWYdafHcjsnviHR2l9fZfbJZ1sbr2NtRWz1TNp4NY1aVdfT3pk8m50RbK11qJB1/Y8RBQ=,iv:QCzNfXEqxvvxoMGjvf95dMo04aNjuRFWyuOlkcO0w+0=,tag:I3hVESkoRDePitGjjl/xww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
