apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:itdbKYCWUkA/jGHVHH1JWZEv0+YWO68JjDhbzImLqFvUfoACgiHZ/Q==,iv:H5OClSTzoDRwrzrAuTJqRekfP4fyNZUOSKkynnRzQqE=,tag:yFnZmU/z7HLBTNHnBPbd4A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnanZOZXFkSFg2VnFpYlZG
        ZHBsSzJPbW1tWVhvSGdRMnBQbzVNM2VoT3lNCndwa2lraWoyMVpFMnppdGVZZHdY
        QkNDamNwZUVMNTZ5V0U2RU12OEluWXMKLS0tIDdKWGxoK2h4RzNTd1JOcjFYcERI
        RXhieVdXUVZab3k2dUx0Tnp0dWN4cmsKMms8/kDwGBfx6yrXxonOKKQTo6upShPN
        Q65l9KokdXSTN5eT1vtQszEucgPAh+B2PYSPxgKoHnPDXTiRwOBlJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:Vw3FgK41G2J2+hWrY/v0H25ReKQBUopVD9ApUt2p58D6nsNg8l1ey5mwE63vVEVcB6ChVrknOBrcNpswtp7jFzM587Oga0ZCsuHwxCekk/YQpVWeK/HemqVCOAOf26+kE1/HU9/WqNeddX0/BZkQpCqygBuy8xnbetkJ3IpqONg=,iv:cWeWT90/Vhi89zyAjHJ2ahgq2w9g0gAtiwgKQ4ogQmE=,tag:37wtWcrAM1uJ5oQYDqysqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
