apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xYDwubusyhIORWJgPa3rzbshOLaevWGY3zBqWzoFzWGATtQGgOvXqQ==,iv:8ujUPjkMnJiQuS9ScjQvOgtx6eHo+wkf+kUrtz1z8FE=,tag:aKg6xh0gR/YaqCC19a68Vw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM3BsdDByd25IUC91dWRM
        K2NISjk5M2RRMDd3clNxcUEya1JrbmNFR2dvClp4WlVzeDVlUUpvMUFlTlNMcmtP
        cXc4YURVNFpiZTBCOFBXWFFidGpYOWMKLS0tIDFIUjhxazFtU3ZiRzZLejJaWEFS
        QSswb2MzaUNvZWpuVTU2U2NMUzFzWG8KY78W494F7ePGVb5K5epG8NSLSRz0jCic
        i9IeG+ogtdGXdutZqh+JrhQrfkbpmqoVS2b2u6ePR+r+FIyEgc8fww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:lOBgdg5fOELRf6bvtzeKPWjsjtoUo9AUdAbr66C3cFD9v/7wH25HKe1WctU8Z3BsOQwxaz4CqBY0LTR8+3Mv+IyXR8aaiOMTp1IScJh3zsP8myt/KlRmy4bG5LHvLNXngdJEJ71I65nT6kl5ukqtcG5eU3sEFdIeSh7MROhq8kI=,iv:OCYPMKvQoNqrybJDpdUviNnBD/hBmzptr9dzZcVhlhg=,tag:HeVpIPFuIRUr166bIBg41w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
