apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:35ckqF/C6AgtFvFXSeMcShlSmo+KCdYMwwa/uj/VUGqBbUzkuZlZFA==,iv:4SoAJSnBQmoWN2Jf5pTk5Z04NTkNSt5dxmxcuNvC58k=,tag:ZzROH9lHOLwOvC8T/Uv6tQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQkVmUWZ0enlhcWEwSVcv
        d2QvN2thdkFscjFUamlvcU1mZEU3TEl3bzI4CklCWGQyTjlUUGgvVm5lNlcyTTBq
        QXFPWFBRT3FmUFgyRFlHSDYzYmF2czQKLS0tIHIvRlV5Z1NLdkVPZ2I3RlU1MGgr
        TTZTKzV3bWhTdlFJNm9taFlnRC81WUkK3ZrH66GqSmZuJ0Q1Ukrx60zPs1dMvcRZ
        KhQS6LUiirkBuF8rZP/nss3UaKk9p+TJqVimGTcH7oUYZJsc9PAVVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:mFxbVqv9T9yUlreOlISN8O02CQip+cAeSDGS0ijdLupkScZft50Qj+g/F5zoVO3qSOiWfvr8SmE9LNRZJ0k9LIwzObEV4KYiVVnqWN0xogsYyARhrJWDEiSIb0aRUt/3U+gPQFy6M+h0Lbt/FEj44AXLHyxyLDfDSeSVQmgoiAs=,iv:/SwnXSG7nYtsgD+JXB4QzS5GiObwvwf5oObufth3Iyk=,tag:Ipb0g4x0u+Id4xkvZB/nuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
