apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ds0ik8JoGFC3+fAlqHNulrk/6IJYTlpTnLGnCWZFrhtWjNXcyCgS3Q==,iv:eIcHP+c0t6vVpu0Hs24w2I+E7CKaj9tzAgRy1FtNHYs=,tag:/GqIcbKsNPwE90qglwExHQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVg1OHFHNC9ZbUlqQ2xC
        WW5jOXZlaG52UkVIMk1wZWRSMURydUdmdlZFCjhFNFlUVldVWk5rR2VGRUg0MERa
        dDBia1lZc2gyU1d5UGUyTitTb0ViSW8KLS0tIEVHSDFHdEQ1SUdQdnVmSnJPTWFU
        Rlh5WTFrb2ZZNkh5NnFTR0ZabDFCa2sKFzooLfONxcL2mfDotZmk2itIjTu21mWY
        e1xJaBBRR4+XJ/Ie1XFVdiUH2oVv6VcpTMGFxXELZGZO3Ggit+00Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:00Z"
  mac: ENC[AES256_GCM,data:oZEnos1yNxPlBsFzDgzRz/tNeiaUABrrsQUeJ3aAcec/lpTRyIAWrc7JlBf3/tczKYLleg2pcjI1GmO67rn6PDfdNy5sdww9p1If7YAx2Obp6+BrvfiyWbLTada6TKne9mn611eOnr7Q+kH1f7vDtbl3kKaSlhUPVFgziQao0t0=,iv:0iu7hvS/OHbl/PfFBW3FJt3sjEeVN+X2qWQDu9iHDDk=,tag:iJz9YpD79BoQjKZ+/NHKIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
