apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:twhjfN6TISeaT8rr6cgdXxvTmk+SnET5tkeCfBMWqDMdB4eSlJtFtQ==,iv:U3vQaaDH7QXIQYXrGZ5ARR+w1R0UAo+98OKjM9+BrYA=,tag:r8hobye5unB1ePONVpIDfQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTzQ0aTU5eUd5QkI1TktJ
        NTJDZVVxekpocUhpVU5YY0dyMHArd1V1ZkEwClVqTCthNWx5a3VBM2xrKzN4Vms1
        cEZ1ZXdaZk9xNWFqSFRzbDFIZnRURm8KLS0tIEZiSUtJd0t3QklzUlJPSzlkaVUw
        cTZITW9ISnlBcW8wck5FTTlZTjNjWEkKEo2f7Ph8MedZ0tfyz6yuObEqFtAEmqhw
        UwfQx1qFMOmFftXUWOABqjMd4eDjY6MGRT3b6evNBFbV3x3a+VVQLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:2Jllft0H7AmiHEqHAaoZE32lDlMXyUj0Ox5nAVBvrodBv/yReISTzciPbPuWMKRSLjirl8p0tG3GkNLZZcEXtNhjSvLEFTuOkMMw3Y/2g7fPodRevp+hALqP5EM1fXnaUGhksUcd44qGcfjjdVGqkpPc2n98GNnCekRrqicwvpU=,iv:frEDH4E/YqN1XYfYtzkPtCZUeO5HcQjkLyZ91lPegCM=,tag:5mgj6hE8wzroVzRtVIqzOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
