apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:zwqij9IHKnUNKogiSS6nJFMH7ZY4qMAzbVvJrEpQLIlVXLZZLMgaEQ==,iv:C5V7xeZ3jKP+Y4KHQ67AagBXvccQUtYL7T1x+spQblI=,tag:E1qL+1YhRETKAGDRfY0GDQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYXB4YnhweWFiRm11WmFS
        TFF2UEJ2eDlJYkM1WDhPYzdYa2JYOEQ5NVFJCkN2RnNpTkZodHM0QkVsOHMxa09S
        S1NBNHVCSkpoQVZwSXh6NjlwMjBITDQKLS0tIEFrK29KSFRkL05wS2Q5bDFiMEpO
        eG9iL04rNkhaVjhOUG5rK25keTZxUDgKBiPfsxh/Hr5qkidRVMp3nSDbfLQOqLWx
        F+fN9zPdaueJDE1Cc21nafkS49m/XfXR95tXvNeqg0OpL4ShNPpTsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:Xi/nPqN/iTiNrWShzFrWUe5DQveC+gT44yoRh1CqjgcDy6fBlHy30q4l6ssqmgsuO6uA4m/v23zBt2fsNEuctyldIGMKKPBVQkSNtaxRBfSA6C1+bqf48c3P935tz+LGMBkZD+a6ACUNTaPPEZaZVupumfLLoism3l8cyrmYZ1o=,iv:AjPg64d1Wfcg4G8fFqiR3VYJ1Ad4b2UkN43tfUngRjo=,tag:DLnxfsQNAYGAuSwRmQ8kNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
