apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:InApKjJn/K2jTgYdS/XiIDbbvwVz1ORgsXzEdMwMeJ68dPv/K43wLA==,iv:519oL977e9SQR755kdHrBfvxORcP0z3CcfCHUz+j7Yk=,tag:KXojWZMR/sKPMya5VM2piA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bDN4TXRVZFB1Vk9Edisr
        aThPWXBCQUhBeVFkNzlPNFZ1WkV2Z25IVmdJCjZVZVFBSHpkbnVXZFNmbTk1cVgz
        TDlzRDRrSDhSTEpqcEJZSGg5V0hGaEEKLS0tIHF2blFIcllKOUNpaENCcWppQ2gx
        RUFmL3VZdzMrYjJwQTlmRGtsM3U0T1kK/kSApP5ADl7ywPzw7cReinJULLM9/7vv
        e82sf5Isf0IQdrB+Zul8W94w45zjjJWmzcYiepx6RhjzW07mNU+7xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:QWd/TDns7sI34pnS9VQ5joiVgzJvP7wX3XHFZJ4JabGQleu1lpOg7+byVL0fc6NSflTEG8RAV6GS6XLLWFafjRuceNtsICW/3WC9/2EQNpygxjJZFiFrq6ifJtglOYyUQtXJBW7a+H6FHr7PmCyyL0W95KFFzaDEYR76+2/NTo0=,iv:ifhxKOKmSXO/hSc1775wnyzVF4sRh2Gs/ZryEHjR1KU=,tag:dHduyLrZwTDLXUVsQ2DOBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
