apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:i+ScDqIXvojTB5RNgUrwoRuwF5xWO3mmW8KFhbIAtXKMs54GTmOhDw==,iv:crucHGkXwdNtRwRX3oCRFzNd1VBUQVZPePZGaTZ0d4U=,tag:mM2hU3g49dKWKUDNdtLQIg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSjRYY012cGxqZEpCZWdR
        Y0JLUUJOVFczcmcrQWowcXQvQmdFS2IwZmx3CmQ1MTJETHZkVzJpS2xvOHRzT0Na
        bEhFNTUrd21IQ1J4ODhnOGpMbFdvNG8KLS0tIFBrdE1pUDJRTDkrZWtQVWNRaVAy
        SE13Q1NoTjZzdjNJNC9LU1JYZjhtRUUKtpD+v4hG2t/MCI5x5P5XJz9dXTyfbKeg
        gyq6XuZXqYAsKFfUlsauMQu42VeGn8VLQ9VC4FXtz9oD522952NjLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:d9ct1BPD8Wv5Hl5Rsq22LswiW4XtPZP2y3DuhkuAhrPyGCBvvqIhrIdFWe4BqW0mAzV7+rKEb2JIyGN6QzbOsMXpKVl13SafsgVamnhbfnuwtWiL7tcR4g0V7ePSgIRmxGL31RxNv5VO2vvqiLhOFRxnXw51LMF/yhBxm+Ts2GA=,iv:YXRXiTjZwkVd8w7YA7Fu+FH3DXL2WUKNTzxxX3ixvdE=,tag:GSR/xPRGatJKbdpKxPJHyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
