apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pNQq8/NcOE0n7tzSkwXQKlj3ddLz9juVsiRzsZ8/ZMJk5q9U4hrX5A==,iv:HhrkgfRSx4lUrxYUx8kjvRaODSM41v63l22t6bXAn6w=,tag:v5LH5aEjxW1QhS/U8Uo7uw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeXprL05SbTc4ZS9RaVdS
        ZnBENDNyNEw1UjVacXVOaFMrWEtTZ2RMUlFFCnloRGFCVmVhY3BtZVM2NGp1Rm5V
        YWFPcVFOcUNSYWZObnhuNU9LYkIrNVEKLS0tIFl3MVZUeldaTkdxaHhscXdna1lF
        amZDQmVrdG90eXBYSTVjakZXN015TVEK4JeLtQoCAliRkIXTYzqxA5QeBJ7npuEz
        S4Bp1jSF6ongTX5PLdPQHOTKV7uFsa4VMrP15GeQLMMnatP0XrIytA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:haPluE1YFG3I5jDNSJeDwJfjlPokfcBQ4usvXYkhyJTGGJXFbx/QW0jD1MEvGRb6Sr1hN8C0y+ufVx+AL9+cYrw/S9LSd6kZyZR5jELNpeZhNTY1kZiboZ40iylxZVJP9peZjtGKZH8un8jcfWwwjA6WjfzW0eZKsBDR8zqo9TM=,iv:axfsDMG5B3vcxn5xHOe5i4+DEgWMjIt+N+Fype665NE=,tag:heKdxI4Yvyo8jfznaE6DCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
