apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6m0HFzyOFwjEzoTjlAPRTgjqpdrTZeWhqq6pt7gKMTqrpcL0C0SGxQ==,iv:AXjmkOOaPKWmEyzBIZaTd2tstqzxIPUgD3y9iR1G7fs=,tag:ut8M6HAkFqD59sHKOKF7mw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYm0rK2Q2ditnYTFqTHRZ
        SEJkK0thTzNFN1F5NE5tWjJTYXlBYnZxRlNJCmxVQi94RzV1VjdCTzR0NUxGcVgv
        VXdzdjI3cDFXM3VnWHlVdmJkNnRpTTQKLS0tIGZFUHphdVJST0RIMzlNa0ptdk1K
        bjJpN252WGJPUFRYN0RCaFdKY1FlTHMKQbupCdvadR/1ul/Rcu8N2en6ip8AOego
        VbQuiKAXlQiv5p1YjBkl3XykECtynOvWMEF1NnJw0sFgpeZw7x+4Gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:U8Hldeuy5XsZ+tfCxHDpaO0U5cqX1gajBqMCjRtQoqZRZ0L7Cl3LF57axOjxOpHYE4+QdPnygTmhybMN9Tn9L4oBz2oDmeuT5RJY7mUe7fxzRIfNWoTBOP6zvcMNwFUwciRrPgMnwVO4BuedO1l7IyqCDTaA/r37fwXm7CjrbJY=,iv:LMkg63rxIGSuAexo0k+FJ1wJTA2OK1rahFaUf1EUrjA=,tag:YvT2HNcs0BcQlkb8n+jglQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
