apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:SSWeF9FVTRC/kijzjAlQX1MNv/r6AR3zZGjOEKLf99v7PuBEmi1qFA==,iv:lCC7c9p026sQL84N28pd60KqhycJhG+orMDURhgGIwM=,tag:Wc8g4bMpb6qAik+3LmmqBA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNGdYL05XeEhwL3NKNms4
        ZEZtcUcvbm5mcSthWkFDRkFCeWVnMlNwa2lFCkNOK1E4bVYydEtXdlhEQnN4WE92
        NXBIcXFIdEJadnR2c3Ewak9yYVFSZXcKLS0tIDhKYm42bFlSQXFWZ0c4NFNScnJC
        UndQUlFRSkFnc042MWNHWmthbWFPVFkKa7VfpY7s4DI5ksG6LXKW8KQYsqZpxvGc
        xF2yqgNhXPKMYedbvGtlUGEfv5E2f6CBRpCs/EC/KV4m8rMJ268Jxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:Cmha0Cl9Sg8d0CtKOcuNAsmB05v6BAjAzpiJdHgySVHVtcosnujVPTTKylUG2yiQuobbreLe7J2YFk/iPmyoPjRBuKCIFacGEyp9UODOYtdsjdLeFF4zPBqkPWGW9+LWGVQd9BkS+aSO7nTOkJYqTQ+12tlUt0UUEqin6WeRc2c=,iv:Wdex2AnK5DGnhu/Co5pNHfFPW9ByTJ6sVXGkOmuhjZA=,tag:c2mSUgbXsma/SPgO5RkE1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
