# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:4Wdke8yO0k/I++Q=,iv:hdqBcAYebPYSMfD6s/soOmaRwk7XFzA1WmPy5TbOtfs=,tag:/dc4SxECq91M3YnlcT6cNw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:FlKUgvruSrqeeMQQ,iv:4KGdwDaHiiVCdZ++zrHqN9UMf5y4qmltrscZTTH2B7k=,tag:unGY5dTpgBHh3ZrT6MiI/Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:YD1cFADg+XWHzbNtrMscLBQ4Pxg5tBzC,iv:StD6RPqYr7yEeCfepFVasN1iQY/GbgcCyF0EAodLn9w=,tag:smvNeiZheDdrjWylWFWzDA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYWJJaVY5WkpwYXZKZWxP
        Skg3ZEl6cC82UzYvb09MZHJZUkgyd1FRd0FvCmtUSjU2SUFLVTlkci9XNHNMOEp4
        Q3M3TEM4R3JyTjR0RTg4UXFjazNCOGMKLS0tIHpTUWNKMzdId2EvKytDWDhXVDR2
        VHovVVlVRzN0cmY3dDJOT3FuUVNaa28Ka+GC/MCE4R2u5EbZJmM10v6qDhVV7D2a
        i4urAmaCvITWThoxI/AbgYx/IsWneMKBe2/bcIPts+yua3dwnEn2oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:isn+9VBhrCEkNzM871vx+9kGO8qcs69qneQRPGDEpQ7P6K/gLoCteJxIipQ7ic4psAfBzf8QZYLF/n596URA6LnSRoNvD9RjxbKt6nEQk+Zz773syOBO52weWVNPNH2wRamkLliBvCYETtOfxVrsYJP4+jVnDO0Blx8B5Bc1bNA=,iv:Y11h47Q+6+37Ht1H9zK+F3q86pPhcgXln67iR9LhnC8=,tag:baSTDfwCdW4tNBTRFyDc2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
