# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:7pkwn+EOc3moTug=,iv:TLHQ+Nt4GM5vmysO8ax17puV3JGLfcXdNFIVtlKpdIU=,tag:GQxtp2C0udcoBH+PjOlu6g==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:dygMZC9xlXwPSGQL,iv:oQanCvSIUhpEoRlAidiWJ7s89h6dDCmcM6nevNeyP/Y=,tag:qcTiALOb6QxRm783Rj4BTQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:keIf+paDCqAWRbI9p+tr0XNFoIr/L9DN,iv:ZBRO5QE9tXcLsLqdYRHEp8Cy1gDAQSu/tKxB7zpcZ9c=,tag:7kIbRqxKJhuIdJIcMcywfA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQnA4ckxSTzJPYzlSRytP
        WHdOaTJiTlE5eUVWQXQ1alpHeDZJellmdkJVCjNwVTlGb0RweGdBZ3hUZzRSYkpr
        bi9aWEppVFNCYzRBYWwyaktLaVdpSUUKLS0tIFNUMjk1akQ0cjNOTi9qcHh3T0U0
        UXU3MEwxME5FaVdlS0ZyaVdrK1p0UlUKzSh2fXGxAQn2aSRfoBLwAYHg4wa92G9w
        XehD+8MpLergupi9devD/lEjG94Ybz3QvwPSzUSfjmUy/lcGS+kePA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:mXhf4/kPLWC+Tlybgr8sfLgWVnIUnwhS2pvUhbAuLiAUY7FMDvtXvaTzs0qkQTM2YrFDwbrQOMhm7P+BsYyzwuPSbiWQ4zo6cafHhFhb+K2ScfO2pH4i9+C2l1YwuK6WOKo17gAaShgR+7pkuvd8oKsAL8oVNxqieTO2qSPRIqs=,iv:ypnLwRbKAVYNPoB5ja1QY5r+pTLYKAsH7ifEMh9zq+8=,tag:DHtFA8ZbWG959Az+BFH6uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
