# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:rYxr+LKEqcZLYl4=,iv:LiD9SVIEYB+3JDrfHESIWkjuOida3RlfVXwMP8rztZc=,tag:XEYokjbshBvE0z0Wf2YNjg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:OKxpXIUfYnlOjthO,iv:/faInn2zykbvd9g+2d46Aw1GM/tM3JuFYBX+dbTtxmA=,tag:Z4qBXZe5Bb+MW6JIwGbf6Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:L0E6bEc9HsFtDrsr6KiXIBis9BUPK83s,iv:VeJM0aKjfslNTZBNuG61kxfe3b/lhdDaTs4bEB/J8H4=,tag:qfM2hvYGG7oWQkKkta6a9A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ2VhM0pyMEpoS3BDcHJF
        WlB1enBwMjhvRmN5N2d6RHdpZGZyRGRmNUNrCkoxM2tLaDZEUWtmQXNuOWVQSXVh
        K3BYd0ExRXlBSGZlZXoraVBsNHZaVDAKLS0tIElMYUpQVDVUSFRtZW85S3lxR0tQ
        NlVNQnJxdDdON1poN0hrSWhHamJBUmcKPIiW34PTS3uW+kFnRw0IS5Bs40AJTfWC
        j2pBszQBvEO2IFFrL2ABhDyS5rT4x801Ql1YDXd27M7bg8y1RdgPWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:EebpO2D2nTrmrKDWS4J6pEG5ISqNmSk6w2qU89SAun5Ngb1IvU2g2Kx4LsezN7HWngwrxNkzQOg9Wq7SK73ARw8pf53ayoG7O4rAG0uo1CchSVi6xbz+HyszM158CRZQLl3Ht5Usesxz4u6bH6SRZ6mrsXsTQxLAXGtU4WJ6MkM=,iv:pQlXIb6DgZpKfGRRmL0IC3SBvjrxg4XqnRFrG7wgO0Y=,tag:aDyx3A9uHGW5SSIrXBSv9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
