# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:Ae7cw6Xh9/9MOF8=,iv:0o+rNbyKhDQZQWDXFiJURvoHOSwHKx6Sc3aaPFFtUS4=,tag:mTZB9GH+qHnEql2mi8iyZg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:jcw/JEn5Dhl5J7Ja,iv:SAz5U1SUR2dKWG7mWsFG0y0JzSs9lJHpi6ICywXJcnI=,tag:nlpEWp0GodD4/SNCnXafyQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:Z/bMPZUbei3IffvdkKmks3DQOjBv0ely,iv:mCOyFjPzjUUoC9j4X7piMAWBctAseoAxpykiCu2VaAk=,tag:n9AldPEOJuI/lC6XWdjLFg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bjhySVJCWDkydkM1Kzhi
        SUNXTmg2UVorRGVLSnFHZk1tUVFyYkRjUXowCmduNy92dTVtN0RZc2pWZW1wK0dI
        TnIzcGlkQlpFZWJVcyt6SlQvUGNZTHcKLS0tIG9iQ0ROM29KeXhLQ2I1V0ZZVEk0
        RTcrRjF5LzRtY3BrbEtncTRZOU5DZFkKjEWVJuwwlFCtDPiSlmlTfg12xWI9TZw+
        JC3QJTHJVogpmViqrQi4C59H218xM79grP1oA1OdbEmVDHLCIgRq9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:nQfssO454F8CYsI5a/xRZU8rooubk1jnqGyqQAKeNKUsVKvqmV6PGY4ZcMWxjXY54K7GyB3qJHuLdYZ++2UsRL1HiLqcN2oUYAJ+bA97GfrcgmNxLaWcldUtv2cN090s/7Xk1g5Jqyobd09ch7xClhderClHaNGQisLt89hYPHw=,iv:MWYPE2AF/XLdWXg7JVHIxgdeaOEk4lt+bBJHHIm9A7k=,tag:2+7shsiHPqzwxIoW6GY8gQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
