# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:rEQ0MANn2axc28Y=,iv:p6C2lTDWVyTfeJ8D9ePO0lNeRfIvGXExmyh3WImq8Tk=,tag:xUCZ8mCwiOTCdzCoiOgpPQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:kotL/sbwpq2LIONt,iv:C2ER+rIh7EUyPf2kTnmLteplWEi8hSXX/yniPKtK0WY=,tag:Ec6OOGHzWun0CX1HX3f97w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:DLX1IZW3oyXbn85aqVkGb8OufAUla8nM,iv:5AtTB0/ti8zzmBN2eVNIA/U52/KW4+kPhT6IGyxgWeQ=,tag:Lby4rwfBW3XOV0xLhaLJtw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd25mUHA2dmpvdGNRZlQ1
        WVRFQmxwQkZrUmU1Z3Q4bDlsMWF1b0VJZ3lVCjNzbSthd0syY2VncTU3bWdIZ3BI
        VFlPN25DZDlEZmV5b2FyWTZiVU9vS2MKLS0tIHdoVnA4dldaNXU3eUhYeDFLcE9I
        cjhSUXhVc2F2U3EvNHNVTmxGenU0UVkKfh9d6kRI45cU9YV8SE+A69uXKfwiRg6p
        CE67G9mfnkE2OZVh8FKFVkKalGoBK2A5iJAAdW3ovRUSSqOn5nmNzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:b+xPBUeDalTjIjRl+N46dsh7t1GsjT/HIejP+8HOXpsoU+bjboP9a6mLsuVwd649WgilcRPvm3jbAkhMEKPwa+ZXoF0bUCd/CjRGTPjK5Bi3CdT1coaQ7kKuVqlXCrwuGvKjJli1ro68t6PhB7I6Wb/n9jO1rDC1CwpqZvlZDGQ=,iv:scirNozyQD05vfkbs5U4B/tmbaLBK9YVb4aIehxPdtM=,tag:Meiapp+oDrcsa5QyFEF5cg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
