# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:6Tm0mJHzd8Xk2tU=,iv:/CK5UYnIbxUCPSg/mbW5o1PD3QcyYqLdxlyODY05l44=,tag:qBXd9ixnZyRM/Diu+bJLug==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QDzeXgdeKOfr0mxy,iv:pVUP/K7nmYlbF6COd6GiXWyEG3+S4qM0q+Zri02ctbo=,tag:0MBJzTXfuXneoL99/hMOzQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:LgoMnNrh8/jQSEG0GzMtLwUz/Ouug3qT,iv:fV4LZx8BvxbHXkgtVo7CU/v4O9yQXImKPHJy1CwhNS8=,tag:mklTeVWArdUyyGKNaYesdw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqLzJZSDREVVhib0J3R2JI
        WUxkV3l4QmpxMEVvdit3dDVEdHd6NzhoeDBvCk1Wd1pIcGVvejBhMXBWVjhwbjdK
        RTZEUXM3V2w3N0kxZ0pHRklJbGxmcGcKLS0tIHBLTS9LWEwzL3RaamVNNkJ2KzBa
        b3JEbnhIZVc2c0RhNzVyWkJGMmwrdjgKAw3LZzyMdHtNo5IUlIas0dcCnnvYIokf
        /NMNdKUw+lLCyeHjgStQIG1lNy7QHPPVHeQhsoN1OTWtlO6f9TxT5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:beJOXifdTrAztxuETMjDVoFI5yOJxlMGYUMMguNuaMxHdF/lacYlHnZAuKKOpGolHFYrMPygS2VGVElpcEDfsM/x7uLw3kZK9Qxx5O489IUQM04YPyRXAF8/CnZmEQZ7IR8OlO9uvci8S/l6bzDc1hoSbUfNnuH0slbQDUGHI/Y=,iv:aJdHZWjHOeHAVm/VjSWaqWonFo47l4WV/q35BVTTRH0=,tag:DipPVkdqIJo/sxMXCC6s3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
