# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:d+vWqoqgwnpGHcU=,iv:rvelKPLrL5z/RmY+1u/PSZw1yQrw4FZfNC0hhB1eUN8=,tag:2RreAIM3+MZdh3SUjzdgWw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:/rWjPC5l1lt+Zymh,iv:ZKpDYpq+cfm6C1Yf51JKqAVd9Eqbdcp8B4puBVeXoB0=,tag:ZejTWHEW324tFmqOcZXRFw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:4z2w4FvlJ75He4faIZTFWvBWGw5OzyiL,iv:ZqCtgJjfl+Eilsh0einhR1MOUYGcusJMq7VSIdrs8ms=,tag:Zf9KYlQupjShuIZL0rHlrQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWR1eURPSjR6V0ZsK01p
        TDFSRmdQVndkMmxTUzRlWHpEa0YyNUx0cmhFCkN3bG5ETXkvQ3FleDJQc1o0NDVk
        eDhpcytlUUJXN25tY08vZzM2ekxqSFkKLS0tIDBjN3NIRkVwWEFjTkI1SVNvNGVm
        aG9jZVhQeFNObFhTSnhld0NNOVFxd2MKoLRDspu8V6YYEUEEfUxNf/Wo3jqVqSbb
        HeN0uGcKyuUIVRnJM5rNThUTC2/5OXo5Q7PNXlb5+/s3KJEx1QGpbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:G41Xjy7uvfNd9hOKCnQh0OATpv9nlg40MiNeqhoR19RnWpsqM3dNPrYhTjR98D9kunsUWEhMM9Y1lmW5js9IdFbj5rkqA77s+STPF6DGDJvHNQ+SreFw5z3X7kLFFvpUdqwM4gMaPFdz7caHTntejCsv1Bficoqur7bgP2/RDN8=,iv:b0Nzj39kt5gMKfTRTuXIq5XEXOMmS/JK9dCbNrdXZ8A=,tag:pSV8MZMg+sFCXmsdCWqNmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
