# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:v2LhqmWMLu0IIWE=,iv:2sqcSyToB6tNX6ywJMHFfcmL7uMR6d7lTkvIeUV6Reo=,tag:2JRdTvYSDX/uK+EgG4swcQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:HDTVrHoHZZIw+BES,iv:DRNB8ZykGP/i5i57ZRCi4r6ockca7sLQonnrKxcv7oU=,tag:lzJdAMYUYwVQMQFuNlrqAA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:RBHTNH+igeYl4XWdJDDl00yEqZ4pT5W6,iv:lDsfxEYcSEn68xstnX0dZieYVSe0H0LogSZ4HwO2SF0=,tag:2ytRrONCEdOKcmDg6dUR0Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVkh0cXBidWFCdTcyR2xw
        SnY2eWZRaDN2eHRuTi9GN1NTSW9DV2VoQzJzCm54RmsrUjJiaGphRDB4aEZQS09B
        WWlydTdYcUVBSFdsU240S21hc05vQ1UKLS0tIDExTkgrTE1hL3hpdWYzWW5xMVFi
        QjdBSEdibW4yYnRIUEtrTjNIb0FOM2MKnW5rd9adC1HQzshNkiNaT2L+EQbe/+FN
        Pgq1xQuJOkphKGmGwgCUkMmgTwKqrqijIQ7stW2S5yfI+1iuRkBg8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:ovz4HGPdL5bk9GcfEkkGO1M9+1D6cvuM9REzavUr0PzqS+idL+WAdpbGgI7YMtMDFQ2qcaALs+R18L/aMYih6965I+DNtjVBctji3yJyyUZ75erwFekKwSrg2DLLyl8s62Oob7kgx8gVnPQ+PFqwIHD7LnBOLpa7KEychCCiaOU=,iv:tHrhA2rixFKvLGV6BVynbi8Ll0VlAnis+DBBhiAOugw=,tag:oDG+9WAQSdtbN1r5ms+FVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
