# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:qtz7pfeDJzjG5Y0=,iv:PPfeHgkbGyomY9Uwa8gDh7w/sGwt9MuvucqzPeec4Q0=,tag:ndtN1oc/8Lvq/D7G3P+XQg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:vT4UwAP8i71OpavE,iv:M0W/V1rvsPBGSaa+/k1NidhLorQQToGusJDD6oh9hm4=,tag:1/en8uubbJ9JbIKGTOyfkA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:85OM50PI/8qr6WAk/s56ZrwOI8xlqPNn,iv:JV1xbpdd7mHhJPMsPvPIv2t9DeHx3LxC/MFPZujDV7w=,tag:wZvGMI0Ixq6HsIBO5n6/jg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L0pqZTY2c3hjd2JMWUNi
        a2o0UTdmcXg1b1p1bURTdDVOTkRUNHdUR2hnCllBUTRzNnpWa1JjMllQcEZkdXd2
        U3lBK3JzbElvNmsxNkNNMmhkUTE3WGcKLS0tIEx4YzRXM3lDVW9GdUVvTFM2TWhQ
        UElTTUlITllLSU83T2k3d3M1eTZGWVEK1HZzDErfyGZ3SeWzxDndgn5BxVsc144F
        Jrg/JYZZn0dgX5PZC5DdIGaJkzn3j0C0sEYr6X0Kugzx3anmHDlRsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:ZMy9IHSIgEe+UG42FKNpIbeiYmWOZa6Zu5h4dHthP+tqQtK+b1dzkKy8D25jMzVDUUD9+pDfUOajE+DTRhfaLDvNBQNepoDRI3fjANjRbA3Ealt+tE/ZYta9OHw6Z52mq5r0R9lnBMpbARMCM7i24kVHqI2Ty+plxO0QtFlvFRs=,iv:PE78YfRaj7p+m/evJ5nIFVK2DS1380KJuMlb8oorBDo=,tag:SZ3vpxJBiYL1Dj1xHJNdfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
