# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:wiQfw2N23N4A/Yo=,iv:LRQBrORvYLrLImT0rLZ15pJ2G0suPDg0PlzmVdNg8D0=,tag:rZVjuHePu3sqoZIsRgI7wg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:O0fwdenSxpj4QWhi,iv:qdtxgevqx+HnIznlVOGa4EkCj8FnlYPXoWE1Teguf+I=,tag:Z574KgpN+3lMq0pegRNQ8w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:hdVWvdfk2iFrqt8yuzWb/WT0GYVgCgp7,iv:7T0aqGBLoEYI4LA1QoKEfDPwKYrWDd2PGq7xzkaPyGU=,tag:PO7FS7h3iXwsIwBg23ATbA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN2VoY09LWHhGdjIrbE5C
        MjVqSTNLZ2kxbHYvQVE0cll3YnlTUy9SMXdnCmpvVm1HNkFxQ0xjUVA3RUJxQXN5
        bU1BZXFhTzllbUVhdTZsYUpBb2grRWsKLS0tIHFMUXY2V3pxc3ZhTXdxaXIrOG5a
        TURNQndyV2JHT2hsa0ZOWGo4R0Y4T0UKebbqcXBZTycuo7+D4RHU+Joy2mWxWpAf
        JepI+EaeCqv9PFh55rL7hoY+0j2ccEeqXrcw1jzKaJLtDuulG2wpKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:Pv9iw0BbwT5AaBqN9Qjjz0PJxGuFcDMjOoYEQWYZY0n+dCeJnoGke79cuDnDUHwZcXetlFNSMfIGp+R5t3CAPQwcu7u+soAP7ZbQI0a8gOsPKhJ58zJWKD6EMLdSoigVn/N/WzSRSFSsktEeUVt+a0sW2BbHbYLL/Y1+x5w/pGk=,iv:Q0eGVfSsk3KVgha7o2V5ei7LpBT4Dr1dAUMAyfiwJlM=,tag:jwbh3IWwuOCYv5qCFFNqwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
