# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:JGRNATVsPO+ZIsQ=,iv:+2AUOBvlqETHaTMg+omTLNli/Rof9yq+9mgJ9MQMBss=,tag:tTBsPZK+q9TLFjZyFZR4Ig==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:4D6ZIte7hXx/MVHB,iv:h/JeWzDvnQuPBKrIVC4vUcFdMRHEIJI+/zEozKoofrM=,tag:O9FahZFYC6Eb0cdD2s7BuQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:X5YssfV/FjnU8oIbCwFMsIBfviN5OxOT,iv:ql6s1ghPv0kVVtMrBnedh+b4H9xDHuYgKbNoy5pHA2E=,tag:424zdwQaRIFUU3MfcMqheQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQTgrbkpWSlBaNGlzQ0p5
        QlBWTW9xOW5ialIxUlhyVG9wRkluaWZEOFFBCkM5dVBvdWZoeTZBL0xMVlEyRFhF
        OEpocml5RVNpREo3S0ZMUjV5Q0JrOFEKLS0tIFN1UmltM0RvdGcvVHRvQVZUUHN2
        VHRYNU5BeXR6VjBsU3p1VVpTWWRpOEEKccGi7VVbl1PxxaoaqpKdxcycu9wFUmNg
        p8A6VPS4/t8JoglBWbNzS9ISLLUczR9YG3ief0lI4GpmJDL5k+ePNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:C9x5+upVyES02sjG6XhQDpDfT8YcLiLxXyZghQ0STOFTLolEgf6Pj9KvM1hfl0g5BN6hCaFuoSiJuCrA1kAHyjmRMa3gobXHvEX5dPm/JwlHQ4OsNdxc3DnGBa99wgtXXnSF+ZQI7vE46C9UWaqMI1pGejudYJoLZDkOAf6dcUA=,iv:jkkVNjAjmUE50pE3z1yQhPmtWJhKRVREYoWrlCgg1OQ=,tag:T1gm4NtzLi9TrB2f7BKqIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
