# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:/ElOhlZ4BQm4ZjI=,iv:R0HXPL0IQ7u4WKM9QBe2sJFDgITfEmvTDXYuyi1vhfU=,tag:xtPNNFqYIKvd2O8ctvlQEg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Huc+j06nH/IqWEw9,iv:/THd7bwV3K6IUfeJ21Lm4FbhqMdvq4lLK/vZC+xqApI=,tag:WuHtj0C3FB+33I+UgJdxwQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:XvdxP6OT9a/AmV3pnHXY3oRmUicdMJCi,iv:xMwAERZ0NWbRMPLI0d0rWeZpwkf676pieNRFo+BRleQ=,tag:r0i17kJuHOJGuccWldrxrw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRFhKbU5zT1RLNXNtbHdH
        SmM3dnBqV2hJNVhjL0VkZzhMUHoyQmM0ZXk4CnVxM0tiZ29EMUg3QXh2WmhoQzhF
        enRnekduQi9HODg5cXJzV1YwRTBIN2sKLS0tIFZSWW9wRnF5NWluSzExY2xNSTJW
        bmZveVJ3cVJ6Sm9talE4Um5PMTdHdWcKo6b/9QzOHIllF89mTFOGeHqhBTjwf7Nr
        UV4n3xC6rRV29tbGRGhd3B0721oYBelwrMyAtG1uBprZXeyaDcA7lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:ycNIMHBgWbHkP8HwbN5Jlb1FPC9u/Iv7Dhcw1YvTML53ZP2F3GLPHEyfcB4TcWmArjN6lobem0Y3Ef/FbrAC907PyGWSVrsVaZSh0b08rYsFYQK7Y3FNa4QL+9KnoJ1CnNEdX6X4rfM+wDEo3H7HHOS4KttH9F0bvoWZmVtnXy0=,iv:JnfRWpPzzWJzyU7hOSdTmuvjtGLzSRNqb5sYDhtyeYk=,tag:jxidimq/CKPJtRXUjEKG5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
