# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:B8Kj4e+hRHjZsWY=,iv:wCkC1upL197T+RekcGcVGirP7V+n7XfWD3HVEn8veFk=,tag:fYZAdneqbveYtZNyjxjOnQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:+xIoEGuYzm+MH6no,iv:xVsm/GrHFxq7hCl1OF++UBgr+7IEaryS4jQ3/QtGpjs=,tag:nsTmxbmFOOCUuYOusvE16g==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:jwwisDmIe/94hwdwIdQp1TtVui//C8HJ,iv:0c13qYROYsL63PbBc+RVkgGqSXnkKpH4ox2DvYp0qlg=,tag:zwK/dTuXwZM6pLOedNnFeQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxalZjcXNQVkwrYjBXNHMz
        M1Y5UW4rMm5BS0ExdldBMjl5VUhFenprNng0CmRYSXlUakNqZmNKV080SzFOTFhw
        U21sREhhclZwTjBRQXlEK1NBbSswam8KLS0tIEJUNVZ5b0lXeWJBbWtTRC9EV0RD
        SFFiWk1TNkJQWm5RM0F3RktCUXU5K1kKOEosY6/vmrzIDe9q5R4tu+qwDwPluyK+
        gBHGMCfgWqbXg1PLgI3qEeV9h0do+Xic7Y0Y8mX0aPNCpViu6FMv1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:Pw7tqmsm39VQHesetPndE5KcgmsyhllkSFQz7N76kzjPKj/V5wjNCfOVhF/rnptG6WF7YoIE2P5P/zNtGJOGNIbxBSt6ttuXD9XZxNiirre74xHGXcfLG6LLAVCu9bRq/79x9q/u1pUuYrQwp+hnoSe1KGOA1GB66LsSXrQCxZg=,iv:m/1er9AkWe6RAEjgTHk8NnyjCnCvTljZqTow8TCUq3c=,tag:a/8t9oCWAgKcg1uyvD7K5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
