# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:bVqFFvWPcNNxPpc=,iv:paG160axt+nP8fSajR5X47gNUMsfAcJml/ZGc7/B+Bk=,tag:2WWIKKIXUuE07VbEtVrVRw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:AiXT2dDWXkiw32To,iv:A3ljLDZcIUynGg/RoLeZTLNIZYP4lFhxne7vnIXzlhE=,tag:Ng0G/l5kTLP9AoaV6yvGkw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:pxPHYthbHabgWlqvBtXhdwty98t8nAVe,iv:PLXEq1x/EES6qrP0WTmR/C9uA+9EVUu3REUEi+SAQ90=,tag:sTTcTyOWxfelqblD5C5J8Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMHRIWWhzU0FsTWltdUFC
        d3p6YlF3ek1iTk5IcmF1ZnhlT3pUQTNvdkI0CmJHMVJ3VHRFTm45b3YvZ3FZbVpP
        a3diTjVUSXhyUVAzV0RZQ0IxQ1B1VjQKLS0tIGRmcFkveXYzM0k5V2x1QitGcnRT
        VFB0QjA4WExEZ0Q3U2lWd1IzZnJnS3MKmJdflPmxhiqHHtafsMJT5WcotOf4rs5M
        CzomWbEOYom1VphJbR1z88E7zjD/TSlFoj0CzUJ8dbKqpjcn/79QZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:2XdCbKxi86c1p9zATw1fB23eAoA3uOmufzVM9rosgj4Cz794IoBYFtrtvK0MbnyOuUc3s8HhrnvEl9x96qMNXfg7Ph3g5dKnWJQhNMiVj1ZtVaL9SiFaPI8BZzm87vzzVlmTzt+726svwDWkC7mcYgU7erUh4ajkpmPC7MY4m1Q=,iv:Lr1U/no1/f4GaluIAczX6aJBvzJI/g9/2dQl55FCtoo=,tag:SASG+7+vTFRzN64w+AikXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
