# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:xutP6RQ/qaW0h2o=,iv:ei9b42Qpehf3odZeXrZtaVsnxmPo84ByeQ+FUOeETiw=,tag:OpWjOkXF15AEmrWlxyQA+A==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:lBGcOLawi9M/3NS6,iv:zeSN5uV4gR6RbZUpLSTI8Nfp/LWNWvS5RbsVp8i7zSE=,tag:gQU+dTuPPKPgmP6Zm/jMfg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:sIptC742HJhqHfB8JDu1P0gT5RVVllj9,iv:9KyenVppZvB4IJ0RuoZXWW3S/PvxuCWvOlNI+qU/3WE=,tag:Fm8ND5u+UZ87Kcd7wFjEXw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnV6Sm1JdGlHU2V4YlEr
        V2ZiZHJsVDhZWjRGb203U3UzN2QzYldtelE4CjViVVV6R2p2Z09adGRpRW9RQ09y
        QXZmdm12akx3ajVMMEt2d0wrNWVqUDQKLS0tIHp0dUl1T2JKR2t6NmlNMXdhcXIz
        Mk9DQ1V0T1YzRzErbVR1dExIQm1BZGsK3AYmnMYoZziG1tN4Wu6xyVbfEB6ajZuN
        Z/jbY6NHFgNHO+YFORgvmHi/F6bPmL6lsvf5HotKPAeNUBEeyLW/Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:05Z"
  mac: ENC[AES256_GCM,data:C6///kfzNoMipUwpuBFO85FVWBjyxi8c7T+/d/G3of6/0peIsAGj1lIoNfuriiTqsy9iutWPlYEf4HAIu3LHhj281qLOFL412rQyNNa8VlShOTBqr0J0EnZjUTEvXlurixKeL8NDNbfevB7GjgggG0/wGISLd/+qlZ+WoRZOQQE=,iv:XRdof5h7KdVvd/gGCCZzXFX0GaShkVwLVFaPhbVk0GE=,tag:hqssJn2DKPQjfg7Y55NQ7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
