# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:a5+miWa9guj4F9I=,iv:WYrazUcAru+pdA8Stbwf99ACZCecXkfboYbTIOl8lEI=,tag:F7NaHuruLslnoYZgN0at3w==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:e7T8YidkVrXxr8av,iv:SuVczHeSxua0kofePXqOa1d3pSHO8/uT/8pBJwoE4zI=,tag:/hVOcwEPcOP5BBP/38EXRw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:mte9ZCm66NDkvvyitDrxr1mkzygbvc+S,iv:Hlnc1DRhyNEOEqeJ6dzfP/wP3a4SYA7RZvbGf+i4DAQ=,tag:FPK1a7jfnC/0GVBdyX/e9Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyak5DSERBRDJleFZHMEFl
        UUtZZHV4djhtVzlSdWw2Y3FIVHo2eWpvWEI4CmI4ZXBGWk1UMWhvUUZMYmJsVHVP
        WWluRUxYTU14czE1cnlkNEZXTTBreTAKLS0tIFBEWTRGMXFtWnJpZzkxaHExVXVL
        TlprSks4UEVTaFRvVk1zck5xS2NVSFEKQ4jKS7N8SoHGHD0GX00Skg5fuBTePU8U
        eeH+h1T5HxjEigAZg6cTMqu8813P8exBnWpviyqsbxJGkt1IMA9/Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:wh0zTPuftxKg7O/6if/37pB02fpY47EzH+gQaWOUSUJIhZemxp/J3SNNFOS/lcDJPuAxpD3Mo1DyzgDVlOyL2bvmlOtqJkPcWcJo6PfSUAyUy+cDgOBFmnNvc9j9MWtLP4x2VI4fWsikGvEXKbJ6XKD7bcj0RGwygoCXI+PJ3pE=,iv:3LQ9k54n8qTxwOogOiMrh7JGxK16986ITWrwiynZSjY=,tag:4qCWWPGYD+bJcxnI8jF5qQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
