# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:UE98gwIDhcAtGrg=,iv:oDqUQz07JLeIO2yMTPuvLwbvaeOtQxQxhAT82Yb4ICI=,tag:xsiqPLi1HbI42FVI2RT1yw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:/yjkSgqyQDCZv4yH,iv:qxt+NfxUbypcWWGdRtrr7KPxplHWHgfH0OYEF1zRo8I=,tag:nXBYbJsibe85gvJit/cYIg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:HO9/AzVuQ92LeaREF4oVYt5vGOBXEKxI,iv:5UKRo8Ga6jkOfO5t6aTEOUwkezeu4hLM0pzU3+WDAfw=,tag:smk/aeG9zhUcCgSR+yaXkw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb0YvVVd2Z0tuQ1dlYVln
        OS9kV2dKYWFkMlN6Yk1EVW5taHd4L1hGUUdjClRlOUY3Uy84KzRDVy8vNmM2VGQ1
        dlAvaHR4S2c2RjBkVHM3bWF4Z3FsMFEKLS0tIDFTY1h2eWkzTTk2bXlQbHVhbHJx
        U1AvYmtOVUFqZ0tpTDR6UHBpWUNwU2MK4pO4wgKhimpkLLhV3yHKtcE6zbLR/TFa
        8f+y4ntmnVi1xLP33HsXTt0qxCYRR83G3/BkiPyIcBDQueYWM/72jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:iAQ5YoxJBXP7dSQEB5uP8CxzmetzmOvoxSudg48rZvqT42utS60IW01VUh9YNeC6xbzP7423LRVxRjueHGIXXbGmGuj2TsVXGq87z/lv7vEbl+Sw+Q+Pc/CpYJfSy/Jy0ATHhmtvIEJRVp60EpEExrp8hoNqbnxcIMKhojloopU=,iv:2JFSbVpejnFb7eyfGExAkK8ckotjneWnekZOXMglYbw=,tag:q/HPQtWul1A16HhHeo4rrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
