# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:JmvN8ZXOpBREFBg=,iv:cNVIuUA7s3UFO3V79FXu0aynpwcUcm2eWt7OxTrVGPc=,tag:F69NAt/YIGSe6xBqf8xrSA==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:wD1TyOFrhTz0iHJS,iv:O7yKGUF/W84PPMOLkKEOoG3E6yrW0pTMt+naNZMFSys=,tag:VYpXGPJ7EneG7arLTQ7pwQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:JCKJtRAiAY4gJft553aCwH2cOnCM76O7,iv:0Br+lCIcqQ2Cp1GOpHd1NfTFqrtem9w0eE6RPpKAfIE=,tag:BzwaQyrg8/xtsuTSQPrUdQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZTJrSlYyQll6RGh2aEs5
        ajU0MmJkZmF3Z2RhYWgwcHBIQmlIYkpnRUhBCkdpa09DbkxKeTlFQy9EMkFRVlJM
        UTVZTkVDaEJidHNlVHlqaVpxaDBOOFEKLS0tIDRyL0twY2RNdVZ5QUFNWVo4ZGgy
        R09zN1RIRkNuMjZ2M0lySE9sKzRLakEKu6pFpuyY/a8ieOH/FGxKfH6TLeu8nFU6
        7IBnwFEH3sTkeY595BzwAC0PefIL/gFI3+eqzSDGIXyirP9mE7aQ3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:55Z"
  mac: ENC[AES256_GCM,data:bNCkE4+wsj/nkBioyowBJGh9STsUaM4lAtSmYGUZmeHyHj3AND6ABZAyhT8n+Zjngg2A8Gw7cxHKU5Y59EJc0OGLUCj1vNyCEOBmVSKGn2r8YZQbMDCR8jmnxXfk6dqtDObeOstVmp4SgrafvSw+VCrzv2WKvxdCMhssBR1D2q0=,iv:6rZXOzct/tcuwQxGXABfUAl9e+qnVdZy+EO8P3NKdvY=,tag:IEdUwkSpk45Amj/dNRW+6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
