# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:B/CcN2vy26jFxTc=,iv:yO98HFNDmF0i+9XFxJYobvgtytq1t/tvD/OzbBG87vA=,tag:ymtqyy+IGciTr3zhMtAPKw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:dTGBd/k+5fsDN38P,iv:Drz0LVsK1mn9Th+ngyjrcgsVPotUeXNdPlH/yi5F8pw=,tag:LuhtXmpPeAIym3SX4HZTxw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:xigG2QIwMvMXxqs+n0I6kHT7p6creas/,iv:39ygDKbKfIS0zzUNIxtNovjycb+7xvwnQuYQOFfid/8=,tag:3mn9R/5/TkCBvQVkX40CcQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMFFsUE44NFdma004SlVD
        bFBJMXhlOUFDVEhzMEtrbTBOME9xblg1WEJzCktEbjdUMW1naFFUVEdDeFUxNWVY
        VnhpTXBCWjBZMDR0d3JlbXdlZjIyOEUKLS0tIHZqdEZaNlF2KysyQVRnQWJhOGN6
        VG0vYjVzL3ZYSmRLY1N1bzVRcHk1WU0K0kBzHuiQ7kNZ0ehXjunR1YSsqwrPAUP6
        u+xlmxuY7+GvwHwwKiXSnonkLPwIYI7C1G4gzlM1cISHQgxAzbc1Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:IgyjbZwtRoFG6G73Ufwa9Or++jVN1pgqoEVFlV6sShP/ZtPVa3tRz/H5gQcqC+WsERq6kuyChhQ7rVKvY/hApO2/kB32xr7MlZ21xieyuWPG7ku0nsp0H4gWmFdn7NL9MoU84IiBhmTlhslcWR/HjEgk2VfaZKcfpUxSNX9UfMo=,iv:rv5htS0LQ75CkwmlemlzWYq18EytHMIW+8B/2th/Hhk=,tag:CNMaBVzbk4ev7N+fRi+7PA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
