# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:Zv+I8Zu1b2zNQkY=,iv:nmpgG4WhxwOuCrK6iQBHSQ9Y4Certw5IfVCRm1Dt/BQ=,tag:2GMKT0qTntzHeFSqxhGPwQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:74KxZylDphWXMyJl,iv:8DKC7cUKre92H75tmB53/ixdD7VNTiBT32UdqW60rWE=,tag:0VWUFe1TqnJWYbnsVPSy6A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:uONSMO+epDyjIKrHeF9PjNzRbhh5ojKs,iv:4ekk/0kMT7/C19qUudI/pz9lHzow+vvEY8TUc7IQSGg=,tag:a4Wbd9+MWFR/YBUPtQnE9Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c0RXUW1seCs3eHRiZTJY
        UzNjd3c2MXd2UnVicThNektRZGNueGNUNXhFCi90eU4zWDBXWEU2cmZtaHJTWWNv
        RjhsUEQ2UjFJTWJtSlVLMzZoSk1JYW8KLS0tIERpYkpJSS9LQWVnL1lNTCtSUER2
        WTlKbjkrSm1RMFN0M3prSWx5N3kyb1EK7VzofOR7Aa2Itcp/s2C7qnet8ygTJYHV
        AEHf4+KEEGQNpK8ItqpCVZBTqXSCidUfTsl+tbagl/dqzTB0+pzsrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:f5dgPO+Xw8WpHykgHTf21GEoPkyhVdetc/GXHr6CFES0o+7fi+D776uPQUzhwcpLhGS2vUYRZZ7ZQVqGD5ANjlliHXIY8Ya7M8XTKQCUzygBCExSRtEP/y1My8sO5m+IVtdYpk1+y2DEDnCZ8k/3Xa1xqe9wnyCqAog3SQ3werI=,iv:uio0S7aQRJSsxqLt/EyEo8hwJYc7Mxiq+DunPfwv6Cg=,tag:P2Ivxz24MlZzfIqtsPpxhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
