---
#yaml-language-server: $schema=https://k8s-schemas.nerdz.cloud/cert-manager.io/v1beta1/issuer.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pgbackrest-selfsigned-issuer
  namespace: databases
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://k8s-schemas.nerdz.cloud/cert-manager.io/v1beta1/certificate.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-controller-client
  namespace: databases
spec:
  commonName: pgbackrest-controller-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: pgbackrest-selfsigned-issuer
  renewBefore: 360h
  secretName: pgbackrest-controller-client-tls
  usages:
    - client auth
---
# yaml-language-server: $schema=https://k8s-schemas.nerdz.cloud/cert-manager.io/v1beta1/certificate.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-controller-server
  namespace: databases
spec:
  commonName: cnpg-pgbackrest
  dnsNames:
    - cnpg-pgbackrest
    - cnpg-pgbackrest.databases
    - cnpg-pgbackrest.databases.svc
    - cnpg-pgbackrest.databases.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: pgbackrest-selfsigned-issuer
  renewBefore: 360h
  secretName: pgbackrest-controller-server-tls
  usages:
    - server auth
