# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:KFVH8kNHe8kxBe9Z,iv:H1xBYcXEOpREEqxap5RmFFqAa4wFctXzTyZriMcZvgU=,tag:fddmW20RFEXNH86vy0NxUg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRG5XTFJLVExQQW9CZWhI
        UHllY3FJN2Z4cm93OGFVWEI3NHlhODF6QXlzCjlBcWcwZE54N3dQczA1TzAxditI
        cm1Xb21KYzBSODhwckVmL0pGV25hVk0KLS0tIGd0TzVLNCt5YXlnUzA2cmFwcitO
        YWhxQ01CcVBYWFhoaUdsYXU3cGg0L0kKnxkdDMWfcZAuB6KZsubnDLqw1UuhD4In
        VOhFCrDicTUn+ECoR/XSHaIiHIyHzMwE2qmUuYtbDxUwLD8UWXjCQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:3obl5XKdPW3TN60HJ4eR/IHB4NVVTSx7ETdgLe2NgRHJOdS1Vk9duj3zF29hUDrnKoCeoNgzHfP1yJ1kcA79C86vMPBDD3H4ForvSQdVvlXH4YFQ51H0Uh/3jXaoySpDXFxB3/TaMyGC3QZ2GisjpSNxLl1PQNjAhOU+M1bnkjs=,iv:S8f4cPLHqxTYZ0e9cmoam3We2HFCKeVB2Z7JAcrFlJA=,tag:pXc00yN+6/qGb+kJ/Ywq0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
