# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:nRmzSZXdclm68Ukk,iv:u9thSw5CZ7HfK1tYYgW+w5/WY/+8Qt8txmFU6kuAV40=,tag:sHSBxkCHdtn570HHkpsdaw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMGFxOEJxb1UxTlAxUTJj
        ZXdtdW9McllGSmxUZXZ0K1NQbVpCUy85VFhBCjd1NXljZXJoemNQOGJibE1pTTds
        RVdFd0lKVW9vL1E5K1RQdEZpVlJPak0KLS0tIHdIZmV5S255cXQrZXR0U1RyQ1FK
        Qzg1dWZpNEhsVE5NbEFCelBxR2xjQkkKWL9SYVyLNiXteUgW+fcCQ78f2rpDN9uq
        HOJ1HoXYxPp8Jvi6MjMJRjBzJitVBuoTI3H5fLvmiBC7QM0p4Z4bdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:Io5TW2/XzpvO7l6XwPEy8C0ks9fSX2SHlw9T6qp5BCkVOrThbc/BmgbjGVvDQCgKO6TtkBBGSEmUzRUt2F2AWx+8jics2VQ+h34WAbWOS5PfBqJa5nba4SP3PRtMmzBHbIz7Z1beHHOLFLR423XzepiH1akDp4LgYEHbzeVD734=,iv:O13/ahoC8PDjdaeF/8Lw+bkvXb+q0jGPMA3RKnm+wJk=,tag:fe20m66B3pCqqztqNLRvkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
