# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:8VHuwVzDN7v+mjvi,iv:bAnBmC9Xp+M+fGiwGJHjKiUb5clK9ZU/Tx8zyA49JXg=,tag:z40YFO6PAeZ150d4C7gdew==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteXE1ZHd4Vkx0bzdGTmFm
        YkFmaXdqQVVZdlJhNjQ3N2RsZzZSb1A5WUVrClkyd2RlazZkRHVCT2t5b1pra0oy
        cHF0d1FtMm9IZ2pnczNIUlZHeENBM2cKLS0tIDVqRnpRVWRKVFcwRE1STG5vTnp2
        VGtyWmc3N1dFQngvUm8waURzUlB4WGMKZdjgCg8d8HHR+yGylpteyCzmcDxz+YKm
        68smXkvdq10vmqXFkRRGyL4ICoXBHL4J4Dp7cvlGcIEFMQe5sYRicg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:6fWtPmdUhe10eFWjFLU6O86AzINv/Q2Vjgyz66MMHTfsKFSQJqOqqQrWAcjO9Sm1zscTvg3vxieq+ZamtFK9AARYhImr59sH1am18SMpz8J+WDTfhb1fsEREGgsERwis6mo5LjtMPV7zGLxkIm2the+etfXJY6/TZSNHmsAeePc=,iv:wKZHASa0tbZOfhhLs/7/da4YKMtqp5Y4wreNLe/pwR8=,tag:DBXSZqivQqRTdg0bhwdsVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
