# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:zNASdNvOJqwxr/c9,iv:h5UtDhw1w7YV6QC3gyIPS1HvGOLt2rHvYFLyoFJ6qnw=,tag:6S3ZpB1lQpvg1MmQXdwSdQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUHZBbFNuc2N4Z0JOL0Qv
        SzVCWHhTVkJHZVhQTVpKZXVRa0JuM0RpMTB3CklvODdFd0Y5VXdGamI0bkhUU25K
        dGtzWU93bzJXbVV3TS8yY2E4MDJHQ0kKLS0tIDlzeStqODR1Z0hiWC9wbDE5ckdT
        SGw1a3ZVdTFaMlh6UlhsMkt2Z0xnMUUKHXa2GiqLG/wIe1U3g8YyZj0WSI5IThU3
        7V+Iekv3tmwCVYXa6JS9A3h5On9EyqxLXsRlEWlrRAI3pL4wbrUiRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:Akgo5RxpMCHHWSCuIByz9ZJQ7CA/annaV0CnQXkQf2qL/hcxIludx9K3wxKUcZrevs21aHkbqTPKkS1Pr7kBlVbl+YDFmTTeYK5shPYs/3c/r80J9bY6EClCFSw5rgTISoRdWbYOSKNS0iZJGIK6dl5XQ8tOGoL4NkHFnd0fF0Q=,iv:mG8B+OHV2fHxocGaX+qNAwSLMBf7VqtwEB92ArQO7p0=,tag:MYhpgRXhh3u0a45s/BJqKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
