# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Uh+j2b2gjyaM4OIB,iv:q7EhrLARREK/L1ZFFb67CsXxfEdWEZ16D0VYIhwP4us=,tag:etu8qoie6azRwCwXz7tlJA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSTROdmdQM3IyNTFLakw5
        bzlXOHVnTmdYcXVic3Z6a25YSHhwUnVacTJRClorZkgxTC9QYW5MWHdXRkNraE8z
        cFBCVVR1azMrVkR0RVVCdUZyYk5XcTgKLS0tIEVZWEZyU3lUSTFPTWFZRUNoMEpO
        c1BlalByUEFXR3dVS0ZVakFFaGJOcGMKyrreffx+mHBlmKu7tctKbLUqmPPO/oD/
        fR4wawFLJO8jgP2lvK+XAiiab75DZZO6O+q1kgM6dkU79cce7cPD2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:NfAsrOS1hVm9L9mXwEZUEmN3RiV7GBf7F4ObVFsBdWDRzs8qN+QWyuUq9BDcu7KTrCb40Ghhc+pLrR1mpmyzc586o8D0Y95PPzWeUjfBLX8GZzVhjy3hR+h4aP8Yjv2aCtHKB7nVF6KQQhtfHckqFP0z1BQGKodm2exslCexz+0=,iv:WVb8Ioyn8QTY0A9Un2DW/wtIgg5p51Uc4tBFTC1ITZY=,tag:2p9txwCbcFK07BZ1Na/ukw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
