# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:5DNFvjmIYdR/GZs9,iv:o+5ng8Nd7kDSSEyuPEFKYLhL2oK3BsxUyqIzKsvVhts=,tag:NkCpCFU2z0zJaH5+6UxG0Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQTRMbVRJUW5zdXFHYlFt
        QUFSTnVOOE5UcTZUbXo1K0hYZEpzUmNLTVU0CjlPbHlwTmNMQ1FlZms4MW1uOGZ3
        ZXdmVkRaVTlQZW1ncHRScUpkMFErY3MKLS0tIFBoV3FQV2c0RFhPMHZyZEsvTFMy
        ZFZmNzErOGRJUWgzWk14STVNcHpsb0kKJt9WFVjtIA/lrM46S1YDzlztZxwOoIZH
        aUePcd+aMaC7VSSMGmOusAwbYzMQRhvuxAZaOW87VraeCdOU5u+ugA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:55Z"
  mac: ENC[AES256_GCM,data:e/rR4GKw8UjDnLgZy3FoUkieK1arHpThgBdzKrwk68bG0bXSWfxS128I1D7Yl85rWMmRsIONfNb7UXTlFHRBgVVTPbmdhoWkBGcn2zhCIC9XsHLG2ABgQeM7YxOCePBAjleBflDgTdjghLVcDC/d93ZPeEGCZstyxL9Bm3Yz5x0=,iv:ZEtl+8NK5rYq4dQjVERzp9AmB3GQIylU5C7F5vegyaY=,tag:umdaRmsg5ESpFEO1/EvcTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
