# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Uri+fWanvLXm4f4s,iv:bo3MRXimh/sioCnhDYfhyglLw8m2NaZP0LXUzPsp8Js=,tag:9A5yYflrm4muPd5apzKDPA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNi9wVVI3cEpNMGhoNzFV
        NDFzUXhMMjdNMXErcHoybnVDTkdaSWFjU0drCkdCVm9TeVIrd3pvZHVFK1hhbXRI
        V3VQQ0xDMTk2bFdVSHp1TUtQNnR5QnMKLS0tIEsrOXp4WlZJTXFFQWJtdFdnS2Ns
        aUZsdjRwNDNjMC9FYXNSNkFQeWdKekkKu6Zr3Umg6zdxJRT/3gsmFJKc2iaXshtH
        hD6UBii98J2NAf3qr+5BwOCHUZOqzrQqW+H2NcIojoFa+V1y6qzXoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:4BPFDTNd4ZwBODVYy0cBWUJHBnMsJ+qQnpBiM5FJwXeT3RLl3XhFRWTN47o/CDCbm5bYqy66t/2/sYfE9g45sC78wOMi2fucX1KB/s3PFztXcu39gc1JAikv/Csqhfyy5XVv6uG7VAKgwpme3YahryRZ57om1jN5dEuq69+KvFE=,iv:tT7QWMVraFYNR0PDbJcMJYeEl1auvaMNcUPGseFlPQU=,tag:Q8m7+PBo2ruYoQwI5Kt0dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
