# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:KcAfs3LAHpy39bi2,iv:bQZCDXUq9ie6kfaXmcYr4qNBMcjMndyyuSgegrkm9lk=,tag:1pDsX6rBJEoAROsaDBukBw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK3VZeDhqL3poQ2dxeU5m
        OHZKRm05TlpjY01OczY5SlI5Sm9qNE50ZkFnCnd2ZDZoenJtQ3VsRk1BbW5neTIr
        ZlMrYzF3NUxOVXl4d2p4anQyVWs4RHMKLS0tIGVHZVhHYUhpc01leWhGTDZIOFlM
        NWs3SlpiOE9vYlMrbjYzdnN3UGo3WEUKLjWZUJoZuw4dyJX+hCYlYCrvihZknvlK
        HGV6+jkOK1HOxFyMOkVD3PtEDWhguMNwRJm/QE75QbitKNS3hxmQUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:k9cd7EQdA/8/8HFuUAodRpSJPYmb8Rl1iZt90xIeswNC3LOExTzR71XtKFxNiw7me0QBCty164aN6qnN336lUIJg6QMGetJsT8pOZGyDgtCkwiNJk+0QgWkcMK4KKAUtiwk5CaYtWjn3+vyRs9rISaAflc4p9FkkEv2ZneIWjJI=,iv:roMn8bNAEcUQVdWuDjo9ss9znKHY3N85Pnkmku/7SbI=,tag:v8FoEmLvwig+277ZI8Z1Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
