# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:dTAz5djrG0ZKdjlG,iv:/2k0ZufDqPb3OcSIv0pSF5v1lQMFDJ1GuIxEbJkB21A=,tag:Q5ErVG8N8QKmwiQR4rPh9w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU0tISGRFTmQzUFN5RE1N
        bHBHaE1ITVdVUHlsUUUvaUNFWmgxVEJLMUJBClZUOEtJUk4wdnFBZlRmblBkSHZQ
        MHFTQWkwNHlXZm9nRjlvdkJmVjVuRWcKLS0tIFRwOXVyYWlHWFVaRThqWnVhS2FU
        SXZWVUdZWGxTRm5YWFZlZ1gzbHhpSEUKHdTtpMI/NvhTPcfJYR+BnNvbzVP7oyHg
        M/nV0MfdKCSOyMx19BOjVfSq7FqtRDd1HUkh1NTgRnY4xdqWR+hniA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:zbRvmIZv18TQhU0JQfEeJSeKS3pxgN9yOo9Lh1sE2yid6EvzJwzNcvQMASnQav+jQE+9Ea+H3o/ATfBUGcP6kVOUtfbrmzd4CoddpeNhDjM2tmPIgJEJL68nZcQ9tK5q3Y4hCvBj/hHQrsYBoILLqeFEZ46DdC7k27zyOWigVh8=,iv:eOkUWKnAwOLuR27CbECT8Jo7vaQxzHngfMMut5q2UG8=,tag:azkf/yCE3GGbkx4ZA9aj5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
