# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:XYqP5l5L9+jSFWhS,iv:+C8wWLS1jLDEX5C0He1OH9NXJFFLckEIEDRxRse7wYI=,tag:shIZtrxHD/0TUHdIg18jMg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSXU4cTFPekE3QWZLcnF5
        QnN1SUZkYmR4blVEKzNhZUdNMzhrQW80MFJFCk1aK2VRQWlBRDR6M3JsUWdrbnEx
        ZUlsZWJ6Y3RpV0ZIdDB3VmR5NitEQjAKLS0tIFBWQlp0OXVEci9KWU9GN2hmZWVD
        d3FJTnpBeHAwbmFweUlDaE4rYXZXVncKnHjFB/u5hpto0ePhQBGJGlo6j67eeqIj
        pMfrrSGHN57lr2BSm5GqqevWDx5QD0KTypFKFzJpmskoIAoml7mDwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:dxvCg0zWr4x0I0fSMuvD2onp6LiBaf9W0nD1M4zXoEa8Log45hz1Cm92znOafuDakCB3RupfiEWK9JryiTe/hFEu9o293tUZdJrvodQFuVVbG09fxRzHmfjOaMt2Q3RPZ9cnPXNUfa5p/3i2rXcXbgHXgaRjmlUxqJ4Esff+A8M=,iv:h4lRnLbDGBK1FDA5LKzuoz9+xeE5eBkd5AvWgWHwvwU=,tag:Ouub8H+M9HxWIwDcnYwJ/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
