# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:2bxml8ifXHTC2hBC,iv:1su4/4GB1CY7K8vvHtLrvAO3ahVZn5VRcMdm/b/yq0c=,tag:dftLOuMOCeyj3n7xN3CaLg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U2QwUEk4WEh1SkVmUXE5
        QVFXV291WUE4M1JUQUR1dXcwY3VOWjlKV1VRCjQ2VXJPQ01aKzkxWUt0d3hGaUFl
        RWlzbllVWlJNTnhvTU5BL01WVkQ4cGsKLS0tIHFyb0N2UkNRR0Y0TVJVYkFLU3Zy
        b2p0MmxUeFV3ZWo4Mk1LMWFlSGM2WnMKGSqjQ3YcSUTNjNTK6pCbkDyUkRKvzvG+
        8egpJIU4hTFt1poW3lb3rS0wY4iHgh8p23qHJ7N/hkc+hQowewbZHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:8XCRogk/bnJQA8SGATGZYK4KWxQYTcEAZ7jZktBS0JvSdQ1I+namWNKqvl2ey2x6RghgDKIZdg8aHPDbL677F/uam4WizYgNM92rakq8Uv68vMNUkmJPkOp/WSa3UbJW2d8NhCyc5oTLYC/R/9xSbjDfENgSDiPx1jurj1of6LQ=,iv:yGhQjeC/T0rHGcpw+Sfi0XJIU85dU+ou2hbfGlQoQG4=,tag:XslZ5iDDI0bSbNxPCP95ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
