# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:BD0QHcBfcNOHX59p,iv:Op0DiXcIhGtaf1VbGqUa8Ma1BJNnotlbJKZvEk0wHlU=,tag:LmVzsCC3Jh2anc8szBJtAw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY2RsaWd5OUZjK0hnTHRl
        Qmc4bEtGQzN4d2FRUkJSZkJXa0RLaWpYVm1FCi9CaiswbzdLOUF0NWpDQVYwKzll
        NTQzTktIOUNNRUJnOHdnV2g3eWlyNUUKLS0tIHBuakFBSElHTTJVcWZyUGtNSWpn
        dGozeUxzdWw0VHR2RGpRT3RiZUxGOTgKV2lDSt7O1PLkn35m06NOMAULMfon4/ck
        LInnV3PXfZiSkAuQUMeNGaREsMWDvuIX4YFzVlKHC/Q6j2XLxC0OMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:3Pb6x3LgqVdoSaJ8COWxEuOJZ99BnU+z/FMMAaRR/C+FDdQrUIB8UOD0Au+tCBvXtzgwqkTwxTSpoWiiFonJhHDNMr2EqHua8IgMwhw80wEEvNMw5aYg8V8+dX93oV8JeIiZGTunbKUdZlzSBz/Bwwvo5Nw8vxrHOg5ScbXCigM=,iv:nerT86ZRDOlJIigNqRZhuGlnh+cDehWk0RhB5zOmyiA=,tag:RTs31ozUUJATJBHE3CRcRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
