# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:jdZQ8UPXyPVoE4eR,iv:42p9pMIoy22NOIvqEbuxp8FlmkG67sYKK/bYehe4eSk=,tag:vWy2hh5jSImipkA21SUq+g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNFQ4clQ3MTRiVFdDYmFH
        T3dEOCtwWi94YWNIT096eWdDQXM1WmpyTzAwCnROTGxYN1p2UFZUam9kQkRBYnN1
        RFF1STN5RHlTWVRpb2ZDQndVZ1FnQmMKLS0tIDJadm51TWFGMisvTFpJNWwyTklX
        ZnUwdlZFSFMyRmluVU93ak9Wd3kraFkK8Tt3gpFm67oriFmPgUxrkF/tjyEs11qJ
        3gx9XK6wmhtkSlM6dRDivifYupc5X6//LGrYphEWBc6Ams9s2DbZAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:srXTPfui8PQdhnevmPomeAcZmQE2eRV0sDw/NnbAkZ53+4bdRNt0JUVlpMt+fH3WhepvMq/LcJcVrTPQTlku50oVHQl22wZMedWmZhfloL+y/MnMW5dUOkQwGlRLe87whRTmSzUf3kit5UB9U3pNGI8EZuhD/SAlgln/XBJdvLE=,iv:vc5LFmY/IvFMxPvP20uWF5M1f8Cq2KqenwYaGjPWp2g=,tag:zWRx6iWugZ46aX9vx+yZ0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
