# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:6c5jbzXIaj2dnw4u,iv:coBx887+911owNPEX5ZfUg1aJut1qeSuPWO1bfSjHUA=,tag:v92i4voxeXlkco0Za3D7MA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNKzVvNXl2Y3NRR1pJUzNC
        MVFISHl6MlUxQkR5R0FHMDNobUNOc3NDVXhvCk9BckZPTGZaeWYyKzhZWlJ6Wngr
        VUI2WGJieUtybFBMZVhtdm9rZElkUUkKLS0tIEJvVFNYMEpndit1UHVDakFhYVFZ
        dENhNnZISHJOOUc3Q2pQekN3MmdhZFUKB4JKaH7GXl2oy+nhnCN5RlN3jlFU93ZQ
        G6SSuB+h5ay9POI1NBXbgzSjLBA+aTNpbBp0rAu+VPYvszzpZx0m1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:RhW4SlLhaUwRzoggnkcB7sLE0wIpDgJ4MKl4oQJ2sR5Soxe0PX4riWlybEZwlhUSvd1Nk8K1drUdHFPEWR4x+RD5hWVPORfK4563o8FeCeu+ncGpnM221Sh6Z4pgDdL+XIWHh3YJ8/f1Pwx141AyjuxjV5J8oXoGfT71cRlRXEk=,iv:dLHjGnsgSMPdtff+g2NDBvxVV5CvyE64eCtMDjuYzFE=,tag:ea+nZlFqYCZb9WknLYULmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
