# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:I4yGeyVZKrWrNhA3,iv:tIz2aL2y4q+aorK0g8LQHIbM6Kg/oA5qMOFabEw3SMc=,tag:nz240B5oHskGa+BTyYsIww==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT01zanR6cnVkbFpGcUdF
        UTJjZlRSNkVrNUhGODhZVkk0d0RrYWw4QkE0Cmg3SmNVdkF1b2ZtTEQ2d2xZL3l5
        cDBIWmhGZmttZEVwQVhVcno4b25DVUkKLS0tIEpYR0xidXZ0cTJpWUt5RnFNTmZT
        THRscTRPU21mcWhicWZlcG5FR0dObzAK0bdLhg+MSIR/ccEpHRmnZ8NpsV1HqTol
        M4GeWdji1kXRKNeOSf7x6Nzeuo1SSyEQSVsC6skXPa5bP/eoQo4Iow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:z4WU1CkFkWPS9ZjITQ0EVEV2NAo/OtWqCOTgcWeNzwC7iHsnnYTacRwUn2lUvHFhKpQh8muPO/Q8s6P3MGix5s+1k2x6oHW2EPvJHEECCBrnk+XsTPIcdz0rgwz+mswr5CKu7kLCpIbgCnBv675SKqReUG2bx7aPhmAqZdynA5k=,iv:VwlwF9qP7y1c2uu+n4GwqHABwqy9P+4Hw0O5CFuQ38I=,tag:vebFVlqZmsIJM47nga5b2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
