# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:8tnwJkpp6VqlKQic,iv:8olvl8Vs2J/jaY3EH18tqqMytFPE8KDZdtNhgUwDk2g=,tag:31qhSzIX/nC39tG8rUaVdQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY3VTL2pFRDJydlE2V3hK
        OUZNT2RnU0xONHRYdVRGMTFuYTR0MWJIeW1zCmxZTVFmR1NkOXNLZTZlU3BXbTVo
        OW1YS255VEFJT3pFVnRXZmN5YW9UQkUKLS0tIFRQbXBmUzB4UWh0S3BIOVNNODBw
        NUJaM1hLWUhBVUo5WXRpZFV2YTRjZGMKHcWPoInspq+bgOaaU1dnERaShF555xqx
        DhibL3R4LF/zI+KCYEXl/VHokb0hISofYxuUx0ZVSYtkGcBWu0Rx2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:RoOQ/JGlPb9Dogdr2qzYGpbqdTCqPC/pIPMZd3bZ9eLo/dAr/ux7xdPt/YqSCl0LhSsZ39LA2Kj6plReasfUeOKRjshCZ1OmQorQA7Tx6jglWaTnPrI337mi8Wz8yJP+wZLGlyFAz6Mqov7biZuafDFBIognfB7pZN5Ni9jZKfQ=,iv:wfUFfr0iPnVr0GW67M/NDS38C8oqfqOGgoCMogDXZwk=,tag:zOeQLdP2QIqjzY9M/H9OmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
