# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:nAfCRKPFm9yk/eGG,iv:yvjOhy/MECFKIgmaLgQCZ3A3gAarorgq5rknXk9AT/8=,tag:ih+hHQQL9zKOnI/9PnT/bQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SnM0bndqazJLVGtOQllF
        b3Q5UHZ5OUV2aStUcUNlZHo2TW5LWDdWblVvClRkcnBORisyZS8zSlJ4bi9Jd0px
        ZVFKK2tQLzduTHBoL3hzZzlVS21JTFUKLS0tIE1kZUJBSGhvRkpNaTV1NzdYOUl5
        Q2dQQmhjODgxS29iR2E1NWtDMDJsa3cKp3SNHLXT0VPzk52CcPNujBd6XzuKUF2l
        aIkf+fdYuKz8cbWE4MyWWsDi3a8SnA4aQ9rbifzsPW0ffEXvWjQIrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:coyGXCnhj5h2TmaV4jutN7g/TKdlZR4cozWlzqmoGfz7F6G/bcgghGcPks+7QWxW/HpeztkhlzpHEJTH2qK0g2l7Ma9Yv6h8kxjlGW8uQngMDvbGJCfZM/e0ubmdNQoTrthQ6putdTYZnZ0zwb1DTB7RGyGySsK7rZWfTNhGvY0=,iv:YsK3kFB0xBOtgoTzascDvLosnZs7zSbXGjA7Kuq/vzs=,tag:UI8mfLFk7owH0jagCx0fhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
