# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SD1rYAyd+j8IQoI6,iv:Mi16tT0tHGyS67QrYZxKUUIr2bD88dUNWhcwEMiR5Jc=,tag:AxsK45Petjn5Kny9+nUkgw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SHdrc1ZBV2NPcWVES2V5
        aXJERHpnS1hFTTR1d0thcURzV2tQMGRHbm1FCnN5UXZiaVpWdGJBM2ZDNW4vZTZQ
        K1hsRld0MG5IWUhaMWJYQ3ExQ1NqbzgKLS0tIEdaWkN1NEJCQm0yMmM3emhuMzlX
        N296R3NHS3RzWkY1dzBRT0k0SlR3UW8Kp+38QVoGk+Q2jEJ3SZtUIE85ZXlQpv54
        OvrFiRu999BA3L6ut8k8vDoH141yGzXF/Ucc2ZxQ07GDvtwtGdrgzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:ZH7mZ5IJXnqFu9ev+9YzYH6GtDJW6bccNdDbSxbyCOWoSaxoSrStT4QszN6ggYqRYLJfBqrHc4O/fJ3HhIRCeSHKhlnYO7jtPd4clKZi4QU0RXhAJJpBTCE0gD2VD4U2hHyuh7SAul5KM0znIiITGksvb0JwNXXOE/sv0QTjhu0=,iv:nLdSlB93JIOd6UqGP9YAR0e8xBNZEtAT3/hJHhUGx8M=,tag:CIGkzM+uRQGokXfTcpvs1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
