# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:aD+xCvEgJk87ef9X,iv:uW3UgTwIR1wtewrQWCZeOlngx/i5EbXai2aNIIykTBs=,tag:oviXBLq1RvQSdggKoNrI0Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSDNrL2Z2TFhITWdyZU9l
        blhKb2xCZDNGOWZBQlR6cnBpUXJQb0ZtVGdvCjVVS3F0eDhpazVITm9UbEp4Z0cw
        M2xIbW5GSzU0bjN5N3hCTXVtaFJ2Y1UKLS0tIEJhSWEvTnVRcTBSVktocEIzeEtL
        NDdVQnpGbGhIQU5KTHp5UVhTb1JYS1EKW0v1+9ADd7o4igxMdJ6U8SdYyBZa/5pP
        Kfj2WuaT15OlEky+zW+yEw+mgc/FgQUDAzT3rGyxcGgeKZ52NYbbMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:hTj7XEpaaeK79Z04lkZ8t+7feF6JvC9n7xagdFMkjxO3O86ZnfKsv06T28c1c2jHgFLKtBQfHrv7AdxZM6pSEhsg4x+vlZbGJoVgp3MRxGAkQAWoueigG9AY+UF3/3dCHupYg/u1KhZ9P04xIpge5Si9Z/H0PJCg8rCUslLDuzA=,iv:54dWQbsiZ7OfFk/p9gUiiSuIr0AasfqbyXojsrDyK14=,tag:8mWbxV4jvs7+u3zbbLzuSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
