# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:gMA4ghrpk35frpMo,iv:L29bl2dB8sxyEzUEk1TztIpmNdlMW0scXdu43CVpfnc=,tag:D6g3M4sSA4dbnBUhqpa7XQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS2M3OCt0NGJMaFdMZ3pG
        TFliUTFXNmUvUjcvb2NuZ2FsMkdtZ00zdFRzCkpRRTg3QzAyYkt5ajl3SjBVcVAr
        S0R5YXJIdGdTNGdmdklxMmNsdnFHLzQKLS0tIERMZTZTamZSSTU4RWYwM3o5b1lK
        QktCWmgwbWcrNm9aeWRrbW55a1pTZDgK4INERfT2YzBSIwPkmF8GS/J6Tui2Xepu
        wF7DiPpOdgphf/eOLmTn4rrwDrMO3vTfnDaoelJeXJa7uwVJHowdHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:05Z"
  mac: ENC[AES256_GCM,data:P1vqmOV2X2GdqdbWj+BzLN8I7w6bkg/WsHidHhXxZlbupmaqy5hHe/GIEpUWZk98RWjeFw1SIiLlNZBEfPIN1zAqoJOFKSzQxuKM7v+8a92BPBvU8oRZ1nEzD4X3qUess8+1SMOJ2JRJbRwP92qalutIVNRBSOEsrB3Vo2dK24I=,iv:Pe2EUOwyGCo2fmedOcq7mq3rGTOskkIY6DY5Yc9uBuI=,tag:QpPAtaxefj2isbTPePZTiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
