# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:ts++vgex3zIoLUob/VUKlyo=,iv:mISZMGdd6VaFvhESLCHrKwR17lCwdCxdUh02zGuQc8s=,tag:e7hAVCaU+uROipGZFgKcvg==,type:str]
  client_secret: ENC[AES256_GCM,data:OqvVCizPr9VXIv/lVL3mwv+1N2LCqab5ADu1SkJS7By0u5Rg7FyVbutRI+O34sZODGHMbhqI8BSK9Z75bsxGKQ==,iv:vBXy8pcDX9bF6W2si2syuxiyxnbeJtvSw0Ga01icCBQ=,tag:0B3n6/8ICk6vutoAKTZY+w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamRuSjBqTU1iVGt5aEFY
        UERWMnBpalczelJ2Q1l0a2xhRUhGbmtRSm04CkpWMzVxMmJiZHMvaVBqMTVYQ0ti
        RkRDTEhmYys4dUVqWm9zM211dUdtVFUKLS0tIGV3a29weG16bTJDSGNaQ1hXMjNZ
        RkN5U3pOL0wweGRCSGpGN1hnMkU5RXcKLDAdFNslB0mW+duWF3x1P7l05I8is71P
        5IlxwFxX0QNuToqrnyVf5V8qB0AodOeMHeD31NyMYj1ObiGVx5LXow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:pboWvlItochY9AlS7L6q4XwmrJwkYNLRXZYW5o3Wxwr3sLZbpuhlq+lgfLyvyE/ahTcvxQyF7Om39bNtppA8Nd+vowI5CeOyeNLO84VJiWsKcCO3xPYDBnXZBbFXRImbIwmrbgvAgtwhbOAcWUF9WrIwcu3ZRus3CBFh8pGbtTI=,iv:t9cKC3QTQZ5hr3NSrFUQlvV7RRkVm+dzzoieOUmRCoI=,tag:bJnjQGbOwIvHeSrJ7924XQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
