# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:zb7IWFkMaQ/u8ZAGlas+Rz8=,iv:phTyesOE1B4zpfvSJmiiQe0A1cK65DtCKuWGwxNmcB8=,tag:jiMdQu8kFWc5zxGlEg8KsQ==,type:str]
  client_secret: ENC[AES256_GCM,data:/h13H3T8SQFURsLK0wUevWio3eYZPkltoDF0fTBDoCFtN+jWlyFmfJx9X2k7NwI7mYaBwRyZlTvD7WenJfRIfA==,iv:eBwQ0w3aJFQEoDulZr3I4EwXFQqiT7nOvWHZGyYdMOI=,tag:NfGlwrGyHlnTpFhey5UfjQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z28xQ01aNUJDcFFXT1Av
        MlliYzJOZmR3OTU3UUNUazBzb3Y2TTJPV1YwCmxWdzc1U0txR3ExNjZacTlMMVhp
        Wk5vcE9BT3ZZMTVXZm5xMnhITVFZakEKLS0tIFJCRmVXa1lRWUtoNHV1WFBoWFdM
        eEw4a01PRXdPWDNsTjJnUzZERFhtNzgK9E8rFuVTi6vY9rV7oACbNnTsaH2X+6Fs
        ZRJ4HW0hVuImHh6aqealvP7xmWx5w4ilOdMX0E4dXNj0XpPkY7nWSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:vzWoQFbn1e1c9GGGpY9GXdqJKUvQVw6gxDh08ry8VXtHvmrqFKkcHJp6JDJrcmjpAKVPtDuhmyH88G5uAp4JWAJbjgOlTJ1o16F8YtwMPCZ6FH6iYNWv3D+QavOgEwH67/Rzp/WoOOmr1oYAzc4szOWTSozE8bqi1k9Xa6ojrxo=,iv:ZynaMiEPbPOLWerjts60VnZAffcK76/mOuQY5ZW/1tE=,tag:Hg/ZRhdXk3jeYi68Nw4zLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
