# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:ozpA2fKFpVwKL1R0kj9kq/g=,iv:lvTQD2oRBna0niavT02fAV4EbpCzFu0MSDBbm+OXBzg=,tag:VbuYRJP/WA2ku0eRArqKBw==,type:str]
  client_secret: ENC[AES256_GCM,data:SdoqyF2GjWEBwpa0CRY6Yg2rHxhqvAYEkWODoI5p+1FqV9zzq8iVMwYqMhdPkwWwWp8G61NxYHYyJw7kmOapdA==,iv:L/Z4eAGw0XSFhbecRg2AdGcJ1Eu68ikAUyV3tboGMgw=,tag:UPkJvqC8wNUDt0ojRQnClg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra3VkbHhBMjRnVnkxY0lC
        cS8yWldreTd5blJDck45TE1rQlF1WURnUG5BCnpMN1BoVUpnTERzRlVEL25KcWpT
        NVFRSTU5TWFXNkordWRucnRKdkhpUG8KLS0tIEpSaXRiZFVYVTUrQUNDZVZ0WUNm
        YlBXWUx5RG04YjFVNFViUGxFeTRyZncKBZQ86tVP4/Een30MzuDDKTT69nlBZOiw
        gJEBptNmfwXOoC+NxyCAQd67Qm3nJAoBdYHijkGabtczeuMAXDn1dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:OaEMFSApMTGX9DJfg2gUVOWOi00d2uqB4ywN6jYN6sT3bnCh+agfi7+5GkzUW7kJMiBjFWh16xclM1RH66aLJGVPPD8DVb2D+xoWd/XVax0ilL88ZNrymdd6jOqwQFX8F/YJyI1WpT7VH5fsQneTFmMxxM/6SR9Ue+2sRFJQsOs=,iv:S/SEK8Iy1ex2ZYH3KeOv+AwqBi7PpOlZZvtqNHGmMOg=,tag:llH7qWACGiQY2BS5GPD0Hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
