# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:rn8C8trzFPJzekwckU8zykU=,iv:nmSCfDtwQh0MtOGF+HKuIUrWR8EVPYSM73fnxAnXcfY=,tag:ZaEbkHCUojPWc5iFN6mvEg==,type:str]
  client_secret: ENC[AES256_GCM,data:tZoJIA/Z+M3mUmursTW76uNe0aF/GewsCD7v3eiKtP8l9EyWaq0ZTGdVZqSR1OB7CysOo05zQd2g5KiR/8Ok1w==,iv:lwLzT94Fh5lLWZ2FmAIguIswE5Kp5zXSa2835CEfMvU=,tag:3e/x/iMyfZzYoo4XyPc16A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMmJoWS8yZUVXQ1ZMbjlW
        SVZSSDV0cXhaZUtQUEkrWWgxU3d0Ynp6L0ZzCkpHcWlXS2ZGcVpGSVpKelkxRzRi
        STdnUHY0SWJ2UnRqMUpub01KZFJzbGcKLS0tIEZtNHJkbTVpMU9ERm1UWE5xNXN3
        dWVmQzdtTmViZkNHQ1dhY2VFZDZ2OVEK5+nk92+4EMdTtsN3UHmZRbky8RjEBHC6
        +cUSNCVopN6ozs7hrlvVPmOGAj7eb1Z4vPvqPz2/XH37dBoCB6PzTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:1TQ+AawdJVKro5EGlaFTXW2Q/NpqT0TmMU9ZyiM6GeT4WIK1XFRZiqZQqodjP8jcj4aAA7lLbmTe/i8aFGAoIaiA/gvpcCBHtURIHIp2PAXjMVxLeh2BifeEMtz8pjbQ3lXTuN6s+UFFscV2HhHuMpZuGdlHqyPwfowmcElYsLo=,iv:qLy0r+XHSjGoeE9OPAViAQ2CmXN6Yxqr/dX1d0sj3nA=,tag:38x5f04f5LZBacEw9k7XKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
