# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:8QoGGYIeEg3KGYEjSSHtBjk=,iv:wYWeDdIcvtmIqA/7CBT6M4AvJqYtVkk5EfUY9hWLrxk=,tag:E25cXkutwb/QKqajncjrug==,type:str]
  client_secret: ENC[AES256_GCM,data:c+1vOfcCOV/riHWCb8/APkYbeRfzsUu9BUju4zXAk4M+Rna5PissWxboH7r0zFJ8urglgXrkphElLhOTMm89gA==,iv:MpJyzZb2DTNnJeAbxJe/GQ4rYuK2Bw8yPAi/ikFxOpM=,tag:3Dqa6IdE16VP1l1kdJZlHQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbjZVSG9iSHg3RFBVQ2pY
        dE83UGpySGhHcHJVNjZ2cnd1d3VTaXZtMXg4CjRDMDh2clFtMnYzU0FIV3Q0cjM0
        WmJ1eWNBY2ZWN1hiRWQyTW93aEs5d2sKLS0tIHJoOVNCNUswVFlyeHhmQlQ1V29Y
        Wjc2eXViM1pPcmtRK1l3MWJhcVNHSnMK7eQDepYlHeNkslhaLhQOCgkF8DFEvj88
        qMgeH2urxqdKfNmurA54YCnzP8Dhrg7v1pCG8/azHVzox+IE0HPS6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:7+fUnzKuWkKshhBPlV7Mj8SBCZ1k05oA3jKCsEgCr4fVW0LqO/hga8kX+0HGFEJC0YeIUh3DjJ8S+aau1ZWAl4wCkfrzJmnsfA5UOxELuCVk2MIJ0mRD8l2VQqu+zwcvEPLArWclRVDP5fx9y/6ekCRQW7Gj4L0yKZ7c7IhwLpo=,iv:YE/rji16GF4uYRUhBLfnZGsspiBP8uH6duiXPOvS+5U=,tag:jGog+WAWMNSj2mc2s0fMFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
