# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:djwzq0o1H8aJP4F0IUWU7SI=,iv:4CAYrnWyHm7rwMSHRGYJH3Rcu1fPd9KRAHHHWvm/j3E=,tag:yNJmtAavO3rV/HMO6pKQ7w==,type:str]
  client_secret: ENC[AES256_GCM,data:akZoZKqZPlQ+a9BV9bnrp1HaK7h+FpRS0R257bUmcDba00V7FF/m0a6tDQIkGsNo8nQBEztXeVWZpu7mbcYUEQ==,iv:MNLrF2J7UvBamQvFzShRQDjFpaB4WBwfLUFteCFfoUY=,tag:4rx4uf+DlcHRiTc5OLiN2w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWXFWOXhFVkkvSGtZd2pV
        RitmU1lNaVJsZlhGOFhZSEhHTzk2UjZseFdnCmhMRjVDNU00WUp0RnZvNVNSM3ZE
        QVdHQTEweVQwbk1nRlRqa0dHeFJWRUUKLS0tIEdQVTlYR0xHbWpqNjdlL0FTY3lw
        c0szL1FwdEV5NStUUWN1MFNMb3JhT1kKyKYgeS7lYS8C4DYEpx5QO3MPrs8wp4f9
        alndHIz4KQG+NwfrDp2t7kI5NR/zfzeuToPftFFqNANie8ojwhxvuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:bGLRMChcmyYFu54PTguz9LrnlxWczNW9hoQi3WJq9Fmctx0uanUxrlO9tJzUYJEtmz5xeyBfZh+rmJElKNdIhDvBO7y1RmjMSv1Ipihljlrs3FPQj+znJu6+56ZvpH7fUFqI3Y5MO3jtUkZJoOmO7j0xBxaGlVlzM9CyWSwabKo=,iv:zXgCB+Xymx7YQr2xGAwQd3DGXqJkPPSU1ywlKyFUHbA=,tag:/Kh0PrO4Cz+ArrwnLEwFmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
