# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:kbrDwQMimatp9aPXz7mKpSk=,iv:SMlmrQvmnxJM2pCFsghhnzLVrNl33ACseUIkFcFpPO4=,tag:KasSeH7Fx257YJCqBcW8hg==,type:str]
  client_secret: ENC[AES256_GCM,data:82KUK6CE69UlD9veYRlIOL48eV1JApVtmc7njiacmiJ5AOf3KVPx6UsKehtWq5TNwWK5nB67vOqknSgUR/N0pQ==,iv:DQO8YyIu7HEAyV+iSMPuh1WMSttQUgrDIGnvZPURwEI=,tag:bUyzIDaVRN6bk1HG7ihPDg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS3hsUlQvWFpzNXFndFI4
        SmtkRGdxdFRJUEFUVWRWQm5VVEgzSzZ6SlFvCmxvbksyMmJ2TW5tdU5MbmxOdXY2
        V0ZXaHNSVTlzREppNW9Ca0ZWSzMyUUUKLS0tIE41eVZ0ZGtGUzRDTnQ2T1QvTzE1
        VURuSnFxK3JpbitPNVBWTDRZSEthcGsKQ4HZPXXV8OI4iypmOJ8gkxi1ZlrDj2AY
        vmAYr/D0n2KzusogUxMmYM202BldIqWD6G4m+6nxNsnBSiIdCtD9ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:18Z"
  mac: ENC[AES256_GCM,data:x0/KQ/+t3DLQ9g6uv0BcBNY88QBum3Aqqnose3lfNyD2Nkxdhf9oaPlGG/qIB/jbD3ugbXWoDc0gyUg2+Y8DDYpF5bKAyu7bBQkNFYulbrkyOz6xi3nrXB0tQjD3IyPw3fbJWQSJqRLLxqft5cIuwqRMNPWqRGjrP4LisNv7RFY=,iv:SOLyfH0wsI31fKxoHKLY5Nh8ZUoM8whqw+dTWnHHHdc=,tag:h1xpC7hB5EiyYWrd2X3XwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
