# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:lonMJ5k3X52xBx61wo9VeAs=,iv:M/V7ZOjJ1C8LIer1RNbHZCCDMtb48CxBsruTyUgoRJU=,tag:ki2nS0hJWO6o5s2z0vUs0A==,type:str]
  client_secret: ENC[AES256_GCM,data:QbIh/BgYN93HzXpfoXo81/lDvKikyYryj1QPm1XC/j1OReblwoq42zHHWV0wpCXuz5s4IBsTKKTKDn7GakOcEA==,iv:Gyd2VjLT6MHu+EWEgeQvIAM+wng/MMAr2OaA7AVAyy8=,tag:ZHtf2PbXO97va3YyFfHd9g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bEl4V2tnNFNtUkZhdmpG
        UTZ5MUU0S011ZnRhNW1HT0ZqWm00SlEreldvClFKL25CeFRLckN1a2xjQXlYY1VO
        bGdsLzRDWURrR1M3eU4wMnpjTGJsYTgKLS0tIFBLbEV3MnViSXVHbGxMQ1JVZTFD
        VmZNYXhzV2NnOXJ0Y0pTME11SHQ0ejAKI4Joknitf2XaQd/ehYrY6KP0gmMXJRnb
        KNEPXbewPlSmUNLAkMc4oJst+5c0n1Di3LhaO/hJVrqLtFikxhoknA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:jTf+v5gGL1a6kTXyiBRjrHc3DXlxaBPRdrWtWEPfnJgjQF/d6naCzFytWkozDYH+1oqXsk5BfYOE8216qib+JGGKFvhoZ0Yrs4BV+T1iyM9hqVpJBpehxLaa2TcRM8vZBS9a2J6WaJV3cBTDeY48D90rt5Vc6mdz6TC9fQ84JRM=,iv:l7nzHNDbw9bRAJDji50YxIeNNMIfvYyptWSi14lRYrg=,tag:esO5OGDV1zjSpKq8QOVPeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
