# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:AhxQ2Dnf4WKflpddmEYt7M8=,iv:ppa1qb1uD8j3nXLsfGn1xnFEzE8ztATotrb5SXXXwJ0=,tag:7Ec8xCxN2/eG34BPG3Xkuw==,type:str]
  client_secret: ENC[AES256_GCM,data:HapDtJW9xobzuTaz9zuscGoqUTSLX3TV2sUacIPuLfjbX3UUXel0cTpFNeAAUQDLitr3cvkpsFvkYLKv00wI3g==,iv:0cf5t2Ecsm4OEO7+DVwvh7dRUi6pW75iYtPyOumxvuE=,tag:1NNzQAnBzysakxlhPPhbTw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cmVXOGEwRkVqSFF2citj
        THRlSU10c3lFUEp2ZHh6VU1RWThETXAwL1EwCllodlY2M0xIQnlEdFdITmduQ3gy
        WXpKbXRZNnp6SGRHb0pJZlQ2RGlBS1kKLS0tIHNLanRoV1VRcFRjUy9HczR5am5E
        ZTJ2VFg5b3FQdzRzZWxraDNFNXRkQ3cKnu0fi6Ff4ckF4ECMyMAKGmLbK/5iwSoT
        DyKglU3DrQgQSLxKlY+Lx1ZjlVc1cAesPWyZU/aJ3nMEEc2AOwcOcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:czBrZ4xCHhSEZeZS5gAICKBzyqrUbvuGR6mpR6vBV6jHlZT88iWE9qNEcqL9WnNJCVU1lOfe0IOrGqCVO4WRHrJ5qcix0ucF2FLhc+gnXB6PafOqEGPomS8BxEr0ldAHI1UTfHZK1qWAPd0UvMYSNT09VlnCEQQfbTc5+B1MriU=,iv:Au+j+N7hT0+jt3JXOmWp0p2wbYHWXyHza3CHGMjT5x4=,tag:AxLwgtkzaYMNqQZuZ5db8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
