# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:Vz6GgPAaFsOz/9I/cpYfMVs=,iv:oF3xPGPGiTwE00eh5GUvQTZEStwGf19+SYQIrh6S0cU=,tag:10/wTXqzK5BO+21zOzV+xw==,type:str]
  client_secret: ENC[AES256_GCM,data:0mnCDPULCuvWL89EAPBikZtRXY1c7mCZHLWEFqT7xvf1gfh0iI+VfBKSy/uo9UktBi2Zl2xHf7Nqj98uliRhng==,iv:w2G7d+mfi9FgXWxQk0Btoq1O86r8GeIR2NoRRWTcF1Y=,tag:ozYDFoQaytR/ZMg1PXvddg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVjU2QjlTM05uRy8yMkFZ
        U1RDREVKRmYvdGtFZTZUQ1JFMitKRmZ2OVFvCmJWNnFDQnJlL2lYZWdpYVhwQXhr
        b3RWdklKMXg3ektHNy9IeDM0RVRnUmcKLS0tIENxWDg5cnZIMTQwM2RrUC9Edmtk
        TkNmZzgrY3pmKzl6SHVLamxENzhrbUkK9q3njwA+dGt+hCV0SpnqqoSsge8JfX7r
        e35GbqOuDQyLIy8IVkYnT2qaxf4dQ0s12jOvNidoao/2k8sS2eQ4Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:3A4VDmE8CzRZXYoWP01n5LGvSkzpmOoMM3bAZRLBwEJsp5VbIZi7Y1nHU8i4LDUY4Y6AR+NIH0p4Uqdbbxto7CplaPttpiJ+udQUf3QYxV0ozep6L6me0KhGZdZszHtYlzp+808q8JyVPEFNiXTympMNDbO1p4BeBoFLMxBeTlM=,iv:WA/OKEj6GO9QS+zX6R4MAgsy9TjF+ztamor58QSfA2w=,tag:O2rdxfJyDXCPP7mJohbx+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
