# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:vZkPVpjfZjbKvcel7IegT6A=,iv:yMjE8t8Gmvf46m0gEKIm2ABR2WXR0L3FQTePysrRWlA=,tag:5IIJ6ipo+StgsAYP9Zdhdg==,type:str]
  client_secret: ENC[AES256_GCM,data:fpCNpDn/XfpI82nQ+P9NYuEP5lqitdfmBkJ/TSos9/Dr1QsBYt7v+p+XfXXjXreIw5ymuyz410B5Ok7S35NeQw==,iv:XJ/GM7sgPQaD5YFBsw3cAArJsTS1m+apTzzFmyUb9lg=,tag:14g17nFl/MmWCTYQ9qy5vA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaWtzQStQbDNPakdVU1RB
        WUw0TEo3UUJOc3VUdTVBZzh6aXBrY3c2NFVzCkpxNUYrazEvMmxRMklPZDNVdkkv
        Z3k4S2F3RkJZdTd2Z2taTUFjYm5ZcHMKLS0tIDBOMHlleTErUE9ja2FxajVNRkNu
        c3ZOUUlSbHhiTGlSem16elpyL0pwQ1UKosop11Smqd96dhBKTIVlsP7cwPy8br/E
        Jh4PAilH2Zy5yEBhhueI6DHJBVt57NxtFir6IkNP3/sb+9+xyAG9HQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:L1eOcPHExuidctKHfi5cfCLwDWwfoQzp0vMJDBDHSv1mGeOami6B51shhZckZtUTzIZxYJyTQlCjWW80HVIiqoZ3sN5UTlfNcc+UR4OPjIJ8nWAzw1maXAxZ4GFnChZLJMgCl72V7edgfIlu2BblIOSFeMSDtBOSVW1aFbY/bMg=,iv:3GOuFh24jOWZ0LmxJJofTiswYrqbxG64OutDwbu3ll4=,tag:hws943x/DZpZAbW+40sOLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
