# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UX9hRdtF,iv:U1DHHc0eaJbC5nsXaPIS1bySJQGNlUYSuAf5KHXJsV8=,tag:nAXkXTNtKe1SOVSg6sJ/1Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:PYQuZRArhBniFsHDDGBfjcNfiLTIjiDEtP7M++QXQJMxMHfFUUZu4bLG8knC6DEn7QsA9w==,iv:fJckyfi8d0Q5bWPdCdFycjb1AVt5xU3xj8BxXXfJUJg=,tag:xPfjhNoNwvCk3UjL44swhA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:GZRkAm9n7x0=,iv:RxJlINPPBRamcLIiFzy0/Cv5MFZQEAM93eUt5vd5lkQ=,tag:OJrbdYsSvrCt5EWfsTHg9w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:MUwqu/G8Z8I=,iv:MTI/2tYwUj++BGee9AnAoQjLtePJ6Eb6QGDlq+Pt798=,tag:N9XmBH3aUh/iOE/0IcohWg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:WMQN3+jajjeSePy0,iv:EpZK5DhH1DjHtVOCdPcJEdv6MOvaqFMcByhqjM8Ex9U=,tag:b9kF2VHkcv1rKSNJLXvyKw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:GDI=,iv:MJ/mDOoDNEtuhIh/IgQIcZV36aSpD9dLTxKEaEWw/BU=,tag:csw6ykY062nBFju/AbomKg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:79E/Q+EMFMM=,iv:JX6zJxlr6/5DrGmmYJpi8gcA3+YTIEKofmBywNB1PEA=,tag:lpkVLJZKMJU+ZYhNkBxp3Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FsrWd7tcHOc=,iv:fpMYMgSswYfk7x1Emnn0sJ2iKzx/lIOt9QeKJVQXW5U=,tag:n2nVwDehkFwZTdU0WtbbfA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1ZUcHYzRTN1RGhCbnhq
        R3F2elZuMnV3NTJ1ZjVoakJhNmx2N2VBU0dFCnMvdHVSZnJOMHNmNjNrVEpqS2My
        Sjd6RDg1K0NiRzJ5SFFTVlQ0MkxyQU0KLS0tIEZDTDBDQk5zbXpwZTh1N2ErT1NT
        VEZ3TzlETVZCS0dLMVJtWVpab0NyVkUK6z9NiSWUy6MbjvfzCd/0hbPIMy0BGaV5
        ENwBsqYVr5+ChJipPrhdkKwbYgtoawcJgfUh5iTSyyJsR8epFxfFDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:36:01Z"
  mac: ENC[AES256_GCM,data:xZ/9MojRLjkqliYon++HlkMgKEQXOUxAfzb01jpR42z1iYwSBl7Ppzaz8iiNRzrXGn4MTO077+TD/TOrnz53IF91c2Pn9VL6wyXU7DbSiAUP4tFpkMS4uXM7/lQEjEDLCthE8VZ3pgIaJqWCpbnvJDjdedGeE5TMUPwDeIVfrCg=,iv:OCD3A4xCAAKUHD7wzFnuUQ+fafH9kqMcK6vi7qig10U=,tag:8RByA1UZoQZLH7YnV4uzXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
