# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
stringData:
    DB_URL: ENC[AES256_GCM,data:a6JBxWkDtaENDew6ALvoywpkLv0moHZm9YwH+m4kAnGS/E+nEa9Qt4+c1/BtF+mVXKd4WJfYVjHSAHocI+SPgXM9PvGTkf3qcFaFZ8QhuBcNFYcFl5VlvSdlbgwzSjNMDSTKf0OiEhGtuF7IyfQKcUnl3stdIQL4dUU567a2LyJcZDmipw==,iv:WoNBsRLJo42Junvp6UId8Li9V3vHXUFCXC6S0/0zY9U=,tag:5y02Yao1Eauyzp3jLs68tg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jtqQvH6Z,iv:dfHK1gYEKtP54+80RzxWLh4mOab3XR+gfR8FIaoUQ5U=,tag:blaS8XRjq66S1AJEt/VHxA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tk9iMJ+3ZLZnFb/x6Y8YJnJNBMJPI2W41iC5syo7mVbcoFIqrOg4i/BOoDVsRDnA,iv:+7GS0UgeOAzd3jbNlSaQLsbARGZi9P1cO91MmaERlIw=,tag:kjz6EfXQMKosHodrtTUyzA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pns+jP7KsbY=,iv:mI0JS2OQJyVhjWvJmJ4y0mFcvxCc7Cm+6HOswfCqsVA=,tag:DWnKaFDEbmh8ughKDN6Yag==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ntMcTL/ZWdk=,iv:iZTE0dzCKhZ9PgHw5uRnL3/2D6BjSkiyIFiSB9GDdfM=,tag:PEq4ZYN+VGBPsDWVSEhd6Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ECfCaWsBQ+9rFybN,iv:rTsNNnzQs0C8MEf0XDKJj+Vfwu6/Vwi33Dp5TwXjHm0=,tag:Q7cXxxjsSGHta6piQ0k1rg==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T20:25:17Z"
    mac: ENC[AES256_GCM,data:kdcR/EdQoRVmKll/zsmKVNOd7yl+j+6+InHHpvkg+VSd40ukyTSdOssFnvxBeyniNVpyklfJbPNmES0s9yUdf1Xjfyj3uztGZn3A5GyZQ6wo9a1L0XcSHYNpSF9yM13nX5pirR3RNtzP34O8rivFlhixZHyVNjAuGmAKshd135E=,iv:Hpd1AuzJ8rKEMONBZxm+WMf8uQT6/6GMOy47KhalxNk=,tag:njv5WIannOUqqhq2EUKI4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
