# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:7uXYLkyw,iv:i+4/d0Zund04LsjfaZSdC+jnkMVBaLHTc4zP8tjODIM=,tag:M3XLaAWZI17FV0W5Tbysaw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bip7N/w+QODrmXxsccWHWQAYGMbYmAL9G4thREA8EABHuAu+gF+iCu2jJUOV1Uhez+Pj4Q==,iv:VnjckCSGAnTljlF12+eMvNRKjWU6SIE6Kys+rfjb10w=,tag:YjUk7R0x+QzBUl+lGCEGKA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:9kcRat5YIvs=,iv:Rb8zYToSaDu/iWIDFuYpoBE+g0XiFmUYkUr5eV+idrY=,tag:4lRoCaoz81PWz0BSYBdsCQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EBYCtRt+ejs=,iv:2/THMIxO7Wwwj1Jgs6qfiSTJQPhiLptVC5jpb9IiPQs=,tag:LJpJR6uTXdOyRthNQi1Ffg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:qPNFXwGf9p7y/f5F,iv:WpQfOuSk8e3xtUKBZaMBmFofAa4bKkb2Vfmy38i5Z+E=,tag:jEUldMUifW5Go6V4iQZBxQ==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:cPg=,iv:4R+yNSqyhXPcJwIAAtCQWaMY2k3l6+VuchV7PtlaHpA=,tag:eLsg2pJIsSPtPGfoCDvBjw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ty7mTOf/NSQ=,iv:LRdojbxLSz2SUz/U/OGXqrw+X/hHvHAKhRI4n2H9IsA=,tag:sjMuYLsulp0Cf6qT1bpUgg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mnUiAdnjlYA=,iv:ZJmCjTN46oqKbo0M5jAS+LocP4wR5u7WMR1IFXSKALw=,tag:XD/p2SAbHAWjNgPhhxZmSg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycVIrcEV0MUZWSTk3T1d1
        OEpaR0hnV0NJa3gvWFowaEtZVmdWSU8wZ3djCmYyRHc4NnFzQVhwOUdTNlRrVk1X
        Q2o3OFkzcjlXWEI3UjM4bUZQZ2ZCRmcKLS0tIHFCeG1SNzRNSjNibGVTNXVOUUZV
        YTdtZzBPKzlhK2drKzR3cE15OWx0ZjAKVv7a/65H86Z+oI18piBM+fDvBzU2ZdhI
        1OuE6tHmTOUTvoRmPCQwRNdDPowOkIO61AJW5msz6BF/BxXfoGbKrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T16:27:17Z"
  mac: ENC[AES256_GCM,data:X/naiYfPkaFu1wwmsyOZerlN9QP0YMDk465+OkZ3MIq5qg8RQrzgN968dg3cEIk002t7Ul13c1/wlInUDtf37UfF1IDOeePnS3lUsx+uC77gM9gx+QosKMjvnZh4A3CnPwdHQUDzIgd+MZRKpPnsBe2lRkq/uxs55K+0r5/VGqk=,iv:N539IBktUldW8sOGUCs3r/ZbMzi4YofPKXe4343OWBs=,tag:3UCK72RtU3glVXZdDFRcYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
