# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZLSm/HIS,iv:n6yybag//iGqSC14VJAn5uNEBWxH9k/s0VAe+7aPVXc=,tag:U9/jn+BevNNtGdYTwQWdtA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:T015Zzz4uyUZyLtENQC3tAtW5NGw55wYM79GKDhRcLmTAF+ErxrhdvBhlIozG7d3ex6rFA==,iv:mKfF0y7Iz86LfNZCvqkX1yn14TguMrGmDZH/gfvMX/Y=,tag:UtE5nXEntPtyJ6fOBkm5Bg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:uZioPP3U1Mc=,iv:3W8MJJ9r1F5hVPAZQjqVsackYrfw9IZhWU1V4HRXhlQ=,tag:HUY/s9GffcXGp1SUbXDVFw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gMwtL0sgLmY=,iv:maJoSect/gnvVSQf3mW24aVAdmgxtWPwjidK07/1WZc=,tag:oD7XcL9+X5JiXh23E0oOUg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:w9HrUw6ngqGed7Fr,iv:5Bsi7FWFbY3W2mDNcEJoln6H4IxFhameD07RIkmNRxY=,tag:CsJAKBIXMBOhN8iWrPQo9A==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:5uY=,iv:cRkzCj2gLiRv8ZBbGq2QNkMF942cbWEoN68jtmQlDRc=,tag:ulPIe3FWvfnYUCw9Z7Qkmw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:7MpblkV6DlM=,iv:jvzSfBB8GWRD9i2ybtBSFHkrki3iZqVWFNXZQiCfVfs=,tag:pljZIr6rYjhFETYqO876HA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:80IHhJvdfIc=,iv:VAjo19q0s2Opb6CgLL8Lkg3ynFlUhH8saebAwv7WEOc=,tag:8eJ5ivHYtTpHwa8tyr7s7A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaU82dlVrd2VkYWFobFVS
        emg4Z1Y1VGY0ZEtLcFJJbVkrcjZoU0M5N0J3CnVMMVVwdWd5UTYwcllHd0ovZ21o
        UHhTTDc3UTZvODRGTjJwWlNYYnh0NTAKLS0tIGJScWMwdXVXc3Fjb1ZQUGM4TFBL
        UlMvajBxTXl6b01OdzJmY05BaS9renMKuDNqcWLqzfBUKn50nZpAVkra41wea6Ls
        ahsx8QxWF458a719Ui4x3jSPWSlGXcK/J3Igcjf4MDeMNplBU0BnFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:51:04Z"
  mac: ENC[AES256_GCM,data:ZyyENQitwF2YIkgwdZR7Lz+PRliU1cxf0JhiaKDwkUUFdMarKTextxI94J/CW2RDU1fElVdb6z22gwYX0YBd8Qk4kvqU2g3QDAeV10gc2zS/0uqEifqyflT5Gr4vlqzskXIgzR7YPl/2j1utCyossx4DN9KNIu6LmQL8rYOstK0=,iv:kke/6H19j4rQKaMi0NL7oECpB6irRlEWIUHFijnNSJE=,tag:Rg4DV1pQCqddAIE/DAWngw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
