# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:H2xvUzf2,iv:D/Dwg/KvSPYlPziIO2E0dP02MAaM8SSp2pfoAoIf/gU=,tag:R7D4U4MVhpUECgh17fO0WA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y44tgsDrKLAIZMssx+Oq4/75DhzWH2zTXAInY1EY7AcUegzKNtuJTbO3/A+XABKfZTOo5A==,iv:6y0GZAY1Y1U4raaO0qH0EjMaVNCqbzEAP1fwQbJmcw8=,tag:cZxU0G1b80g92Fxtq+cvqg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:9H/1BYvWE4k=,iv:TLtGpE+8dq443nfCxOPerTyzzHCeUP633aKSZ+LSRk8=,tag:fy/MtBCHYqk0Wm6XrSNk2w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:csRYEobJejE=,iv:vHZB0P5qEBn6vEKk7jxsJi9e3n9UwLlPrXjN4SMu9to=,tag:DVydPEy5lbYkloYUvwB4kg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:DrmtOn3wFNAHuoKC,iv:jE8+VY2UtamTYm9ifWOYR/Wi850hkXR8RSiLIZ7vdWQ=,tag:Iw5hDBLd1Ovw5GfGaFotdg==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:YOs=,iv:1QTgJ5IGaRl0BtnKnNhhwNm1hB82ed9g/zlY3QC0k7I=,tag:tcY8oTsS8k4imjwNE4jGgA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:RgdpUkP/06k=,iv:K5ahvl44yHhe57UqjE9/pP7tQRmgt34y3cdYdAeXeuk=,tag:spXDiOAevzXMb4cKqNKO2g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:HQncu620xgQ=,iv:JAZ5jIUCcGFyZEL9OZS9MnRFMtivPMtSN7260tJZVaQ=,tag:5Ue27M4gJYAWL08bAY1zAQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPemhVUjFMSU80VEdaQW5L
        bXk5clhIUWRic1dWeVVjOE9oU0FBUGlmcnkwCk5raEYwYVdiWGl3UFI0MXRobkdV
        S2pMVlZGeGNRL1lpNUppQmNzeExyTTAKLS0tIG5uM2F4dzMwZ2ZwWERMZTRpTlk3
        VHdsY253RXdkbzJYRlRtbGRMWVo0WTQK552Vu8UhifU9fxMXOdUjH0lz8FrFr/mM
        8YUrneX81dNsUhBj93it/8WwDTCQtoqAolUY1jzApvXcq040pmLQWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:10:38Z"
  mac: ENC[AES256_GCM,data:eLnOQfWWtVRbkEjxJ0ULEMkh+yVxsTJgQ2V0UtdSlhos/L+JKBX0tdE4VeHaFocYoiDdQSP59LBL9ab58L548l2BTMeZ3tYL/9N+Fz06zNWonoNdVS+gJ9rC/8Rd/GyZOZ/ZRDoLp4HiMLX/YIcER28Y2WVa/rKkrazlLIBgEKA=,iv:+bUcuAG4DhOXhVW2jJnfm6fOXkQ6bcWTyqY7Sba1Nrs=,tag:Mq0dqrfYHzWQ2zA6oh2vOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
