# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
stringData:
    DB_URL: ENC[AES256_GCM,data:a6JBxWkDtaENDew6ALvoywpkLv0moHZm9YwH+m4kAnGS/E+nEa9Qt4+c1/BtF+mVXKd4WJfYVjHSAHocI+SPgXM9PvGTkf3qcFaFZ8QhuBcNFYcFl5VlvSdlbgwzSjNMDSTKf0OiEhGtuF7IyfQKcUnl3stdIQL4dUU567a2LyJcZDmipw==,iv:WoNBsRLJo42Junvp6UId8Li9V3vHXUFCXC6S0/0zY9U=,tag:5y02Yao1Eauyzp3jLs68tg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jtqQvH6Z,iv:dfHK1gYEKtP54+80RzxWLh4mOab3XR+gfR8FIaoUQ5U=,tag:blaS8XRjq66S1AJEt/VHxA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tk9iMJ+3ZLZnFb/x6Y8YJnJNBMJPI2W41iC5syo7mVbcoFIqrOg4i/BOoDVsRDnA,iv:+7GS0UgeOAzd3jbNlSaQLsbARGZi9P1cO91MmaERlIw=,tag:kjz6EfXQMKosHodrtTUyzA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:NOChM8QKQO8DqRHmZxMT,iv:XA7zqnJFM28IjMQlZOW1omroch0m6lEX7ucmpuJyFTo=,tag:W+BWig9CJclugacZCf10hw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kRuTUTJxP6dA8owGofia,iv:AeoWboHij+q0kJaBc8X3gSMy6ZkwsfNCQVeyvgSgmdY=,tag:1rOGEZJw5Ee10G/bIZedzw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SGiz1lldvl4b06vIZYn7E1vtxgg=,iv:Ak60EcZ7f3sK6CgWmyTPCzKHmY17EAXg6SrmK1cCItM=,tag:kLxNB/IBqCSY9pKF88uXKg==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T19:48:42Z"
    mac: ENC[AES256_GCM,data:+1JxqlWjofpQ09aTrGF2N2FM1nOYFGqwi6/QYvhIfOF8CAqNaGNiQb+/iO/I5P2DLwk6RD+ujzQWbJOy+zp0YQQkIo8w3LEsn7gZuvaUXy9ka2VJSCAQc2J4Ni8EKzn0zOYq1x/bYGsZxiVJuZr1c5U1mtwKF3sLWSGbEoIRU5I=,iv:kohcBect7NUG2vsUkdYWNxZowHE/8OGy6Z4nuN8MjPQ=,tag:8fp9p9vBkEZPYu70s5pw9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
