# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:yOrPrkq/,iv:eT2nKY48yj8YzX0Ke9/yNmn4ltqBSamJoZdj3IU/kxo=,tag:4OOdOSSBW7vITtz4QafHyA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:URMV8uFiTEExzmTomyd1TYQwqdrn6b2prKiRkt8Vc/hRUpKVDcIhPJTxTBFTPFni47qtGA==,iv:f/klAFJtrD1VnzrEC15EGLihqzPHfoFqAN1SluaQCrU=,tag:u7SolbKWQnsAA8ymn1G8AA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:SIir/kbmlJM=,iv:26HO2/CZoPcC04lXRgNcXTl6B4SISG9CiYFUpaGp+P4=,tag:EW6WJH8If/VSODQl5gwUXg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IGGMb8P08js=,iv:EMHDPJM4UnmQ7pQf+MOhO066UdpcCYiCRHryVCQ/sCc=,tag:OqjgCvFPrUv7zLCSvU+/rg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:oTWzGQDDwEOYzBFg,iv:vNBYyz090fNGSDcRmyT4jWmXsGPryO+K9oDOeE90T1Y=,tag:Yd9z+74gY5siRPLspIiX0Q==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:HoU=,iv:S9YX++YGQx42B9gmfh9MRH1h8shr34QPdUb1/S048TY=,tag:rZ6BAIxyJPGNVMJGOpT2jw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:2ncHrZpkuEI=,iv:5WOhaE2obHan7GynXyi5ZTTYSRVw9BoQlJQ1ZbwxPoo=,tag:RRjYnmFC5TbRiH34LtFPhg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vJmKqyJc4SM=,iv:egRj+pzAAzTt8pwyLRCh5gGIdSISN7n8KnEXzErnads=,tag:DwapswG9tNPfKwDV88asgg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSVpYaWpYdDBUWUJQVXdY
        alJBY1QwV0ZYeDFuOFNNSnNKTDFNYmRkeVhVCldJcDZhOHNETDBteWk3QzVXaTdr
        bnh0L1h2cHVya0xaWFdob29DRHhoK1EKLS0tIGoyZVBzNE55N3FXKzZMZTUyLzBR
        cFJMZWgyWUQ5RFBWMllub3pBSVJYN1EK4qXDfBZBbYtbWINJsJCST7bkW4zQaRXS
        dj0GTyDvj4ydj2/qqBvW4wbkIa8bdYIjv/X6hC+Xm3rv7Teo3TyKUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:29Z"
  mac: ENC[AES256_GCM,data:dIw9qLuNTpNhad3BndC1UNmLHarESKVeDeeEIGlISRxNfBgJ3Qs+JA4iQ68i/dJcfwZjtvozWhWOT6ZYC8uneuJhjAWaDgP8QEHzw56MJWBD4UyeT3agdIt+4pt0+e3ZOnjal1mhLsgtgAMWD8HKnuAYJ0OQuOk783iKFZ/1KP8=,iv:0bFnhiwYcHfL1z+yKS0zDIAw0jGHRat7rCUzbx+d7zE=,tag:7ununX7GsjCwRPGbdpfuZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
