# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:P2QXRZSu,iv:Etf6U+dXDzZJi5PsnzslHI4TosacyGVCSSepJoauzIU=,tag:ELd7Q/wc56Ihk5KKBOsJ4Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gnsM+nEyGDLIweqISIbSq3gsy0yC/FXoHWmGj15pYFoosDyEW+53LW9T00ed3DNIYeYAag==,iv:e57fBF44yDjOsUVXdalUBiAQzXdcl2ECIUxGBHmjl6g=,tag:QNzWLN/dE0sGatWos5wZaA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:w/pgP2jztmU=,iv:VgW6t7EOw/11ELacJaK7Cz+1A2aNG3cGI0oO8/RMeK0=,tag:z0ct8e6iwf/sZnV1NlnSug==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:MN0ppX5E11Y=,iv:HPxndxPWtomyXwYaMOAzVgj+6LBLgSGNBpCyEEzWHG8=,tag:YZC4JC2Xmv4jMWBJMcqwnw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:uQXCFQazxFUKmCrR,iv:vOl2qmETvXW0t28obe6LgxttQWXRXGhJwnTpND44Enc=,tag:366JInzt72G5mzvFuPqnnQ==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:Bgk=,iv:hMBxFxvLEI5l8S6AP8u4uJyybNlgmaiBOBhtGkfLKWg=,tag:PWIK1e2IzTXRUoW17NkoSw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:HCjQiCP4sQs=,iv:i5yS8cbSmxx5UsEoUuHAdddKJNRDZgern3u/nH04HWA=,tag:YInFH/aHSJS39GjNQeHfyg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:l5fkJ+AvPXc=,iv:FsVjM+tyBb17Sx08Qybxc5AjyMuVSqx30P4yXkZ5vb8=,tag:6LJ/UiCLEqVWSanT8EZdcw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbWxwQTRiVkhmdjljR1hZ
        MThhY3dGZDRaQmhYNzY2M3lBYWlXY2x1bmpZCmZkNDVpMzBKb0UwS2x1T0Y3Mktu
        SGRndDF6dThrU253d0phdmZuYW4vUUkKLS0tIGk1anNZY0U1RmdBU0NKRkI2STJj
        VVc1akFvUEFWbHdxSVJGYlI0ZHpETk0KcJx3eGAKdGWbeH2Ns7WqPtddbEbiaOc5
        r+5IAXrF//faujE1MZ7d9aQvS/jFkUh1EhuihNVcLenpHYJD33TEKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:30Z"
  mac: ENC[AES256_GCM,data:o8+uT9iZN42p7ifqSYXEbO9n9G6NtW6g8aEXMWxJXYE0mqDSskG6EhQm+TyBijzAMSytb6d02qs2AEVu7OuoGGJW6dSDCs7G0t60Fr05ItoTeFQfkvJTqyTKg68g8TOzyRDhtBDBUPBT3DFOpQWadiBYers0NCoyiy528BW7GVE=,iv:ezo7J+INEEPImcq3oiSmkEctx8x1O1Jffely0CHv9t0=,tag:qN8sxAmiB/tvE2mhbzjS/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
