# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bCMa80ln,iv:/YSGbpD/98Ye77vrX7n7/8nMr5H1pPYx+4OVqJIoQc0=,tag:2fU6qXcUZVBvEFmATN/0HQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8QQ9rkoesVDtQNyp5erW38QK/wfizetol+0C7ivqIt3JiwqcLF7iF1bXzom8YvBVmsY3VA==,iv:xqCBmaNYVybLbZAUpuDxAIdPy3jEUU8Qgyuu2pWkSNk=,tag:xPQBRo+5ZV45kMeawYq12g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TomyROqfZ14=,iv:l9HbpdFHWQuiuO/hZdsIuW9yMG/QySdP9pVJlDIP0qo=,tag:Ni7zAhPlZuUDsbfaa9WjoQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eH6hxeYCw+8=,iv:mIr3bjxar6hFM4CAq9xW4F5GiD18s3hkiOrenrPuo/4=,tag:bPc0hyf+11jjF41xY/8jIQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:91H95GjHelXzl7dU,iv:ZArM9PGoezqGjPOIjpvaAvleH03POroQ5OsTl3m8DKY=,tag:/gVCGYxJQglKdWaGahL4Tg==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:SJs=,iv:sQ0Z7WkGRa0j0mQdFUYvgR0C1UOWUchBlEfBBzgLCsI=,tag:E9ym5+SOPInqJ0MrU4JmPg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:m0M0qfR3eD8=,iv:dzMJrcCak+vNL6uAgQ3bEkm0Ge8XTz8DTvmlue8AOfM=,tag:2Ty1Rb2Z24I/yFxZIluEnA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:jI7ki9zADyc=,iv:SZSeaeCOFOY3l+FTDq1qWc3vqGMgg0rsfAxCOz2i2mo=,tag:pJipwHTUhGvuTtBjYYF9ZA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSG9FWWppK1hVR1VhWWpK
        aDhGN0NtSGZzOVZaTnNWVld5VFM4TFlSSXhZClhZajBkeTB2cGdUcjRuQVpadlZm
        SU1HVVJTTUg0RDhOTXN3YjBtTWdZMG8KLS0tIEpBMWlQWGVtOE9HWE5QVzZUQ0Vr
        aFZ4Q3huOXNmamRIelkxWjU5RU9Kd0UK9inE5UUbmnnp0lg4b9cnDjXhkUOLsCIw
        lIU6nb3cXA4z26nXjebFKrcaRkODet/cdPkPLHbst3zN2jVbkD7vww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:1lhuDmqFv4K//x4xdoV1itJabTrxcS+OZsug5CcDTNhrymPIW3ZFd9E4zOL/lbx13eQW9RmtIfCEtLw/POIpcEHsQnDuZflhAizgpMo8eo6gJrfz/Btm0LfxzgCsqmfrvEFkrwjQuys7p8Obj2/z/On/dZKOaaEO00sjrpsRoYs=,iv:mMI4g3r0runGEELZ0yHPxvsPpMyCQSKdqBca3fbK5xU=,tag:WpSb88rJUCGt2ghkJqLA8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
