# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:i6vrjxO7,iv:ZULxAbeKRbmk8DHDaQNZw7bK3T/vXm3KpDGFGc/JIoE=,tag:2Df/ZgFKh9gNXotoEyDSfw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CryCyRN3w9Xz+OiLw2LBXbyHKU7i9Ri+onNHcqYOEOgDchQJCrmQuTnxlBNHh0JgR1PbiA==,iv:/pm8tGE1PjPhU/WWIjwGPhSuFlV1jBqFyETTP2NaqxA=,tag:4bDc39ygdsBQenAWifFo1A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:e3pjXbEOrfw=,iv:ORvo9F7CKmo706TAHamGm+ZspPUM/fScFt/ZSBqc1Eg=,tag:oZi16nQLo/0TrfHJYjrzsA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GgyK0PePdbU=,iv:nIy/wPtX9DZHCRSx4aELk6ebHLii70xf0FWNexwfysM=,tag:zgGEfd0Jbo6uDEDC91g6Ag==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:v1yATFp+HeOTNPTz,iv:c4fKqh91lddn092cC20gc2qGFuJXIJpMNc5alHsCt/E=,tag:TtbHP7y1sdt/Jsuqsfm8jg==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:YeQ=,iv:cGilgzJC0orQqvTpTTIznJ0BA/9LnntRsmjuDMCXAJE=,tag:FM4xwnvdArbOWgVnZPe4aA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:1BVP7mI7aL8=,iv:OiRjiYM7UV/zqLAKvUuBisMXjTnZ4++X+oY74WoVYAQ=,tag:9NWVClQjlBSvse1ttxrChw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:L9ASLxwIh0c=,iv:QAq3D70rrLUEybyn4axGsX50YsS3oUydMoOm3Hb6Pk0=,tag:0MDlVIiHXQeNOWzoT3M14w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY3p0REpSbVA0cTlXUEVY
        ZEEzajdna1VpN3YveU1EYWptR2RuUi9hRUY0CjkrcHMwWWVmRGlDaVU0YXhWS3hC
        b09tUUxlZWY0TmdqS0Y2NzY5KytxYWMKLS0tIFd0Qmh1eUcyRmZEU1ZGV3lQYUE0
        TVZJSkdadTEvUS94ZlpWaXlaaTBPY1kK1xgECwHw+YzVF/Qu9NXkgmNNj0BijpRt
        k5AqMUygbiVVzEJ8b9SjNx+GREAXBcvOadIG80Bf2nG+XbAhgtJvgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:18Z"
  mac: ENC[AES256_GCM,data:Z/s/gOCk+sMA/XmANaSKwILZfd8HQZX0fZV+fXdbxEHuUjtEpGzFgOnkdb5FHdWJYM2jj1ofnjjjZ4WCHQnmoeTwMcoHTYYtnENjrGyIbfevf/j2fQ/Tr6K46HvfzTiiApdylOWokm0OqRIpR4jOJvgzhBUu8kqgxfaMQ1c9nEk=,iv:Qxi9QNBbeOuCG0CB05rZw1piovrwJ29IJOYAhYTEBZY=,tag:E/53Ca7m8GZMPnEdZNV9mA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
