# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Avfb4DIc,iv:gAIOBPr1YdMrGfJdwtANr/Cjb1TVKQIx+aiz4HhYI8M=,tag:Rkm7cbokqG3WpNsSHILCNQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xEaUZvdFzE0mmBvZoMtd8hLgfx/51x7Y5gc/QoIKIavdbA7sJnhJC5mihvAzbIAfi8G6YQ==,iv:oYsqC4QM7Mj3y8H+fP21M2uQFHfDskRggepXhxc1STc=,tag:wWvEn5bhoV5qr4Br7WItGA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UHomBEdekzI=,iv:gFP4kdVBLqAYv0/LVUIYAdhGGNBeJ3Vp+rl4oVkTYUc=,tag:DY1ahViAftFx+cc/l9Z3WA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SfkuGmJEHNk=,iv:cqyIH9FG1KWYE0yB/LSGhLPp77vh9ft8mVSjKE2gFzA=,tag:h0/h+gv0S4DonVcdICVHGA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:wjmn/WuB68SY69lF,iv:Le7thXAx/kXrbjFHbmgOjcfpu6giml/zWl3K8jBeD/s=,tag:aUKPFxTYy8B1/IeBAoCXug==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:qYw=,iv:DMTkaMr9sKLd0zSnxfJIH0REORCai/vSmxsWQawWKiQ=,tag:0KZwiF2mBfewPwiHeK7anQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:5a/OzBd8mQs=,iv:ZZqnwRwgYsUYJKBMJhbzJIW6YCiUvrgLOoAjA6CV8UY=,tag:r831TBBwdR1w9nvBoVFdVQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:bCn175fGJw8=,iv:qDhGpqp1ebDS2sWZEGgcMEFNxhJ3x8ENMC6CiEg/wog=,tag:YTcnBB3Q5cUKHZAJ3BDxig==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHY0eVkrcytxZDRzdGhi
        UjVkTEk1OHB0NVJndmgzZEp1cjBJUG1jbzJVCmtOeXljaUZOQzgxVFNWWXNwVC9r
        QnVQd1pHT1lSdnMzdDZ3dEdUdkdGNk0KLS0tIEtMTzM5b0YvQU1vdEowcTNodnhY
        M3pLc0ZDWUpzVkxpV1g3eXlGb0FJczgKnmKlXX+HNAi0adSmcrGGp9i2xV51aEIv
        t/Vowj6myqDrN5CcJSTgetC44HLiyGbsZ4rcZ/2T6x0LRyjcc+h0YQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:24:47Z"
  mac: ENC[AES256_GCM,data:WQl2XEvB1f20hlt2F1dIcUl05Un5ADZZq0Cf11KBC5iVGMP5+iERxdKlnXwH6K9uXmLNhxkRG4DsfGsabt3DXOX45YtvdgaW5T99qSWCWrcH6+SaZVtl+Yvxw0xVOJZpgq+YnserZv0cJMu7FT6EodLe2Pxw8lwZbzQ9nxz3Bio=,iv:3VedGlq+n8eSf4781u/p/7XQn0jVWNoFIpqanPle9hI=,tag:X39cS9xXqQkGrZAbDITUrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
