# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Kc56WWcX,iv:o7ufolYymBg60fbkJmVohQMAjrmcde9ZXBw8EJDPCOs=,tag:M6o3VVNSaY9QLIPEkkqw0Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kA9L20/L9VBaLnQe6P+OZEkZ7wFA/Xor91tn70YZmTJopYUf+wDWeQf2qp8TXoLIf/TQ3g==,iv:mWY5l8+Z8nUaIij5GZBQIgP72MRl6FvYSDCAf6Gxsww=,tag:sdR3J4XdN739t8wqFPUvLQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Yya6snwSkXA=,iv:Z0oPkq9+nfJUjFunb7zGenPRKSTGnHvQhEggyAi0nbA=,tag:21JyUwEgjmPcosor8xcEtw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gM6vB5KOF68=,iv:KkqCdnDfmKShTzR/u/O7FgcoebEzp9aTBY+8ZxrZ3fE=,tag:JU/9REl3d1j0BMEsL0gtIg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:ysOc6Vq3lhclhCa+,iv:A8Q8XCNXS87jaKmWIEwNnB3P/br66pQ+oirvSrURqGA=,tag:+VB31B6IEYS8Ni9wL0MsGQ==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:1T0=,iv:sUpCeMsV5VlT9cXuCtDzA2MOzAQ5VDUqQ5NE2rBgzso=,tag:CY4+UTvZg1+UP5WejfDJgw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:mVqDzQxvKUQ=,iv:SGBeykvM/0mge0gyAuOVcEAficWNa+FX6TOYYx4uYD4=,tag:4OJaCwQ7Qi833BctrNh3BQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:x4ohXs7qWbY=,iv:YJK6w9FhhTw8mAuTNFWFrXzhb8UGL1UeSy1EWBWBuCg=,tag:2ZQiLuZDMwYSCrgaLXX2qg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL3A5bkxPZGVpRmZPMVVn
        N0xrTzRZalNieTVySENIeDBFa3pkQTJXUnhVCnU1QWtLSDFaWmNKTzF6KzN2Z1B6
        U2VPQksvaXpRTVcvNTB0blJGdlRuTjAKLS0tIExRL21NaVpEM0NUdWI3ZFhISUt0
        V2k4UVhZby90NWFNdDVuL3lwNzVuUFkKCDYHUiT4pJsNJiq6Q5U1HTey+irEpzKy
        KHWoPvve25xWWAWAZyiyPsKopCQ+ulN51tU8efpQc8TBm4ZSYgtd2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:22Z"
  mac: ENC[AES256_GCM,data:wROLWOZndZa7b9PXu6cAa/WxTWtCdc7ZLG5fh8kKZt58eC4lcLhRozhkBKm8vwOLhTgp69GRnRgTlmcWIaFNawJ5ISha21dqoc0JojH8OTSD9SmdF/xYqaZp/tx88Qs7EQLZdeE+pBKVhyVfdqja16tmxXuagi+e8dsLiS0Xxg8=,iv:F98ye70v6SUfw68b+A6+Hw2ZWmEstkgX7Yx6VaZoMFU=,tag:bvRzyBCXjdHGEn7JfGjEVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
