# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
stringData:
    DB_URL: ENC[AES256_GCM,data:wIGLEq3T8dIkqgdPE7egxUw8bQJnyJMFXPga81Tt665R3eAObHBCuH1GnIX28cOLy1cvsb4j5WdA0+sIPmE86bvfJyKowGlr55Rb+EkcyV5G1mzVG/p8vNMXE/2OSTQ=,iv:4PmJb+ew0ZxUtQiX2OFaZlEG4czIbVKwAFv92ISYdkg=,tag:lOQQC6FRvJinnh0lvJkbAw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jtqQvH6Z,iv:dfHK1gYEKtP54+80RzxWLh4mOab3XR+gfR8FIaoUQ5U=,tag:blaS8XRjq66S1AJEt/VHxA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tk9iMJ+3ZLZnFb/x6Y8YJnJNBMJPI2W41iC5syo7mVbcoFIqrOg4i/BOoDVsRDnA,iv:+7GS0UgeOAzd3jbNlSaQLsbARGZi9P1cO91MmaERlIw=,tag:kjz6EfXQMKosHodrtTUyzA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pns+jP7KsbY=,iv:mI0JS2OQJyVhjWvJmJ4y0mFcvxCc7Cm+6HOswfCqsVA=,tag:DWnKaFDEbmh8ughKDN6Yag==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ntMcTL/ZWdk=,iv:iZTE0dzCKhZ9PgHw5uRnL3/2D6BjSkiyIFiSB9GDdfM=,tag:PEq4ZYN+VGBPsDWVSEhd6Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:WEY6J4GzfcqHAejJ,iv:r+71sIE3L3tGfin5GAWL1j9exkt5pG4QF6Qzbm1XMg0=,tag:FNfrlilheGFVnIPpxvh90Q==,type:str]
    INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:OB8=,iv:Qsy3DUt29T1qV8zgHV+TvDXVkPX5/hu/6bqSZ02sN48=,tag:vepKJf25fGoyPEYuLB4BRg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:kcg7gDAuQGI=,iv:Fe1V3ouTeRvODAOM30y7Qi0nileKzZKUzFzC/Cxj08M=,tag:LGPxOJ1z4AzWjOnaEK4/iw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:+30vlOC+vFM=,iv:Rmjf3QKJb+y1NQICIZ3CHN8IMLtTKjuyT6FUPReAVIg=,tag:StFM49ByHe9jYJGR+0nTsw==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNm1JcXNleFZnUW9QNXRi
            SURERmpLcU1ESHdLMVpoSGhxY24rcWVQTmhrCmlsNHZqYWExNUlQOTBpQVhxY05S
            UGNDSEk0a3ZjYkVYdytFSEdleUNvdlEKLS0tIC9TRE5HejAvc05qNk5jRXBRWnF2
            c2xUUXZYU1FUKzVDMnpHMTFlSDlnUDQKGllfYDPh39nITnPOeE7rbi7GrfN+JC/B
            K/Yjht6J/xLkmsa/+czZ+xYBvkVx9/QnUFYDCPLIAUXIaEKt5uEXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:14:06Z"
    mac: ENC[AES256_GCM,data:pFNiCB8sMzDIIeeXfpew+66qo7KhYcQi0nHSmqI9vqL2e/2rETcQ1weVQwP8JsHxGzVM0DKS3oDZuOLNlgvnEd0J2roQzM1OkLWICi79xacVWDhMAaL0ceNrIuZ0qrc/rGGD2Ry6hIyf9HdmmAsyyuC6A4Y6HaWFIti/KkZfLQY=,iv:hOIsOH8GYYPksdMwBQIqnInbjjS5a0YP5zZ/dF69upE=,tag:/QTp8Z0UAp7zrFB5grcYHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
