# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:QgyYexXF,iv:6iuhYZxuMPRKRAOV+ek7IEnCgoumi3NjeGpI6GkPSb8=,tag:ahcU2awkEQ5UGm+dFi+cSg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:RAnKN9jUW5pb9SkVlJywY64VOMs9hoN6X6GtPt786KngGL8yVW4nUFoYe7Xs+YBoWhGKwQ==,iv:VMFIjlrUDlgzwiF8Xy96jWkp58Q1NQYm8Km0Khzu7As=,tag:Pn88mlIxW0hkBN1VDk3PdA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UPWP7y1wtk0=,iv:2MX7ttVgLLpTyFlFhCfmxG2YgMmgTdGmUAYIIqEeZm4=,tag:IVPpsA/xWSlAzoJazw3ztQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wENyULQmWFY=,iv:y7k9hmw4KcjdauElf9BVu+AF6Xxbr2qyzYYUSXdi7G8=,tag:tc1lcmrm8sPL1Qjk00GHAA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:HOXKyWcYU6EYaDjb,iv:BYvU8MpYTja3HDuKwORv07feN9+us2C4/cOGKntw7qw=,tag:vjQ56e+ZLTduxzwWV6jCIQ==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:zsM=,iv:5E3YaTM4gRPPQHoGDA7/LyEE7ACyhBYRow49J7bNFxE=,tag:ZgI0FxWZ7QiVup2Y1a5tVQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:7oM+dF1AJxg=,iv:jq+XMjrGCLyxiaWKSWX3g0KLXxw3gTG1P4AtBmyQTEQ=,tag:heTMqNugwRWz0w0u/9BjlA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9L0UhlgWMg8=,iv:nmID0a5wgrAKyqCBymfoX2IIsXtAWvUFxsUC2i2EhIM=,tag:EFRZY9aSdG85WKBtaA18JA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXBSbU43c0hic3l2S1E0
        MkpoOWFRUmJuOUZFZVJnRCswcHBxMWwvUnlnCkV0WnVTMlN0czhTWS90TjByZWNB
        dmw2Tk1KZDFtSjUybmRzVWVIZlZrS1kKLS0tIGZ0TGpYMXFNTlRJUTZMT3E3WUI5
        b0ZLZXVUQ2NCRnlRTUQwelhjZ3dzVmcKyTgEHm7xyh5JcGAAkQowv70p6fZMhUAV
        n9FYrx6R3J0OMzB2hcEEZu1wLo5AF7LqTpyaFXqz+Trhy0tm1GREGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:DLEc06v3HPSQQdkO6eSnZ1rnidkcUAcRXvAtzLAVmexMC8c89Ez892vJU/KFD8CXXWloJJSuo5vfV9lhbY9Me7YD8Kx3sSGFCMHdX99XmIgmK/dT5TyEKy56lPXdxXBlQq2e6r8oAgPduakbFVVkClqSDZ46WMCa3CL7PazE4TQ=,iv:MmQOUzRZAHnPKns6I8HYwsQbIoQ6MzIOmg1/cDsAHrU=,tag:v5Mgyyhhd1Ysp+jHSJoBVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
