# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MFRt5UOH,iv:3MaZu9tZhpnLoJ430lrk+YZzdD8y55WLH5hIvyAc2fk=,tag:EXZXmNrVymAwPZs985DovA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kz03CaduBjCmTadaqoqNbH8b/35Cx6vODqzaOqYYePQcfOBhIB+HrzgZB19YQUuEYAIZTQ==,iv:EdhEPmdp9gwmC8tMu7xO0b62pOM33PHzoPtRnUkp0bU=,tag:JfsQkeZpmJrjyfJDtQQ0ug==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:z6g+bxvJyko=,iv:hFW4P1aUDfU0XOcemzN6STB+7lfI/xPYKEsW6yL0DPY=,tag:MfW1QMvrrNeTKA4732MPfg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mhU1A6/mS8Q=,iv:Q+hZNB6Cj3xzSozX+oJTK6eROTDHlDglxQeXi7CCkI0=,tag:Cf5yQ5HVKD2VWLwz9g1egg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:PwPCtm6x2KEJ0p7a,iv:P3sEuMi46s6EUX9uSvVMRN3LhnlLHGJZdgXs0ZFYnlE=,tag:TRWluHwqC80gEdxuO2Mrjw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:604=,iv:LhkgSTnt3Z2ZTnLl4vAnFn0JMpVqoVswk2l1j7PSCcI=,tag:a17Cgf0grkebYU1XNNCAbw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:M6rUhNnnWVM=,iv:VNMiDCzNRFW3Y7QTZf/PJuM6pss1z7YtfhBRr/BHSx8=,tag:VpYINc/sVL7pHqxVlDUUqg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:u6zfy/LnSa8=,iv:deTHwH31hFCLL1AoRJi+Oic17mfX0EZz5smKTO0hIp0=,tag:l1PXmuV6XvkVUComPzPXew==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK1orNXBEeUJxeDVVdEdV
        RzZnVUFqbFNZbDE5a3hkUFRDKzA2SFZJUURZCnJ2L3g0YUdvY1RxZTFxYXFhTzRZ
        Qzd0bTBnTkZ6NEwyb29kMXdUTnM2TlUKLS0tIForbmJBUFpxMXR1Njg1WGVFT2Jx
        WE9IQ3BDL1E2cm0yclNORHhRYnkzR2sKD9O+jCq9/rx6rNW6VKcB3jfZKdEzpY26
        PImq72zRDNe4WkZ0lfkZJiZbzW/0wsFwM6SRn/N2JA0feN3LcR/cyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:HKvPnB4JhBarSsfNUtTjPq6g8th4L2T90MfHMZh2RD1NS2B6kM1QUWIgOP1qMBidGFOnPpdAgp/PLofcbt96ZDtcB1bel8x7KRb8GDCZJzs2Jes6/+yYytW8voAoVbuOkpGUj68zx7cvUYWfLcyfZTNDWiJo+YcX28giWbjdoP0=,iv:L1EP0kzaqRuqKd2yf0Z5yz1pI8QN6oU+wx+NEIe4stk=,tag:YcMgl3W0elNYL4zO+GjdZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
