# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XEBYQds3,iv:d6V4v86GfqvVsrx/Dkx0FdEsy1GHtF8pTFKYtd3g708=,tag:Kag9IhSHK2F1fk/oc3z7ZQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:P4DhaLUQEnTHsIcUb7KkRpsqbFQ0WlV+W5kTkzFU7i1IT5RoVdTXMhy4xiuT2tM99K9seg==,iv:ZDWT08joVs71xlKWRu0AjRhdn0lpAtJcVGnqAR2366o=,tag:VLI38BXkoXKalttwhK8OFg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KL3P1uckF1Y=,iv:YpXbkL2UEBKnQwEwvG8oesSqvLeu4my8YNi5SkTWyD0=,tag:2c9ulbC3EiKlMDPq4ly+0w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5+VSQ0aQT4w=,iv:/k/nVKdkk2aHyn1Igs1O0uJFPOnTyFKm4CxIG5LNPbo=,tag:c02ik2PhNIC9CbPJR5EIyQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:vgFIGV4QNlOyRPBd,iv:Mf+mZc3Hp+Es/WoVrYylZ4buuf68cM8AZWns+UT+gHc=,tag:RTiEqqnCg9cxbZZursW6Bg==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:4Vw=,iv:GBB0LxMJ4sjwxf1CYllZSVDpE/KLwyg619dTwaPOqGM=,tag:UkZ24bz8ql8p7cPBICRzHA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:3wH7OsY/8kQ=,iv:H/AM8irUkSu5cgj7O+NAtzondMUSYZTvTOOHu0+R5pw=,tag:j6+dUkSo9tnYN90Jnb3Y4Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wqwfotbsFpE=,iv:3T1ye3DpBS4Z1sy4VdVk+1/tsSFhKVjbqhCuLwIbi18=,tag:WdfjcLaubGq02j505z0Fog==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdE5hNDJ0MlgvNHg2dUNR
        V1MyaTlyNVIrdU1XRDdDZ2J2T3BLdFg1WEJRCjdXWGp1ZjVHL2FidlBCMFd2N2J4
        ZVRSYkN5SmZSSEdqYWRmVWRQZFd3c0kKLS0tIE9OZDNCcDhUbGtDQUpBWnhjKzN2
        L1pYaklseENWT1M5QXpUYkZkc1dYWmsKwF2K2SWZp8TGYnjE6DpzT5+Ls0+P4j7l
        A80/qwHDLoK8NbbFgwueSB6T9hw+MgRmUMuxp/csDboZnv8YTuXc3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:mklX+PbBtTh1dEUHcpu+6/ZjzFRV0TvomlLhns/wloHlMkC+pRY8pTQaxrxCX9Ha45dmtHxv5nI3Yhfl7a228ccpKPtz5h4OFvFrDAiYWIbAcgDv4LhcqBcC3sUXwgLkP3bG8BGQS3PGOjhLJV0e6ZCIZEUnO2Ybh+DKooyEOQ0=,iv:YPhxwSARFUkfNmg3akaJSqLf/tDVjX67YuDtgawjyAc=,tag:PK2RoBjqCDVjPPfcYAuuIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
