# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:dJcIDOR6,iv:AZ85TgjrMEuZ8yoeJr24FD6hEpIx3g774jJles/A424=,tag:olhmpzhHIjSEQV3QZTVayg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Hxtjz0IFYRHTy84HS5cRP4zTkCQCIM0U6BLJCZ8OZtf2ERZHYls3a2WlG1FFzMLnxuj/yw==,iv:PLBu/G97323eaFVmOpbAPYoFrivC3BfMdN58kpugouA=,tag:G7c+hSwyOU/kwCwNiFvBZA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:IagVlMvE1uk=,iv:XhyDmLsKy4jKhBNVnZUVt9SINawbIlB/aj79oQTZWsI=,tag:zhgny6OFqHmnEVK07Mm8hA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eYZVeO3rUN0=,iv:kM4KFT4ae9YO11dO2c38woDI1HgwKJalIAiYkqHrfFI=,tag:z3tgLQNnTGs6ZLLPAniZAg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:Vs71UDLrPedV2ZN/,iv:GCfX0d81gaEhynpczoBjtwtjd6V52LkAvRNEVuygbTI=,tag:AqXpPwTZS6g4Mr8ujfoQmw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:Fa0=,iv:uaJX9aHbaBSpneFFTBRkhXQyGK4GiGv8kg8z41xLwaE=,tag:PastP7h9R57Co4VskcAazQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:a2jjTbOcWw8=,iv:rjycLf93oaiTx5814XLMVufOzLQJVSZ+v13bx07rsGo=,tag:fGnEB/+au6nnlf0lDQj0tQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:S1cuDQ0HoUc=,iv:QfZniPfM1kXBfwrKNQQF/PSLF6knQzblvKIC9wtYbBY=,tag:5+AEVKIhdZ1TIgp+PDZJfw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkY4c01VeU8waTFGaFpn
        M1pIVjJCMGVvYitKMnhCOXMxYVExazVJUEU0CkZ2aVlyMDQvU3Z3emxrbHVGSFRB
        NkRjUmEvbUNLRDRYcDZtNndGdnhGK28KLS0tIFZieTUrNENScjQ0b3IvYUZxRFdJ
        NE9DdjZuVVVMcldJbk5Cc2hWUHFTaWsK1UHIHkoxAy3fhdyzO3IHUcQZ41xZEZIt
        t9c1S6Efzyl/arOGJdR8e45cPF98/A+KXiRJ8DqTq04thb9//Z6elA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T23:23:33Z"
  mac: ENC[AES256_GCM,data:jwip9dnrHG+3lljOhojGO891TK/Nzl4Rum4nqV/hqxyUlsPlBd/4OouqXl3zsOUJNhChOJPIIaulTiq2QfzKRzFNMaHddZUo1bVt6V4TZH2BnTHzmGXDtfR685jkw8mEa0m/+ivYEf8JUpbBlNj2nSoCihccJMF0p9L7z3LpKo0=,iv:N2k8UyvqyNYGd9APB9cmvhjw0MBRZug8JGqtMojvybk=,tag:Qnp1yCfm8oHVoajufnVaFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
