# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:BuSSyVGA2VA5MZ8T,iv:MmPbzWVJDP43W88qdSd8tgKf9IYkPI6O0Nsismrkbeg=,tag:qcb4/C43VI4U6MX/QNsuSg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQnlod1lUdjcwRG9jRmJV
        dnc4bDFYaFhwc1UxTXZ0a2NFM3FNaG5BYW1jClQwL0h1cHhXVWc2ZkRtTjBTbXNm
        ZEMremRXVSs2a2VLK3FBUElBQXRjSjgKLS0tIG8yWnZvQStBNytMQTU1Z25ubmFz
        eHpxaWtqeHZpekR4eE5jVmpxUktxOXcK79FZYi03SPc+r6XoIMi9wxU/3kqtTsEP
        FDpj125iXcDdefNfZUFPf62O6KroY6KUxmxvJWgqbjgqocWN9HtaAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T23:06:30Z"
  mac: ENC[AES256_GCM,data:rz9+2ZaC831PB45Wtx2/cvSpvuV+vY6gdk/rPeYvvrisXrlgNWz2FSgypCDnXl8nNBEAgyA4rx8ZEqQOjP6ih2ih9l/xaSBE2T2tcLuCI35nBXpdk6CUntQgHSXpfaRNlCsLeyF3EThf6HK1N6Yr1FXwPBArmQ/JNNL1hQIBrSg=,iv:9CktdI2kKK2w/Uf/ZgbhF87oaMl+J2s9kPwi2lhecGM=,tag:7iEFIWgZGlHY9XvaYp+kxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
