# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:2XU47fTMYqJ1FSBb,iv:bqAeo11dLKbougUUbOYsvCgi872QNlxeSrsDX9T99Ik=,tag:uxVE4Ne4jXAsqaqbcq4PYw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZEphL1J5ZFlsUGJSQ0pQ
        eFFJbVFmM05ZSUJKL3Q1cHRxRTNIdFZjNmtjClA5aHMzOU4wMUltd29RUXh2OWtS
        bTNhYkNuQ2RVRlVnVHBPZjl5clYrM28KLS0tIEluRW41cG9hdnNJL1d2ZklYbFYr
        aURyT0JycURYTGZxV0R4L0FJTEQ0N28KNlmwOxMdGuNu2uz4csGjSs0HMnXSN3wC
        O0SsnI1mlmAiFoUR/Vku/UCV8x13xs1ORJetqy8gHPSZmg4qy/cjyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T19:57:19Z"
  mac: ENC[AES256_GCM,data:wmKpNGCEc67EyuoT3ylXmhpLJnZDRbkq2dCRhOe/5aQoMzQM3WXt57g61u4I8nWCgeLCuGvWGGyZGxD8eB27r7ZZrQd/0fqgNCg/ZON5VdGwBjRskVHp6vXpLiIHBLS2t/EgbYoCEfwkfyH8ZgwP31XHfaJDJzWxZFPQnp2ozCs=,iv:VeG8YFeStZ5nlcp0esQoru6R3WwM8tsrjCR2hWEsAbQ=,tag:8qdn+bEuZyK6kPZms8CQuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
