# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:4PzCud9Tm9CuBdPg,iv:DOlceFHf6Fyy0zl/Uyk2yOwkWb9mmsR7rPnfd/1XNCA=,tag:UZ5ObSHTYCGpyjT7aeR2rw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUUpPTmIyRHJxU2MzUitk
        Ni9iVFR3VDMrTjhyN2ZLeWJqdjJ0bi9BcXpFCnBzTXJYZ3lEOUdJN3NEQjVmZmlz
        aExsTUtnVDVnSEJmTi91ZU5MbTRsV0kKLS0tIEZKVDdLdTFTcXNLVDAzdWNqYmRW
        WTJOZkttYzFwMk5BbXFlUU1abnpCR2sKmoDm6hfUq3kC5fRSmNSO5z5ZCYG+6kMO
        cBP1XLpuJvk/3rsHWsyn63yJ8UcHzB24f/fZHSLGxXIoeP1NrSU4jA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:23:02Z"
  mac: ENC[AES256_GCM,data:T6z6DsQPYEQ+Yib1CxmXmWUZOS9lwBI7Lu+jR0R3Gy16aQTzhDm06Nl4iULYTBMri52O3BiBcMw5RIkKJN0Hdt7IpC4yKfB0MwH7WhDGTMwSSDwBVABHBQiK9SO25XTsqSt4eAEhh0XJN0UOFZVfKF37YiC2F/rtwzwF9tal1tQ=,iv:0cQ07dralzzdltGSIzcl9ycKyPCUtOOgKWJGVTa63rc=,tag:OgxRVnWYx/+XM9vDWdM/Vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
