# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:7MdXdOKfD32yeNRA,iv:+YibsXV8cLeYavrs395/qnINbcC1moXspPsZdsxEA1c=,tag:CNB6rnrXhmnvJBtz3NpEoA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmhzWWU0ZXg3UEo3eUZp
        Z0tCV2hsSjlEVXhTanlvS1hOVHZITGc3VzJRClR0aHRsUHZnZENXa0J3N2tJZDJa
        T1BYZlJNRndWV0hwMFVzLytWODd4RkEKLS0tIFhURHJVUm9NaklWYWFRcGFXZ2V5
        K1paVG94OWhXMjNJTDl0aTAvbzVQNHMKAacW42mlOp0iRCDUpp34Po8eybtdeB7R
        OuUBrVbLC7Gh2cF8zVSGK3Lk6oLa2rbXkOc1DAFvWpBZH0qmzi/AFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:43:19Z"
  mac: ENC[AES256_GCM,data:P4uwS2TSnu+R3alwbM5C2tJBSfK4qf9Us238jiMkZPp+wDxj8HjEwU3ys1jL5q5Y885tRiYkHiRIPGgNf9QtEWp7jpiVuLKw3etrVDlXRcCbtsRQ5fPaIFwUW6MR43TuFH2mcHPydQfXRmhhvo2zo6Jnx5uprR1MbND4WrtlHb8=,iv:ucfbVSwyE7U1hLW3bxkGFX6KK6TimBXaKyYriT9+Ouo=,tag:SBywCYEAgqeHTmXR/NOGJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
