# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:lw6/MFx29kevENJi,iv:BiBlrWQakZXy0l8fBHoNOBE1WYESVWhus6ESQe4+bWk=,tag:XpYHwbJb8ovXo+nX1WF68A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSytTTVhMUWpIdVRzZ3RJ
        M2NtMVQ3eVNYS21JdGJHVEpwcVAyR21xb0M0CmVLSjB6NVFFUUExU1o2eU5XVnRl
        TGNyemdVRy8yOCtTbDlGY0tvc0ZwTTQKLS0tIElBMFV6M1p2WS92RDdpdkdvdEZu
        KzRqa3ZxdGVaUUlEUUp2aXh6MmJlWTAKpJj/cHQQDHAztbTAfzC/iFsyMtHGPrCr
        z7RUSQYcON0Vz/2bqkcG8d5Mk/0FVAj3CLZIF5FfYOS/aedhSCT/XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-03T15:12:49Z"
  mac: ENC[AES256_GCM,data:mbjYr7cRUNRCI9gRmi8Il42cmIhGq5LstNX74Rd7LeA9I/EYALA2eSTXd5VTnFSA+uEG3hRAHtolYER8ZPD0z+GqZf6UZtGcHpSZDPFVPQl/nOy5K7MkrQW4ediAenAybbg2VjmFYrQMBtt04lFkKbMojI/cRwlA8y2jdwEfHss=,iv:mUmUSZ2JyLkyLM1LgVrifX3QwNtcKBlZImvukFJN2K0=,tag:lY68dqB2y5KyfhqN/anrhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
