# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:7fd8fC3Rwu3lGFZo,iv:RgxLzfgkQ10Wd94HSz8O0BfwYI1+5YGDF8BjgJxoFxE=,tag:p9Lx9rPrFxNTVFLTUxomWw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrKzV1bXA0emFHTHBPQXVo
        TWJYa1RpUDUrNGxZTjZENm9OUThmOEVheW04CkVyNTNmQUVTb3dKd3grbFMrbG92
        eGo3ZXViYzBjZ2RjMGQwT09uSGNnTEkKLS0tICtRUUtRV3RGSDlJOThuVE91R3Z1
        NG1GNjNLV09QaHFQWEczcE9udmh6R0UKysbpmKmS1qsK45qHs04qRbp08JWr/YyA
        VfON0H1g+Bk6I5e1Mh22AVaAmO+m4E2+frOtABzrTIR3A8k8pEry5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:47Z"
  mac: ENC[AES256_GCM,data:0QgsY9Piv1mVT28G+aI5hOFhmzSfgWKbgu9yWn4nbiSEIvbFvyBvZJ3+c9CIw2p/dJZpfTZdWeG25Tpwc9LwGARabxlJVWHOmJiiNby0eQrz4KFo0ar0exhxQcpVk21D5ziDRcWE+dVJuql7Uug8/ExjD8fsKO8oAD+EOoMybTg=,iv:ZLIBsZUlnKCfGB05PDehxpoPK+7N1YX/MoZp8zYo6o0=,tag:b0eViMWsxDaGUr8rdNbHJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
