# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:DBswDmsiKpefLFjo,iv:woriL7HjZie1GYeDt46gAdn0UwGhCmnFsDicZHAKsSw=,tag:HJJ7933JhRMMxy5Oylv5Rw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOVk5R0RDZWFIYjJCLzl0
        NGdhRWU1aEIzb0ZuaUlabHNudGpCM21zSGtnCmlYUnNCRFFacGJKMjh0L3BkbldS
        NGdFNjVPcHlyKzRSYUZkdVNPM2NGU2MKLS0tIC9sWmt1d0RkV1BUaU9ETmVJTVEz
        QkJIcHhjQVhNSU9YL3FweldlaW04b0UKSVT9nZWKNOzCLqeM0BqY7AvLP/ONGkkB
        ptimyCcCkiekHYY6eFn6905aJcSaOM/NM/0iHnMgVWapb7L1IUwMjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:3af6VjubuN+6Kr3ENxPMAIUml60ia7fZvJWyWn0U5mO64IKz6TvYjh4G+9yu+4df2av8Mt9HSFO6uJADnkQPtV92dEeAmbkspqcMJ0Zl8IKY4YBrKlG8AvxG1yKHkVe1PGG+MHAMgwRU2+DM71CHXA2uKKav2MoYNjBYhJMaEoE=,iv:YHpb3GKqA7+wYu/6x7Jf6vUbTn0scNNiSpm0o3jfA98=,tag:gJpBF6ujivQMelVXrnt6vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
