# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:Pj//sji2h+rbGXpk,iv:YCAxptMJGGRb3VUNEIIYwNxA146aeON6i8aHA9N3KBE=,tag:Ye9R7JKoRaVml8VAx1mVCw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKME9JYW41RFFLV09pbW9S
        cVpGUHlNOUd0RVlNaWJDcHZ4WUhNTG1JRTJFCnNuR1VEL01idUM3YVRHMmxRSXoz
        TlRWZEs1YnkreUNtM3g2WnRNcU9UdkEKLS0tIGRLY0JwRUp3ZFlWVmdyaVpXbW44
        N1Q0SkplaWY0MGZOVHlrbmF3a0JwRk0K+QluFETK72Bgy8ufg31pnCt/GaqfWHtR
        /LgGN/s/Cw0R5zc/iQdYfmR4Im2Q8+0zJAWaikHNpPZcohLSC6CoiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:48:26Z"
  mac: ENC[AES256_GCM,data:E36N4oypc0GxxPPdB+lBC5cNDehY+kI9Y70AUhe/IC2SAXy1S9eT36Zri60WooDc81/TfBFGKAhwTtysgO4DHO1JEwxapUalBVaNGwAPMBlHM9vvmYM9waGyF/cnbAp0T21TgxjH1XlFYO519ZatVKCwAaCEYs73ieXkDnT2198=,iv:X5CFz8DylCbu3R5k2s9D2T43GEpFLBuztqqaJRtPQ0w=,tag:HbOgBeSmRRYC3+V2ITrwog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
