# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:oU7FrMYCsyBR+vhI,iv:SAQbCnYROzPz7UXgnzKJLbSlrX43TRehu72c1eXEPo0=,tag:kJ/LP51wcGZwHA82Ybsrkg==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcytHRll5QzkyaWFwdzFz
        azhvRE1QTWJ0QXdhWnpidmk4RFNaMGZQN1dJCnlsN20vMjRCWk4zVlNrWkI4WTFV
        STVKajNLaVdIOWxVeXBjN3NDNm85V1UKLS0tIHZnNnN3Rm5ZSTlRd2dpYTQ5a1F3
        RkpYcDE3cE1Jd1kyNmJIRHRobkNlcE0KKeEpSg8awsZN+t6JptiQRqFSvt4bkOO/
        BFM8ybKleTm0LMRe/xtyxttBCNqyUQo4lCf0vk4LjUmDVqk3J+CHwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T18:56:38Z"
  mac: ENC[AES256_GCM,data:vRmLW8VvjjiEyy5ElAgi1TcoR7eOQCq+2smcVguEYXvRmrhsHJKkJWKc6Vj5oolxzXtNaTqDBbaRdkmp2vU6DFyKjPmzzIMfzr4wLxd1GfH74EQTiSyaj0Ep4IBa8tdzbBJaKJRztQ4N0uhv5j/yYVXQYsQ7yhLDVkv8C5c/ivY=,iv:fn+LRcvk9wZBBuiYz+yASuXlGjc7rg0Wu6aMRYefqoU=,tag:aCBJGQnWNMpScO1s+MEfdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
