# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:rTlilSTdI74/7dyQ,iv:ZNz5ZjEebNg4JCBdLO1tx0lKD7xih3aY7DuCjIQjmP0=,tag:ucrmuTtNoi87063guFL6nw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYit5ZncwdVlCL1c4L0ps
        K1BpU3g1QXlRNWNpK2sxeXBvcjF0TW9FWUhzCnNsa3ZlUmUwdWFtbTNMYnFmMWls
        Q0pGZ2lDMFVaTFhpZlV2Lzk0N25GeUEKLS0tIDhHUk1ucnFlS0FIOG41MFNISU5R
        UjllNkhOQjJ4T3FSUm9TQk12cmdLSTAKB76/wM9iWtKMfOBEzsPxTirIR/dV8n47
        R9V8yCJjOCMVz54ARwMi8osmXfG0mTMgEjfc7X2BoSPrGdbuoO9erQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:10:45Z"
  mac: ENC[AES256_GCM,data:ALSIiZi9xAsPJ7ikce0RBfn5y9tYlaO+uyZ2wFqDIusmXPA0jsTxRJxFYQVI6ubLbgG27ceoi+MOtUWtP/fSlEr6uY+xXM24bCoqL5s7/M/rIYqp9BNdNVVP/dG+KSnlGG2VxVzm/RbFnoD1qoSbTeAkTScadRMf6+1Ni0O9tjA=,iv:FQwBMkP6szLgBmxfFyIYX1N1b2vSzUSOQQMwUbwthsQ=,tag:nGwcYB/SoCzhWci7+HQqgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
