# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:lw1KO3d5ctJfC0NR,iv:R8pGpvnnFvpn/RS6tkKkHCpHzG0HWMM5/HiSYw3Vihc=,tag:3MIgpc5zyGyXCX8IOYawZQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTmpod3Vna0xiR09sdHNo
        RWU2anUyRndKckEyYlZuTVhhY1I0K1dSTHdZCkFvVUZJVEZuTytwQU53YUhTREJr
        dS90WWxiTXZSSGc1d1liNnNJemRUUjQKLS0tIE00ZENDZ2hFZjBYU0ljN1RBUEtM
        bVlYZUtGNnVHdUlTL09YemtCWmRxU3cKQfWDj3OTClqkUqARukRj2aQp7/kvPCPw
        oBjAhs9lU0NgU7+8s0tWGsfJXEpM2tdd8LBpqCqjofBQkkfFeOnmxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T19:30:47Z"
  mac: ENC[AES256_GCM,data:4rSBwCwU43yUCilIo3ZDGVjwuSR/245ZPHRREy/4k6Qn78hF+WomoVfwUjiBYZ81VzKIZP6bfIO3rnFJS09P13FD6yJSnORkCI8d2gUqtjOHfBSohsolTNFNGjJPeYp23KmA54HL/b6J7xp0HmcadJd1YFW/ONslU+dEzHn+1kc=,iv:npA/WD0wCqlLj4zXGT8KoMsZBAsIZftv47tPlRLAinw=,tag:a8BxuxXxMKtLnleCuMx+WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
