# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:J2+BFoehXvlFv2vT,iv:W0FTIKBoi9bPAtfEDx2ftrcBTzyKbPEViI1sn+Btjss=,tag:sSmztmp0nbvWq+wpArKavA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva3VTMUt4WHh4TnJQeHl2
        MFFvSXIyUHFnaGpaaGI0V3B5TnNtSHg0VjJ3ClJHWWsrYk5WQjNLME9TVStsNldB
        aFpjbitXbXpRMTErY21UN0dGaHlWczQKLS0tIEh2d1ljWlpEQnBLUURMMUdxaDN2
        M3ZVeHdkRWsvTitOQ0UzYitsUENoMzQKGBfSlR88bQzVE55U5TkD7cHe3/1vc/O9
        taKrxhg2IAbkw9WK7pcG96PJs0pvBsJ8s4ibyzLGBXJ6dRhmHCYnlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:4hYrfkaMnJdZmvcoDX6pGCu1og3UKqwSs0AOwUltx4Z5DL3Pse7SWf2DeVVXL1LMuriR3GgWbwOXsvkgb5Xcx6fO7MAN/P+q0uuBmZmxDS1OZeHb8UBF/27YE2hXe2roM21GWky51eLiT1ftIR3DUQrEhAfbboDzmvcd4FHU36o=,iv:1F2rRYWDD4wLI9fL3/MDBkwFic8+2gGgWxFXFvaoQrs=,tag:Ms7NTEMmRFscU2ALx7zn0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
