# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:lmb2LOHKSHF5m1d+,iv:fPKQAaNl/DnPwIwcrLYzQrQOPqI2J60LXfJL3I0JY8Q=,tag:UsA8E3ItXHaSH1OgLRfV7Q==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZC9UUXZIKzJhcjZUYmxi
        T25qMldjbkpBMkxWYmpKcitHOUluanJ6dUNjCnFrMEczNlBqdnNEUXZpc1ZQc1JG
        OVlRNnV4V3I0VEZQdU4vb0NaZG5GMHMKLS0tIEFESlBGdUJ3TjlTa3JZV28xMGtD
        VnRHdU5LTlo0ZU8xQjNKbzF3NzUrZzAKJmq7Bj9t+/iCSm7OpH43hYg6GcBodeyN
        Jxd/QBFthFTWiAekJYGLsuDKKa8BV3b3DhO/i3Q8txQ1X0ns99+iOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T11:46:07Z"
  mac: ENC[AES256_GCM,data:Odo0nwdtq0FADRVACXd3TDgdu6gBBVglANAnB5u/5IS5kY6b0oMU5nmBJJ7kBPkDvWZ4a7bzmVvsD11puPrcxOieh+9N7jQ+jUmIEkfAqV+uaWyJNpbD/wHO0rLgA3RQpowd1Cwix7w6mudptqrMNatgS5/HN+FkPS4KuQhVwOI=,iv:hSi78yDS7gsWMGromC+TidX7XLsMtnlvHkwG2QskCTo=,tag:BKe1Yj0+JYymL4UWGZDYvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
