# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:BUaoIrDy79e/CAy0,iv:C0U/dkq2SUz+B4eVyunb+FlZ2+pnQ6gQwQnvSc1Gw1A=,tag:ju5RVLNBzutGSJgA6nT7+w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU1dKc0k1MDdocVBZN0Zs
        TktJenN2MjE1L0Uxb3VGMUZtV1ByKzRtYkE0ClVoMWszSDdBOGVOSkN4RXBra3Y2
        WGtyaXZDOXlzUTlJbDZhUlVLY2g1cncKLS0tIGppcnF0K3FUc0JEbGpCa1V3TDdp
        bGw3RTRCdmtuWDRTT3ZSR2t4WElyRWMKPGwyKG6onjTho0ApJtCjJ+KnnhDiLm7b
        EPgKqjvpEswUFpmMAUu2sWMAtfxEnlwwV5XlpD3AyYMh1whDHdESxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T16:26:55Z"
  mac: ENC[AES256_GCM,data:2GJB0WVGayhosZGtTEmWABqdHJrIrt7vgRQ4xVbvG872Jj98COIOQdH8GfRmR3JlQBWqFY3OIiIt1NFCMrq+oJvVN2PcgMWNgpmB6UQnbKt7Y4pUbvoWPVfqv6osoIeMjy21xWX0JGIVARlwld+OqKSNcy9X3fyv+tjvmnSR0EU=,iv:WOQ8gB+gk4cAKYxRWnE9jEDqR/R85Mqinw1Z/8gZAAY=,tag:XrK6zXuCmvrFwXvGDjv2Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
