---
# yaml-language-server: $schema=https://kubernetes-schemas.ergho.org/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
  namespace: databases
  annotations:
    cnpg.io/skipWalArchiving: "enabled"
    kyverno.io/exclude: "true"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  primaryUpdateStrategy: unsupervised
  storage:
    size: 15Gi
    storageClass: ceph-block
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      memory: 2048Mi
  superuserSecret:
    name: postgres-superuser
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "200"
      max_slot_wal_keep_size: 5GB

  #backup:
  #  retentionPolicy: 30d
  #  barmanObjectStore:
  #    tags:
  #      retention: "30days"
  #    data:
  #      compression: gzip
  #    wal:
  #      compression: gzip
  #      maxParallel: 8
  #    destinationPath: s3://postgresql/v15/
  #    endpointURL: https://truenas.ergho.org:9000
  #    s3Credentials:
  #      accessKeyId:
  #        name: cloudnative-pg-s3
  #        key: S3_ACCESS_KEY
  #      secretAccessKey:
  #        name: cloudnative-pg-s3
  #        key: S3_SECRET_KEY

  externalClusters: []
