---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres18-local
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://cnpg-backup/
    endpointURL: https://minio.harissaeed.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: MINIO_ROOT_USER
      secretAccessKey:
        name: cloudnative-pg-secret
        key: MINIO_ROOT_PASSWORD
    wal:
      compression: bzip2 # change to zstd at some point
      maxParallel: 2 # change to 4 at some point
  retentionPolicy: 30d
