# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:05BvgdvWT/8WTmtgV+AbbkyNCJlQiYdRsTvy3q5GffFZ4YLb/5yHLlXSzwE=,iv:u5gWSmB6o65H11eYSz6OPyipmmCe6iKOQvh8bczIZQo=,tag:gJkK7Y9YMcY461MF3rw2Xg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:eWA72tgZabl8N8E=,iv:MwMi/kc1bG1jsbor1yyCkGffWuESnL7NduWU5NVi0Vg=,tag:2iCgNgtul3PYPRh2gapx7w==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWdpVWNBRVJMamlLNVg5
        bEd2SlRvZDdmMWFZTllqOE5Sa1UveVVjNEdnCmhEdTNZSDNWK2VFSFRqalpXQTJM
        SEdVUFFwZEVpNzZBK29UV255NEdWNXcKLS0tIGpXakw3TU9CMTU3d1JlYmM5N050
        eFdEc2QwbVJNN1pENnRwdllHQmdoZjAKm23Av7yXYCtD6xeV2tGMmsxLQ1ewVE+Z
        fA2X3k5/a2nhZ2wOgnFMLH7T9MEf1vu7dyGCBJZHzZmJjshJ8ZVF5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T21:52:54Z"
  mac: ENC[AES256_GCM,data:/BNLFIVUVklILx1ltcxwhNWGlvyWfKkAR99+0iXLX8LHWzjaV4l+EBFEXNjQREl3t7JoE8nCtjn4OdnsAZ0xkKNoH540uhqI1pLB0axRlssh1hIATmshPv+OUOM3UXjPOqjTvSYFyRmAIbPdSyREh6Ue8btQXwECCFhvpg/Kr/0=,iv:MdY7aRtQ38qQWDR8z+1SO5bB9gA4e4b3Iyp19C5qj8Y=,tag:zqfZwQhq7zTYDY0+Tl9Oyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
