# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:P4X7A0BIoGm8GOF8xS1o2FqvIf+kgZFyo2UrobQzksha6Y2/uYgv2BRQfec=,iv:nMWB08JpnnbN2EPPDloy4AV0m3n+QdOAWU7KswK8Aog=,tag:c//mgug4pXRzfa8aJdrLXA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:89HioZ355ernONM=,iv:GgoeWnazar4dyzlwZ/A2/qHNQtbOgbOC/biLObEL/9A=,tag:3QGSGfNMsoF5Aj56t26GhQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTZ2NVJhR2RJNDJSOFNp
        ZFZ0TkF3NmtJYUNRL0RXSTNabVE4b3BkOVRBCmZyVzVId3ZpNVAyN3hNSDF2RVRt
        VTRoemM1WXJPU3hkZEhxTGR0TFF4U28KLS0tIGVOMC94cCtVdzNUbEpMSzNzUm43
        eEJLRGE0dVFtSEtOWTFiK2wzV3JZSmcKXILh6Jg7GNA/VSZ20N/+ZaBIIrRHK1sv
        wjxb89wsAeIYY2ICBf74xrBk9fXP3l51SpQ2bD/eIhpPAQQxXiOxTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T20:52:46Z"
  mac: ENC[AES256_GCM,data:LLgmbtqDiTk1wSkaOhPa+Th8TaGv/xJc/iZo+K+WoLGardzQKjv3hZ7huHTvWh3TgKPCCxBn317mvuDvmi0yihDKyU/CQhDBuBuF3wKKF5lhZweb9X7GipXFnp4IW8sRHOfDNIOUssVShpeRz8SQSu9awB8lB6mBhtF7meHfNWg=,iv:VFozTHCJ/79EYS4iJTxOr5KVbIwpSMn1Db5WmNjfdMI=,tag:iS1AuYU4RcdPjQr20s0q1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
