# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:dayZF8fzbcAKexse1UILSQcSHpPkv+KXKWxVc4JMOlI6jvuEPMt+2OlCih4=,iv:8O88qtoF2YlkQpGoybbNnk16SKzmL6Fi6x9iz3hOjuM=,tag:1x4lSeZV71xJrY3So0rOsA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:xrFz0aGV0EGD7gE=,iv:M3zxsbPk9uVJkH2i9VHiKCJzqM9vvFxllBr+Hxda9Ss=,tag:xQjNFAEMChjmTRSxAH5IHw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ODBzU0lNcmtnNjE3dXk5
        NzNQNml3d2s0TUJQVEl1NllsWnFNRUhWWFVjClpaSXArMkpWRHRjZkRMUndiRTFT
        djhWanJ3aTkzVXdZTy95aWEzczlBbzAKLS0tIHUvNUZScGI3Qm9tL0NQRlY3TzI5
        cG5WNytQZDU4Y1ZCM2g4SS9qekZlSlUKRkoc2XvDk3rHdzxXj+53IrWmcHtBcRH6
        7d9+x/mQsxhk214eHz0TF9Ll7o3SS5Y+Xx3xfR6umlgfPBo5wW0JmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:00:23Z"
  mac: ENC[AES256_GCM,data:m51iwhVGM5J50e1p6X2VCKPTnY8BxmcMu0xp4l1Dm/5+gCiC24Zg5qcRPfCBCoPMHkiU9n3CxtRbLtRBpsbGi8Z8gEie+VvT5v4H8+YxE3RtKZ1Ap1kNYsxxEPjRkKgqgCoHP6v6dwgdXRqCmmx7I1qIu6cYppDEgvf0uWf4aF0=,iv:DSn/PKAMTwAH507ezQgJBCqAYRl7CKQUZz41ahBK4AY=,tag:ceyplfdxlVMafoiB6+SCGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
