# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tiR+wo+xe19uo6kXItFDNtYACChZbS6MNpYctpkBvvSl6la59J0DoxnOcaQ=,iv:/CE7T/byvhihU/o/Pr+q6byfk8pWaZZt3lkuKlvI23M=,tag:5YEz2ahDbK7sK0QfsVZ8UA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:6spNMQFTuFmkhiU=,iv:YXoriUyhwoX352SiXqZ4tdzingqR6iluFit3Iemh9R8=,tag:1GUIfor32Alq7DFf0VtFgw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTHVDZlgvY2hsSHBLRXFD
        UjZyZi9jRjhkM3NPN2pzckRFUCtNVDNPeTJVCmlSQXpwNk5WOUplelhNMGVQOHNv
        c1hnNmEzOXJWditRV1lPZVhJTWJ6VFUKLS0tIElra1N5VjM3WEZrWnltV1lEZ3gy
        ZzF3eGMzekV2TlhYREN5RVRmeWhyREEKmlgNZGXryoNfIzQ1Ha5Kf/EWQNuRtJ0C
        Rw+ApoimVGwqGC/su7upZnFKGShPgeSBnTzQPegd7DUnBcRFKZ78+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T14:27:32Z"
  mac: ENC[AES256_GCM,data:qFbHujD6Psn48U0G+Ah7TZXwm3exhmoiFdhhd0vy1HBMvZTpm1zHhXOtqEbBZ+laRRJ9KqYa6HlakgOpQtFBQEnAs901ygHvlDjIs73AeYV8xAbDKSm2Djp89PM7ImjjoAfwzYHc+DqdDCmVxPr+5CbZjIBO/gDWh3cGE++uZbA=,iv:Fjl6RG58nvWjrtBLp1W3vq95xKXl6XIeWn9vxLpdNWU=,tag:t1bim9n39PY+eT9BYsPEMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
