# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:6D9Gidkp8vHVbjOIXxy29HX/ZGiusg+nAjA3gbIMAGa/ST7mXp1MhOqYK0w=,iv:kiS5ba8e7pIk/2o1GH8Yfv58Btl1KtIgOOwJBaW4/Vk=,tag:QMLN7aX1QKpWsrlXaKTYsA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:WWd2CnSU2KufFM4=,iv:1fkO4U3trFh9TauFEuV0uuxajz+EExpQC0xVD7UFNEk=,tag:pA3DV/klEwxHHI5SgDXtpA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcEEwRlMxQWs3WlU2Slgv
        Qk1zWG51MGp6MXl3RFBVNlJ2ejhHS0FyS1RnCmhmdGc4MzcxTkU2SjBXbnNpc1Zn
        cWVRS0Y2aTVXZzJLNGhCeW9zdmxOakkKLS0tIEdPdS9aT2VCS1krSzBIUyt0N1c2
        cTdSZW5TYWdUaHFkYnhXSE5DeFRPTmMKF1COO2oQpr3wjd1a/Yd22gnKWUaEn72L
        woiJ3H5RayhFA7Kmkxik6oK4qYHwjEArXr8EZIm56XepGZCvhT4nqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T08:17:31Z"
  mac: ENC[AES256_GCM,data:9LmbCoWwaV7XdAYyIe82BmmAhmU0rtzQ7eLGGdiFmuIzOGZIePYWgfd2OIfN1r3yDb1rr6HRZTapgERujUjxzJOv14r3EIk2SlxhJ0fbXQHCREv72ILri1aQ7T2CfDkYdGJm4mxPdAFb18Eio0VxvincoG/4qEdSC5zyWQHecQ8=,iv:h/5P6GsNnknxAX3dV9d1MVn7mcDYtDs2AKjJptdLEz4=,tag:OwRJus3hWXnGRMQCRJc5kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
