# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:OD9PkkQ4j1UWUdaL+OyH/O2QEDVRkvd6wwW/lL0V6R6FLT1P+qPjhH7196s=,iv:yxvhd1GplNdHdVYBceTGhS9fA6rv2azPeYZTX/UWW/w=,tag:rWKAnlWZc480NFSMXHtzaw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:tjiqBxENmLF26ww=,iv:fmASRDWj1QVkgvcwNN8gyVeqzzj+IzS1M8tyiZ6Erso=,tag:DNWiyiZdNRKYrvzyyTmHjA==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra3VkbHhBMjRnVnkxY0lC
            cS8yWldreTd5blJDck45TE1rQlF1WURnUG5BCnpMN1BoVUpnTERzRlVEL25KcWpT
            NVFRSTU5TWFXNkordWRucnRKdkhpUG8KLS0tIEpSaXRiZFVYVTUrQUNDZVZ0WUNm
            YlBXWUx5RG04YjFVNFViUGxFeTRyZncKBZQ86tVP4/Een30MzuDDKTT69nlBZOiw
            gJEBptNmfwXOoC+NxyCAQd67Qm3nJAoBdYHijkGabtczeuMAXDn1dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T06:23:37Z"
    mac: ENC[AES256_GCM,data:CFrBmcxl2ueAVaAStFfbadpSZrD24ArC/WSQYH9O6OWi1qvPbe6/qO/KI1180E49TEMxGXJKjxEDFyl6NzWMTI4LQKVkIrmSpQTX7W3R4yHM6QzdEW7aPEfjnWb3OTtWLvo/rXIhv6oDtoez4AMJyAbetw1nmE6NF7h3/bTHcdU=,iv:kcR6l2lGz63k8aecMgXn4nobzj0ioW+x4A2BAbo7F5Q=,tag:/+6gbp3KrICqnkV7XyKRyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
